// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/compiler/include/compiler/series_parallel/computation_graph/computation_graph_binary_parallel_split.dtg.toml
/* proj-data
{
  "generated_from": "1cccf3f005f79476dcda5ef6782b7437"
}
*/

#ifndef _FLEXFLOW_LIB_COMPILER_INCLUDE_COMPILER_SERIES_PARALLEL_COMPUTATION_GRAPH_COMPUTATION_GRAPH_BINARY_PARALLEL_SPLIT_DTG_H
#define _FLEXFLOW_LIB_COMPILER_INCLUDE_COMPILER_SERIES_PARALLEL_COMPUTATION_GRAPH_COMPUTATION_GRAPH_BINARY_PARALLEL_SPLIT_DTG_H

#include <tuple>
#include <iostream>
#include <ostream>
#include <fmt/format.h>
#include <memory>
#include <nlohmann/json.hpp>
#include <functional>

namespace FlexFlow{struct ComputationGraphBinarySPDecomposition;
}// namespace FlexFlow

namespace FlexFlow{struct ComputationGraphBinaryParallelSplit{ComputationGraphBinaryParallelSplit() = delete;
explicit ComputationGraphBinaryParallelSplit(::FlexFlow::ComputationGraphBinarySPDecomposition const &left_child, ::FlexFlow::ComputationGraphBinarySPDecomposition const &right_child);

bool operator==(ComputationGraphBinaryParallelSplit const &) const;bool operator!=(ComputationGraphBinaryParallelSplit const &) const;
std::string debug_to_string() const;void debug_print() const;
private:
std::shared_ptr<::FlexFlow::ComputationGraphBinarySPDecomposition> left_child_ptr;
public:
::FlexFlow::ComputationGraphBinarySPDecomposition const &get_left_child() const;
private:
std::shared_ptr<::FlexFlow::ComputationGraphBinarySPDecomposition> right_child_ptr;
public:
::FlexFlow::ComputationGraphBinarySPDecomposition const &get_right_child() const;
};}// namespace FlexFlow


///\cond
namespace std{template <>
struct hash<::FlexFlow::ComputationGraphBinaryParallelSplit>{size_t operator()(::FlexFlow::ComputationGraphBinaryParallelSplit const &)const;};}// namespace std

///\endcond

namespace nlohmann{template <>
struct adl_serializer<::FlexFlow::ComputationGraphBinaryParallelSplit>{static void to_json(json &, ::FlexFlow::ComputationGraphBinaryParallelSplit const &);
};}// namespace nlohmann

namespace FlexFlow{std::string format_as(ComputationGraphBinaryParallelSplit const &);
std::ostream &operator<<(std::ostream &, ComputationGraphBinaryParallelSplit const &);}// namespace FlexFlow
#include "compiler/series_parallel/computation_graph/computation_graph_binary_sp_decomposition.dtg.h"

#endif // _FLEXFLOW_LIB_COMPILER_INCLUDE_COMPILER_SERIES_PARALLEL_COMPUTATION_GRAPH_COMPUTATION_GRAPH_BINARY_PARALLEL_SPLIT_DTG_H
