// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/utils/include/utils/graph/node/node.dtg.toml
/* proj-data
{
  "generated_from": "cba3a2bd9dffc28b0f655a5277b712f3"
}
*/

#ifndef _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_GRAPH_NODE_NODE_DTG_H
#define _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_GRAPH_NODE_NODE_DTG_H

#include <tuple>
#include <iostream>
#include <cstddef>
#include <ostream>
#include <fmt/format.h>
#include <nlohmann/json.hpp>
#include <functional>


namespace FlexFlow{struct Node{Node() = delete;
explicit Node(size_t const &raw_uid);

bool operator==(Node const &) const;bool operator!=(Node const &) const;
bool operator<(Node const &) const;bool operator>(Node const &) const;bool operator<=(Node const &) const;bool operator>=(Node const &) const;
std::string debug_to_string() const;void debug_print() const;
size_t raw_uid;
};}// namespace FlexFlow


///\cond
namespace std{template <>
struct hash<::FlexFlow::Node>{size_t operator()(::FlexFlow::Node const &)const;};}// namespace std

///\endcond

namespace nlohmann{template <>
struct adl_serializer<::FlexFlow::Node>{static ::FlexFlow::Node from_json(json const &);
static void to_json(json &, ::FlexFlow::Node const &);
};}// namespace nlohmann

namespace FlexFlow{std::string format_as(Node const &);
std::ostream &operator<<(std::ostream &, Node const &);}// namespace FlexFlow

#endif // _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_GRAPH_NODE_NODE_DTG_H
