// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/pcg/include/pcg/optimizers/sgd_optimizer_attrs.dtg.toml
/* proj-data
{
  "generated_from": "f4d320ea888dd0a9a2d2a052ff0f1481"
}
*/

#ifndef _FLEXFLOW_LIB_PCG_INCLUDE_PCG_OPTIMIZERS_SGD_OPTIMIZER_ATTRS_DTG_H
#define _FLEXFLOW_LIB_PCG_INCLUDE_PCG_OPTIMIZERS_SGD_OPTIMIZER_ATTRS_DTG_H

#include <tuple>
#include <iostream>
#include <ostream>
#include <rapidcheck.h>
#include <fmt/format.h>
#include <nlohmann/json.hpp>
#include <functional>


namespace FlexFlow{struct SGDOptimizerAttrs{SGDOptimizerAttrs() = delete;
explicit SGDOptimizerAttrs(double const &lr, double const &momentum, bool const &nesterov, double const &weight_decay);

bool operator==(SGDOptimizerAttrs const &) const;bool operator!=(SGDOptimizerAttrs const &) const;
bool operator<(SGDOptimizerAttrs const &) const;bool operator>(SGDOptimizerAttrs const &) const;bool operator<=(SGDOptimizerAttrs const &) const;bool operator>=(SGDOptimizerAttrs const &) const;
std::string debug_to_string() const;void debug_print() const;
double lr;
double momentum;
bool nesterov;
double weight_decay;
};}// namespace FlexFlow


///\cond
namespace std{template <>
struct hash<::FlexFlow::SGDOptimizerAttrs>{size_t operator()(::FlexFlow::SGDOptimizerAttrs const &)const;};}// namespace std

///\endcond

namespace nlohmann{template <>
struct adl_serializer<::FlexFlow::SGDOptimizerAttrs>{static ::FlexFlow::SGDOptimizerAttrs from_json(json const &);
static void to_json(json &, ::FlexFlow::SGDOptimizerAttrs const &);
};}// namespace nlohmann

namespace rc{template <>
struct Arbitrary<::FlexFlow::SGDOptimizerAttrs>{static Gen<::FlexFlow::SGDOptimizerAttrs> arbitrary();
};}// namespace rc

namespace FlexFlow{std::string format_as(SGDOptimizerAttrs const &);
std::ostream &operator<<(std::ostream &, SGDOptimizerAttrs const &);}// namespace FlexFlow

#endif // _FLEXFLOW_LIB_PCG_INCLUDE_PCG_OPTIMIZERS_SGD_OPTIMIZER_ATTRS_DTG_H
