// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/substitutions/include/substitutions/pcg_pattern_match.dtg.toml
/* proj-data
{
  "generated_from": "52fb606f73ff31586f304ad38c0b8984"
}
*/

#ifndef _FLEXFLOW_LIB_SUBSTITUTIONS_INCLUDE_SUBSTITUTIONS_PCG_PATTERN_MATCH_DTG_H
#define _FLEXFLOW_LIB_SUBSTITUTIONS_INCLUDE_SUBSTITUTIONS_PCG_PATTERN_MATCH_DTG_H

#include <tuple>
#include <iostream>
#include "utils/bidict/bidict.h"
#include "substitutions/unlabelled/pattern_input.dtg.h"
#include <map>
#include <ostream>
#include "pcg/parallel_computation_graph/parallel_layer_guid_t.dtg.h"
#include "substitutions/unlabelled/pattern_node.dtg.h"
#include <fmt/format.h>
#include <nlohmann/json.hpp>
#include <functional>
#include "substitutions/open_parallel_tensor_guid_t.dtg.h"


namespace FlexFlow{struct PCGPatternMatch{PCGPatternMatch() = delete;
explicit PCGPatternMatch(::FlexFlow::bidict<::FlexFlow::PatternNode, ::FlexFlow::parallel_layer_guid_t> const &node_assignment, std::map<::FlexFlow::PatternInput, ::FlexFlow::open_parallel_tensor_guid_t> const &input_assignment);

bool operator==(PCGPatternMatch const &) const;bool operator!=(PCGPatternMatch const &) const;
bool operator<(PCGPatternMatch const &) const;bool operator>(PCGPatternMatch const &) const;bool operator<=(PCGPatternMatch const &) const;bool operator>=(PCGPatternMatch const &) const;
std::string debug_to_string() const;void debug_print() const;
::FlexFlow::bidict<::FlexFlow::PatternNode, ::FlexFlow::parallel_layer_guid_t> node_assignment;
std::map<::FlexFlow::PatternInput, ::FlexFlow::open_parallel_tensor_guid_t> input_assignment;
};}// namespace FlexFlow


///\cond
namespace std{template <>
struct hash<::FlexFlow::PCGPatternMatch>{size_t operator()(::FlexFlow::PCGPatternMatch const &)const;};}// namespace std

///\endcond

namespace nlohmann{template <>
struct adl_serializer<::FlexFlow::PCGPatternMatch>{static void to_json(json &, ::FlexFlow::PCGPatternMatch const &);
};}// namespace nlohmann

namespace FlexFlow{std::string format_as(PCGPatternMatch const &);
std::ostream &operator<<(std::ostream &, PCGPatternMatch const &);}// namespace FlexFlow

#endif // _FLEXFLOW_LIB_SUBSTITUTIONS_INCLUDE_SUBSTITUTIONS_PCG_PATTERN_MATCH_DTG_H
