// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/substitutions/include/substitutions/sub_parallel_computation_graph_edge.dtg.toml
/* proj-data
{
  "generated_from": "2f3e377f6d785c6f3c0fc187fc0d0851"
}
*/

#ifndef _FLEXFLOW_LIB_SUBSTITUTIONS_INCLUDE_SUBSTITUTIONS_SUB_PARALLEL_COMPUTATION_GRAPH_EDGE_DTG_H
#define _FLEXFLOW_LIB_SUBSTITUTIONS_INCLUDE_SUBSTITUTIONS_SUB_PARALLEL_COMPUTATION_GRAPH_EDGE_DTG_H

#include <tuple>
#include <iostream>
#include <ostream>
#include "utils/graph/open_kwarg_dataflow_graph/open_kwarg_dataflow_edge.dtg.h"
#include <fmt/format.h>
#include "op-attrs/tensor_slot_name.dtg.h"
#include <nlohmann/json.hpp>
#include <functional>


namespace FlexFlow{struct SubParallelComputationGraphEdge{SubParallelComputationGraphEdge() = delete;
explicit SubParallelComputationGraphEdge(::FlexFlow::OpenKwargDataflowEdge<int, ::FlexFlow::TensorSlotName> const &raw_edge);

bool operator==(SubParallelComputationGraphEdge const &) const;bool operator!=(SubParallelComputationGraphEdge const &) const;
bool operator<(SubParallelComputationGraphEdge const &) const;bool operator>(SubParallelComputationGraphEdge const &) const;bool operator<=(SubParallelComputationGraphEdge const &) const;bool operator>=(SubParallelComputationGraphEdge const &) const;
std::string debug_to_string() const;void debug_print() const;
::FlexFlow::OpenKwargDataflowEdge<int, ::FlexFlow::TensorSlotName> raw_edge;
};}// namespace FlexFlow


///\cond
namespace std{template <>
struct hash<::FlexFlow::SubParallelComputationGraphEdge>{size_t operator()(::FlexFlow::SubParallelComputationGraphEdge const &)const;};}// namespace std

///\endcond

namespace nlohmann{template <>
struct adl_serializer<::FlexFlow::SubParallelComputationGraphEdge>{static void to_json(json &, ::FlexFlow::SubParallelComputationGraphEdge const &);
};}// namespace nlohmann

namespace FlexFlow{std::string format_as(SubParallelComputationGraphEdge const &);
std::ostream &operator<<(std::ostream &, SubParallelComputationGraphEdge const &);}// namespace FlexFlow

#endif // _FLEXFLOW_LIB_SUBSTITUTIONS_INCLUDE_SUBSTITUTIONS_SUB_PARALLEL_COMPUTATION_GRAPH_EDGE_DTG_H
