// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/models/include/models/yolov10/yolov10_scaling_config.dtg.toml
/* proj-data
{
  "generated_from": "0df9f211e8c29f34ceb23cc0564abe72"
}
*/

#include "models/yolov10/yolov10_scaling_config.dtg.h"

#include <sstream>

namespace FlexFlow{YOLOv10ScalingConfig::YOLOv10ScalingConfig(float const &depth_scaling_factor, float const &width_scaling_factor, ::FlexFlow::positive_int const &max_channels) : depth_scaling_factor(depth_scaling_factor), width_scaling_factor(width_scaling_factor), max_channels(max_channels){}
bool YOLOv10ScalingConfig::operator==(YOLOv10ScalingConfig const &other) const{
return std::tie(this->depth_scaling_factor, this->width_scaling_factor, this->max_channels) == std::tie(other.depth_scaling_factor, other.width_scaling_factor, other.max_channels);
}bool YOLOv10ScalingConfig::operator!=(YOLOv10ScalingConfig const &other) const{
return std::tie(this->depth_scaling_factor, this->width_scaling_factor, this->max_channels) != std::tie(other.depth_scaling_factor, other.width_scaling_factor, other.max_channels);
}bool YOLOv10ScalingConfig::operator<(YOLOv10ScalingConfig const &other) const{
return std::tie(this->depth_scaling_factor, this->width_scaling_factor, this->max_channels) < std::tie(other.depth_scaling_factor, other.width_scaling_factor, other.max_channels);
}bool YOLOv10ScalingConfig::operator>(YOLOv10ScalingConfig const &other) const{
return std::tie(this->depth_scaling_factor, this->width_scaling_factor, this->max_channels) > std::tie(other.depth_scaling_factor, other.width_scaling_factor, other.max_channels);
}bool YOLOv10ScalingConfig::operator<=(YOLOv10ScalingConfig const &other) const{
return std::tie(this->depth_scaling_factor, this->width_scaling_factor, this->max_channels) <= std::tie(other.depth_scaling_factor, other.width_scaling_factor, other.max_channels);
}bool YOLOv10ScalingConfig::operator>=(YOLOv10ScalingConfig const &other) const{
return std::tie(this->depth_scaling_factor, this->width_scaling_factor, this->max_channels) >= std::tie(other.depth_scaling_factor, other.width_scaling_factor, other.max_channels);
}}// namespace FlexFlow


///\cond
namespace std{size_t hash<FlexFlow::YOLOv10ScalingConfig>::operator()(::FlexFlow::YOLOv10ScalingConfig const &x)const{size_t result = 0;
result ^= std::hash<float>{}(x.depth_scaling_factor) + 0x9e3779b9 + (result << 6) + (result >> 2);result ^= std::hash<float>{}(x.width_scaling_factor) + 0x9e3779b9 + (result << 6) + (result >> 2);result ^= std::hash<::FlexFlow::positive_int>{}(x.max_channels) + 0x9e3779b9 + (result << 6) + (result >> 2);return result;
}}// namespace std

///\endcond

namespace nlohmann{void adl_serializer<::FlexFlow::YOLOv10ScalingConfig>::to_json(json &j, ::FlexFlow::YOLOv10ScalingConfig const &v) {j["__type"] = "YOLOv10ScalingConfig";
j["depth_scaling_factor"] = v.depth_scaling_factor;
j["width_scaling_factor"] = v.width_scaling_factor;
j["max_channels"] = v.max_channels;
}}// namespace nlohmann

namespace nlohmann{::FlexFlow::YOLOv10ScalingConfig adl_serializer<::FlexFlow::YOLOv10ScalingConfig>::from_json(json const &j) {return ::FlexFlow::YOLOv10ScalingConfig{j.at("depth_scaling_factor").template get<float>(), j.at("width_scaling_factor").template get<float>(), j.at("max_channels").template get<::FlexFlow::positive_int>()};}}// namespace nlohmann

namespace rc{Gen<::FlexFlow::YOLOv10ScalingConfig> Arbitrary<::FlexFlow::YOLOv10ScalingConfig>::arbitrary() {return gen::construct<::FlexFlow::YOLOv10ScalingConfig>(gen::arbitrary<float>(), gen::arbitrary<float>(), gen::arbitrary<::FlexFlow::positive_int>());}}// namespace rc

namespace FlexFlow{std::string YOLOv10ScalingConfig::debug_to_string() const { return fmt::to_string(*this); }void YOLOv10ScalingConfig::debug_print() const { std::cout << this->debug_to_string() << std::endl; }std::string format_as(YOLOv10ScalingConfig const &x){::nlohmann::json j = x;
return j.dump();
}std::ostream &operator<<(std::ostream &s, YOLOv10ScalingConfig const &x) {return s << fmt::to_string(x);}}// namespace FlexFlow
