// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/models/include/models/yolov10/yolov10_layer_config_psa.dtg.toml
/* proj-data
{
  "generated_from": "7be1571c3a7f40b78f160495c984050f"
}
*/

#include "models/yolov10/yolov10_layer_config_psa.dtg.h"

#include <sstream>

namespace FlexFlow{YOLOv10LayerConfigPSA::YOLOv10LayerConfigPSA(::FlexFlow::yolov10_tensor_idx_t const &input_tensor_idx, ::FlexFlow::positive_int const &num_output_channels) : input_tensor_idx(input_tensor_idx), num_output_channels(num_output_channels){}
bool YOLOv10LayerConfigPSA::operator==(YOLOv10LayerConfigPSA const &other) const{
return std::tie(this->input_tensor_idx, this->num_output_channels) == std::tie(other.input_tensor_idx, other.num_output_channels);
}bool YOLOv10LayerConfigPSA::operator!=(YOLOv10LayerConfigPSA const &other) const{
return std::tie(this->input_tensor_idx, this->num_output_channels) != std::tie(other.input_tensor_idx, other.num_output_channels);
}bool YOLOv10LayerConfigPSA::operator<(YOLOv10LayerConfigPSA const &other) const{
return std::tie(this->input_tensor_idx, this->num_output_channels) < std::tie(other.input_tensor_idx, other.num_output_channels);
}bool YOLOv10LayerConfigPSA::operator>(YOLOv10LayerConfigPSA const &other) const{
return std::tie(this->input_tensor_idx, this->num_output_channels) > std::tie(other.input_tensor_idx, other.num_output_channels);
}bool YOLOv10LayerConfigPSA::operator<=(YOLOv10LayerConfigPSA const &other) const{
return std::tie(this->input_tensor_idx, this->num_output_channels) <= std::tie(other.input_tensor_idx, other.num_output_channels);
}bool YOLOv10LayerConfigPSA::operator>=(YOLOv10LayerConfigPSA const &other) const{
return std::tie(this->input_tensor_idx, this->num_output_channels) >= std::tie(other.input_tensor_idx, other.num_output_channels);
}}// namespace FlexFlow


///\cond
namespace std{size_t hash<FlexFlow::YOLOv10LayerConfigPSA>::operator()(::FlexFlow::YOLOv10LayerConfigPSA const &x)const{size_t result = 0;
result ^= std::hash<::FlexFlow::yolov10_tensor_idx_t>{}(x.input_tensor_idx) + 0x9e3779b9 + (result << 6) + (result >> 2);result ^= std::hash<::FlexFlow::positive_int>{}(x.num_output_channels) + 0x9e3779b9 + (result << 6) + (result >> 2);return result;
}}// namespace std

///\endcond

namespace nlohmann{void adl_serializer<::FlexFlow::YOLOv10LayerConfigPSA>::to_json(json &j, ::FlexFlow::YOLOv10LayerConfigPSA const &v) {j["__type"] = "YOLOv10LayerConfigPSA";
j["input_tensor_idx"] = v.input_tensor_idx;
j["num_output_channels"] = v.num_output_channels;
}}// namespace nlohmann

namespace nlohmann{::FlexFlow::YOLOv10LayerConfigPSA adl_serializer<::FlexFlow::YOLOv10LayerConfigPSA>::from_json(json const &j) {return ::FlexFlow::YOLOv10LayerConfigPSA{j.at("input_tensor_idx").template get<::FlexFlow::yolov10_tensor_idx_t>(), j.at("num_output_channels").template get<::FlexFlow::positive_int>()};}}// namespace nlohmann

namespace rc{Gen<::FlexFlow::YOLOv10LayerConfigPSA> Arbitrary<::FlexFlow::YOLOv10LayerConfigPSA>::arbitrary() {return gen::construct<::FlexFlow::YOLOv10LayerConfigPSA>(gen::arbitrary<::FlexFlow::yolov10_tensor_idx_t>(), gen::arbitrary<::FlexFlow::positive_int>());}}// namespace rc

namespace FlexFlow{std::string YOLOv10LayerConfigPSA::debug_to_string() const { return fmt::to_string(*this); }void YOLOv10LayerConfigPSA::debug_print() const { std::cout << this->debug_to_string() << std::endl; }std::string format_as(YOLOv10LayerConfigPSA const &x){::nlohmann::json j = x;
return j.dump();
}std::ostream &operator<<(std::ostream &s, YOLOv10LayerConfigPSA const &x) {return s << fmt::to_string(x);}}// namespace FlexFlow
