// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/models/include/models/yolov10/yolov10_detect_head_outputs.dtg.toml
/* proj-data
{
  "generated_from": "fa9dbed99a3f5f5206cda56df870e466"
}
*/

#include "models/yolov10/yolov10_detect_head_outputs.dtg.h"

#include <sstream>

namespace FlexFlow{YOLOv10DetectHeadOutputs::YOLOv10DetectHeadOutputs(::FlexFlow::tensor_guid_t const &boxes, ::FlexFlow::tensor_guid_t const &scores) : boxes(boxes), scores(scores){}
bool YOLOv10DetectHeadOutputs::operator==(YOLOv10DetectHeadOutputs const &other) const{
return std::tie(this->boxes, this->scores) == std::tie(other.boxes, other.scores);
}bool YOLOv10DetectHeadOutputs::operator!=(YOLOv10DetectHeadOutputs const &other) const{
return std::tie(this->boxes, this->scores) != std::tie(other.boxes, other.scores);
}bool YOLOv10DetectHeadOutputs::operator<(YOLOv10DetectHeadOutputs const &other) const{
return std::tie(this->boxes, this->scores) < std::tie(other.boxes, other.scores);
}bool YOLOv10DetectHeadOutputs::operator>(YOLOv10DetectHeadOutputs const &other) const{
return std::tie(this->boxes, this->scores) > std::tie(other.boxes, other.scores);
}bool YOLOv10DetectHeadOutputs::operator<=(YOLOv10DetectHeadOutputs const &other) const{
return std::tie(this->boxes, this->scores) <= std::tie(other.boxes, other.scores);
}bool YOLOv10DetectHeadOutputs::operator>=(YOLOv10DetectHeadOutputs const &other) const{
return std::tie(this->boxes, this->scores) >= std::tie(other.boxes, other.scores);
}}// namespace FlexFlow


///\cond
namespace std{size_t hash<FlexFlow::YOLOv10DetectHeadOutputs>::operator()(::FlexFlow::YOLOv10DetectHeadOutputs const &x)const{size_t result = 0;
result ^= std::hash<::FlexFlow::tensor_guid_t>{}(x.boxes) + 0x9e3779b9 + (result << 6) + (result >> 2);result ^= std::hash<::FlexFlow::tensor_guid_t>{}(x.scores) + 0x9e3779b9 + (result << 6) + (result >> 2);return result;
}}// namespace std

///\endcond

namespace nlohmann{void adl_serializer<::FlexFlow::YOLOv10DetectHeadOutputs>::to_json(json &j, ::FlexFlow::YOLOv10DetectHeadOutputs const &v) {j["__type"] = "YOLOv10DetectHeadOutputs";
j["boxes"] = v.boxes;
j["scores"] = v.scores;
}}// namespace nlohmann

namespace nlohmann{::FlexFlow::YOLOv10DetectHeadOutputs adl_serializer<::FlexFlow::YOLOv10DetectHeadOutputs>::from_json(json const &j) {return ::FlexFlow::YOLOv10DetectHeadOutputs{j.at("boxes").template get<::FlexFlow::tensor_guid_t>(), j.at("scores").template get<::FlexFlow::tensor_guid_t>()};}}// namespace nlohmann

namespace FlexFlow{std::string YOLOv10DetectHeadOutputs::debug_to_string() const { return fmt::to_string(*this); }void YOLOv10DetectHeadOutputs::debug_print() const { std::cout << this->debug_to_string() << std::endl; }std::string format_as(YOLOv10DetectHeadOutputs const &x){::nlohmann::json j = x;
return j.dump();
}std::ostream &operator<<(std::ostream &s, YOLOv10DetectHeadOutputs const &x) {return s << fmt::to_string(x);}}// namespace FlexFlow
