// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/models/include/models/yolov10/yolov10_layer_config_concat.dtg.toml
/* proj-data
{
  "generated_from": "b3ed3873ecae6d6cf16ed08baf2d01a1"
}
*/

#include "models/yolov10/yolov10_layer_config_concat.dtg.h"

#include "utils/fmt/vector.h"
#include "utils/hash/vector.h"
#include <sstream>
#include "utils/ord/vector.h"

namespace FlexFlow{YOLOv10LayerConfigConcat::YOLOv10LayerConfigConcat(std::vector<::FlexFlow::yolov10_tensor_idx_t> const &input_tensor_idxs, ::FlexFlow::relative_ff_dim_t const &dim) : input_tensor_idxs(input_tensor_idxs), dim(dim){}
bool YOLOv10LayerConfigConcat::operator==(YOLOv10LayerConfigConcat const &other) const{
return std::tie(this->input_tensor_idxs, this->dim) == std::tie(other.input_tensor_idxs, other.dim);
}bool YOLOv10LayerConfigConcat::operator!=(YOLOv10LayerConfigConcat const &other) const{
return std::tie(this->input_tensor_idxs, this->dim) != std::tie(other.input_tensor_idxs, other.dim);
}bool YOLOv10LayerConfigConcat::operator<(YOLOv10LayerConfigConcat const &other) const{
return std::tie(this->input_tensor_idxs, this->dim) < std::tie(other.input_tensor_idxs, other.dim);
}bool YOLOv10LayerConfigConcat::operator>(YOLOv10LayerConfigConcat const &other) const{
return std::tie(this->input_tensor_idxs, this->dim) > std::tie(other.input_tensor_idxs, other.dim);
}bool YOLOv10LayerConfigConcat::operator<=(YOLOv10LayerConfigConcat const &other) const{
return std::tie(this->input_tensor_idxs, this->dim) <= std::tie(other.input_tensor_idxs, other.dim);
}bool YOLOv10LayerConfigConcat::operator>=(YOLOv10LayerConfigConcat const &other) const{
return std::tie(this->input_tensor_idxs, this->dim) >= std::tie(other.input_tensor_idxs, other.dim);
}}// namespace FlexFlow


///\cond
namespace std{size_t hash<FlexFlow::YOLOv10LayerConfigConcat>::operator()(::FlexFlow::YOLOv10LayerConfigConcat const &x)const{size_t result = 0;
result ^= std::hash<std::vector<::FlexFlow::yolov10_tensor_idx_t>>{}(x.input_tensor_idxs) + 0x9e3779b9 + (result << 6) + (result >> 2);result ^= std::hash<::FlexFlow::relative_ff_dim_t>{}(x.dim) + 0x9e3779b9 + (result << 6) + (result >> 2);return result;
}}// namespace std

///\endcond

namespace nlohmann{void adl_serializer<::FlexFlow::YOLOv10LayerConfigConcat>::to_json(json &j, ::FlexFlow::YOLOv10LayerConfigConcat const &v) {j["__type"] = "YOLOv10LayerConfigConcat";
j["input_tensor_idxs"] = v.input_tensor_idxs;
j["dim"] = v.dim;
}}// namespace nlohmann

namespace nlohmann{::FlexFlow::YOLOv10LayerConfigConcat adl_serializer<::FlexFlow::YOLOv10LayerConfigConcat>::from_json(json const &j) {return ::FlexFlow::YOLOv10LayerConfigConcat{j.at("input_tensor_idxs").template get<std::vector<::FlexFlow::yolov10_tensor_idx_t>>(), j.at("dim").template get<::FlexFlow::relative_ff_dim_t>()};}}// namespace nlohmann

namespace FlexFlow{std::string YOLOv10LayerConfigConcat::debug_to_string() const { return fmt::to_string(*this); }void YOLOv10LayerConfigConcat::debug_print() const { std::cout << this->debug_to_string() << std::endl; }std::string format_as(YOLOv10LayerConfigConcat const &x){::nlohmann::json j = x;
return j.dump();
}std::ostream &operator<<(std::ostream &s, YOLOv10LayerConfigConcat const &x) {return s << fmt::to_string(x);}}// namespace FlexFlow
