// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/models/include/models/yolov10/yolov10_layer_config_c2f.dtg.toml
/* proj-data
{
  "generated_from": "7b42c145f8602c5255a4677711e89382"
}
*/

#include "models/yolov10/yolov10_layer_config_c2f.dtg.h"

#include <sstream>

namespace FlexFlow{YOLOv10LayerConfigC2f::YOLOv10LayerConfigC2f(::FlexFlow::yolov10_tensor_idx_t const &input_tensor_idx, ::FlexFlow::positive_int const &num_output_channels, ::FlexFlow::positive_int const &num_bottleneck_blocks, bool const &use_shortcut_connection) : input_tensor_idx(input_tensor_idx), num_output_channels(num_output_channels), num_bottleneck_blocks(num_bottleneck_blocks), use_shortcut_connection(use_shortcut_connection){}
bool YOLOv10LayerConfigC2f::operator==(YOLOv10LayerConfigC2f const &other) const{
return std::tie(this->input_tensor_idx, this->num_output_channels, this->num_bottleneck_blocks, this->use_shortcut_connection) == std::tie(other.input_tensor_idx, other.num_output_channels, other.num_bottleneck_blocks, other.use_shortcut_connection);
}bool YOLOv10LayerConfigC2f::operator!=(YOLOv10LayerConfigC2f const &other) const{
return std::tie(this->input_tensor_idx, this->num_output_channels, this->num_bottleneck_blocks, this->use_shortcut_connection) != std::tie(other.input_tensor_idx, other.num_output_channels, other.num_bottleneck_blocks, other.use_shortcut_connection);
}bool YOLOv10LayerConfigC2f::operator<(YOLOv10LayerConfigC2f const &other) const{
return std::tie(this->input_tensor_idx, this->num_output_channels, this->num_bottleneck_blocks, this->use_shortcut_connection) < std::tie(other.input_tensor_idx, other.num_output_channels, other.num_bottleneck_blocks, other.use_shortcut_connection);
}bool YOLOv10LayerConfigC2f::operator>(YOLOv10LayerConfigC2f const &other) const{
return std::tie(this->input_tensor_idx, this->num_output_channels, this->num_bottleneck_blocks, this->use_shortcut_connection) > std::tie(other.input_tensor_idx, other.num_output_channels, other.num_bottleneck_blocks, other.use_shortcut_connection);
}bool YOLOv10LayerConfigC2f::operator<=(YOLOv10LayerConfigC2f const &other) const{
return std::tie(this->input_tensor_idx, this->num_output_channels, this->num_bottleneck_blocks, this->use_shortcut_connection) <= std::tie(other.input_tensor_idx, other.num_output_channels, other.num_bottleneck_blocks, other.use_shortcut_connection);
}bool YOLOv10LayerConfigC2f::operator>=(YOLOv10LayerConfigC2f const &other) const{
return std::tie(this->input_tensor_idx, this->num_output_channels, this->num_bottleneck_blocks, this->use_shortcut_connection) >= std::tie(other.input_tensor_idx, other.num_output_channels, other.num_bottleneck_blocks, other.use_shortcut_connection);
}}// namespace FlexFlow


///\cond
namespace std{size_t hash<FlexFlow::YOLOv10LayerConfigC2f>::operator()(::FlexFlow::YOLOv10LayerConfigC2f const &x)const{size_t result = 0;
result ^= std::hash<::FlexFlow::yolov10_tensor_idx_t>{}(x.input_tensor_idx) + 0x9e3779b9 + (result << 6) + (result >> 2);result ^= std::hash<::FlexFlow::positive_int>{}(x.num_output_channels) + 0x9e3779b9 + (result << 6) + (result >> 2);result ^= std::hash<::FlexFlow::positive_int>{}(x.num_bottleneck_blocks) + 0x9e3779b9 + (result << 6) + (result >> 2);result ^= std::hash<bool>{}(x.use_shortcut_connection) + 0x9e3779b9 + (result << 6) + (result >> 2);return result;
}}// namespace std

///\endcond

namespace nlohmann{void adl_serializer<::FlexFlow::YOLOv10LayerConfigC2f>::to_json(json &j, ::FlexFlow::YOLOv10LayerConfigC2f const &v) {j["__type"] = "YOLOv10LayerConfigC2f";
j["input_tensor_idx"] = v.input_tensor_idx;
j["num_output_channels"] = v.num_output_channels;
j["num_bottleneck_blocks"] = v.num_bottleneck_blocks;
j["use_shortcut_connection"] = v.use_shortcut_connection;
}}// namespace nlohmann

namespace nlohmann{::FlexFlow::YOLOv10LayerConfigC2f adl_serializer<::FlexFlow::YOLOv10LayerConfigC2f>::from_json(json const &j) {return ::FlexFlow::YOLOv10LayerConfigC2f{j.at("input_tensor_idx").template get<::FlexFlow::yolov10_tensor_idx_t>(), j.at("num_output_channels").template get<::FlexFlow::positive_int>(), j.at("num_bottleneck_blocks").template get<::FlexFlow::positive_int>(), j.at("use_shortcut_connection").template get<bool>()};}}// namespace nlohmann

namespace rc{Gen<::FlexFlow::YOLOv10LayerConfigC2f> Arbitrary<::FlexFlow::YOLOv10LayerConfigC2f>::arbitrary() {return gen::construct<::FlexFlow::YOLOv10LayerConfigC2f>(gen::arbitrary<::FlexFlow::yolov10_tensor_idx_t>(), gen::arbitrary<::FlexFlow::positive_int>(), gen::arbitrary<::FlexFlow::positive_int>(), gen::arbitrary<bool>());}}// namespace rc

namespace FlexFlow{std::string YOLOv10LayerConfigC2f::debug_to_string() const { return fmt::to_string(*this); }void YOLOv10LayerConfigC2f::debug_print() const { std::cout << this->debug_to_string() << std::endl; }std::string format_as(YOLOv10LayerConfigC2f const &x){::nlohmann::json j = x;
return j.dump();
}std::ostream &operator<<(std::ostream &s, YOLOv10LayerConfigC2f const &x) {return s << fmt::to_string(x);}}// namespace FlexFlow
