// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/task-spec/include/task-spec/dynamic_graph/dynamic_node_invocation.dtg.toml
/* proj-data
{
  "generated_from": "3b443f3210d4fd60991f6abb5a7b0899"
}
*/

#ifndef _FLEXFLOW_LIB_TASK_SPEC_INCLUDE_TASK_SPEC_DYNAMIC_GRAPH_DYNAMIC_NODE_INVOCATION_DTG_H
#define _FLEXFLOW_LIB_TASK_SPEC_INCLUDE_TASK_SPEC_DYNAMIC_GRAPH_DYNAMIC_NODE_INVOCATION_DTG_H

#include <tuple>
#include <iostream>
#include <map>
#include "task-spec/dynamic_graph/dynamic_tensor_slot.dtg.h"
#include "task-spec/dynamic_graph/dynamic_value_attrs.dtg.h"
#include <ostream>
#include "task-spec/dynamic_graph/dynamic_node_attrs.dtg.h"
#include <fmt/format.h>
#include <nlohmann/json.hpp>
#include <functional>


namespace FlexFlow{struct DynamicNodeInvocation{DynamicNodeInvocation() = delete;
explicit DynamicNodeInvocation(std::map<::FlexFlow::DynamicTensorSlot, ::FlexFlow::DynamicValueAttrs> const &inputs, ::FlexFlow::DynamicNodeAttrs const &node_attrs, std::map<::FlexFlow::DynamicTensorSlot, ::FlexFlow::DynamicValueAttrs> const &outputs);

bool operator==(DynamicNodeInvocation const &) const;bool operator!=(DynamicNodeInvocation const &) const;
bool operator<(DynamicNodeInvocation const &) const;bool operator>(DynamicNodeInvocation const &) const;bool operator<=(DynamicNodeInvocation const &) const;bool operator>=(DynamicNodeInvocation const &) const;
std::string debug_to_string() const;void debug_print() const;
std::map<::FlexFlow::DynamicTensorSlot, ::FlexFlow::DynamicValueAttrs> inputs;
::FlexFlow::DynamicNodeAttrs node_attrs;
std::map<::FlexFlow::DynamicTensorSlot, ::FlexFlow::DynamicValueAttrs> outputs;
};}// namespace FlexFlow


///\cond
namespace std{template <>
struct hash<::FlexFlow::DynamicNodeInvocation>{size_t operator()(::FlexFlow::DynamicNodeInvocation const &)const;};}// namespace std

///\endcond

namespace nlohmann{template <>
struct adl_serializer<::FlexFlow::DynamicNodeInvocation>{static void to_json(json &, ::FlexFlow::DynamicNodeInvocation const &);
};}// namespace nlohmann

namespace FlexFlow{std::string format_as(DynamicNodeInvocation const &);
std::ostream &operator<<(std::ostream &, DynamicNodeInvocation const &);}// namespace FlexFlow

#endif // _FLEXFLOW_LIB_TASK_SPEC_INCLUDE_TASK_SPEC_DYNAMIC_GRAPH_DYNAMIC_NODE_INVOCATION_DTG_H
