// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/task-spec/include/task-spec/dynamic_graph/dynamic_task_type.dtg.toml
/* proj-data
{
  "generated_from": "21ba512fc2437cc10860947c0b29a914"
}
*/

#ifndef _FLEXFLOW_LIB_TASK_SPEC_INCLUDE_TASK_SPEC_DYNAMIC_GRAPH_DYNAMIC_TASK_TYPE_DTG_H
#define _FLEXFLOW_LIB_TASK_SPEC_INCLUDE_TASK_SPEC_DYNAMIC_GRAPH_DYNAMIC_TASK_TYPE_DTG_H

#include <string>
#include <ostream>
#include <fmt/format.h>
#include <nlohmann/json.hpp>
#include <functional>
#include <rapidcheck.h>

namespace FlexFlow{enum class DynamicTaskType{FWD, BWD, UPD, LOSS};std::string format_as(DynamicTaskType);
std::ostream &operator<<(std::ostream &, DynamicTaskType);
void to_json(::nlohmann::json &, DynamicTaskType);
void from_json(::nlohmann::json const &, DynamicTaskType &);
}// namespace FlexFlow

///\cond
namespace std{template <>
struct hash<FlexFlow::DynamicTaskType> {size_t operator()(FlexFlow::DynamicTaskType) const;
};}// namespace std

///\endcond
namespace rc{template <>
struct Arbitrary<FlexFlow::DynamicTaskType> {static Gen<FlexFlow::DynamicTaskType> arbitrary();
};}// namespace rc

#endif // _FLEXFLOW_LIB_TASK_SPEC_INCLUDE_TASK_SPEC_DYNAMIC_GRAPH_DYNAMIC_TASK_TYPE_DTG_H
