// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/task-spec/include/task-spec/dynamic_graph/dynamic_loss_config.dtg.toml
/* proj-data
{
  "generated_from": "847cf55ec51b6a34954aa44f67cc619e"
}
*/

#ifndef _FLEXFLOW_LIB_TASK_SPEC_INCLUDE_TASK_SPEC_DYNAMIC_GRAPH_DYNAMIC_LOSS_CONFIG_DTG_H
#define _FLEXFLOW_LIB_TASK_SPEC_INCLUDE_TASK_SPEC_DYNAMIC_GRAPH_DYNAMIC_LOSS_CONFIG_DTG_H

#include <tuple>
#include <iostream>
#include "op-attrs/ops/loss_functions/loss_attrs.dtg.h"
#include <ostream>
#include <fmt/format.h>
#include <nlohmann/json.hpp>
#include <functional>
#include "task-spec/dynamic_graph/dynamic_value_guid_t.dtg.h"


namespace FlexFlow{struct DynamicLossConfig{DynamicLossConfig() = delete;
explicit DynamicLossConfig(::FlexFlow::LossAttrs const &loss_attrs, ::FlexFlow::dynamic_value_guid_t const &logit_tensor, ::FlexFlow::dynamic_value_guid_t const &logit_grad_tensor, ::FlexFlow::dynamic_value_guid_t const &label_tensor);

bool operator==(DynamicLossConfig const &) const;bool operator!=(DynamicLossConfig const &) const;
bool operator<(DynamicLossConfig const &) const;bool operator>(DynamicLossConfig const &) const;bool operator<=(DynamicLossConfig const &) const;bool operator>=(DynamicLossConfig const &) const;
std::string debug_to_string() const;void debug_print() const;
::FlexFlow::LossAttrs loss_attrs;
::FlexFlow::dynamic_value_guid_t logit_tensor;
::FlexFlow::dynamic_value_guid_t logit_grad_tensor;
::FlexFlow::dynamic_value_guid_t label_tensor;
};}// namespace FlexFlow


///\cond
namespace std{template <>
struct hash<::FlexFlow::DynamicLossConfig>{size_t operator()(::FlexFlow::DynamicLossConfig const &)const;};}// namespace std

///\endcond

namespace nlohmann{template <>
struct adl_serializer<::FlexFlow::DynamicLossConfig>{static void to_json(json &, ::FlexFlow::DynamicLossConfig const &);
};}// namespace nlohmann

namespace FlexFlow{std::string format_as(DynamicLossConfig const &);
std::ostream &operator<<(std::ostream &, DynamicLossConfig const &);}// namespace FlexFlow

#endif // _FLEXFLOW_LIB_TASK_SPEC_INCLUDE_TASK_SPEC_DYNAMIC_GRAPH_DYNAMIC_LOSS_CONFIG_DTG_H
