// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/task-spec/include/task-spec/dynamic_graph/dynamic_loss_tensor_guid_t.dtg.toml
/* proj-data
{
  "generated_from": "4fc12ba70f899566c44c2949eaeef2d3"
}
*/

#ifndef _FLEXFLOW_LIB_TASK_SPEC_INCLUDE_TASK_SPEC_DYNAMIC_GRAPH_DYNAMIC_LOSS_TENSOR_GUID_T_DTG_H
#define _FLEXFLOW_LIB_TASK_SPEC_INCLUDE_TASK_SPEC_DYNAMIC_GRAPH_DYNAMIC_LOSS_TENSOR_GUID_T_DTG_H

#include <tuple>
#include <iostream>
#include <ostream>
#include <rapidcheck.h>
#include <fmt/format.h>
#include <nlohmann/json.hpp>
#include <functional>


namespace FlexFlow{struct dynamic_loss_tensor_guid_t{
bool operator==(dynamic_loss_tensor_guid_t const &) const;bool operator!=(dynamic_loss_tensor_guid_t const &) const;
bool operator<(dynamic_loss_tensor_guid_t const &) const;bool operator>(dynamic_loss_tensor_guid_t const &) const;bool operator<=(dynamic_loss_tensor_guid_t const &) const;bool operator>=(dynamic_loss_tensor_guid_t const &) const;
std::string debug_to_string() const;void debug_print() const;
};}// namespace FlexFlow


///\cond
namespace std{template <>
struct hash<::FlexFlow::dynamic_loss_tensor_guid_t>{size_t operator()(::FlexFlow::dynamic_loss_tensor_guid_t const &)const;};}// namespace std

///\endcond

namespace nlohmann{template <>
struct adl_serializer<::FlexFlow::dynamic_loss_tensor_guid_t>{static ::FlexFlow::dynamic_loss_tensor_guid_t from_json(json const &);
static void to_json(json &, ::FlexFlow::dynamic_loss_tensor_guid_t const &);
};}// namespace nlohmann

namespace rc{template <>
struct Arbitrary<::FlexFlow::dynamic_loss_tensor_guid_t>{static Gen<::FlexFlow::dynamic_loss_tensor_guid_t> arbitrary();
};}// namespace rc

namespace FlexFlow{std::string format_as(dynamic_loss_tensor_guid_t const &);
std::ostream &operator<<(std::ostream &, dynamic_loss_tensor_guid_t const &);}// namespace FlexFlow

#endif // _FLEXFLOW_LIB_TASK_SPEC_INCLUDE_TASK_SPEC_DYNAMIC_GRAPH_DYNAMIC_LOSS_TENSOR_GUID_T_DTG_H
