// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/task-spec/include/task-spec/dynamic_graph/parallel_tensor_mapping.dtg.toml
/* proj-data
{
  "generated_from": "efcd48f478230990735d64234318897e"
}
*/

#ifndef _FLEXFLOW_LIB_TASK_SPEC_INCLUDE_TASK_SPEC_DYNAMIC_GRAPH_PARALLEL_TENSOR_MAPPING_DTG_H
#define _FLEXFLOW_LIB_TASK_SPEC_INCLUDE_TASK_SPEC_DYNAMIC_GRAPH_PARALLEL_TENSOR_MAPPING_DTG_H

#include <tuple>
#include "op-attrs/parallel_tensor_space_coordinate.dtg.h"
#include <iostream>
#include "task-spec/global_device_id_t.dtg.h"
#include <ostream>
#include <fmt/format.h>
#include <nlohmann/json.hpp>
#include <functional>
#include "utils/bidict/bidict.h"


namespace FlexFlow{struct ParallelTensorMapping{ParallelTensorMapping() = delete;
explicit ParallelTensorMapping(::FlexFlow::bidict<::FlexFlow::ParallelTensorSpaceCoordinate, ::FlexFlow::global_device_id_t> const &raw);

bool operator==(ParallelTensorMapping const &) const;bool operator!=(ParallelTensorMapping const &) const;
bool operator<(ParallelTensorMapping const &) const;bool operator>(ParallelTensorMapping const &) const;bool operator<=(ParallelTensorMapping const &) const;bool operator>=(ParallelTensorMapping const &) const;
std::string debug_to_string() const;void debug_print() const;
::FlexFlow::bidict<::FlexFlow::ParallelTensorSpaceCoordinate, ::FlexFlow::global_device_id_t> raw;
};}// namespace FlexFlow


///\cond
namespace std{template <>
struct hash<::FlexFlow::ParallelTensorMapping>{size_t operator()(::FlexFlow::ParallelTensorMapping const &)const;};}// namespace std

///\endcond

namespace nlohmann{template <>
struct adl_serializer<::FlexFlow::ParallelTensorMapping>{static ::FlexFlow::ParallelTensorMapping from_json(json const &);
static void to_json(json &, ::FlexFlow::ParallelTensorMapping const &);
};}// namespace nlohmann

namespace FlexFlow{std::string format_as(ParallelTensorMapping const &);
std::ostream &operator<<(std::ostream &, ParallelTensorMapping const &);}// namespace FlexFlow

#endif // _FLEXFLOW_LIB_TASK_SPEC_INCLUDE_TASK_SPEC_DYNAMIC_GRAPH_PARALLEL_TENSOR_MAPPING_DTG_H
