// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/task-spec/include/task-spec/dynamic_graph/serializable_dynamic_value_attrs.dtg.toml
/* proj-data
{
  "generated_from": "0cdfc7962e782cb03147f63949605aff"
}
*/

#ifndef _FLEXFLOW_LIB_TASK_SPEC_INCLUDE_TASK_SPEC_DYNAMIC_GRAPH_SERIALIZABLE_DYNAMIC_VALUE_ATTRS_DTG_H
#define _FLEXFLOW_LIB_TASK_SPEC_INCLUDE_TASK_SPEC_DYNAMIC_GRAPH_SERIALIZABLE_DYNAMIC_VALUE_ATTRS_DTG_H

#include <tuple>
#include "op-attrs/parallel_tensor_space_coordinate.dtg.h"
#include <iostream>
#include "task-spec/dynamic_graph/dynamic_tensor_guid_t.dtg.h"
#include <nlohmann/json.hpp>
#include "task-spec/dynamic_graph/parallel_tensor_mapping.dtg.h"
#include "task-spec/dynamic_graph/subgradient_id_t.dtg.h"
#include "task-spec/dynamic_graph/dynamic_tensor_role.dtg.h"
#include "pcg/machine_space_coordinate.dtg.h"
#include <ostream>
#include <fmt/format.h>
#include <optional>
#include <functional>
#include "utils/bidict/bidict.h"
#include "op-attrs/parallel_tensor_shape.dtg.h"


namespace FlexFlow{struct SerializableDynamicValueAttrs{SerializableDynamicValueAttrs() = delete;
explicit SerializableDynamicValueAttrs(::FlexFlow::dynamic_tensor_guid_t const &tensor_guid, std::optional<::FlexFlow::ParallelTensorShape> const &parallel_tensor_shape, std::optional<bool> const &create_grad, std::optional<::FlexFlow::subgradient_id_t> const &subgradient_id, std::optional<::FlexFlow::ParallelTensorSpaceCoordinate> const &shard_coord, std::optional<::FlexFlow::ParallelTensorMapping> const &mapping, std::optional<::FlexFlow::DynamicTensorRole> const &role);

bool operator==(SerializableDynamicValueAttrs const &) const;bool operator!=(SerializableDynamicValueAttrs const &) const;
bool operator<(SerializableDynamicValueAttrs const &) const;bool operator>(SerializableDynamicValueAttrs const &) const;bool operator<=(SerializableDynamicValueAttrs const &) const;bool operator>=(SerializableDynamicValueAttrs const &) const;
std::string debug_to_string() const;void debug_print() const;
::FlexFlow::dynamic_tensor_guid_t tensor_guid;
std::optional<::FlexFlow::ParallelTensorShape> parallel_tensor_shape;
std::optional<bool> create_grad;
std::optional<::FlexFlow::subgradient_id_t> subgradient_id;
std::optional<::FlexFlow::ParallelTensorSpaceCoordinate> shard_coord;
std::optional<::FlexFlow::ParallelTensorMapping> mapping;
std::optional<::FlexFlow::DynamicTensorRole> role;
};}// namespace FlexFlow


///\cond
namespace std{template <>
struct hash<::FlexFlow::SerializableDynamicValueAttrs>{size_t operator()(::FlexFlow::SerializableDynamicValueAttrs const &)const;};}// namespace std

///\endcond

namespace nlohmann{template <>
struct adl_serializer<::FlexFlow::SerializableDynamicValueAttrs>{static ::FlexFlow::SerializableDynamicValueAttrs from_json(json const &);
static void to_json(json &, ::FlexFlow::SerializableDynamicValueAttrs const &);
};}// namespace nlohmann

namespace FlexFlow{std::string format_as(SerializableDynamicValueAttrs const &);
std::ostream &operator<<(std::ostream &, SerializableDynamicValueAttrs const &);}// namespace FlexFlow

#endif // _FLEXFLOW_LIB_TASK_SPEC_INCLUDE_TASK_SPEC_DYNAMIC_GRAPH_SERIALIZABLE_DYNAMIC_VALUE_ATTRS_DTG_H
