// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/task-spec/include/task-spec/dynamic_graph/serializable_dynamic_node_invocation.dtg.toml
/* proj-data
{
  "generated_from": "76a20346fb38c5c7dc653ddb3ca9cee3"
}
*/

#ifndef _FLEXFLOW_LIB_TASK_SPEC_INCLUDE_TASK_SPEC_DYNAMIC_GRAPH_SERIALIZABLE_DYNAMIC_NODE_INVOCATION_DTG_H
#define _FLEXFLOW_LIB_TASK_SPEC_INCLUDE_TASK_SPEC_DYNAMIC_GRAPH_SERIALIZABLE_DYNAMIC_NODE_INVOCATION_DTG_H

#include <tuple>
#include <iostream>
#include "task-spec/dynamic_graph/serializable_dynamic_node_attrs.dtg.h"
#include <map>
#include "task-spec/dynamic_graph/dynamic_tensor_slot.dtg.h"
#include <ostream>
#include <fmt/format.h>
#include "task-spec/dynamic_graph/serializable_dynamic_value_attrs.dtg.h"
#include <nlohmann/json.hpp>
#include <functional>


namespace FlexFlow{struct SerializableDynamicNodeInvocation{SerializableDynamicNodeInvocation() = delete;
explicit SerializableDynamicNodeInvocation(std::map<::FlexFlow::DynamicTensorSlot, ::FlexFlow::SerializableDynamicValueAttrs> const &inputs, ::FlexFlow::SerializableDynamicNodeAttrs const &node_attrs, std::map<::FlexFlow::DynamicTensorSlot, ::FlexFlow::SerializableDynamicValueAttrs> const &outputs);

bool operator==(SerializableDynamicNodeInvocation const &) const;bool operator!=(SerializableDynamicNodeInvocation const &) const;
bool operator<(SerializableDynamicNodeInvocation const &) const;bool operator>(SerializableDynamicNodeInvocation const &) const;bool operator<=(SerializableDynamicNodeInvocation const &) const;bool operator>=(SerializableDynamicNodeInvocation const &) const;
std::string debug_to_string() const;void debug_print() const;
std::map<::FlexFlow::DynamicTensorSlot, ::FlexFlow::SerializableDynamicValueAttrs> inputs;
::FlexFlow::SerializableDynamicNodeAttrs node_attrs;
std::map<::FlexFlow::DynamicTensorSlot, ::FlexFlow::SerializableDynamicValueAttrs> outputs;
};}// namespace FlexFlow


///\cond
namespace std{template <>
struct hash<::FlexFlow::SerializableDynamicNodeInvocation>{size_t operator()(::FlexFlow::SerializableDynamicNodeInvocation const &)const;};}// namespace std

///\endcond

namespace nlohmann{template <>
struct adl_serializer<::FlexFlow::SerializableDynamicNodeInvocation>{static ::FlexFlow::SerializableDynamicNodeInvocation from_json(json const &);
static void to_json(json &, ::FlexFlow::SerializableDynamicNodeInvocation const &);
};}// namespace nlohmann

namespace FlexFlow{std::string format_as(SerializableDynamicNodeInvocation const &);
std::ostream &operator<<(std::ostream &, SerializableDynamicNodeInvocation const &);}// namespace FlexFlow

#endif // _FLEXFLOW_LIB_TASK_SPEC_INCLUDE_TASK_SPEC_DYNAMIC_GRAPH_SERIALIZABLE_DYNAMIC_NODE_INVOCATION_DTG_H
