// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/task-spec/include/task-spec/dynamic_graph/training_op_type.dtg.toml
/* proj-data
{
  "generated_from": "d27c09b34f59646f3c32c8bcb1361fff"
}
*/

#ifndef _FLEXFLOW_LIB_TASK_SPEC_INCLUDE_TASK_SPEC_DYNAMIC_GRAPH_TRAINING_OP_TYPE_DTG_H
#define _FLEXFLOW_LIB_TASK_SPEC_INCLUDE_TASK_SPEC_DYNAMIC_GRAPH_TRAINING_OP_TYPE_DTG_H

#include <cstddef>
#include <fmt/format.h>
#include <functional>
#include <iostream>
#include <libassert/assert.hpp>
#include <nlohmann/json.hpp>
#include "op-attrs/operator_type.dtg.h"
#include <optional>
#include <ostream>
#include <stdexcept>
#include "task-spec/dynamic_graph/training_only_op_type.dtg.h"
#include <type_traits>
#include <variant>

namespace FlexFlow{struct TrainingOpType{TrainingOpType() = delete;
explicit TrainingOpType(::FlexFlow::OperatorType const &);
explicit TrainingOpType(::FlexFlow::TrainingOnlyOpType const &);template <typename T>
static constexpr bool IsPartOfTrainingOpType_v =std::is_same_v<T, ::FlexFlow::OperatorType> || std::is_same_v<T, ::FlexFlow::TrainingOnlyOpType>;template <typename ReturnType, typename Visitor>
ReturnType visit(Visitor &&v) const{switch (this->index()){case 0: {ReturnType result = v(this->get<::FlexFlow::OperatorType>());
return result;
}case 1: {ReturnType result = v(this->get<::FlexFlow::TrainingOnlyOpType>());
return result;
}default: {throw std::runtime_error(fmt::format("Unknown index {} for type TrainingOpType", this->index()));
}}}
template <typename ReturnType, typename Visitor>
ReturnType visit(Visitor &&v){switch (this->index()){case 0: {ReturnType result = v(this->get<::FlexFlow::OperatorType>());
return result;
}case 1: {ReturnType result = v(this->get<::FlexFlow::TrainingOnlyOpType>());
return result;
}default: {throw std::runtime_error(fmt::format("Unknown index {} for type TrainingOpType", this->index()));
}}}
template <typename T>
bool has() const{static_assert(IsPartOfTrainingOpType_v<T>, "TrainingOpType::has() expected one of [::FlexFlow::OperatorType, ::FlexFlow::TrainingOnlyOpType], received T");return std::holds_alternative<T>(this->raw_variant);}
template <typename T>
T const & get() const{static_assert(IsPartOfTrainingOpType_v<T>, "TrainingOpType::get() expected one of [::FlexFlow::OperatorType, ::FlexFlow::TrainingOnlyOpType], received T");bool holds_expected = std::holds_alternative<T>(this->raw_variant);
ASSERT(holds_expected);
return std::get<T>(this->raw_variant);
}
template <typename T>
T  & get(){static_assert(IsPartOfTrainingOpType_v<T>, "TrainingOpType::get() expected one of [::FlexFlow::OperatorType, ::FlexFlow::TrainingOnlyOpType], received T");bool holds_expected = std::holds_alternative<T>(this->raw_variant);
ASSERT(holds_expected);
return std::get<T>(this->raw_variant);
}
size_t index() const { return this->raw_variant.index(); }
bool operator==(TrainingOpType const &) const;bool operator!=(TrainingOpType const &) const;::FlexFlow::OperatorType const & require_pcg_op() const;
::FlexFlow::OperatorType & require_pcg_op();
::FlexFlow::TrainingOnlyOpType const & require_training_only_op() const;
::FlexFlow::TrainingOnlyOpType & require_training_only_op();
std::optional<::FlexFlow::OperatorType> try_require_pcg_op() const;
std::optional<::FlexFlow::TrainingOnlyOpType> try_require_training_only_op() const;
bool is_pcg_op() const;
bool is_training_only_op() const;
std::string debug_to_string() const;void debug_print() const;std::variant<::FlexFlow::OperatorType, ::FlexFlow::TrainingOnlyOpType> raw_variant;};}// namespace FlexFlow

///\cond
namespace std{template <>
struct hash<::FlexFlow::TrainingOpType>{size_t operator()(::FlexFlow::TrainingOpType const &) const;
};}// namespace std

///\endcond
namespace nlohmann{template <>
struct adl_serializer<::FlexFlow::TrainingOpType>{static ::FlexFlow::TrainingOpType from_json(json const &);
static void to_json(json &, ::FlexFlow::TrainingOpType const &);
};}// namespace nlohmann
namespace FlexFlow{std::string format_as(::FlexFlow::TrainingOpType const &);
std::ostream & operator<<(std::ostream &, ::FlexFlow::TrainingOpType const &);
}// namespace FlexFlow

#endif // _FLEXFLOW_LIB_TASK_SPEC_INCLUDE_TASK_SPEC_DYNAMIC_GRAPH_TRAINING_OP_TYPE_DTG_H
