// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/op-attrs/include/op-attrs/ops/batch_matmul_attrs.dtg.toml
/* proj-data
{
  "generated_from": "31c032dba832f2f111e7a51b64cf9615"
}
*/

#ifndef _FLEXFLOW_LIB_OP_ATTRS_INCLUDE_OP_ATTRS_OPS_BATCH_MATMUL_ATTRS_DTG_H
#define _FLEXFLOW_LIB_OP_ATTRS_INCLUDE_OP_ATTRS_OPS_BATCH_MATMUL_ATTRS_DTG_H

#include <tuple>
#include <iostream>
#include <ostream>
#include <rapidcheck.h>
#include <fmt/format.h>
#include <nlohmann/json.hpp>
#include <functional>


namespace FlexFlow{struct BatchMatmulAttrs{
bool operator==(BatchMatmulAttrs const &) const;bool operator!=(BatchMatmulAttrs const &) const;
bool operator<(BatchMatmulAttrs const &) const;bool operator>(BatchMatmulAttrs const &) const;bool operator<=(BatchMatmulAttrs const &) const;bool operator>=(BatchMatmulAttrs const &) const;
std::string debug_to_string() const;void debug_print() const;
};}// namespace FlexFlow


///\cond
namespace std{template <>
struct hash<::FlexFlow::BatchMatmulAttrs>{size_t operator()(::FlexFlow::BatchMatmulAttrs const &)const;};}// namespace std

///\endcond

namespace nlohmann{template <>
struct adl_serializer<::FlexFlow::BatchMatmulAttrs>{static ::FlexFlow::BatchMatmulAttrs from_json(json const &);
static void to_json(json &, ::FlexFlow::BatchMatmulAttrs const &);
};}// namespace nlohmann

namespace rc{template <>
struct Arbitrary<::FlexFlow::BatchMatmulAttrs>{static Gen<::FlexFlow::BatchMatmulAttrs> arbitrary();
};}// namespace rc

namespace FlexFlow{std::string format_as(BatchMatmulAttrs const &);
std::ostream &operator<<(std::ostream &, BatchMatmulAttrs const &);}// namespace FlexFlow

#endif // _FLEXFLOW_LIB_OP_ATTRS_INCLUDE_OP_ATTRS_OPS_BATCH_MATMUL_ATTRS_DTG_H
