// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/op-attrs/include/op-attrs/ops/layer_norm_attrs.dtg.toml
/* proj-data
{
  "generated_from": "4a3d985f5691544e0c3adaf5533eb7c2"
}
*/

#ifndef _FLEXFLOW_LIB_OP_ATTRS_INCLUDE_OP_ATTRS_OPS_LAYER_NORM_ATTRS_DTG_H
#define _FLEXFLOW_LIB_OP_ATTRS_INCLUDE_OP_ATTRS_OPS_LAYER_NORM_ATTRS_DTG_H

#include <tuple>
#include <iostream>
#include <set>
#include <ostream>
#include <rapidcheck.h>
#include <fmt/format.h>
#include <nlohmann/json.hpp>
#include <functional>
#include "op-attrs/ff_dim_t.dtg.h"


namespace FlexFlow{struct LayerNormAttrs{LayerNormAttrs() = delete;
explicit LayerNormAttrs(std::set<::FlexFlow::ff_dim_t> const &axes, bool const &elementwise_affine, float const &eps);

bool operator==(LayerNormAttrs const &) const;bool operator!=(LayerNormAttrs const &) const;
bool operator<(LayerNormAttrs const &) const;bool operator>(LayerNormAttrs const &) const;bool operator<=(LayerNormAttrs const &) const;bool operator>=(LayerNormAttrs const &) const;
std::string debug_to_string() const;void debug_print() const;
std::set<::FlexFlow::ff_dim_t> axes;
bool elementwise_affine;
float eps;
};}// namespace FlexFlow


///\cond
namespace std{template <>
struct hash<::FlexFlow::LayerNormAttrs>{size_t operator()(::FlexFlow::LayerNormAttrs const &)const;};}// namespace std

///\endcond

namespace nlohmann{template <>
struct adl_serializer<::FlexFlow::LayerNormAttrs>{static ::FlexFlow::LayerNormAttrs from_json(json const &);
static void to_json(json &, ::FlexFlow::LayerNormAttrs const &);
};}// namespace nlohmann

namespace rc{template <>
struct Arbitrary<::FlexFlow::LayerNormAttrs>{static Gen<::FlexFlow::LayerNormAttrs> arbitrary();
};}// namespace rc

namespace FlexFlow{std::string format_as(LayerNormAttrs const &);
std::ostream &operator<<(std::ostream &, LayerNormAttrs const &);}// namespace FlexFlow

#endif // _FLEXFLOW_LIB_OP_ATTRS_INCLUDE_OP_ATTRS_OPS_LAYER_NORM_ATTRS_DTG_H
