// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/op-attrs/include/op-attrs/ops/linear_attrs.dtg.toml
/* proj-data
{
  "generated_from": "c93c6180aa51d5b3309088f58af9d093"
}
*/

#ifndef _FLEXFLOW_LIB_OP_ATTRS_INCLUDE_OP_ATTRS_OPS_LINEAR_ATTRS_DTG_H
#define _FLEXFLOW_LIB_OP_ATTRS_INCLUDE_OP_ATTRS_OPS_LINEAR_ATTRS_DTG_H

#include <tuple>
#include <iostream>
#include <functional>
#include "op-attrs/regularizer_attrs.dtg.h"
#include <nlohmann/json.hpp>
#include <ostream>
#include "op-attrs/datatype.dtg.h"
#include <rapidcheck.h>
#include <fmt/format.h>
#include "utils/positive_int/positive_int.h"
#include "op-attrs/activation.dtg.h"
#include <optional>


namespace FlexFlow{

/**
 * \brief Compiler-side representation of a Linear operator.
 * 
 * For details on how operators are represented on the compiler side, see \ref op-attrs-ops.
 */struct LinearAttrs{LinearAttrs() = delete;
explicit LinearAttrs(::FlexFlow::positive_int const &out_channels, bool const &use_bias, ::FlexFlow::DataType const &data_type, std::optional<::FlexFlow::Activation> const &activation, std::optional<::FlexFlow::RegularizerAttrs> const &regularizer);

bool operator==(LinearAttrs const &) const;bool operator!=(LinearAttrs const &) const;
bool operator<(LinearAttrs const &) const;bool operator>(LinearAttrs const &) const;bool operator<=(LinearAttrs const &) const;bool operator>=(LinearAttrs const &) const;
std::string debug_to_string() const;void debug_print() const;
::FlexFlow::positive_int out_channels;
bool use_bias;
::FlexFlow::DataType data_type;
std::optional<::FlexFlow::Activation> activation;
std::optional<::FlexFlow::RegularizerAttrs> regularizer;
};}// namespace FlexFlow


///\cond
namespace std{template <>
struct hash<::FlexFlow::LinearAttrs>{size_t operator()(::FlexFlow::LinearAttrs const &)const;};}// namespace std

///\endcond

namespace nlohmann{template <>
struct adl_serializer<::FlexFlow::LinearAttrs>{static ::FlexFlow::LinearAttrs from_json(json const &);
static void to_json(json &, ::FlexFlow::LinearAttrs const &);
};}// namespace nlohmann

namespace rc{template <>
struct Arbitrary<::FlexFlow::LinearAttrs>{static Gen<::FlexFlow::LinearAttrs> arbitrary();
};}// namespace rc

namespace FlexFlow{std::string format_as(LinearAttrs const &);
std::ostream &operator<<(std::ostream &, LinearAttrs const &);}// namespace FlexFlow

#endif // _FLEXFLOW_LIB_OP_ATTRS_INCLUDE_OP_ATTRS_OPS_LINEAR_ATTRS_DTG_H
