// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/op-attrs/include/op-attrs/ops/repartition_attrs.dtg.toml
/* proj-data
{
  "generated_from": "f814a2358fa2e9cfad328b81282cd5cb"
}
*/

#ifndef _FLEXFLOW_LIB_OP_ATTRS_INCLUDE_OP_ATTRS_OPS_REPARTITION_ATTRS_DTG_H
#define _FLEXFLOW_LIB_OP_ATTRS_INCLUDE_OP_ATTRS_OPS_REPARTITION_ATTRS_DTG_H

#include <tuple>
#include <iostream>
#include <ostream>
#include <rapidcheck.h>
#include <fmt/format.h>
#include "utils/positive_int/positive_int.h"
#include "op-attrs/ff_dim_t.h"
#include <nlohmann/json.hpp>
#include <functional>
#include "op-attrs/ff_dim_t.dtg.h"


namespace FlexFlow{struct RepartitionAttrs{RepartitionAttrs() = delete;
explicit RepartitionAttrs(::FlexFlow::ff_dim_t const &repartition_dim, ::FlexFlow::positive_int const &repartition_degree);

bool operator==(RepartitionAttrs const &) const;bool operator!=(RepartitionAttrs const &) const;
bool operator<(RepartitionAttrs const &) const;bool operator>(RepartitionAttrs const &) const;bool operator<=(RepartitionAttrs const &) const;bool operator>=(RepartitionAttrs const &) const;
std::string debug_to_string() const;void debug_print() const;
::FlexFlow::ff_dim_t repartition_dim;
::FlexFlow::positive_int repartition_degree;
};}// namespace FlexFlow


///\cond
namespace std{template <>
struct hash<::FlexFlow::RepartitionAttrs>{size_t operator()(::FlexFlow::RepartitionAttrs const &)const;};}// namespace std

///\endcond

namespace nlohmann{template <>
struct adl_serializer<::FlexFlow::RepartitionAttrs>{static ::FlexFlow::RepartitionAttrs from_json(json const &);
static void to_json(json &, ::FlexFlow::RepartitionAttrs const &);
};}// namespace nlohmann

namespace rc{template <>
struct Arbitrary<::FlexFlow::RepartitionAttrs>{static Gen<::FlexFlow::RepartitionAttrs> arbitrary();
};}// namespace rc

namespace FlexFlow{std::string format_as(RepartitionAttrs const &);
std::ostream &operator<<(std::ostream &, RepartitionAttrs const &);}// namespace FlexFlow

#endif // _FLEXFLOW_LIB_OP_ATTRS_INCLUDE_OP_ATTRS_OPS_REPARTITION_ATTRS_DTG_H
