// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/op-attrs/include/op-attrs/ops/softmax_attrs.dtg.toml
/* proj-data
{
  "generated_from": "ce17042f9f38110df4e1fd23fb925e1d"
}
*/

#ifndef _FLEXFLOW_LIB_OP_ATTRS_INCLUDE_OP_ATTRS_OPS_SOFTMAX_ATTRS_DTG_H
#define _FLEXFLOW_LIB_OP_ATTRS_INCLUDE_OP_ATTRS_OPS_SOFTMAX_ATTRS_DTG_H

#include <tuple>
#include <iostream>
#include <ostream>
#include <rapidcheck.h>
#include <fmt/format.h>
#include "op-attrs/ff_dim_t.h"
#include <nlohmann/json.hpp>
#include <functional>
#include "op-attrs/ff_dim_t.dtg.h"


namespace FlexFlow{struct SoftmaxAttrs{SoftmaxAttrs() = delete;
explicit SoftmaxAttrs(::FlexFlow::ff_dim_t const &dim);

bool operator==(SoftmaxAttrs const &) const;bool operator!=(SoftmaxAttrs const &) const;
bool operator<(SoftmaxAttrs const &) const;bool operator>(SoftmaxAttrs const &) const;bool operator<=(SoftmaxAttrs const &) const;bool operator>=(SoftmaxAttrs const &) const;
std::string debug_to_string() const;void debug_print() const;
::FlexFlow::ff_dim_t dim;
};}// namespace FlexFlow


///\cond
namespace std{template <>
struct hash<::FlexFlow::SoftmaxAttrs>{size_t operator()(::FlexFlow::SoftmaxAttrs const &)const;};}// namespace std

///\endcond

namespace nlohmann{template <>
struct adl_serializer<::FlexFlow::SoftmaxAttrs>{static ::FlexFlow::SoftmaxAttrs from_json(json const &);
static void to_json(json &, ::FlexFlow::SoftmaxAttrs const &);
};}// namespace nlohmann

namespace rc{template <>
struct Arbitrary<::FlexFlow::SoftmaxAttrs>{static Gen<::FlexFlow::SoftmaxAttrs> arbitrary();
};}// namespace rc

namespace FlexFlow{std::string format_as(SoftmaxAttrs const &);
std::ostream &operator<<(std::ostream &, SoftmaxAttrs const &);}// namespace FlexFlow

#endif // _FLEXFLOW_LIB_OP_ATTRS_INCLUDE_OP_ATTRS_OPS_SOFTMAX_ATTRS_DTG_H
