// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/op-attrs/include/op-attrs/ops/split_attrs.dtg.toml
/* proj-data
{
  "generated_from": "2396b4f03c66b0d076e5d570fccb0162"
}
*/

#ifndef _FLEXFLOW_LIB_OP_ATTRS_INCLUDE_OP_ATTRS_OPS_SPLIT_ATTRS_DTG_H
#define _FLEXFLOW_LIB_OP_ATTRS_INCLUDE_OP_ATTRS_OPS_SPLIT_ATTRS_DTG_H

#include <tuple>
#include <iostream>
#include <ostream>
#include <vector>
#include <rapidcheck.h>
#include <fmt/format.h>
#include "utils/positive_int/positive_int.h"
#include "op-attrs/ff_dim_t.h"
#include <nlohmann/json.hpp>
#include <functional>
#include "op-attrs/ff_dim_t.dtg.h"


namespace FlexFlow{struct SplitAttrs{SplitAttrs() = delete;
explicit SplitAttrs(std::vector<::FlexFlow::positive_int> const &splits, ::FlexFlow::ff_dim_t const &axis);

bool operator==(SplitAttrs const &) const;bool operator!=(SplitAttrs const &) const;
bool operator<(SplitAttrs const &) const;bool operator>(SplitAttrs const &) const;bool operator<=(SplitAttrs const &) const;bool operator>=(SplitAttrs const &) const;
std::string debug_to_string() const;void debug_print() const;
std::vector<::FlexFlow::positive_int> splits;
::FlexFlow::ff_dim_t axis;
};}// namespace FlexFlow


///\cond
namespace std{template <>
struct hash<::FlexFlow::SplitAttrs>{size_t operator()(::FlexFlow::SplitAttrs const &)const;};}// namespace std

///\endcond

namespace nlohmann{template <>
struct adl_serializer<::FlexFlow::SplitAttrs>{static ::FlexFlow::SplitAttrs from_json(json const &);
static void to_json(json &, ::FlexFlow::SplitAttrs const &);
};}// namespace nlohmann

namespace rc{template <>
struct Arbitrary<::FlexFlow::SplitAttrs>{static Gen<::FlexFlow::SplitAttrs> arbitrary();
};}// namespace rc

namespace FlexFlow{std::string format_as(SplitAttrs const &);
std::ostream &operator<<(std::ostream &, SplitAttrs const &);}// namespace FlexFlow

#endif // _FLEXFLOW_LIB_OP_ATTRS_INCLUDE_OP_ATTRS_OPS_SPLIT_ATTRS_DTG_H
