// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/kernels/include/kernels/device_stream_t.dtg.toml
/* proj-data
{
  "generated_from": "1405469cc5db61c43ccfd185fec7a7ac"
}
*/

#ifndef _FLEXFLOW_LIB_KERNELS_INCLUDE_KERNELS_DEVICE_STREAM_T_DTG_H
#define _FLEXFLOW_LIB_KERNELS_INCLUDE_KERNELS_DEVICE_STREAM_T_DTG_H

#include <cstddef>
#include <fmt/format.h>
#include "kernels/device.h"
#include <libassert/assert.hpp>
#include <optional>
#include <stdexcept>
#include <type_traits>
#include <utility>
#include <variant>

namespace FlexFlow{

/**
 * \brief The stream a kernel places its device work on, or a marker that the
 * kernel runs on the host.
 * 
 * Built with \ref get_gpu_device_stream or \ref get_cpu_device_stream. Note that
 * neither produces a GPU stream on demand: a GPU stream is a resource owned by
 * whoever is running the task, and is passed in from there.
 */struct device_stream_t{device_stream_t() = delete;
explicit device_stream_t(ffStream_t const &);
explicit device_stream_t(std::monostate const &);template <typename T>
static constexpr bool IsPartOfdevice_stream_t_v =std::is_same_v<T, ffStream_t> || std::is_same_v<T, std::monostate>;template <typename ReturnType, typename Visitor>
ReturnType visit(Visitor &&v) const{switch (this->index()){case 0: {ReturnType result = v(this->get<ffStream_t>());
return result;
}case 1: {ReturnType result = v(this->get<std::monostate>());
return result;
}default: {throw std::runtime_error(fmt::format("Unknown index {} for type device_stream_t", this->index()));
}}}
template <typename ReturnType, typename Visitor>
ReturnType visit(Visitor &&v){switch (this->index()){case 0: {ReturnType result = v(this->get<ffStream_t>());
return result;
}case 1: {ReturnType result = v(this->get<std::monostate>());
return result;
}default: {throw std::runtime_error(fmt::format("Unknown index {} for type device_stream_t", this->index()));
}}}
template <typename T>
bool has() const{static_assert(IsPartOfdevice_stream_t_v<T>, "device_stream_t::has() expected one of [ffStream_t, std::monostate], received T");return std::holds_alternative<T>(this->raw_variant);}
template <typename T>
T const & get() const{static_assert(IsPartOfdevice_stream_t_v<T>, "device_stream_t::get() expected one of [ffStream_t, std::monostate], received T");bool holds_expected = std::holds_alternative<T>(this->raw_variant);
ASSERT(holds_expected);
return std::get<T>(this->raw_variant);
}
template <typename T>
T  & get(){static_assert(IsPartOfdevice_stream_t_v<T>, "device_stream_t::get() expected one of [ffStream_t, std::monostate], received T");bool holds_expected = std::holds_alternative<T>(this->raw_variant);
ASSERT(holds_expected);
return std::get<T>(this->raw_variant);
}
size_t index() const { return this->raw_variant.index(); }
ffStream_t const & require_gpu() const;
ffStream_t & require_gpu();
std::monostate const & require_cpu() const;
std::monostate & require_cpu();
std::optional<ffStream_t> try_require_gpu() const;
std::optional<std::monostate> try_require_cpu() const;
bool is_gpu() const;
bool is_cpu() const;
std::variant<ffStream_t, std::monostate> raw_variant;};}// namespace FlexFlow

#endif // _FLEXFLOW_LIB_KERNELS_INCLUDE_KERNELS_DEVICE_STREAM_T_DTG_H
