// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/kernels/include/kernels/layer_norm_per_device_state.dtg.toml
/* proj-data
{
  "generated_from": "672ad0c553248f6297f7ae2125ba4ec9"
}
*/

#ifndef _FLEXFLOW_LIB_KERNELS_INCLUDE_KERNELS_LAYER_NORM_PER_DEVICE_STATE_DTG_H
#define _FLEXFLOW_LIB_KERNELS_INCLUDE_KERNELS_LAYER_NORM_PER_DEVICE_STATE_DTG_H

#include "kernels/ff_handle.h"
#include "op-attrs/datatype.dtg.h"


namespace FlexFlow{struct LayerNormPerDeviceState{LayerNormPerDeviceState() = delete;
explicit LayerNormPerDeviceState(::FlexFlow::PerDeviceFFHandle const &handle, bool const &elementwise_affine, int64_t const &effective_num_elements, int64_t const &effective_batch_size, float const &eps, float * const &mean, float * const &rstd, float * const &ds, float * const &db, float * const &scale, float * const &bias, ::FlexFlow::DataType const &data_type);

::FlexFlow::PerDeviceFFHandle handle;
bool elementwise_affine;
int64_t effective_num_elements;
int64_t effective_batch_size;
float eps;
float * mean;
float * rstd;
float * ds;
float * db;
float * scale;
float * bias;
::FlexFlow::DataType data_type;
};}// namespace FlexFlow

#endif // _FLEXFLOW_LIB_KERNELS_INCLUDE_KERNELS_LAYER_NORM_PER_DEVICE_STATE_DTG_H
