// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/utils/include/utils/graph/digraph/di_input.dtg.toml
/* proj-data
{
  "generated_from": "34f448c20ea6d6bc7e8be874d79c461e"
}
*/

#ifndef _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_GRAPH_DIGRAPH_DI_INPUT_DTG_H
#define _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_GRAPH_DIGRAPH_DI_INPUT_DTG_H

#include <tuple>
#include <iostream>
#include <ostream>
#include <fmt/format.h>
#include <nlohmann/json.hpp>
#include <functional>
#include "utils/graph/node/node.dtg.h"


namespace FlexFlow{struct DiInput{DiInput() = delete;
explicit DiInput(::FlexFlow::Node const &dst);

bool operator==(DiInput const &) const;bool operator!=(DiInput const &) const;
bool operator<(DiInput const &) const;bool operator>(DiInput const &) const;bool operator<=(DiInput const &) const;bool operator>=(DiInput const &) const;
std::string debug_to_string() const;void debug_print() const;
::FlexFlow::Node dst;
};}// namespace FlexFlow


///\cond
namespace std{template <>
struct hash<::FlexFlow::DiInput>{size_t operator()(::FlexFlow::DiInput const &)const;};}// namespace std

///\endcond

namespace nlohmann{template <>
struct adl_serializer<::FlexFlow::DiInput>{static void to_json(json &, ::FlexFlow::DiInput const &);
};}// namespace nlohmann

namespace FlexFlow{std::string format_as(DiInput const &);
std::ostream &operator<<(std::ostream &, DiInput const &);}// namespace FlexFlow

#endif // _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_GRAPH_DIGRAPH_DI_INPUT_DTG_H
