// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/utils/include/utils/graph/digraph/directed_edge_query.dtg.toml
/* proj-data
{
  "generated_from": "c33757981da2d6d035469007dbac68bb"
}
*/

#ifndef _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_GRAPH_DIGRAPH_DIRECTED_EDGE_QUERY_DTG_H
#define _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_GRAPH_DIGRAPH_DIRECTED_EDGE_QUERY_DTG_H

#include <tuple>
#include <iostream>
#include "utils/graph/query_set.h"
#include <ostream>
#include <fmt/format.h>
#include <nlohmann/json.hpp>
#include <functional>
#include "utils/graph/node/node.dtg.h"


namespace FlexFlow{struct DirectedEdgeQuery{DirectedEdgeQuery() = delete;
explicit DirectedEdgeQuery(::FlexFlow::query_set<::FlexFlow::Node> const &srcs, ::FlexFlow::query_set<::FlexFlow::Node> const &dsts);

bool operator==(DirectedEdgeQuery const &) const;bool operator!=(DirectedEdgeQuery const &) const;
bool operator<(DirectedEdgeQuery const &) const;bool operator>(DirectedEdgeQuery const &) const;bool operator<=(DirectedEdgeQuery const &) const;bool operator>=(DirectedEdgeQuery const &) const;
std::string debug_to_string() const;void debug_print() const;
::FlexFlow::query_set<::FlexFlow::Node> srcs;
::FlexFlow::query_set<::FlexFlow::Node> dsts;
};}// namespace FlexFlow


///\cond
namespace std{template <>
struct hash<::FlexFlow::DirectedEdgeQuery>{size_t operator()(::FlexFlow::DirectedEdgeQuery const &)const;};}// namespace std

///\endcond

namespace nlohmann{template <>
struct adl_serializer<::FlexFlow::DirectedEdgeQuery>{static void to_json(json &, ::FlexFlow::DirectedEdgeQuery const &);
};}// namespace nlohmann

namespace FlexFlow{std::string format_as(DirectedEdgeQuery const &);
std::ostream &operator<<(std::ostream &, DirectedEdgeQuery const &);}// namespace FlexFlow

#endif // _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_GRAPH_DIGRAPH_DIRECTED_EDGE_QUERY_DTG_H
