// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/realm-execution/include/realm-execution/tasks/impl/serializable_zero_gradients_register_args.dtg.toml
/* proj-data
{
  "generated_from": "1f27b10a2b7aa7721ae605741e43844c"
}
*/

#ifndef _FLEXFLOW_LIB_REALM_EXECUTION_INCLUDE_REALM_EXECUTION_TASKS_IMPL_SERIALIZABLE_ZERO_GRADIENTS_REGISTER_ARGS_DTG_H
#define _FLEXFLOW_LIB_REALM_EXECUTION_INCLUDE_REALM_EXECUTION_TASKS_IMPL_SERIALIZABLE_ZERO_GRADIENTS_REGISTER_ARGS_DTG_H

#include <tuple>
#include <iostream>
#include <ostream>
#include "realm-execution/tasks/serializer/serializable_tensor_instance_backing.dtg.h"
#include <fmt/format.h>
#include <nlohmann/json.hpp>
#include <functional>


namespace FlexFlow{

/**
 * \brief The gradient instances a node is to zero at the start of each backward
 * pass.
 * 
 * Sent once, during initialization, for the same reason a task's arguments are:
 * which instances back the gradients does not change from one iteration to the
 * next, and there are on the order of a thousand of them.
 */struct SerializableZeroGradientsRegisterArgs{SerializableZeroGradientsRegisterArgs() = delete;
explicit SerializableZeroGradientsRegisterArgs(::FlexFlow::SerializableTensorInstanceBacking const &gradients);

bool operator==(SerializableZeroGradientsRegisterArgs const &) const;bool operator!=(SerializableZeroGradientsRegisterArgs const &) const;
std::string debug_to_string() const;void debug_print() const;
::FlexFlow::SerializableTensorInstanceBacking gradients;
};}// namespace FlexFlow


///\cond
namespace std{template <>
struct hash<::FlexFlow::SerializableZeroGradientsRegisterArgs>{size_t operator()(::FlexFlow::SerializableZeroGradientsRegisterArgs const &)const;};}// namespace std

///\endcond

namespace nlohmann{template <>
struct adl_serializer<::FlexFlow::SerializableZeroGradientsRegisterArgs>{static ::FlexFlow::SerializableZeroGradientsRegisterArgs from_json(json const &);
static void to_json(json &, ::FlexFlow::SerializableZeroGradientsRegisterArgs const &);
};}// namespace nlohmann

namespace FlexFlow{std::string format_as(SerializableZeroGradientsRegisterArgs const &);
std::ostream &operator<<(std::ostream &, SerializableZeroGradientsRegisterArgs const &);}// namespace FlexFlow

#endif // _FLEXFLOW_LIB_REALM_EXECUTION_INCLUDE_REALM_EXECUTION_TASKS_IMPL_SERIALIZABLE_ZERO_GRADIENTS_REGISTER_ARGS_DTG_H
