// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/realm-execution/include/realm-execution/tasks/impl/serializable_op_task_group_register_args.dtg.toml
/* proj-data
{
  "generated_from": "7486e297871c71fb9f3a926338a2a1b7"
}
*/

#ifndef _FLEXFLOW_LIB_REALM_EXECUTION_INCLUDE_REALM_EXECUTION_TASKS_IMPL_SERIALIZABLE_OP_TASK_GROUP_REGISTER_ARGS_DTG_H
#define _FLEXFLOW_LIB_REALM_EXECUTION_INCLUDE_REALM_EXECUTION_TASKS_IMPL_SERIALIZABLE_OP_TASK_GROUP_REGISTER_ARGS_DTG_H

#include <tuple>
#include <iostream>
#include "task-spec/dynamic_graph/dynamic_invocation_id_t.dtg.h"
#include <ostream>
#include <vector>
#include <fmt/format.h>
#include <nlohmann/json.hpp>
#include <functional>


namespace FlexFlow{

/**
 * \brief What names a fused group to the node that will run it.
 * 
 * The members' own arguments were registered separately (see \ref
 * SerializableOpTaskArgRegisterArgs), so all that is left to say is which of them
 * this group runs, and in what order.
 */struct SerializableOpTaskGroupRegisterArgs{SerializableOpTaskGroupRegisterArgs() = delete;
explicit SerializableOpTaskGroupRegisterArgs(::FlexFlow::dynamic_invocation_id_t const &group_id, std::vector<::FlexFlow::dynamic_invocation_id_t> const &member_ids);

bool operator==(SerializableOpTaskGroupRegisterArgs const &) const;bool operator!=(SerializableOpTaskGroupRegisterArgs const &) const;
std::string debug_to_string() const;void debug_print() const;
::FlexFlow::dynamic_invocation_id_t group_id;
std::vector<::FlexFlow::dynamic_invocation_id_t> member_ids;
};}// namespace FlexFlow


///\cond
namespace std{template <>
struct hash<::FlexFlow::SerializableOpTaskGroupRegisterArgs>{size_t operator()(::FlexFlow::SerializableOpTaskGroupRegisterArgs const &)const;};}// namespace std

///\endcond

namespace nlohmann{template <>
struct adl_serializer<::FlexFlow::SerializableOpTaskGroupRegisterArgs>{static ::FlexFlow::SerializableOpTaskGroupRegisterArgs from_json(json const &);
static void to_json(json &, ::FlexFlow::SerializableOpTaskGroupRegisterArgs const &);
};}// namespace nlohmann

namespace FlexFlow{std::string format_as(SerializableOpTaskGroupRegisterArgs const &);
std::ostream &operator<<(std::ostream &, SerializableOpTaskGroupRegisterArgs const &);}// namespace FlexFlow

#endif // _FLEXFLOW_LIB_REALM_EXECUTION_INCLUDE_REALM_EXECUTION_TASKS_IMPL_SERIALIZABLE_OP_TASK_GROUP_REGISTER_ARGS_DTG_H
