// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/compiler/include/compiler/machine_mapping/memory_optimization/machine_memory_constraints.dtg.toml
/* proj-data
{
  "generated_from": "a525ecf7dca3ea42756448b8b6f3e34f"
}
*/

#ifndef _FLEXFLOW_LIB_COMPILER_INCLUDE_COMPILER_MACHINE_MAPPING_MEMORY_OPTIMIZATION_MACHINE_MEMORY_CONSTRAINTS_DTG_H
#define _FLEXFLOW_LIB_COMPILER_INCLUDE_COMPILER_MACHINE_MAPPING_MEMORY_OPTIMIZATION_MACHINE_MEMORY_CONSTRAINTS_DTG_H

#include <tuple>
#include <iostream>
#include <ostream>
#include <fmt/format.h>
#include <nlohmann/json.hpp>
#include <functional>


namespace FlexFlow{struct MachineMemoryConstraints{MachineMemoryConstraints() = delete;
explicit MachineMemoryConstraints(size_t const &memory_limit);

bool operator==(MachineMemoryConstraints const &) const;bool operator!=(MachineMemoryConstraints const &) const;
std::string debug_to_string() const;void debug_print() const;
size_t memory_limit;
};}// namespace FlexFlow


///\cond
namespace std{template <>
struct hash<::FlexFlow::MachineMemoryConstraints>{size_t operator()(::FlexFlow::MachineMemoryConstraints const &)const;};}// namespace std

///\endcond

namespace nlohmann{template <>
struct adl_serializer<::FlexFlow::MachineMemoryConstraints>{static void to_json(json &, ::FlexFlow::MachineMemoryConstraints const &);
};}// namespace nlohmann

namespace FlexFlow{std::string format_as(MachineMemoryConstraints const &);
std::ostream &operator<<(std::ostream &, MachineMemoryConstraints const &);}// namespace FlexFlow

#endif // _FLEXFLOW_LIB_COMPILER_INCLUDE_COMPILER_MACHINE_MAPPING_MEMORY_OPTIMIZATION_MACHINE_MEMORY_CONSTRAINTS_DTG_H
