// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/pcg/include/pcg/file_format/v1/v1_mapped_parallel_computation_graph.dtg.toml
/* proj-data
{
  "generated_from": "d181b28f559bdd46a47e8f15b1fa07c5"
}
*/

#include "pcg/file_format/v1/v1_mapped_parallel_computation_graph.dtg.h"

#include <sstream>

namespace FlexFlow{V1MappedParallelComputationGraph::V1MappedParallelComputationGraph(::FlexFlow::V1LabelledKwargDataflowGraph<::FlexFlow::MappedParallelLayerAttrs, ::FlexFlow::ParallelTensorAttrs, ::FlexFlow::TensorSlotName> const &raw_graph) : raw_graph(raw_graph){}
bool V1MappedParallelComputationGraph::operator==(V1MappedParallelComputationGraph const &other) const{
return std::tie(this->raw_graph) == std::tie(other.raw_graph);
}bool V1MappedParallelComputationGraph::operator!=(V1MappedParallelComputationGraph const &other) const{
return std::tie(this->raw_graph) != std::tie(other.raw_graph);
}}// namespace FlexFlow


///\cond
namespace std{size_t hash<FlexFlow::V1MappedParallelComputationGraph>::operator()(::FlexFlow::V1MappedParallelComputationGraph const &x)const{size_t result = 0;
result ^= std::hash<::FlexFlow::V1LabelledKwargDataflowGraph<::FlexFlow::MappedParallelLayerAttrs, ::FlexFlow::ParallelTensorAttrs, ::FlexFlow::TensorSlotName>>{}(x.raw_graph) + 0x9e3779b9 + (result << 6) + (result >> 2);return result;
}}// namespace std

///\endcond

namespace nlohmann{void adl_serializer<::FlexFlow::V1MappedParallelComputationGraph>::to_json(json &j, ::FlexFlow::V1MappedParallelComputationGraph const &v) {j["__type"] = "V1MappedParallelComputationGraph";
j["raw_graph"] = v.raw_graph;
}}// namespace nlohmann

namespace nlohmann{::FlexFlow::V1MappedParallelComputationGraph adl_serializer<::FlexFlow::V1MappedParallelComputationGraph>::from_json(json const &j) {return ::FlexFlow::V1MappedParallelComputationGraph{j.at("raw_graph").template get<::FlexFlow::V1LabelledKwargDataflowGraph<::FlexFlow::MappedParallelLayerAttrs, ::FlexFlow::ParallelTensorAttrs, ::FlexFlow::TensorSlotName>>()};}}// namespace nlohmann

namespace FlexFlow{std::string V1MappedParallelComputationGraph::debug_to_string() const { return fmt::to_string(*this); }void V1MappedParallelComputationGraph::debug_print() const { std::cout << this->debug_to_string() << std::endl; }std::string format_as(V1MappedParallelComputationGraph const &x){::nlohmann::json j = x;
return j.dump();
}std::ostream &operator<<(std::ostream &s, V1MappedParallelComputationGraph const &x) {return s << fmt::to_string(x);}}// namespace FlexFlow
