// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/pcg/include/pcg/file_format/v1/v1_parallel_computation_graph.dtg.toml
/* proj-data
{
  "generated_from": "8ed1870b42d3b20df89d10be16dbc043"
}
*/

#include "pcg/file_format/v1/v1_parallel_computation_graph.dtg.h"

#include <sstream>

namespace FlexFlow{V1ParallelComputationGraph::V1ParallelComputationGraph(::FlexFlow::V1LabelledKwargDataflowGraph<::FlexFlow::ParallelLayerAttrs, ::FlexFlow::ParallelTensorAttrs, ::FlexFlow::TensorSlotName> const &raw_graph) : raw_graph(raw_graph){}
bool V1ParallelComputationGraph::operator==(V1ParallelComputationGraph const &other) const{
return std::tie(this->raw_graph) == std::tie(other.raw_graph);
}bool V1ParallelComputationGraph::operator!=(V1ParallelComputationGraph const &other) const{
return std::tie(this->raw_graph) != std::tie(other.raw_graph);
}}// namespace FlexFlow


///\cond
namespace std{size_t hash<FlexFlow::V1ParallelComputationGraph>::operator()(::FlexFlow::V1ParallelComputationGraph const &x)const{size_t result = 0;
result ^= std::hash<::FlexFlow::V1LabelledKwargDataflowGraph<::FlexFlow::ParallelLayerAttrs, ::FlexFlow::ParallelTensorAttrs, ::FlexFlow::TensorSlotName>>{}(x.raw_graph) + 0x9e3779b9 + (result << 6) + (result >> 2);return result;
}}// namespace std

///\endcond

namespace nlohmann{void adl_serializer<::FlexFlow::V1ParallelComputationGraph>::to_json(json &j, ::FlexFlow::V1ParallelComputationGraph const &v) {j["__type"] = "V1ParallelComputationGraph";
j["raw_graph"] = v.raw_graph;
}}// namespace nlohmann

namespace nlohmann{::FlexFlow::V1ParallelComputationGraph adl_serializer<::FlexFlow::V1ParallelComputationGraph>::from_json(json const &j) {return ::FlexFlow::V1ParallelComputationGraph{j.at("raw_graph").template get<::FlexFlow::V1LabelledKwargDataflowGraph<::FlexFlow::ParallelLayerAttrs, ::FlexFlow::ParallelTensorAttrs, ::FlexFlow::TensorSlotName>>()};}}// namespace nlohmann

namespace FlexFlow{std::string V1ParallelComputationGraph::debug_to_string() const { return fmt::to_string(*this); }void V1ParallelComputationGraph::debug_print() const { std::cout << this->debug_to_string() << std::endl; }std::string format_as(V1ParallelComputationGraph const &x){::nlohmann::json j = x;
return j.dump();
}std::ostream &operator<<(std::ostream &s, V1ParallelComputationGraph const &x) {return s << fmt::to_string(x);}}// namespace FlexFlow
