// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/substitutions/include/substitutions/operator_pattern/operator_attribute_value.dtg.toml
/* proj-data
{
  "generated_from": "7a39881ac02265747e597b3ef308aa93"
}
*/

#include "substitutions/operator_pattern/operator_attribute_value.dtg.h"

#include "utils/hash/vector.h"
#include <sstream>
#include "utils/fmt/optional.h"
#include "utils/fmt/vector.h"
#include "utils/json/optional.h"

namespace FlexFlow{OperatorAttributeValue::OperatorAttributeValue(::FlexFlow::nonnegative_int const &v) : raw_variant(v) { }
OperatorAttributeValue::OperatorAttributeValue(bool const &v) : raw_variant(v) { }
OperatorAttributeValue::OperatorAttributeValue(float const &v) : raw_variant(v) { }
OperatorAttributeValue::OperatorAttributeValue(std::optional<float> const &v) : raw_variant(v) { }
OperatorAttributeValue::OperatorAttributeValue(std::vector<::FlexFlow::positive_int> const &v) : raw_variant(v) { }
OperatorAttributeValue::OperatorAttributeValue(std::vector<::FlexFlow::ff_dim_t> const &v) : raw_variant(v) { }
OperatorAttributeValue::OperatorAttributeValue(::FlexFlow::OperatorType const &v) : raw_variant(v) { }
OperatorAttributeValue::OperatorAttributeValue(std::optional<::FlexFlow::Activation> const &v) : raw_variant(v) { }
OperatorAttributeValue::OperatorAttributeValue(::FlexFlow::ff_dim_t const &v) : raw_variant(v) { }
OperatorAttributeValue::OperatorAttributeValue(std::optional<::FlexFlow::AggregateOp> const &v) : raw_variant(v) { }
OperatorAttributeValue::OperatorAttributeValue(std::optional<::FlexFlow::RegularizerAttrs> const &v) : raw_variant(v) { }
OperatorAttributeValue::OperatorAttributeValue(::FlexFlow::PoolOp const &v) : raw_variant(v) { }
OperatorAttributeValue::OperatorAttributeValue(::FlexFlow::TensorShape const &v) : raw_variant(v) { }
OperatorAttributeValue::OperatorAttributeValue(::FlexFlow::TensorDims const &v) : raw_variant(v) { }
OperatorAttributeValue::OperatorAttributeValue(::FlexFlow::DataType const &v) : raw_variant(v) { }
OperatorAttributeValue::OperatorAttributeValue(::FlexFlow::TensorDimPermutation const &v) : raw_variant(v) { }bool OperatorAttributeValue::operator==(OperatorAttributeValue const &other) const{return this->raw_variant == other.raw_variant;}
bool OperatorAttributeValue::operator!=(OperatorAttributeValue const &other) const{return this->raw_variant != other.raw_variant;}
bool OperatorAttributeValue::operator<(OperatorAttributeValue const &other) const{return this->raw_variant < other.raw_variant;}
bool OperatorAttributeValue::operator>(OperatorAttributeValue const &other) const{return this->raw_variant > other.raw_variant;}
bool OperatorAttributeValue::operator<=(OperatorAttributeValue const &other) const{return this->raw_variant <= other.raw_variant;}
bool OperatorAttributeValue::operator>=(OperatorAttributeValue const &other) const{return this->raw_variant >= other.raw_variant;}
}// namespace FlexFlow

///\cond
namespace std{size_t hash<::FlexFlow::OperatorAttributeValue>::operator()(::FlexFlow::OperatorAttributeValue const &x) const{return std::hash<std::variant<::FlexFlow::nonnegative_int, bool, float, std::optional<float>, std::vector<::FlexFlow::positive_int>, std::vector<::FlexFlow::ff_dim_t>, ::FlexFlow::OperatorType, std::optional<::FlexFlow::Activation>, ::FlexFlow::ff_dim_t, std::optional<::FlexFlow::AggregateOp>, std::optional<::FlexFlow::RegularizerAttrs>, ::FlexFlow::PoolOp, ::FlexFlow::TensorShape, ::FlexFlow::TensorDims, ::FlexFlow::DataType, ::FlexFlow::TensorDimPermutation>>{}(x.raw_variant);}
}// namespace std

///\endcond
namespace nlohmann{void adl_serializer<::FlexFlow::OperatorAttributeValue>::to_json(json &j, ::FlexFlow::OperatorAttributeValue const &x){j["__type"] = "OperatorAttributeValue";
switch (x.index()){case 0:{j["type"] = "::FlexFlow::nonnegative_int";
j["value"] = x.template get<::FlexFlow::nonnegative_int>();
break;
}case 1:{j["type"] = "bool";
j["value"] = x.template get<bool>();
break;
}case 2:{j["type"] = "float";
j["value"] = x.template get<float>();
break;
}case 3:{j["type"] = "std::optional<float>";
j["value"] = x.template get<std::optional<float>>();
break;
}case 4:{j["type"] = "std::vector<::FlexFlow::positive_int>";
j["value"] = x.template get<std::vector<::FlexFlow::positive_int>>();
break;
}case 5:{j["type"] = "std::vector<::FlexFlow::ff_dim_t>";
j["value"] = x.template get<std::vector<::FlexFlow::ff_dim_t>>();
break;
}case 6:{j["type"] = "::FlexFlow::OperatorType";
j["value"] = x.template get<::FlexFlow::OperatorType>();
break;
}case 7:{j["type"] = "std::optional<::FlexFlow::Activation>";
j["value"] = x.template get<std::optional<::FlexFlow::Activation>>();
break;
}case 8:{j["type"] = "::FlexFlow::ff_dim_t";
j["value"] = x.template get<::FlexFlow::ff_dim_t>();
break;
}case 9:{j["type"] = "std::optional<::FlexFlow::AggregateOp>";
j["value"] = x.template get<std::optional<::FlexFlow::AggregateOp>>();
break;
}case 10:{j["type"] = "std::optional<::FlexFlow::RegularizerAttrs>";
j["value"] = x.template get<std::optional<::FlexFlow::RegularizerAttrs>>();
break;
}case 11:{j["type"] = "::FlexFlow::PoolOp";
j["value"] = x.template get<::FlexFlow::PoolOp>();
break;
}case 12:{j["type"] = "::FlexFlow::TensorShape";
j["value"] = x.template get<::FlexFlow::TensorShape>();
break;
}case 13:{j["type"] = "::FlexFlow::TensorDims";
j["value"] = x.template get<::FlexFlow::TensorDims>();
break;
}case 14:{j["type"] = "::FlexFlow::DataType";
j["value"] = x.template get<::FlexFlow::DataType>();
break;
}case 15:{j["type"] = "::FlexFlow::TensorDimPermutation";
j["value"] = x.template get<::FlexFlow::TensorDimPermutation>();
break;
}default:{throw std::runtime_error(fmt::format("Unknown index {} for type OperatorAttributeValue", x.index()));
}}}
}// namespace nlohmann
namespace nlohmann{::FlexFlow::OperatorAttributeValue adl_serializer<::FlexFlow::OperatorAttributeValue>::from_json(json const &j){std::string key = j.at("type").template get<std::string>();
if (key == "::FlexFlow::nonnegative_int"){return ::FlexFlow::OperatorAttributeValue{j.at("value").template get<::FlexFlow::nonnegative_int>()};
} else if (key == "bool"){return ::FlexFlow::OperatorAttributeValue{j.at("value").template get<bool>()};
} else if (key == "float"){return ::FlexFlow::OperatorAttributeValue{j.at("value").template get<float>()};
} else if (key == "std::optional<float>"){return ::FlexFlow::OperatorAttributeValue{j.at("value").template get<std::optional<float>>()};
} else if (key == "std::vector<::FlexFlow::positive_int>"){return ::FlexFlow::OperatorAttributeValue{j.at("value").template get<std::vector<::FlexFlow::positive_int>>()};
} else if (key == "std::vector<::FlexFlow::ff_dim_t>"){return ::FlexFlow::OperatorAttributeValue{j.at("value").template get<std::vector<::FlexFlow::ff_dim_t>>()};
} else if (key == "::FlexFlow::OperatorType"){return ::FlexFlow::OperatorAttributeValue{j.at("value").template get<::FlexFlow::OperatorType>()};
} else if (key == "std::optional<::FlexFlow::Activation>"){return ::FlexFlow::OperatorAttributeValue{j.at("value").template get<std::optional<::FlexFlow::Activation>>()};
} else if (key == "::FlexFlow::ff_dim_t"){return ::FlexFlow::OperatorAttributeValue{j.at("value").template get<::FlexFlow::ff_dim_t>()};
} else if (key == "std::optional<::FlexFlow::AggregateOp>"){return ::FlexFlow::OperatorAttributeValue{j.at("value").template get<std::optional<::FlexFlow::AggregateOp>>()};
} else if (key == "std::optional<::FlexFlow::RegularizerAttrs>"){return ::FlexFlow::OperatorAttributeValue{j.at("value").template get<std::optional<::FlexFlow::RegularizerAttrs>>()};
} else if (key == "::FlexFlow::PoolOp"){return ::FlexFlow::OperatorAttributeValue{j.at("value").template get<::FlexFlow::PoolOp>()};
} else if (key == "::FlexFlow::TensorShape"){return ::FlexFlow::OperatorAttributeValue{j.at("value").template get<::FlexFlow::TensorShape>()};
} else if (key == "::FlexFlow::TensorDims"){return ::FlexFlow::OperatorAttributeValue{j.at("value").template get<::FlexFlow::TensorDims>()};
} else if (key == "::FlexFlow::DataType"){return ::FlexFlow::OperatorAttributeValue{j.at("value").template get<::FlexFlow::DataType>()};
} else if (key == "::FlexFlow::TensorDimPermutation"){return ::FlexFlow::OperatorAttributeValue{j.at("value").template get<::FlexFlow::TensorDimPermutation>()};
} else {throw std::runtime_error(fmt::format("Unknown type key {}", key));
}}
}// namespace nlohmann
namespace FlexFlow{std::string OperatorAttributeValue::debug_to_string() const{return fmt::to_string(*this);}
void OperatorAttributeValue::debug_print() const{std::cout << this->debug_to_string() << std::endl;}
std::string format_as(::FlexFlow::OperatorAttributeValue const &x){::nlohmann::json j = x;
return j.dump();
}
std::ostream & operator<<(std::ostream &s, ::FlexFlow::OperatorAttributeValue const &x){return s << fmt::to_string(x);
}
}// namespace FlexFlow
