// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/task-spec/include/task-spec/dynamic_graph/dynamic_node_invocation_sharding_info.dtg.toml
/* proj-data
{
  "generated_from": "8b6162a7f9b41055740383effc1dca80"
}
*/

#include "task-spec/dynamic_graph/dynamic_node_invocation_sharding_info.dtg.h"

#include <sstream>

namespace FlexFlow{DynamicNodeInvocationShardingInfo::DynamicNodeInvocationShardingInfo(::FlexFlow::nonempty_set<::FlexFlow::global_device_id_t> const &device_ids, ::FlexFlow::BinaryRelation<::FlexFlow::DynamicTensorSlot, ::FlexFlow::DynamicValueAttrsShardingInfo> const &value_sharding) : device_ids(device_ids), value_sharding(value_sharding){}
bool DynamicNodeInvocationShardingInfo::operator==(DynamicNodeInvocationShardingInfo const &other) const{
return std::tie(this->device_ids, this->value_sharding) == std::tie(other.device_ids, other.value_sharding);
}bool DynamicNodeInvocationShardingInfo::operator!=(DynamicNodeInvocationShardingInfo const &other) const{
return std::tie(this->device_ids, this->value_sharding) != std::tie(other.device_ids, other.value_sharding);
}bool DynamicNodeInvocationShardingInfo::operator<(DynamicNodeInvocationShardingInfo const &other) const{
return std::tie(this->device_ids, this->value_sharding) < std::tie(other.device_ids, other.value_sharding);
}bool DynamicNodeInvocationShardingInfo::operator>(DynamicNodeInvocationShardingInfo const &other) const{
return std::tie(this->device_ids, this->value_sharding) > std::tie(other.device_ids, other.value_sharding);
}bool DynamicNodeInvocationShardingInfo::operator<=(DynamicNodeInvocationShardingInfo const &other) const{
return std::tie(this->device_ids, this->value_sharding) <= std::tie(other.device_ids, other.value_sharding);
}bool DynamicNodeInvocationShardingInfo::operator>=(DynamicNodeInvocationShardingInfo const &other) const{
return std::tie(this->device_ids, this->value_sharding) >= std::tie(other.device_ids, other.value_sharding);
}}// namespace FlexFlow


///\cond
namespace std{size_t hash<FlexFlow::DynamicNodeInvocationShardingInfo>::operator()(::FlexFlow::DynamicNodeInvocationShardingInfo const &x)const{size_t result = 0;
result ^= std::hash<::FlexFlow::nonempty_set<::FlexFlow::global_device_id_t>>{}(x.device_ids) + 0x9e3779b9 + (result << 6) + (result >> 2);result ^= std::hash<::FlexFlow::BinaryRelation<::FlexFlow::DynamicTensorSlot, ::FlexFlow::DynamicValueAttrsShardingInfo>>{}(x.value_sharding) + 0x9e3779b9 + (result << 6) + (result >> 2);return result;
}}// namespace std

///\endcond

namespace nlohmann{void adl_serializer<::FlexFlow::DynamicNodeInvocationShardingInfo>::to_json(json &j, ::FlexFlow::DynamicNodeInvocationShardingInfo const &v) {j["__type"] = "DynamicNodeInvocationShardingInfo";
j["device_ids"] = v.device_ids;
j["value_sharding"] = v.value_sharding;
}}// namespace nlohmann

namespace nlohmann{::FlexFlow::DynamicNodeInvocationShardingInfo adl_serializer<::FlexFlow::DynamicNodeInvocationShardingInfo>::from_json(json const &j) {return ::FlexFlow::DynamicNodeInvocationShardingInfo{j.at("device_ids").template get<::FlexFlow::nonempty_set<::FlexFlow::global_device_id_t>>(), j.at("value_sharding").template get<::FlexFlow::BinaryRelation<::FlexFlow::DynamicTensorSlot, ::FlexFlow::DynamicValueAttrsShardingInfo>>()};}}// namespace nlohmann

namespace FlexFlow{std::string DynamicNodeInvocationShardingInfo::debug_to_string() const { return fmt::to_string(*this); }void DynamicNodeInvocationShardingInfo::debug_print() const { std::cout << this->debug_to_string() << std::endl; }std::string format_as(DynamicNodeInvocationShardingInfo const &x){::nlohmann::json j = x;
return j.dump();
}std::ostream &operator<<(std::ostream &s, DynamicNodeInvocationShardingInfo const &x) {return s << fmt::to_string(x);}}// namespace FlexFlow
