// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/task-spec/include/task-spec/dynamic_graph/dynamic_parameter_guid_t.dtg.toml
/* proj-data
{
  "generated_from": "7bac443ff63b4434beb67ca30c146e4e"
}
*/

#include "task-spec/dynamic_graph/dynamic_parameter_guid_t.dtg.h"


namespace FlexFlow{dynamic_parameter_guid_t::dynamic_parameter_guid_t(::FlexFlow::DataflowGraphInput const &raw_value) : raw_value(raw_value){}
bool dynamic_parameter_guid_t::operator==(dynamic_parameter_guid_t const &other) const{
return std::tie(this->raw_value) == std::tie(other.raw_value);
}bool dynamic_parameter_guid_t::operator!=(dynamic_parameter_guid_t const &other) const{
return std::tie(this->raw_value) != std::tie(other.raw_value);
}bool dynamic_parameter_guid_t::operator<(dynamic_parameter_guid_t const &other) const{
return std::tie(this->raw_value) < std::tie(other.raw_value);
}bool dynamic_parameter_guid_t::operator>(dynamic_parameter_guid_t const &other) const{
return std::tie(this->raw_value) > std::tie(other.raw_value);
}bool dynamic_parameter_guid_t::operator<=(dynamic_parameter_guid_t const &other) const{
return std::tie(this->raw_value) <= std::tie(other.raw_value);
}bool dynamic_parameter_guid_t::operator>=(dynamic_parameter_guid_t const &other) const{
return std::tie(this->raw_value) >= std::tie(other.raw_value);
}}// namespace FlexFlow


///\cond
namespace std{size_t hash<FlexFlow::dynamic_parameter_guid_t>::operator()(::FlexFlow::dynamic_parameter_guid_t const &x)const{size_t result = 0;
result ^= std::hash<::FlexFlow::DataflowGraphInput>{}(x.raw_value) + 0x9e3779b9 + (result << 6) + (result >> 2);return result;
}}// namespace std

///\endcond
