// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/task-spec/include/task-spec/dynamic_graph/dynamic_node_mapping.dtg.toml
/* proj-data
{
  "generated_from": "e5effb8b439285b76fef9f89e0329e0c"
}
*/

#include "task-spec/dynamic_graph/dynamic_node_mapping.dtg.h"

#include <sstream>

namespace FlexFlow{DynamicNodeMapping::DynamicNodeMapping(::FlexFlow::MappedOperatorTaskGroup const &op_task_group, ::FlexFlow::DeviceType const &device_type) : op_task_group(op_task_group), device_type(device_type){}
bool DynamicNodeMapping::operator==(DynamicNodeMapping const &other) const{
return std::tie(this->op_task_group, this->device_type) == std::tie(other.op_task_group, other.device_type);
}bool DynamicNodeMapping::operator!=(DynamicNodeMapping const &other) const{
return std::tie(this->op_task_group, this->device_type) != std::tie(other.op_task_group, other.device_type);
}bool DynamicNodeMapping::operator<(DynamicNodeMapping const &other) const{
return std::tie(this->op_task_group, this->device_type) < std::tie(other.op_task_group, other.device_type);
}bool DynamicNodeMapping::operator>(DynamicNodeMapping const &other) const{
return std::tie(this->op_task_group, this->device_type) > std::tie(other.op_task_group, other.device_type);
}bool DynamicNodeMapping::operator<=(DynamicNodeMapping const &other) const{
return std::tie(this->op_task_group, this->device_type) <= std::tie(other.op_task_group, other.device_type);
}bool DynamicNodeMapping::operator>=(DynamicNodeMapping const &other) const{
return std::tie(this->op_task_group, this->device_type) >= std::tie(other.op_task_group, other.device_type);
}}// namespace FlexFlow


///\cond
namespace std{size_t hash<FlexFlow::DynamicNodeMapping>::operator()(::FlexFlow::DynamicNodeMapping const &x)const{size_t result = 0;
result ^= std::hash<::FlexFlow::MappedOperatorTaskGroup>{}(x.op_task_group) + 0x9e3779b9 + (result << 6) + (result >> 2);result ^= std::hash<::FlexFlow::DeviceType>{}(x.device_type) + 0x9e3779b9 + (result << 6) + (result >> 2);return result;
}}// namespace std

///\endcond

namespace nlohmann{void adl_serializer<::FlexFlow::DynamicNodeMapping>::to_json(json &j, ::FlexFlow::DynamicNodeMapping const &v) {j["__type"] = "DynamicNodeMapping";
j["op_task_group"] = v.op_task_group;
j["device_type"] = v.device_type;
}}// namespace nlohmann

namespace nlohmann{::FlexFlow::DynamicNodeMapping adl_serializer<::FlexFlow::DynamicNodeMapping>::from_json(json const &j) {return ::FlexFlow::DynamicNodeMapping{j.at("op_task_group").template get<::FlexFlow::MappedOperatorTaskGroup>(), j.at("device_type").template get<::FlexFlow::DeviceType>()};}}// namespace nlohmann

namespace FlexFlow{std::string DynamicNodeMapping::debug_to_string() const { return fmt::to_string(*this); }void DynamicNodeMapping::debug_print() const { std::cout << this->debug_to_string() << std::endl; }std::string format_as(DynamicNodeMapping const &x){::nlohmann::json j = x;
return j.dump();
}std::ostream &operator<<(std::ostream &s, DynamicNodeMapping const &x) {return s << fmt::to_string(x);}}// namespace FlexFlow
