// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/task-spec/include/task-spec/dynamic_graph/dynamic_tensor_role.dtg.toml
/* proj-data
{
  "generated_from": "63c1265d8d5c7dd262deb60adf6ba3ef"
}
*/

#include "task-spec/dynamic_graph/dynamic_tensor_role.dtg.h"

#include <sstream>

namespace FlexFlow{DynamicTensorRole::DynamicTensorRole(::FlexFlow::FwbTensorType const &v) : raw_variant(v) { }
DynamicTensorRole::DynamicTensorRole(::FlexFlow::DynamicOptimizerTensorRole const &v) : raw_variant(v) { }
DynamicTensorRole::DynamicTensorRole(::FlexFlow::DynamicLossTensorRole const &v) : raw_variant(v) { }bool DynamicTensorRole::operator==(DynamicTensorRole const &other) const{return this->raw_variant == other.raw_variant;}
bool DynamicTensorRole::operator!=(DynamicTensorRole const &other) const{return this->raw_variant != other.raw_variant;}
bool DynamicTensorRole::operator<(DynamicTensorRole const &other) const{return this->raw_variant < other.raw_variant;}
bool DynamicTensorRole::operator>(DynamicTensorRole const &other) const{return this->raw_variant > other.raw_variant;}
bool DynamicTensorRole::operator<=(DynamicTensorRole const &other) const{return this->raw_variant <= other.raw_variant;}
bool DynamicTensorRole::operator>=(DynamicTensorRole const &other) const{return this->raw_variant >= other.raw_variant;}
::FlexFlow::FwbTensorType const & DynamicTensorRole::require_fwb_tensor() const{bool holds_expected = std::holds_alternative<::FlexFlow::FwbTensorType>(this->raw_variant);
ASSERT(holds_expected, "Expected ::FlexFlow::FwbTensorType");
return std::get<::FlexFlow::FwbTensorType>(this->raw_variant);
}
::FlexFlow::FwbTensorType & DynamicTensorRole::require_fwb_tensor(){bool holds_expected = std::holds_alternative<::FlexFlow::FwbTensorType>(this->raw_variant);
ASSERT(holds_expected, "Expected ::FlexFlow::FwbTensorType");
return std::get<::FlexFlow::FwbTensorType>(this->raw_variant);
}
::FlexFlow::DynamicOptimizerTensorRole const & DynamicTensorRole::require_optimizer_tensor() const{bool holds_expected = std::holds_alternative<::FlexFlow::DynamicOptimizerTensorRole>(this->raw_variant);
ASSERT(holds_expected, "Expected ::FlexFlow::DynamicOptimizerTensorRole");
return std::get<::FlexFlow::DynamicOptimizerTensorRole>(this->raw_variant);
}
::FlexFlow::DynamicOptimizerTensorRole & DynamicTensorRole::require_optimizer_tensor(){bool holds_expected = std::holds_alternative<::FlexFlow::DynamicOptimizerTensorRole>(this->raw_variant);
ASSERT(holds_expected, "Expected ::FlexFlow::DynamicOptimizerTensorRole");
return std::get<::FlexFlow::DynamicOptimizerTensorRole>(this->raw_variant);
}
::FlexFlow::DynamicLossTensorRole const & DynamicTensorRole::require_loss_tensor() const{bool holds_expected = std::holds_alternative<::FlexFlow::DynamicLossTensorRole>(this->raw_variant);
ASSERT(holds_expected, "Expected ::FlexFlow::DynamicLossTensorRole");
return std::get<::FlexFlow::DynamicLossTensorRole>(this->raw_variant);
}
::FlexFlow::DynamicLossTensorRole & DynamicTensorRole::require_loss_tensor(){bool holds_expected = std::holds_alternative<::FlexFlow::DynamicLossTensorRole>(this->raw_variant);
ASSERT(holds_expected, "Expected ::FlexFlow::DynamicLossTensorRole");
return std::get<::FlexFlow::DynamicLossTensorRole>(this->raw_variant);
}
std::optional<::FlexFlow::FwbTensorType> DynamicTensorRole::try_require_fwb_tensor() const{if (this->is_fwb_tensor()) {return this->require_fwb_tensor();
}else {return std::nullopt;
}}
std::optional<::FlexFlow::DynamicOptimizerTensorRole> DynamicTensorRole::try_require_optimizer_tensor() const{if (this->is_optimizer_tensor()) {return this->require_optimizer_tensor();
}else {return std::nullopt;
}}
std::optional<::FlexFlow::DynamicLossTensorRole> DynamicTensorRole::try_require_loss_tensor() const{if (this->is_loss_tensor()) {return this->require_loss_tensor();
}else {return std::nullopt;
}}
bool DynamicTensorRole::is_fwb_tensor() const{return std::holds_alternative<::FlexFlow::FwbTensorType>(this->raw_variant);
}
bool DynamicTensorRole::is_optimizer_tensor() const{return std::holds_alternative<::FlexFlow::DynamicOptimizerTensorRole>(this->raw_variant);
}
bool DynamicTensorRole::is_loss_tensor() const{return std::holds_alternative<::FlexFlow::DynamicLossTensorRole>(this->raw_variant);
}
}// namespace FlexFlow

///\cond
namespace std{size_t hash<::FlexFlow::DynamicTensorRole>::operator()(::FlexFlow::DynamicTensorRole const &x) const{return std::hash<std::variant<::FlexFlow::FwbTensorType, ::FlexFlow::DynamicOptimizerTensorRole, ::FlexFlow::DynamicLossTensorRole>>{}(x.raw_variant);}
}// namespace std

///\endcond
namespace nlohmann{void adl_serializer<::FlexFlow::DynamicTensorRole>::to_json(json &j, ::FlexFlow::DynamicTensorRole const &x){j["__type"] = "DynamicTensorRole";
switch (x.index()){case 0:{j["type"] = "fwb_tensor";
j["value"] = x.template get<::FlexFlow::FwbTensorType>();
break;
}case 1:{j["type"] = "optimizer_tensor";
j["value"] = x.template get<::FlexFlow::DynamicOptimizerTensorRole>();
break;
}case 2:{j["type"] = "loss_tensor";
j["value"] = x.template get<::FlexFlow::DynamicLossTensorRole>();
break;
}default:{throw std::runtime_error(fmt::format("Unknown index {} for type DynamicTensorRole", x.index()));
}}}
}// namespace nlohmann
namespace nlohmann{::FlexFlow::DynamicTensorRole adl_serializer<::FlexFlow::DynamicTensorRole>::from_json(json const &j){std::string key = j.at("type").template get<std::string>();
if (key == "fwb_tensor"){return ::FlexFlow::DynamicTensorRole{j.at("value").template get<::FlexFlow::FwbTensorType>()};
} else if (key == "optimizer_tensor"){return ::FlexFlow::DynamicTensorRole{j.at("value").template get<::FlexFlow::DynamicOptimizerTensorRole>()};
} else if (key == "loss_tensor"){return ::FlexFlow::DynamicTensorRole{j.at("value").template get<::FlexFlow::DynamicLossTensorRole>()};
} else {throw std::runtime_error(fmt::format("Unknown type key {}", key));
}}
}// namespace nlohmann
namespace FlexFlow{std::string DynamicTensorRole::debug_to_string() const{return fmt::to_string(*this);}
void DynamicTensorRole::debug_print() const{std::cout << this->debug_to_string() << std::endl;}
std::string format_as(::FlexFlow::DynamicTensorRole const &x){::nlohmann::json j = x;
return j.dump();
}
std::ostream & operator<<(std::ostream &s, ::FlexFlow::DynamicTensorRole const &x){return s << fmt::to_string(x);
}
}// namespace FlexFlow
