// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/task-spec/include/task-spec/dynamic_graph/subgradient_id_t.dtg.toml
/* proj-data
{
  "generated_from": "4fcb9a458d88ac30119e195a74e9c534"
}
*/

#include "task-spec/dynamic_graph/subgradient_id_t.dtg.h"

#include <sstream>

namespace FlexFlow{subgradient_id_t::subgradient_id_t(::FlexFlow::TensorSlotName const &gradient_reduction_slot) : gradient_reduction_slot(gradient_reduction_slot){}
bool subgradient_id_t::operator==(subgradient_id_t const &other) const{
return std::tie(this->gradient_reduction_slot) == std::tie(other.gradient_reduction_slot);
}bool subgradient_id_t::operator!=(subgradient_id_t const &other) const{
return std::tie(this->gradient_reduction_slot) != std::tie(other.gradient_reduction_slot);
}bool subgradient_id_t::operator<(subgradient_id_t const &other) const{
return std::tie(this->gradient_reduction_slot) < std::tie(other.gradient_reduction_slot);
}bool subgradient_id_t::operator>(subgradient_id_t const &other) const{
return std::tie(this->gradient_reduction_slot) > std::tie(other.gradient_reduction_slot);
}bool subgradient_id_t::operator<=(subgradient_id_t const &other) const{
return std::tie(this->gradient_reduction_slot) <= std::tie(other.gradient_reduction_slot);
}bool subgradient_id_t::operator>=(subgradient_id_t const &other) const{
return std::tie(this->gradient_reduction_slot) >= std::tie(other.gradient_reduction_slot);
}}// namespace FlexFlow


///\cond
namespace std{size_t hash<FlexFlow::subgradient_id_t>::operator()(::FlexFlow::subgradient_id_t const &x)const{size_t result = 0;
result ^= std::hash<::FlexFlow::TensorSlotName>{}(x.gradient_reduction_slot) + 0x9e3779b9 + (result << 6) + (result >> 2);return result;
}}// namespace std

///\endcond

namespace nlohmann{void adl_serializer<::FlexFlow::subgradient_id_t>::to_json(json &j, ::FlexFlow::subgradient_id_t const &v) {j["__type"] = "subgradient_id_t";
j["gradient_reduction_slot"] = v.gradient_reduction_slot;
}}// namespace nlohmann

namespace nlohmann{::FlexFlow::subgradient_id_t adl_serializer<::FlexFlow::subgradient_id_t>::from_json(json const &j) {return ::FlexFlow::subgradient_id_t{j.at("gradient_reduction_slot").template get<::FlexFlow::TensorSlotName>()};}}// namespace nlohmann

namespace FlexFlow{std::string subgradient_id_t::debug_to_string() const { return fmt::to_string(*this); }void subgradient_id_t::debug_print() const { std::cout << this->debug_to_string() << std::endl; }std::string format_as(subgradient_id_t const &x){::nlohmann::json j = x;
return j.dump();
}std::ostream &operator<<(std::ostream &s, subgradient_id_t const &x) {return s << fmt::to_string(x);}}// namespace FlexFlow
