// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/task-spec/include/task-spec/dynamic_graph/training_op_type.dtg.toml
/* proj-data
{
  "generated_from": "d27c09b34f59646f3c32c8bcb1361fff"
}
*/

#include "task-spec/dynamic_graph/training_op_type.dtg.h"

#include <sstream>

namespace FlexFlow{TrainingOpType::TrainingOpType(::FlexFlow::OperatorType const &v) : raw_variant(v) { }
TrainingOpType::TrainingOpType(::FlexFlow::TrainingOnlyOpType const &v) : raw_variant(v) { }bool TrainingOpType::operator==(TrainingOpType const &other) const{return this->raw_variant == other.raw_variant;}
bool TrainingOpType::operator!=(TrainingOpType const &other) const{return this->raw_variant != other.raw_variant;}
::FlexFlow::OperatorType const & TrainingOpType::require_pcg_op() const{bool holds_expected = std::holds_alternative<::FlexFlow::OperatorType>(this->raw_variant);
ASSERT(holds_expected, "Expected ::FlexFlow::OperatorType");
return std::get<::FlexFlow::OperatorType>(this->raw_variant);
}
::FlexFlow::OperatorType & TrainingOpType::require_pcg_op(){bool holds_expected = std::holds_alternative<::FlexFlow::OperatorType>(this->raw_variant);
ASSERT(holds_expected, "Expected ::FlexFlow::OperatorType");
return std::get<::FlexFlow::OperatorType>(this->raw_variant);
}
::FlexFlow::TrainingOnlyOpType const & TrainingOpType::require_training_only_op() const{bool holds_expected = std::holds_alternative<::FlexFlow::TrainingOnlyOpType>(this->raw_variant);
ASSERT(holds_expected, "Expected ::FlexFlow::TrainingOnlyOpType");
return std::get<::FlexFlow::TrainingOnlyOpType>(this->raw_variant);
}
::FlexFlow::TrainingOnlyOpType & TrainingOpType::require_training_only_op(){bool holds_expected = std::holds_alternative<::FlexFlow::TrainingOnlyOpType>(this->raw_variant);
ASSERT(holds_expected, "Expected ::FlexFlow::TrainingOnlyOpType");
return std::get<::FlexFlow::TrainingOnlyOpType>(this->raw_variant);
}
std::optional<::FlexFlow::OperatorType> TrainingOpType::try_require_pcg_op() const{if (this->is_pcg_op()) {return this->require_pcg_op();
}else {return std::nullopt;
}}
std::optional<::FlexFlow::TrainingOnlyOpType> TrainingOpType::try_require_training_only_op() const{if (this->is_training_only_op()) {return this->require_training_only_op();
}else {return std::nullopt;
}}
bool TrainingOpType::is_pcg_op() const{return std::holds_alternative<::FlexFlow::OperatorType>(this->raw_variant);
}
bool TrainingOpType::is_training_only_op() const{return std::holds_alternative<::FlexFlow::TrainingOnlyOpType>(this->raw_variant);
}
}// namespace FlexFlow

///\cond
namespace std{size_t hash<::FlexFlow::TrainingOpType>::operator()(::FlexFlow::TrainingOpType const &x) const{return std::hash<std::variant<::FlexFlow::OperatorType, ::FlexFlow::TrainingOnlyOpType>>{}(x.raw_variant);}
}// namespace std

///\endcond
namespace nlohmann{void adl_serializer<::FlexFlow::TrainingOpType>::to_json(json &j, ::FlexFlow::TrainingOpType const &x){j["__type"] = "TrainingOpType";
switch (x.index()){case 0:{j["type"] = "pcg_op";
j["value"] = x.template get<::FlexFlow::OperatorType>();
break;
}case 1:{j["type"] = "training_only_op";
j["value"] = x.template get<::FlexFlow::TrainingOnlyOpType>();
break;
}default:{throw std::runtime_error(fmt::format("Unknown index {} for type TrainingOpType", x.index()));
}}}
}// namespace nlohmann
namespace nlohmann{::FlexFlow::TrainingOpType adl_serializer<::FlexFlow::TrainingOpType>::from_json(json const &j){std::string key = j.at("type").template get<std::string>();
if (key == "pcg_op"){return ::FlexFlow::TrainingOpType{j.at("value").template get<::FlexFlow::OperatorType>()};
} else if (key == "training_only_op"){return ::FlexFlow::TrainingOpType{j.at("value").template get<::FlexFlow::TrainingOnlyOpType>()};
} else {throw std::runtime_error(fmt::format("Unknown type key {}", key));
}}
}// namespace nlohmann
namespace FlexFlow{std::string TrainingOpType::debug_to_string() const{return fmt::to_string(*this);}
void TrainingOpType::debug_print() const{std::cout << this->debug_to_string() << std::endl;}
std::string format_as(::FlexFlow::TrainingOpType const &x){::nlohmann::json j = x;
return j.dump();
}
std::ostream & operator<<(std::ostream &s, ::FlexFlow::TrainingOpType const &x){return s << fmt::to_string(x);
}
}// namespace FlexFlow
