// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/task-spec/include/task-spec/fwb_tensor_type.dtg.toml
/* proj-data
{
  "generated_from": "6333f9aae3d526a0ee672b6b3d271ed6"
}
*/

#ifndef _FLEXFLOW_LIB_TASK_SPEC_INCLUDE_TASK_SPEC_FWB_TENSOR_TYPE_DTG_H
#define _FLEXFLOW_LIB_TASK_SPEC_INCLUDE_TASK_SPEC_FWB_TENSOR_TYPE_DTG_H

#include <string>
#include <ostream>
#include <fmt/format.h>
#include <nlohmann/json.hpp>
#include <functional>
#include <rapidcheck.h>

namespace FlexFlow{enum class FwbTensorType{FORWARD, GRADIENT};std::string format_as(FwbTensorType);
std::ostream &operator<<(std::ostream &, FwbTensorType);
void to_json(::nlohmann::json &, FwbTensorType);
void from_json(::nlohmann::json const &, FwbTensorType &);
}// namespace FlexFlow

///\cond
namespace std{template <>
struct hash<FlexFlow::FwbTensorType> {size_t operator()(FlexFlow::FwbTensorType) const;
};}// namespace std

///\endcond
namespace rc{template <>
struct Arbitrary<FlexFlow::FwbTensorType> {static Gen<FlexFlow::FwbTensorType> arbitrary();
};}// namespace rc

#endif // _FLEXFLOW_LIB_TASK_SPEC_INCLUDE_TASK_SPEC_FWB_TENSOR_TYPE_DTG_H
