// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/utils/include/utils/graph/open_dataflow_graph/algorithms/open_dataflow_graph_data.dtg.toml
/* proj-data
{
  "generated_from": "f01c61b918564d5330bc58ca36a1c703"
}
*/

#ifndef _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_GRAPH_OPEN_DATAFLOW_GRAPH_ALGORITHMS_OPEN_DATAFLOW_GRAPH_DATA_DTG_H
#define _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_GRAPH_OPEN_DATAFLOW_GRAPH_ALGORITHMS_OPEN_DATAFLOW_GRAPH_DATA_DTG_H

#include <tuple>
#include <iostream>
#include <functional>
#include <set>
#include <nlohmann/json.hpp>
#include "utils/graph/dataflow_graph/dataflow_output.dtg.h"
#include <ostream>
#include <fmt/format.h>
#include "utils/graph/open_dataflow_graph/open_dataflow_edge.dtg.h"
#include "utils/graph/open_dataflow_graph/dataflow_graph_input.dtg.h"
#include "utils/graph/node/node.dtg.h"


namespace FlexFlow{struct OpenDataflowGraphData{OpenDataflowGraphData() = delete;
explicit OpenDataflowGraphData(std::set<::FlexFlow::Node> const &nodes, std::set<::FlexFlow::OpenDataflowEdge> const &edges, std::set<::FlexFlow::DataflowGraphInput> const &inputs, std::set<::FlexFlow::DataflowOutput> const &outputs);

bool operator==(OpenDataflowGraphData const &) const;bool operator!=(OpenDataflowGraphData const &) const;
std::string debug_to_string() const;void debug_print() const;
std::set<::FlexFlow::Node> nodes;
std::set<::FlexFlow::OpenDataflowEdge> edges;
std::set<::FlexFlow::DataflowGraphInput> inputs;
std::set<::FlexFlow::DataflowOutput> outputs;
};}// namespace FlexFlow


///\cond
namespace std{template <>
struct hash<::FlexFlow::OpenDataflowGraphData>{size_t operator()(::FlexFlow::OpenDataflowGraphData const &)const;};}// namespace std

///\endcond

namespace nlohmann{template <>
struct adl_serializer<::FlexFlow::OpenDataflowGraphData>{static void to_json(json &, ::FlexFlow::OpenDataflowGraphData const &);
};}// namespace nlohmann

namespace FlexFlow{std::string format_as(OpenDataflowGraphData const &);
std::ostream &operator<<(std::ostream &, OpenDataflowGraphData const &);}// namespace FlexFlow

#endif // _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_GRAPH_OPEN_DATAFLOW_GRAPH_ALGORITHMS_OPEN_DATAFLOW_GRAPH_DATA_DTG_H
