// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/pcg/include/pcg/machine_specification_dimension.dtg.toml
/* proj-data
{
  "generated_from": "f20ab40d318c7e083c2a97373acfb0c7"
}
*/

#include "pcg/machine_specification_dimension.dtg.h"

#include <stdexcept>
#include <sstream>


///\cond
namespace std{size_t hash<FlexFlow::MachineSpecificationDimension>::operator()(FlexFlow::MachineSpecificationDimension x) const{return std::hash<int>{}(static_cast<int>(x));
}}// namespace std

///\endcond
namespace FlexFlow{std::string format_as(MachineSpecificationDimension x){::nlohmann::json j = x;
return j.dump();
}std::ostream &operator<<(std::ostream &s, MachineSpecificationDimension x){return s << fmt::to_string(x);}}// namespace FlexFlow
namespace FlexFlow{void to_json(::nlohmann::json &j, MachineSpecificationDimension x){switch (x){case MachineSpecificationDimension::INTER_NODE:
j = "INTER_NODE";
break;
case MachineSpecificationDimension::INTRA_NODE:
j = "INTRA_NODE";
break;
default:
std::ostringstream oss;
oss << "Unknown MachineSpecificationDimension value " << static_cast<int>(x);
throw std::runtime_error(oss.str());
}}}// namespace FlexFlow
namespace FlexFlow{void from_json(::nlohmann::json const &j, MachineSpecificationDimension &x){std::string as_str = j.get<std::string>();
if (as_str == "INTER_NODE"){x = MachineSpecificationDimension::INTER_NODE;
}else if (as_str == "INTRA_NODE"){x = MachineSpecificationDimension::INTRA_NODE;
}else {std::ostringstream oss;
oss << "Unknown MachineSpecificationDimension value " << as_str;
throw std::runtime_error(oss.str());
}}}// namespace FlexFlow
namespace rc{Gen<FlexFlow::MachineSpecificationDimension> Arbitrary<FlexFlow::MachineSpecificationDimension>::arbitrary(){return gen::element<FlexFlow::MachineSpecificationDimension>(FlexFlow::MachineSpecificationDimension::INTER_NODE, FlexFlow::MachineSpecificationDimension::INTRA_NODE);}}// namespace rc
