// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/pcg/include/pcg/machine_specification.dtg.toml
/* proj-data
{
  "generated_from": "4881a7031f7a3014328c7d657eb9408c"
}
*/

#include "pcg/machine_specification.dtg.h"

#include <sstream>

namespace FlexFlow{MachineSpecification::MachineSpecification(::FlexFlow::MachineComputeSpecification const &compute_specification, ::FlexFlow::MachineInterconnectSpecification const &interconnect_specification) : compute_specification(compute_specification), interconnect_specification(interconnect_specification){}
bool MachineSpecification::operator==(MachineSpecification const &other) const{
return std::tie(this->compute_specification, this->interconnect_specification) == std::tie(other.compute_specification, other.interconnect_specification);
}bool MachineSpecification::operator!=(MachineSpecification const &other) const{
return std::tie(this->compute_specification, this->interconnect_specification) != std::tie(other.compute_specification, other.interconnect_specification);
}bool MachineSpecification::operator<(MachineSpecification const &other) const{
return std::tie(this->compute_specification, this->interconnect_specification) < std::tie(other.compute_specification, other.interconnect_specification);
}bool MachineSpecification::operator>(MachineSpecification const &other) const{
return std::tie(this->compute_specification, this->interconnect_specification) > std::tie(other.compute_specification, other.interconnect_specification);
}bool MachineSpecification::operator<=(MachineSpecification const &other) const{
return std::tie(this->compute_specification, this->interconnect_specification) <= std::tie(other.compute_specification, other.interconnect_specification);
}bool MachineSpecification::operator>=(MachineSpecification const &other) const{
return std::tie(this->compute_specification, this->interconnect_specification) >= std::tie(other.compute_specification, other.interconnect_specification);
}}// namespace FlexFlow


///\cond
namespace std{size_t hash<FlexFlow::MachineSpecification>::operator()(::FlexFlow::MachineSpecification const &x)const{size_t result = 0;
result ^= std::hash<::FlexFlow::MachineComputeSpecification>{}(x.compute_specification) + 0x9e3779b9 + (result << 6) + (result >> 2);result ^= std::hash<::FlexFlow::MachineInterconnectSpecification>{}(x.interconnect_specification) + 0x9e3779b9 + (result << 6) + (result >> 2);return result;
}}// namespace std

///\endcond

namespace nlohmann{void adl_serializer<::FlexFlow::MachineSpecification>::to_json(json &j, ::FlexFlow::MachineSpecification const &v) {j["__type"] = "MachineSpecification";
j["compute_specification"] = v.compute_specification;
j["interconnect_specification"] = v.interconnect_specification;
}}// namespace nlohmann

namespace nlohmann{::FlexFlow::MachineSpecification adl_serializer<::FlexFlow::MachineSpecification>::from_json(json const &j) {return ::FlexFlow::MachineSpecification{j.at("compute_specification").template get<::FlexFlow::MachineComputeSpecification>(), j.at("interconnect_specification").template get<::FlexFlow::MachineInterconnectSpecification>()};}}// namespace nlohmann

namespace rc{Gen<::FlexFlow::MachineSpecification> Arbitrary<::FlexFlow::MachineSpecification>::arbitrary() {return gen::construct<::FlexFlow::MachineSpecification>(gen::arbitrary<::FlexFlow::MachineComputeSpecification>(), gen::arbitrary<::FlexFlow::MachineInterconnectSpecification>());}}// namespace rc

namespace FlexFlow{std::string MachineSpecification::debug_to_string() const { return fmt::to_string(*this); }void MachineSpecification::debug_print() const { std::cout << this->debug_to_string() << std::endl; }std::string format_as(MachineSpecification const &x){::nlohmann::json j = x;
return j.dump();
}std::ostream &operator<<(std::ostream &s, MachineSpecification const &x) {return s << fmt::to_string(x);}}// namespace FlexFlow
