// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/pcg/include/pcg/num_points_t.dtg.toml
/* proj-data
{
  "generated_from": "8752220c475f31d1bf328f5378966579"
}
*/

#include "pcg/num_points_t.dtg.h"

#include <sstream>

namespace FlexFlow{num_points_t::num_points_t(::FlexFlow::positive_int const &unwrapped) : unwrapped(unwrapped){}
bool num_points_t::operator==(num_points_t const &other) const{
return std::tie(this->unwrapped) == std::tie(other.unwrapped);
}bool num_points_t::operator!=(num_points_t const &other) const{
return std::tie(this->unwrapped) != std::tie(other.unwrapped);
}bool num_points_t::operator<(num_points_t const &other) const{
return std::tie(this->unwrapped) < std::tie(other.unwrapped);
}bool num_points_t::operator>(num_points_t const &other) const{
return std::tie(this->unwrapped) > std::tie(other.unwrapped);
}bool num_points_t::operator<=(num_points_t const &other) const{
return std::tie(this->unwrapped) <= std::tie(other.unwrapped);
}bool num_points_t::operator>=(num_points_t const &other) const{
return std::tie(this->unwrapped) >= std::tie(other.unwrapped);
}}// namespace FlexFlow


///\cond
namespace std{size_t hash<FlexFlow::num_points_t>::operator()(::FlexFlow::num_points_t const &x)const{size_t result = 0;
result ^= std::hash<::FlexFlow::positive_int>{}(x.unwrapped) + 0x9e3779b9 + (result << 6) + (result >> 2);return result;
}}// namespace std

///\endcond

namespace nlohmann{void adl_serializer<::FlexFlow::num_points_t>::to_json(json &j, ::FlexFlow::num_points_t const &v) {j["__type"] = "num_points_t";
j["unwrapped"] = v.unwrapped;
}}// namespace nlohmann

namespace nlohmann{::FlexFlow::num_points_t adl_serializer<::FlexFlow::num_points_t>::from_json(json const &j) {return ::FlexFlow::num_points_t{j.at("unwrapped").template get<::FlexFlow::positive_int>()};}}// namespace nlohmann

namespace rc{Gen<::FlexFlow::num_points_t> Arbitrary<::FlexFlow::num_points_t>::arbitrary() {return gen::construct<::FlexFlow::num_points_t>(gen::arbitrary<::FlexFlow::positive_int>());}}// namespace rc

namespace FlexFlow{std::string num_points_t::debug_to_string() const { return fmt::to_string(*this); }void num_points_t::debug_print() const { std::cout << this->debug_to_string() << std::endl; }std::string format_as(num_points_t const &x){::nlohmann::json j = x;
return j.dump();
}std::ostream &operator<<(std::ostream &s, num_points_t const &x) {return s << fmt::to_string(x);}}// namespace FlexFlow
