// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/pcg/include/pcg/optimizer_slot_name.dtg.toml
/* proj-data
{
  "generated_from": "a12c2cfbfd78a9947edf76ffc450e6cf"
}
*/

#include "pcg/optimizer_slot_name.dtg.h"

#include <stdexcept>
#include <sstream>


///\cond
namespace std{size_t hash<FlexFlow::OptimizerSlotName>::operator()(FlexFlow::OptimizerSlotName x) const{return std::hash<int>{}(static_cast<int>(x));
}}// namespace std

///\endcond
namespace FlexFlow{std::string format_as(OptimizerSlotName x){::nlohmann::json j = x;
return j.dump();
}std::ostream &operator<<(std::ostream &s, OptimizerSlotName x){return s << fmt::to_string(x);}}// namespace FlexFlow
namespace FlexFlow{void to_json(::nlohmann::json &j, OptimizerSlotName x){switch (x){case OptimizerSlotName::SGD_V:
j = "SGD_V";
break;
case OptimizerSlotName::ADAM_M:
j = "ADAM_M";
break;
case OptimizerSlotName::ADAM_V:
j = "ADAM_V";
break;
default:
std::ostringstream oss;
oss << "Unknown OptimizerSlotName value " << static_cast<int>(x);
throw std::runtime_error(oss.str());
}}}// namespace FlexFlow
namespace FlexFlow{void from_json(::nlohmann::json const &j, OptimizerSlotName &x){std::string as_str = j.get<std::string>();
if (as_str == "SGD_V"){x = OptimizerSlotName::SGD_V;
}else if (as_str == "ADAM_M"){x = OptimizerSlotName::ADAM_M;
}else if (as_str == "ADAM_V"){x = OptimizerSlotName::ADAM_V;
}else {std::ostringstream oss;
oss << "Unknown OptimizerSlotName value " << as_str;
throw std::runtime_error(oss.str());
}}}// namespace FlexFlow
namespace rc{Gen<FlexFlow::OptimizerSlotName> Arbitrary<FlexFlow::OptimizerSlotName>::arbitrary(){return gen::element<FlexFlow::OptimizerSlotName>(FlexFlow::OptimizerSlotName::SGD_V, FlexFlow::OptimizerSlotName::ADAM_M, FlexFlow::OptimizerSlotName::ADAM_V);}}// namespace rc
