// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/substitutions/include/substitutions/output_graph/output_graph_expr_input.dtg.toml
/* proj-data
{
  "generated_from": "3e4f61e9d5bc1273d8f5081d35f3094c"
}
*/

#include "substitutions/output_graph/output_graph_expr_input.dtg.h"

#include <sstream>

namespace FlexFlow{OutputGraphExprInput::OutputGraphExprInput(::FlexFlow::KwargDataflowGraphInput<int> const &raw_dataflow_graph_input) : raw_dataflow_graph_input(raw_dataflow_graph_input){}
bool OutputGraphExprInput::operator==(OutputGraphExprInput const &other) const{
return std::tie(this->raw_dataflow_graph_input) == std::tie(other.raw_dataflow_graph_input);
}bool OutputGraphExprInput::operator!=(OutputGraphExprInput const &other) const{
return std::tie(this->raw_dataflow_graph_input) != std::tie(other.raw_dataflow_graph_input);
}bool OutputGraphExprInput::operator<(OutputGraphExprInput const &other) const{
return std::tie(this->raw_dataflow_graph_input) < std::tie(other.raw_dataflow_graph_input);
}bool OutputGraphExprInput::operator>(OutputGraphExprInput const &other) const{
return std::tie(this->raw_dataflow_graph_input) > std::tie(other.raw_dataflow_graph_input);
}bool OutputGraphExprInput::operator<=(OutputGraphExprInput const &other) const{
return std::tie(this->raw_dataflow_graph_input) <= std::tie(other.raw_dataflow_graph_input);
}bool OutputGraphExprInput::operator>=(OutputGraphExprInput const &other) const{
return std::tie(this->raw_dataflow_graph_input) >= std::tie(other.raw_dataflow_graph_input);
}}// namespace FlexFlow


///\cond
namespace std{size_t hash<FlexFlow::OutputGraphExprInput>::operator()(::FlexFlow::OutputGraphExprInput const &x)const{size_t result = 0;
result ^= std::hash<::FlexFlow::KwargDataflowGraphInput<int>>{}(x.raw_dataflow_graph_input) + 0x9e3779b9 + (result << 6) + (result >> 2);return result;
}}// namespace std

///\endcond

namespace nlohmann{void adl_serializer<::FlexFlow::OutputGraphExprInput>::to_json(json &j, ::FlexFlow::OutputGraphExprInput const &v) {j["__type"] = "OutputGraphExprInput";
j["raw_dataflow_graph_input"] = v.raw_dataflow_graph_input;
}}// namespace nlohmann

namespace FlexFlow{std::string OutputGraphExprInput::debug_to_string() const { return fmt::to_string(*this); }void OutputGraphExprInput::debug_print() const { std::cout << this->debug_to_string() << std::endl; }std::string format_as(OutputGraphExprInput const &x){::nlohmann::json j = x;
return j.dump();
}std::ostream &operator<<(std::ostream &s, OutputGraphExprInput const &x) {return s << fmt::to_string(x);}}// namespace FlexFlow
