// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/realm-execution/include/realm-execution/tasks/impl/serializable_op_task_launch_args.dtg.toml
/* proj-data
{
  "generated_from": "7aa677c0b5fd499f9873ec3b45fb887f"
}
*/

#include "realm-execution/tasks/impl/serializable_op_task_launch_args.dtg.h"

#include <sstream>
#include "utils/json/optional.h"
#include "utils/fmt/optional.h"

namespace FlexFlow{SerializableOpTaskLaunchArgs::SerializableOpTaskLaunchArgs(::FlexFlow::dynamic_invocation_id_t const &invocation_id, std::optional<::FlexFlow::OptimizerAttrs> const &optimizer_attrs) : invocation_id(invocation_id), optimizer_attrs(optimizer_attrs){}
bool SerializableOpTaskLaunchArgs::operator==(SerializableOpTaskLaunchArgs const &other) const{
return std::tie(this->invocation_id, this->optimizer_attrs) == std::tie(other.invocation_id, other.optimizer_attrs);
}bool SerializableOpTaskLaunchArgs::operator!=(SerializableOpTaskLaunchArgs const &other) const{
return std::tie(this->invocation_id, this->optimizer_attrs) != std::tie(other.invocation_id, other.optimizer_attrs);
}}// namespace FlexFlow


///\cond
namespace std{size_t hash<FlexFlow::SerializableOpTaskLaunchArgs>::operator()(::FlexFlow::SerializableOpTaskLaunchArgs const &x)const{size_t result = 0;
result ^= std::hash<::FlexFlow::dynamic_invocation_id_t>{}(x.invocation_id) + 0x9e3779b9 + (result << 6) + (result >> 2);result ^= std::hash<std::optional<::FlexFlow::OptimizerAttrs>>{}(x.optimizer_attrs) + 0x9e3779b9 + (result << 6) + (result >> 2);return result;
}}// namespace std

///\endcond

namespace nlohmann{void adl_serializer<::FlexFlow::SerializableOpTaskLaunchArgs>::to_json(json &j, ::FlexFlow::SerializableOpTaskLaunchArgs const &v) {j["__type"] = "SerializableOpTaskLaunchArgs";
j["invocation_id"] = v.invocation_id;
j["optimizer_attrs"] = v.optimizer_attrs;
}}// namespace nlohmann

namespace nlohmann{::FlexFlow::SerializableOpTaskLaunchArgs adl_serializer<::FlexFlow::SerializableOpTaskLaunchArgs>::from_json(json const &j) {return ::FlexFlow::SerializableOpTaskLaunchArgs{j.at("invocation_id").template get<::FlexFlow::dynamic_invocation_id_t>(), j.at("optimizer_attrs").template get<std::optional<::FlexFlow::OptimizerAttrs>>()};}}// namespace nlohmann

namespace FlexFlow{std::string SerializableOpTaskLaunchArgs::debug_to_string() const { return fmt::to_string(*this); }void SerializableOpTaskLaunchArgs::debug_print() const { std::cout << this->debug_to_string() << std::endl; }std::string format_as(SerializableOpTaskLaunchArgs const &x){::nlohmann::json j = x;
return j.dump();
}std::ostream &operator<<(std::ostream &s, SerializableOpTaskLaunchArgs const &x) {return s << fmt::to_string(x);}}// namespace FlexFlow
