// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/op-attrs/include/op-attrs/initializers/constant_initializer_attrs.dtg.toml
/* proj-data
{
  "generated_from": "13bdcbc38ec9b2c9434a8fa3697f8f00"
}
*/

#include "op-attrs/initializers/constant_initializer_attrs.dtg.h"

#include <sstream>

namespace FlexFlow{ConstantInitializerAttrs::ConstantInitializerAttrs(::FlexFlow::DataTypeValue const &value) : value(value){}
bool ConstantInitializerAttrs::operator==(ConstantInitializerAttrs const &other) const{
return std::tie(this->value) == std::tie(other.value);
}bool ConstantInitializerAttrs::operator!=(ConstantInitializerAttrs const &other) const{
return std::tie(this->value) != std::tie(other.value);
}bool ConstantInitializerAttrs::operator<(ConstantInitializerAttrs const &other) const{
return std::tie(this->value) < std::tie(other.value);
}bool ConstantInitializerAttrs::operator>(ConstantInitializerAttrs const &other) const{
return std::tie(this->value) > std::tie(other.value);
}bool ConstantInitializerAttrs::operator<=(ConstantInitializerAttrs const &other) const{
return std::tie(this->value) <= std::tie(other.value);
}bool ConstantInitializerAttrs::operator>=(ConstantInitializerAttrs const &other) const{
return std::tie(this->value) >= std::tie(other.value);
}}// namespace FlexFlow


///\cond
namespace std{size_t hash<FlexFlow::ConstantInitializerAttrs>::operator()(::FlexFlow::ConstantInitializerAttrs const &x)const{size_t result = 0;
result ^= std::hash<::FlexFlow::DataTypeValue>{}(x.value) + 0x9e3779b9 + (result << 6) + (result >> 2);return result;
}}// namespace std

///\endcond

namespace nlohmann{void adl_serializer<::FlexFlow::ConstantInitializerAttrs>::to_json(json &j, ::FlexFlow::ConstantInitializerAttrs const &v) {j["__type"] = "ConstantInitializerAttrs";
j["value"] = v.value;
}}// namespace nlohmann

namespace nlohmann{::FlexFlow::ConstantInitializerAttrs adl_serializer<::FlexFlow::ConstantInitializerAttrs>::from_json(json const &j) {return ::FlexFlow::ConstantInitializerAttrs{j.at("value").template get<::FlexFlow::DataTypeValue>()};}}// namespace nlohmann

namespace rc{Gen<::FlexFlow::ConstantInitializerAttrs> Arbitrary<::FlexFlow::ConstantInitializerAttrs>::arbitrary() {return gen::construct<::FlexFlow::ConstantInitializerAttrs>(gen::arbitrary<::FlexFlow::DataTypeValue>());}}// namespace rc

namespace FlexFlow{std::string ConstantInitializerAttrs::debug_to_string() const { return fmt::to_string(*this); }void ConstantInitializerAttrs::debug_print() const { std::cout << this->debug_to_string() << std::endl; }std::string format_as(ConstantInitializerAttrs const &x){::nlohmann::json j = x;
return j.dump();
}std::ostream &operator<<(std::ostream &s, ConstantInitializerAttrs const &x) {return s << fmt::to_string(x);}}// namespace FlexFlow
