// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/op-attrs/include/op-attrs/initializers/kaiming_initializer_mode.dtg.toml
/* proj-data
{
  "generated_from": "774a3ef1a4c0c4244699e5fa866dd85a"
}
*/

#include "op-attrs/initializers/kaiming_initializer_mode.dtg.h"

#include <stdexcept>
#include <sstream>


///\cond
namespace std{size_t hash<FlexFlow::KaimingInitializerMode>::operator()(FlexFlow::KaimingInitializerMode x) const{return std::hash<int>{}(static_cast<int>(x));
}}// namespace std

///\endcond
namespace FlexFlow{std::string format_as(KaimingInitializerMode x){::nlohmann::json j = x;
return j.dump();
}std::ostream &operator<<(std::ostream &s, KaimingInitializerMode x){return s << fmt::to_string(x);}}// namespace FlexFlow
namespace FlexFlow{void to_json(::nlohmann::json &j, KaimingInitializerMode x){switch (x){case KaimingInitializerMode::FAN_IN:
j = "FAN_IN";
break;
case KaimingInitializerMode::FAN_OUT:
j = "FAN_OUT";
break;
default:
std::ostringstream oss;
oss << "Unknown KaimingInitializerMode value " << static_cast<int>(x);
throw std::runtime_error(oss.str());
}}}// namespace FlexFlow
namespace FlexFlow{void from_json(::nlohmann::json const &j, KaimingInitializerMode &x){std::string as_str = j.get<std::string>();
if (as_str == "FAN_IN"){x = KaimingInitializerMode::FAN_IN;
}else if (as_str == "FAN_OUT"){x = KaimingInitializerMode::FAN_OUT;
}else {std::ostringstream oss;
oss << "Unknown KaimingInitializerMode value " << as_str;
throw std::runtime_error(oss.str());
}}}// namespace FlexFlow
namespace rc{Gen<FlexFlow::KaimingInitializerMode> Arbitrary<FlexFlow::KaimingInitializerMode>::arbitrary(){return gen::element<FlexFlow::KaimingInitializerMode>(FlexFlow::KaimingInitializerMode::FAN_IN, FlexFlow::KaimingInitializerMode::FAN_OUT);}}// namespace rc
