// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/models/include/models/yolov10/yolov10_layer_config_psa.dtg.toml
/* proj-data
{
  "generated_from": "7be1571c3a7f40b78f160495c984050f"
}
*/

#ifndef _FLEXFLOW_LIB_MODELS_INCLUDE_MODELS_YOLOV10_YOLOV10_LAYER_CONFIG_PSA_DTG_H
#define _FLEXFLOW_LIB_MODELS_INCLUDE_MODELS_YOLOV10_YOLOV10_LAYER_CONFIG_PSA_DTG_H

#include <tuple>
#include <iostream>
#include "models/yolov10/yolov10_tensor_idx_t.dtg.h"
#include <ostream>
#include <rapidcheck.h>
#include <fmt/format.h>
#include "utils/positive_int/positive_int.h"
#include <nlohmann/json.hpp>
#include <functional>


namespace FlexFlow{struct YOLOv10LayerConfigPSA{YOLOv10LayerConfigPSA() = delete;
explicit YOLOv10LayerConfigPSA(::FlexFlow::yolov10_tensor_idx_t const &input_tensor_idx, ::FlexFlow::positive_int const &num_output_channels);

bool operator==(YOLOv10LayerConfigPSA const &) const;bool operator!=(YOLOv10LayerConfigPSA const &) const;
bool operator<(YOLOv10LayerConfigPSA const &) const;bool operator>(YOLOv10LayerConfigPSA const &) const;bool operator<=(YOLOv10LayerConfigPSA const &) const;bool operator>=(YOLOv10LayerConfigPSA const &) const;
std::string debug_to_string() const;void debug_print() const;
::FlexFlow::yolov10_tensor_idx_t input_tensor_idx;
::FlexFlow::positive_int num_output_channels;
};}// namespace FlexFlow


///\cond
namespace std{template <>
struct hash<::FlexFlow::YOLOv10LayerConfigPSA>{size_t operator()(::FlexFlow::YOLOv10LayerConfigPSA const &)const;};}// namespace std

///\endcond

namespace nlohmann{template <>
struct adl_serializer<::FlexFlow::YOLOv10LayerConfigPSA>{static ::FlexFlow::YOLOv10LayerConfigPSA from_json(json const &);
static void to_json(json &, ::FlexFlow::YOLOv10LayerConfigPSA const &);
};}// namespace nlohmann

namespace rc{template <>
struct Arbitrary<::FlexFlow::YOLOv10LayerConfigPSA>{static Gen<::FlexFlow::YOLOv10LayerConfigPSA> arbitrary();
};}// namespace rc

namespace FlexFlow{std::string format_as(YOLOv10LayerConfigPSA const &);
std::ostream &operator<<(std::ostream &, YOLOv10LayerConfigPSA const &);}// namespace FlexFlow

#endif // _FLEXFLOW_LIB_MODELS_INCLUDE_MODELS_YOLOV10_YOLOV10_LAYER_CONFIG_PSA_DTG_H
