// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/models/include/models/yolov10/yolov10_layer_config.dtg.toml
/* proj-data
{
  "generated_from": "f749dd58ef3745fd28ea74050a06ed8f"
}
*/

#ifndef _FLEXFLOW_LIB_MODELS_INCLUDE_MODELS_YOLOV10_YOLOV10_LAYER_CONFIG_DTG_H
#define _FLEXFLOW_LIB_MODELS_INCLUDE_MODELS_YOLOV10_YOLOV10_LAYER_CONFIG_DTG_H

#include <cstddef>
#include <fmt/format.h>
#include <functional>
#include <iostream>
#include <libassert/assert.hpp>
#include "models/yolov10/yolov10_layer_config_c2f.dtg.h"
#include "models/yolov10/yolov10_layer_config_c2fcib.dtg.h"
#include "models/yolov10/yolov10_layer_config_concat.dtg.h"
#include "models/yolov10/yolov10_layer_config_conv.dtg.h"
#include "models/yolov10/yolov10_layer_config_psa.dtg.h"
#include "models/yolov10/yolov10_layer_config_scdown.dtg.h"
#include "models/yolov10/yolov10_layer_config_sppf.dtg.h"
#include "models/yolov10/yolov10_layer_config_upsample.dtg.h"
#include <nlohmann/json.hpp>
#include <optional>
#include <ostream>
#include <stdexcept>
#include <type_traits>
#include <variant>

namespace FlexFlow{struct YOLOv10LayerConfig{YOLOv10LayerConfig() = delete;
explicit YOLOv10LayerConfig(::FlexFlow::YOLOv10LayerConfigC2f const &);
explicit YOLOv10LayerConfig(::FlexFlow::YOLOv10LayerConfigC2fCIB const &);
explicit YOLOv10LayerConfig(::FlexFlow::YOLOv10LayerConfigConcat const &);
explicit YOLOv10LayerConfig(::FlexFlow::YOLOv10LayerConfigConv const &);
explicit YOLOv10LayerConfig(::FlexFlow::YOLOv10LayerConfigPSA const &);
explicit YOLOv10LayerConfig(::FlexFlow::YOLOv10LayerConfigSCDown const &);
explicit YOLOv10LayerConfig(::FlexFlow::YOLOv10LayerConfigSPPF const &);
explicit YOLOv10LayerConfig(::FlexFlow::YOLOv10LayerConfigUpsample const &);template <typename T>
static constexpr bool IsPartOfYOLOv10LayerConfig_v =std::is_same_v<T, ::FlexFlow::YOLOv10LayerConfigC2f> || std::is_same_v<T, ::FlexFlow::YOLOv10LayerConfigC2fCIB> || std::is_same_v<T, ::FlexFlow::YOLOv10LayerConfigConcat> || std::is_same_v<T, ::FlexFlow::YOLOv10LayerConfigConv> || std::is_same_v<T, ::FlexFlow::YOLOv10LayerConfigPSA> || std::is_same_v<T, ::FlexFlow::YOLOv10LayerConfigSCDown> || std::is_same_v<T, ::FlexFlow::YOLOv10LayerConfigSPPF> || std::is_same_v<T, ::FlexFlow::YOLOv10LayerConfigUpsample>;template <typename ReturnType, typename Visitor>
ReturnType visit(Visitor &&v) const{switch (this->index()){case 0: {ReturnType result = v(this->get<::FlexFlow::YOLOv10LayerConfigC2f>());
return result;
}case 1: {ReturnType result = v(this->get<::FlexFlow::YOLOv10LayerConfigC2fCIB>());
return result;
}case 2: {ReturnType result = v(this->get<::FlexFlow::YOLOv10LayerConfigConcat>());
return result;
}case 3: {ReturnType result = v(this->get<::FlexFlow::YOLOv10LayerConfigConv>());
return result;
}case 4: {ReturnType result = v(this->get<::FlexFlow::YOLOv10LayerConfigPSA>());
return result;
}case 5: {ReturnType result = v(this->get<::FlexFlow::YOLOv10LayerConfigSCDown>());
return result;
}case 6: {ReturnType result = v(this->get<::FlexFlow::YOLOv10LayerConfigSPPF>());
return result;
}case 7: {ReturnType result = v(this->get<::FlexFlow::YOLOv10LayerConfigUpsample>());
return result;
}default: {throw std::runtime_error(fmt::format("Unknown index {} for type YOLOv10LayerConfig", this->index()));
}}}
template <typename ReturnType, typename Visitor>
ReturnType visit(Visitor &&v){switch (this->index()){case 0: {ReturnType result = v(this->get<::FlexFlow::YOLOv10LayerConfigC2f>());
return result;
}case 1: {ReturnType result = v(this->get<::FlexFlow::YOLOv10LayerConfigC2fCIB>());
return result;
}case 2: {ReturnType result = v(this->get<::FlexFlow::YOLOv10LayerConfigConcat>());
return result;
}case 3: {ReturnType result = v(this->get<::FlexFlow::YOLOv10LayerConfigConv>());
return result;
}case 4: {ReturnType result = v(this->get<::FlexFlow::YOLOv10LayerConfigPSA>());
return result;
}case 5: {ReturnType result = v(this->get<::FlexFlow::YOLOv10LayerConfigSCDown>());
return result;
}case 6: {ReturnType result = v(this->get<::FlexFlow::YOLOv10LayerConfigSPPF>());
return result;
}case 7: {ReturnType result = v(this->get<::FlexFlow::YOLOv10LayerConfigUpsample>());
return result;
}default: {throw std::runtime_error(fmt::format("Unknown index {} for type YOLOv10LayerConfig", this->index()));
}}}
template <typename T>
bool has() const{static_assert(IsPartOfYOLOv10LayerConfig_v<T>, "YOLOv10LayerConfig::has() expected one of [::FlexFlow::YOLOv10LayerConfigC2f, ::FlexFlow::YOLOv10LayerConfigC2fCIB, ::FlexFlow::YOLOv10LayerConfigConcat, ::FlexFlow::YOLOv10LayerConfigConv, ::FlexFlow::YOLOv10LayerConfigPSA, ::FlexFlow::YOLOv10LayerConfigSCDown, ::FlexFlow::YOLOv10LayerConfigSPPF, ::FlexFlow::YOLOv10LayerConfigUpsample], received T");return std::holds_alternative<T>(this->raw_variant);}
template <typename T>
T const & get() const{static_assert(IsPartOfYOLOv10LayerConfig_v<T>, "YOLOv10LayerConfig::get() expected one of [::FlexFlow::YOLOv10LayerConfigC2f, ::FlexFlow::YOLOv10LayerConfigC2fCIB, ::FlexFlow::YOLOv10LayerConfigConcat, ::FlexFlow::YOLOv10LayerConfigConv, ::FlexFlow::YOLOv10LayerConfigPSA, ::FlexFlow::YOLOv10LayerConfigSCDown, ::FlexFlow::YOLOv10LayerConfigSPPF, ::FlexFlow::YOLOv10LayerConfigUpsample], received T");bool holds_expected = std::holds_alternative<T>(this->raw_variant);
ASSERT(holds_expected);
return std::get<T>(this->raw_variant);
}
template <typename T>
T  & get(){static_assert(IsPartOfYOLOv10LayerConfig_v<T>, "YOLOv10LayerConfig::get() expected one of [::FlexFlow::YOLOv10LayerConfigC2f, ::FlexFlow::YOLOv10LayerConfigC2fCIB, ::FlexFlow::YOLOv10LayerConfigConcat, ::FlexFlow::YOLOv10LayerConfigConv, ::FlexFlow::YOLOv10LayerConfigPSA, ::FlexFlow::YOLOv10LayerConfigSCDown, ::FlexFlow::YOLOv10LayerConfigSPPF, ::FlexFlow::YOLOv10LayerConfigUpsample], received T");bool holds_expected = std::holds_alternative<T>(this->raw_variant);
ASSERT(holds_expected);
return std::get<T>(this->raw_variant);
}
size_t index() const { return this->raw_variant.index(); }
bool operator==(YOLOv10LayerConfig const &) const;bool operator!=(YOLOv10LayerConfig const &) const;bool operator<(YOLOv10LayerConfig const &) const;bool operator>(YOLOv10LayerConfig const &) const;bool operator<=(YOLOv10LayerConfig const &) const;bool operator>=(YOLOv10LayerConfig const &) const;::FlexFlow::YOLOv10LayerConfigC2f const & require_c2f() const;
::FlexFlow::YOLOv10LayerConfigC2f & require_c2f();
::FlexFlow::YOLOv10LayerConfigC2fCIB const & require_c2fcib() const;
::FlexFlow::YOLOv10LayerConfigC2fCIB & require_c2fcib();
::FlexFlow::YOLOv10LayerConfigConcat const & require_concat() const;
::FlexFlow::YOLOv10LayerConfigConcat & require_concat();
::FlexFlow::YOLOv10LayerConfigConv const & require_conv() const;
::FlexFlow::YOLOv10LayerConfigConv & require_conv();
::FlexFlow::YOLOv10LayerConfigPSA const & require_psa() const;
::FlexFlow::YOLOv10LayerConfigPSA & require_psa();
::FlexFlow::YOLOv10LayerConfigSCDown const & require_scdown() const;
::FlexFlow::YOLOv10LayerConfigSCDown & require_scdown();
::FlexFlow::YOLOv10LayerConfigSPPF const & require_sppf() const;
::FlexFlow::YOLOv10LayerConfigSPPF & require_sppf();
::FlexFlow::YOLOv10LayerConfigUpsample const & require_upsample() const;
::FlexFlow::YOLOv10LayerConfigUpsample & require_upsample();
std::optional<::FlexFlow::YOLOv10LayerConfigC2f> try_require_c2f() const;
std::optional<::FlexFlow::YOLOv10LayerConfigC2fCIB> try_require_c2fcib() const;
std::optional<::FlexFlow::YOLOv10LayerConfigConcat> try_require_concat() const;
std::optional<::FlexFlow::YOLOv10LayerConfigConv> try_require_conv() const;
std::optional<::FlexFlow::YOLOv10LayerConfigPSA> try_require_psa() const;
std::optional<::FlexFlow::YOLOv10LayerConfigSCDown> try_require_scdown() const;
std::optional<::FlexFlow::YOLOv10LayerConfigSPPF> try_require_sppf() const;
std::optional<::FlexFlow::YOLOv10LayerConfigUpsample> try_require_upsample() const;
bool is_c2f() const;
bool is_c2fcib() const;
bool is_concat() const;
bool is_conv() const;
bool is_psa() const;
bool is_scdown() const;
bool is_sppf() const;
bool is_upsample() const;
std::string debug_to_string() const;void debug_print() const;std::variant<::FlexFlow::YOLOv10LayerConfigC2f, ::FlexFlow::YOLOv10LayerConfigC2fCIB, ::FlexFlow::YOLOv10LayerConfigConcat, ::FlexFlow::YOLOv10LayerConfigConv, ::FlexFlow::YOLOv10LayerConfigPSA, ::FlexFlow::YOLOv10LayerConfigSCDown, ::FlexFlow::YOLOv10LayerConfigSPPF, ::FlexFlow::YOLOv10LayerConfigUpsample> raw_variant;};}// namespace FlexFlow

///\cond
namespace std{template <>
struct hash<::FlexFlow::YOLOv10LayerConfig>{size_t operator()(::FlexFlow::YOLOv10LayerConfig const &) const;
};}// namespace std

///\endcond
namespace nlohmann{template <>
struct adl_serializer<::FlexFlow::YOLOv10LayerConfig>{static ::FlexFlow::YOLOv10LayerConfig from_json(json const &);
static void to_json(json &, ::FlexFlow::YOLOv10LayerConfig const &);
};}// namespace nlohmann
namespace FlexFlow{std::string format_as(::FlexFlow::YOLOv10LayerConfig const &);
std::ostream & operator<<(std::ostream &, ::FlexFlow::YOLOv10LayerConfig const &);
}// namespace FlexFlow

#endif // _FLEXFLOW_LIB_MODELS_INCLUDE_MODELS_YOLOV10_YOLOV10_LAYER_CONFIG_DTG_H
