// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/models/include/models/yolov10/yolov10_layer_config_c2fcib.dtg.toml
/* proj-data
{
  "generated_from": "3038ff923d6e86d385b44ab5f093e535"
}
*/

#ifndef _FLEXFLOW_LIB_MODELS_INCLUDE_MODELS_YOLOV10_YOLOV10_LAYER_CONFIG_C2FCIB_DTG_H
#define _FLEXFLOW_LIB_MODELS_INCLUDE_MODELS_YOLOV10_YOLOV10_LAYER_CONFIG_C2FCIB_DTG_H

#include <tuple>
#include <iostream>
#include "models/yolov10/yolov10_tensor_idx_t.dtg.h"
#include <ostream>
#include <rapidcheck.h>
#include <fmt/format.h>
#include "utils/positive_int/positive_int.h"
#include <nlohmann/json.hpp>
#include <functional>


namespace FlexFlow{struct YOLOv10LayerConfigC2fCIB{YOLOv10LayerConfigC2fCIB() = delete;
explicit YOLOv10LayerConfigC2fCIB(::FlexFlow::yolov10_tensor_idx_t const &input_tensor_idx, ::FlexFlow::positive_int const &num_output_channels, ::FlexFlow::positive_int const &num_cib_modules_to_stack, bool const &use_shortcut_connection, bool const &use_large_kernel);

bool operator==(YOLOv10LayerConfigC2fCIB const &) const;bool operator!=(YOLOv10LayerConfigC2fCIB const &) const;
bool operator<(YOLOv10LayerConfigC2fCIB const &) const;bool operator>(YOLOv10LayerConfigC2fCIB const &) const;bool operator<=(YOLOv10LayerConfigC2fCIB const &) const;bool operator>=(YOLOv10LayerConfigC2fCIB const &) const;
std::string debug_to_string() const;void debug_print() const;
::FlexFlow::yolov10_tensor_idx_t input_tensor_idx;
::FlexFlow::positive_int num_output_channels;
::FlexFlow::positive_int num_cib_modules_to_stack;
bool use_shortcut_connection;
bool use_large_kernel;
};}// namespace FlexFlow


///\cond
namespace std{template <>
struct hash<::FlexFlow::YOLOv10LayerConfigC2fCIB>{size_t operator()(::FlexFlow::YOLOv10LayerConfigC2fCIB const &)const;};}// namespace std

///\endcond

namespace nlohmann{template <>
struct adl_serializer<::FlexFlow::YOLOv10LayerConfigC2fCIB>{static ::FlexFlow::YOLOv10LayerConfigC2fCIB from_json(json const &);
static void to_json(json &, ::FlexFlow::YOLOv10LayerConfigC2fCIB const &);
};}// namespace nlohmann

namespace rc{template <>
struct Arbitrary<::FlexFlow::YOLOv10LayerConfigC2fCIB>{static Gen<::FlexFlow::YOLOv10LayerConfigC2fCIB> arbitrary();
};}// namespace rc

namespace FlexFlow{std::string format_as(YOLOv10LayerConfigC2fCIB const &);
std::ostream &operator<<(std::ostream &, YOLOv10LayerConfigC2fCIB const &);}// namespace FlexFlow

#endif // _FLEXFLOW_LIB_MODELS_INCLUDE_MODELS_YOLOV10_YOLOV10_LAYER_CONFIG_C2FCIB_DTG_H
