// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/compiler/include/compiler/machine_mapping/machine_mapping_problem_tree/mm_problem_tree_parallel_split.dtg.toml
/* proj-data
{
  "generated_from": "49de7bb804d6df56d660e8a85be9384b"
}
*/

#ifndef _FLEXFLOW_LIB_COMPILER_INCLUDE_COMPILER_MACHINE_MAPPING_MACHINE_MAPPING_PROBLEM_TREE_MM_PROBLEM_TREE_PARALLEL_SPLIT_DTG_H
#define _FLEXFLOW_LIB_COMPILER_INCLUDE_COMPILER_MACHINE_MAPPING_MACHINE_MAPPING_PROBLEM_TREE_MM_PROBLEM_TREE_PARALLEL_SPLIT_DTG_H

#include <tuple>
#include <iostream>
#include <ostream>
#include <fmt/format.h>
#include <memory>
#include <nlohmann/json.hpp>
#include <functional>

namespace FlexFlow{struct MachineMappingProblemTree;
}// namespace FlexFlow

namespace FlexFlow{struct MMProblemTreeParallelSplit{MMProblemTreeParallelSplit() = delete;
explicit MMProblemTreeParallelSplit(::FlexFlow::MachineMappingProblemTree const &left_child, ::FlexFlow::MachineMappingProblemTree const &right_child);

bool operator==(MMProblemTreeParallelSplit const &) const;bool operator!=(MMProblemTreeParallelSplit const &) const;
bool operator<(MMProblemTreeParallelSplit const &) const;bool operator>(MMProblemTreeParallelSplit const &) const;bool operator<=(MMProblemTreeParallelSplit const &) const;bool operator>=(MMProblemTreeParallelSplit const &) const;
std::string debug_to_string() const;void debug_print() const;
private:
std::shared_ptr<::FlexFlow::MachineMappingProblemTree> left_child_ptr;
public:
::FlexFlow::MachineMappingProblemTree const &get_left_child() const;
private:
std::shared_ptr<::FlexFlow::MachineMappingProblemTree> right_child_ptr;
public:
::FlexFlow::MachineMappingProblemTree const &get_right_child() const;
};}// namespace FlexFlow


///\cond
namespace std{template <>
struct hash<::FlexFlow::MMProblemTreeParallelSplit>{size_t operator()(::FlexFlow::MMProblemTreeParallelSplit const &)const;};}// namespace std

///\endcond

namespace nlohmann{template <>
struct adl_serializer<::FlexFlow::MMProblemTreeParallelSplit>{static ::FlexFlow::MMProblemTreeParallelSplit from_json(json const &);
static void to_json(json &, ::FlexFlow::MMProblemTreeParallelSplit const &);
};}// namespace nlohmann

namespace FlexFlow{std::string format_as(MMProblemTreeParallelSplit const &);
std::ostream &operator<<(std::ostream &, MMProblemTreeParallelSplit const &);}// namespace FlexFlow
#include "compiler/machine_mapping/machine_mapping_problem_tree/machine_mapping_problem_tree.dtg.h"

#endif // _FLEXFLOW_LIB_COMPILER_INCLUDE_COMPILER_MACHINE_MAPPING_MACHINE_MAPPING_PROBLEM_TREE_MM_PROBLEM_TREE_PARALLEL_SPLIT_DTG_H
