// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/compiler/include/compiler/machine_mapping/machine_mapping_problem_tree/unmapped_op_cost_estimate_key.dtg.toml
/* proj-data
{
  "generated_from": "46f26a118557267d57856ab16dc297e7"
}
*/

#ifndef _FLEXFLOW_LIB_COMPILER_INCLUDE_COMPILER_MACHINE_MAPPING_MACHINE_MAPPING_PROBLEM_TREE_UNMAPPED_OP_COST_ESTIMATE_KEY_DTG_H
#define _FLEXFLOW_LIB_COMPILER_INCLUDE_COMPILER_MACHINE_MAPPING_MACHINE_MAPPING_PROBLEM_TREE_UNMAPPED_OP_COST_ESTIMATE_KEY_DTG_H

#include <tuple>
#include <iostream>
#include "pcg/optimizer_attrs.dtg.h"
#include "op-attrs/pcg_operator_attrs.dtg.h"
#include <map>
#include <ostream>
#include <fmt/format.h>
#include "op-attrs/tensor_slot_name.dtg.h"
#include <nlohmann/json.hpp>
#include <functional>
#include "op-attrs/parallel_tensor_shape.dtg.h"


namespace FlexFlow{struct UnmappedOpCostEstimateKey{UnmappedOpCostEstimateKey() = delete;
explicit UnmappedOpCostEstimateKey(::FlexFlow::PCGOperatorAttrs const &op_attrs, std::map<::FlexFlow::TensorSlotName, ::FlexFlow::ParallelTensorShape> const &input_shapes, std::map<::FlexFlow::TensorSlotName, ::FlexFlow::ParallelTensorShape> const &weight_shapes, std::map<::FlexFlow::TensorSlotName, ::FlexFlow::ParallelTensorShape> const &output_shapes, ::FlexFlow::OptimizerAttrs const &optimizer_attrs);

bool operator==(UnmappedOpCostEstimateKey const &) const;bool operator!=(UnmappedOpCostEstimateKey const &) const;
std::string debug_to_string() const;void debug_print() const;
::FlexFlow::PCGOperatorAttrs op_attrs;
std::map<::FlexFlow::TensorSlotName, ::FlexFlow::ParallelTensorShape> input_shapes;
std::map<::FlexFlow::TensorSlotName, ::FlexFlow::ParallelTensorShape> weight_shapes;
std::map<::FlexFlow::TensorSlotName, ::FlexFlow::ParallelTensorShape> output_shapes;
::FlexFlow::OptimizerAttrs optimizer_attrs;
};}// namespace FlexFlow


///\cond
namespace std{template <>
struct hash<::FlexFlow::UnmappedOpCostEstimateKey>{size_t operator()(::FlexFlow::UnmappedOpCostEstimateKey const &)const;};}// namespace std

///\endcond

namespace nlohmann{template <>
struct adl_serializer<::FlexFlow::UnmappedOpCostEstimateKey>{static void to_json(json &, ::FlexFlow::UnmappedOpCostEstimateKey const &);
};}// namespace nlohmann

namespace FlexFlow{std::string format_as(UnmappedOpCostEstimateKey const &);
std::ostream &operator<<(std::ostream &, UnmappedOpCostEstimateKey const &);}// namespace FlexFlow

#endif // _FLEXFLOW_LIB_COMPILER_INCLUDE_COMPILER_MACHINE_MAPPING_MACHINE_MAPPING_PROBLEM_TREE_UNMAPPED_OP_COST_ESTIMATE_KEY_DTG_H
