// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/compiler/include/compiler/machine_mapping/pcg_split_boundary_layers.dtg.toml
/* proj-data
{
  "generated_from": "7098103ebdc596ffc5e06b4e0438a5fd"
}
*/

#ifndef _FLEXFLOW_LIB_COMPILER_INCLUDE_COMPILER_MACHINE_MAPPING_PCG_SPLIT_BOUNDARY_LAYERS_DTG_H
#define _FLEXFLOW_LIB_COMPILER_INCLUDE_COMPILER_MACHINE_MAPPING_PCG_SPLIT_BOUNDARY_LAYERS_DTG_H

#include <tuple>
#include <iostream>
#include <set>
#include <ostream>
#include "pcg/parallel_computation_graph/parallel_layer_guid_t.dtg.h"
#include <fmt/format.h>
#include <nlohmann/json.hpp>
#include <functional>


namespace FlexFlow{struct PCGSplitBoundaryLayers{PCGSplitBoundaryLayers() = delete;
explicit PCGSplitBoundaryLayers(std::set<::FlexFlow::parallel_layer_guid_t> const &pre_split_boundary, std::set<::FlexFlow::parallel_layer_guid_t> const &post_split_boundary);

bool operator==(PCGSplitBoundaryLayers const &) const;bool operator!=(PCGSplitBoundaryLayers const &) const;
std::string debug_to_string() const;void debug_print() const;
std::set<::FlexFlow::parallel_layer_guid_t> pre_split_boundary;
std::set<::FlexFlow::parallel_layer_guid_t> post_split_boundary;
};}// namespace FlexFlow


///\cond
namespace std{template <>
struct hash<::FlexFlow::PCGSplitBoundaryLayers>{size_t operator()(::FlexFlow::PCGSplitBoundaryLayers const &)const;};}// namespace std

///\endcond

namespace nlohmann{template <>
struct adl_serializer<::FlexFlow::PCGSplitBoundaryLayers>{static void to_json(json &, ::FlexFlow::PCGSplitBoundaryLayers const &);
};}// namespace nlohmann

namespace FlexFlow{std::string format_as(PCGSplitBoundaryLayers const &);
std::ostream &operator<<(std::ostream &, PCGSplitBoundaryLayers const &);}// namespace FlexFlow

#endif // _FLEXFLOW_LIB_COMPILER_INCLUDE_COMPILER_MACHINE_MAPPING_PCG_SPLIT_BOUNDARY_LAYERS_DTG_H
