// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/utils/include/utils/dot/dot_html_table_row.dtg.toml
/* proj-data
{
  "generated_from": "ffadc7c07024379957da5e2535ca8258"
}
*/

#include "utils/dot/dot_html_table_row.dtg.h"

#include "utils/fmt/vector.h"
#include "utils/hash/vector.h"
#include <sstream>
#include "utils/ord/vector.h"

namespace FlexFlow{DotHtmlTableRow::DotHtmlTableRow(std::vector<::FlexFlow::DotHtmlTableCell> const &cells) : cells(cells){}
bool DotHtmlTableRow::operator==(DotHtmlTableRow const &other) const{
return std::tie(this->cells) == std::tie(other.cells);
}bool DotHtmlTableRow::operator!=(DotHtmlTableRow const &other) const{
return std::tie(this->cells) != std::tie(other.cells);
}}// namespace FlexFlow

namespace nlohmann{void adl_serializer<::FlexFlow::DotHtmlTableRow>::to_json(json &j, ::FlexFlow::DotHtmlTableRow const &v) {j["__type"] = "DotHtmlTableRow";
j["cells"] = v.cells;
}}// namespace nlohmann

namespace FlexFlow{std::string DotHtmlTableRow::debug_to_string() const { return fmt::to_string(*this); }void DotHtmlTableRow::debug_print() const { std::cout << this->debug_to_string() << std::endl; }std::string format_as(DotHtmlTableRow const &x){::nlohmann::json j = x;
return j.dump();
}std::ostream &operator<<(std::ostream &s, DotHtmlTableRow const &x) {return s << fmt::to_string(x);}}// namespace FlexFlow
