// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/utils/include/utils/dot/dot_html_table.dtg.toml
/* proj-data
{
  "generated_from": "29b050eb1d70d14453a905c7f7afc993"
}
*/

#include "utils/dot/dot_html_table.dtg.h"

#include "utils/fmt/vector.h"
#include "utils/hash/vector.h"
#include <sstream>
#include "utils/ord/vector.h"

namespace FlexFlow{DotHtmlTable::DotHtmlTable(::FlexFlow::nonnegative_int const &border, ::FlexFlow::nonnegative_int const &cellborder, ::FlexFlow::nonnegative_int const &cellspacing, std::vector<::FlexFlow::DotHtmlTableRow> const &rows) : border(border), cellborder(cellborder), cellspacing(cellspacing), rows(rows){}
bool DotHtmlTable::operator==(DotHtmlTable const &other) const{
return std::tie(this->border, this->cellborder, this->cellspacing, this->rows) == std::tie(other.border, other.cellborder, other.cellspacing, other.rows);
}bool DotHtmlTable::operator!=(DotHtmlTable const &other) const{
return std::tie(this->border, this->cellborder, this->cellspacing, this->rows) != std::tie(other.border, other.cellborder, other.cellspacing, other.rows);
}}// namespace FlexFlow

namespace nlohmann{void adl_serializer<::FlexFlow::DotHtmlTable>::to_json(json &j, ::FlexFlow::DotHtmlTable const &v) {j["__type"] = "DotHtmlTable";
j["border"] = v.border;
j["cellborder"] = v.cellborder;
j["cellspacing"] = v.cellspacing;
j["rows"] = v.rows;
}}// namespace nlohmann

namespace FlexFlow{std::string DotHtmlTable::debug_to_string() const { return fmt::to_string(*this); }void DotHtmlTable::debug_print() const { std::cout << this->debug_to_string() << std::endl; }std::string format_as(DotHtmlTable const &x){::nlohmann::json j = x;
return j.dump();
}std::ostream &operator<<(std::ostream &s, DotHtmlTable const &x) {return s << fmt::to_string(x);}}// namespace FlexFlow
