// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/task-spec/include/task-spec/ops/op_tensor_slot_spec.dtg.toml
/* proj-data
{
  "generated_from": "6e34d2d10204eb57efc51f2b796b646e"
}
*/

#ifndef _FLEXFLOW_LIB_TASK_SPEC_INCLUDE_TASK_SPEC_OPS_OP_TENSOR_SLOT_SPEC_DTG_H
#define _FLEXFLOW_LIB_TASK_SPEC_INCLUDE_TASK_SPEC_OPS_OP_TENSOR_SLOT_SPEC_DTG_H

#include <tuple>
#include "op-attrs/tensor_role.dtg.h"
#include "task-spec/ops/op_slot_options.dtg.h"
#include <iostream>
#include "task-spec/is_grad.dtg.h"
#include <ostream>
#include <fmt/format.h>
#include "op-attrs/tensor_slot_name.dtg.h"
#include <nlohmann/json.hpp>
#include <functional>


namespace FlexFlow{struct OpTensorSlotSpec{OpTensorSlotSpec() = delete;
explicit OpTensorSlotSpec(::FlexFlow::TensorSlotName const &name, ::FlexFlow::TensorRole const &tensor_role, ::FlexFlow::IsGrad const &is_grad, ::FlexFlow::OpSlotOptions const &slot_option);

bool operator==(OpTensorSlotSpec const &) const;bool operator!=(OpTensorSlotSpec const &) const;
bool operator<(OpTensorSlotSpec const &) const;bool operator>(OpTensorSlotSpec const &) const;bool operator<=(OpTensorSlotSpec const &) const;bool operator>=(OpTensorSlotSpec const &) const;
std::string debug_to_string() const;void debug_print() const;
::FlexFlow::TensorSlotName name;
::FlexFlow::TensorRole tensor_role;
::FlexFlow::IsGrad is_grad;
::FlexFlow::OpSlotOptions slot_option;
};}// namespace FlexFlow


///\cond
namespace std{template <>
struct hash<::FlexFlow::OpTensorSlotSpec>{size_t operator()(::FlexFlow::OpTensorSlotSpec const &)const;};}// namespace std

///\endcond

namespace nlohmann{template <>
struct adl_serializer<::FlexFlow::OpTensorSlotSpec>{static void to_json(json &, ::FlexFlow::OpTensorSlotSpec const &);
};}// namespace nlohmann

namespace FlexFlow{std::string format_as(OpTensorSlotSpec const &);
std::ostream &operator<<(std::ostream &, OpTensorSlotSpec const &);}// namespace FlexFlow

#endif // _FLEXFLOW_LIB_TASK_SPEC_INCLUDE_TASK_SPEC_OPS_OP_TENSOR_SLOT_SPEC_DTG_H
