// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/task-spec/include/task-spec/ops/op_task_type.dtg.toml
/* proj-data
{
  "generated_from": "53e446255ac2e21cb8f390eda8607dd2"
}
*/

#ifndef _FLEXFLOW_LIB_TASK_SPEC_INCLUDE_TASK_SPEC_OPS_OP_TASK_TYPE_DTG_H
#define _FLEXFLOW_LIB_TASK_SPEC_INCLUDE_TASK_SPEC_OPS_OP_TASK_TYPE_DTG_H

#include <string>
#include <ostream>
#include <fmt/format.h>
#include <nlohmann/json.hpp>
#include <functional>
#include <rapidcheck.h>

namespace FlexFlow{enum class OpTaskType{INIT, FWD, BWD};std::string format_as(OpTaskType);
std::ostream &operator<<(std::ostream &, OpTaskType);
void to_json(::nlohmann::json &, OpTaskType);
void from_json(::nlohmann::json const &, OpTaskType &);
}// namespace FlexFlow

///\cond
namespace std{template <>
struct hash<FlexFlow::OpTaskType> {size_t operator()(FlexFlow::OpTaskType) const;
};}// namespace std

///\endcond
namespace rc{template <>
struct Arbitrary<FlexFlow::OpTaskType> {static Gen<FlexFlow::OpTaskType> arbitrary();
};}// namespace rc

#endif // _FLEXFLOW_LIB_TASK_SPEC_INCLUDE_TASK_SPEC_OPS_OP_TASK_TYPE_DTG_H
