// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/utils/include/utils/full_binary_tree/binary_tree_path.dtg.toml
/* proj-data
{
  "generated_from": "a88e643ab2cfa02b9a618823d015cc9c"
}
*/

#include "utils/full_binary_tree/binary_tree_path.dtg.h"

#include "utils/fmt/vector.h"
#include "utils/hash/vector.h"
#include <sstream>

namespace FlexFlow{BinaryTreePath::BinaryTreePath(std::vector<::FlexFlow::BinaryTreePathEntry> const &entries) : entries(entries){}
bool BinaryTreePath::operator==(BinaryTreePath const &other) const{
return std::tie(this->entries) == std::tie(other.entries);
}bool BinaryTreePath::operator!=(BinaryTreePath const &other) const{
return std::tie(this->entries) != std::tie(other.entries);
}bool BinaryTreePath::operator<(BinaryTreePath const &other) const{
return std::tie(this->entries) < std::tie(other.entries);
}bool BinaryTreePath::operator>(BinaryTreePath const &other) const{
return std::tie(this->entries) > std::tie(other.entries);
}bool BinaryTreePath::operator<=(BinaryTreePath const &other) const{
return std::tie(this->entries) <= std::tie(other.entries);
}bool BinaryTreePath::operator>=(BinaryTreePath const &other) const{
return std::tie(this->entries) >= std::tie(other.entries);
}}// namespace FlexFlow


///\cond
namespace std{size_t hash<FlexFlow::BinaryTreePath>::operator()(::FlexFlow::BinaryTreePath const &x)const{size_t result = 0;
result ^= std::hash<std::vector<::FlexFlow::BinaryTreePathEntry>>{}(x.entries) + 0x9e3779b9 + (result << 6) + (result >> 2);return result;
}}// namespace std

///\endcond

namespace nlohmann{void adl_serializer<::FlexFlow::BinaryTreePath>::to_json(json &j, ::FlexFlow::BinaryTreePath const &v) {j["__type"] = "BinaryTreePath";
j["entries"] = v.entries;
}}// namespace nlohmann

namespace nlohmann{::FlexFlow::BinaryTreePath adl_serializer<::FlexFlow::BinaryTreePath>::from_json(json const &j) {return ::FlexFlow::BinaryTreePath{j.at("entries").template get<std::vector<::FlexFlow::BinaryTreePathEntry>>()};}}// namespace nlohmann

namespace rc{Gen<::FlexFlow::BinaryTreePath> Arbitrary<::FlexFlow::BinaryTreePath>::arbitrary() {return gen::construct<::FlexFlow::BinaryTreePath>(gen::arbitrary<std::vector<::FlexFlow::BinaryTreePathEntry>>());}}// namespace rc

namespace FlexFlow{std::string BinaryTreePath::debug_to_string() const { return fmt::to_string(*this); }void BinaryTreePath::debug_print() const { std::cout << this->debug_to_string() << std::endl; }std::string format_as(BinaryTreePath const &x){::nlohmann::json j = x;
return j.dump();
}std::ostream &operator<<(std::ostream &s, BinaryTreePath const &x) {return s << fmt::to_string(x);}}// namespace FlexFlow
