// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/utils/include/utils/full_binary_tree/full_binary_tree_visitor.dtg.toml
/* proj-data
{
  "generated_from": "1a4283e88554e449e6909d9ca6ef0fb3"
}
*/

#include "utils/full_binary_tree/full_binary_tree_visitor.dtg.h"

