// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/utils/include/utils/graph/multidigraph/multidiedge_query.dtg.toml
/* proj-data
{
  "generated_from": "7dc988d32f11b0b34e36e53abf85b5e8"
}
*/

#include "utils/graph/multidigraph/multidiedge_query.dtg.h"

#include <sstream>

namespace FlexFlow{MultiDiEdgeQuery::MultiDiEdgeQuery(::FlexFlow::query_set<::FlexFlow::Node> const &srcs, ::FlexFlow::query_set<::FlexFlow::Node> const &dsts) : srcs(srcs), dsts(dsts){}
bool MultiDiEdgeQuery::operator==(MultiDiEdgeQuery const &other) const{
return std::tie(this->srcs, this->dsts) == std::tie(other.srcs, other.dsts);
}bool MultiDiEdgeQuery::operator!=(MultiDiEdgeQuery const &other) const{
return std::tie(this->srcs, this->dsts) != std::tie(other.srcs, other.dsts);
}bool MultiDiEdgeQuery::operator<(MultiDiEdgeQuery const &other) const{
return std::tie(this->srcs, this->dsts) < std::tie(other.srcs, other.dsts);
}bool MultiDiEdgeQuery::operator>(MultiDiEdgeQuery const &other) const{
return std::tie(this->srcs, this->dsts) > std::tie(other.srcs, other.dsts);
}bool MultiDiEdgeQuery::operator<=(MultiDiEdgeQuery const &other) const{
return std::tie(this->srcs, this->dsts) <= std::tie(other.srcs, other.dsts);
}bool MultiDiEdgeQuery::operator>=(MultiDiEdgeQuery const &other) const{
return std::tie(this->srcs, this->dsts) >= std::tie(other.srcs, other.dsts);
}}// namespace FlexFlow


///\cond
namespace std{size_t hash<FlexFlow::MultiDiEdgeQuery>::operator()(::FlexFlow::MultiDiEdgeQuery const &x)const{size_t result = 0;
result ^= std::hash<::FlexFlow::query_set<::FlexFlow::Node>>{}(x.srcs) + 0x9e3779b9 + (result << 6) + (result >> 2);result ^= std::hash<::FlexFlow::query_set<::FlexFlow::Node>>{}(x.dsts) + 0x9e3779b9 + (result << 6) + (result >> 2);return result;
}}// namespace std

///\endcond

namespace nlohmann{void adl_serializer<::FlexFlow::MultiDiEdgeQuery>::to_json(json &j, ::FlexFlow::MultiDiEdgeQuery const &v) {j["__type"] = "MultiDiEdgeQuery";
j["srcs"] = v.srcs;
j["dsts"] = v.dsts;
}}// namespace nlohmann

namespace FlexFlow{std::string MultiDiEdgeQuery::debug_to_string() const { return fmt::to_string(*this); }void MultiDiEdgeQuery::debug_print() const { std::cout << this->debug_to_string() << std::endl; }std::string format_as(MultiDiEdgeQuery const &x){::nlohmann::json j = x;
return j.dump();
}std::ostream &operator<<(std::ostream &s, MultiDiEdgeQuery const &x) {return s << fmt::to_string(x);}}// namespace FlexFlow
