// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/utils/include/utils/graph/undirected/undirected_edge_query.dtg.toml
/* proj-data
{
  "generated_from": "74c18fa975cfe8d2a6020aa04d202f86"
}
*/

#include "utils/graph/undirected/undirected_edge_query.dtg.h"

#include <sstream>

namespace FlexFlow{UndirectedEdgeQuery::UndirectedEdgeQuery(::FlexFlow::query_set<::FlexFlow::Node> const &nodes) : nodes(nodes){}
bool UndirectedEdgeQuery::operator==(UndirectedEdgeQuery const &other) const{
return std::tie(this->nodes) == std::tie(other.nodes);
}bool UndirectedEdgeQuery::operator!=(UndirectedEdgeQuery const &other) const{
return std::tie(this->nodes) != std::tie(other.nodes);
}bool UndirectedEdgeQuery::operator<(UndirectedEdgeQuery const &other) const{
return std::tie(this->nodes) < std::tie(other.nodes);
}bool UndirectedEdgeQuery::operator>(UndirectedEdgeQuery const &other) const{
return std::tie(this->nodes) > std::tie(other.nodes);
}bool UndirectedEdgeQuery::operator<=(UndirectedEdgeQuery const &other) const{
return std::tie(this->nodes) <= std::tie(other.nodes);
}bool UndirectedEdgeQuery::operator>=(UndirectedEdgeQuery const &other) const{
return std::tie(this->nodes) >= std::tie(other.nodes);
}}// namespace FlexFlow


///\cond
namespace std{size_t hash<FlexFlow::UndirectedEdgeQuery>::operator()(::FlexFlow::UndirectedEdgeQuery const &x)const{size_t result = 0;
result ^= std::hash<::FlexFlow::query_set<::FlexFlow::Node>>{}(x.nodes) + 0x9e3779b9 + (result << 6) + (result >> 2);return result;
}}// namespace std

///\endcond

namespace nlohmann{void adl_serializer<::FlexFlow::UndirectedEdgeQuery>::to_json(json &j, ::FlexFlow::UndirectedEdgeQuery const &v) {j["__type"] = "UndirectedEdgeQuery";
j["nodes"] = v.nodes;
}}// namespace nlohmann

namespace FlexFlow{std::string UndirectedEdgeQuery::debug_to_string() const { return fmt::to_string(*this); }void UndirectedEdgeQuery::debug_print() const { std::cout << this->debug_to_string() << std::endl; }std::string format_as(UndirectedEdgeQuery const &x){::nlohmann::json j = x;
return j.dump();
}std::ostream &operator<<(std::ostream &s, UndirectedEdgeQuery const &x) {return s << fmt::to_string(x);}}// namespace FlexFlow
