// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/op-attrs/include/op-attrs/initializers/kaiming_initializer_mode.dtg.toml
/* proj-data
{
  "generated_from": "774a3ef1a4c0c4244699e5fa866dd85a"
}
*/

#ifndef _FLEXFLOW_LIB_OP_ATTRS_INCLUDE_OP_ATTRS_INITIALIZERS_KAIMING_INITIALIZER_MODE_DTG_H
#define _FLEXFLOW_LIB_OP_ATTRS_INCLUDE_OP_ATTRS_INITIALIZERS_KAIMING_INITIALIZER_MODE_DTG_H

#include <string>
#include <ostream>
#include <fmt/format.h>
#include <nlohmann/json.hpp>
#include <functional>
#include <rapidcheck.h>

namespace FlexFlow{enum class KaimingInitializerMode{FAN_IN, FAN_OUT};std::string format_as(KaimingInitializerMode);
std::ostream &operator<<(std::ostream &, KaimingInitializerMode);
void to_json(::nlohmann::json &, KaimingInitializerMode);
void from_json(::nlohmann::json const &, KaimingInitializerMode &);
}// namespace FlexFlow

///\cond
namespace std{template <>
struct hash<FlexFlow::KaimingInitializerMode> {size_t operator()(FlexFlow::KaimingInitializerMode) const;
};}// namespace std

///\endcond
namespace rc{template <>
struct Arbitrary<FlexFlow::KaimingInitializerMode> {static Gen<FlexFlow::KaimingInitializerMode> arbitrary();
};}// namespace rc

#endif // _FLEXFLOW_LIB_OP_ATTRS_INCLUDE_OP_ATTRS_INITIALIZERS_KAIMING_INITIALIZER_MODE_DTG_H
