// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/op-attrs/include/op-attrs/initializers/truncated_normal_initializer_attrs.dtg.toml
/* proj-data
{
  "generated_from": "93127df700dd1787a6d254e99a867e8b"
}
*/

#ifndef _FLEXFLOW_LIB_OP_ATTRS_INCLUDE_OP_ATTRS_INITIALIZERS_TRUNCATED_NORMAL_INITIALIZER_ATTRS_DTG_H
#define _FLEXFLOW_LIB_OP_ATTRS_INCLUDE_OP_ATTRS_INITIALIZERS_TRUNCATED_NORMAL_INITIALIZER_ATTRS_DTG_H

#include <tuple>
#include <iostream>
#include <ostream>
#include <rapidcheck.h>
#include <fmt/format.h>
#include <nlohmann/json.hpp>
#include <functional>


namespace FlexFlow{struct TruncatedNormalInitializerAttrs{TruncatedNormalInitializerAttrs() = delete;
explicit TruncatedNormalInitializerAttrs(int const &seed, float const &mean, float const &stddev, float const &min_cutoff, float const &max_cutoff);

bool operator==(TruncatedNormalInitializerAttrs const &) const;bool operator!=(TruncatedNormalInitializerAttrs const &) const;
bool operator<(TruncatedNormalInitializerAttrs const &) const;bool operator>(TruncatedNormalInitializerAttrs const &) const;bool operator<=(TruncatedNormalInitializerAttrs const &) const;bool operator>=(TruncatedNormalInitializerAttrs const &) const;
std::string debug_to_string() const;void debug_print() const;
int seed;
float mean;
float stddev;
float min_cutoff;
float max_cutoff;
};}// namespace FlexFlow


///\cond
namespace std{template <>
struct hash<::FlexFlow::TruncatedNormalInitializerAttrs>{size_t operator()(::FlexFlow::TruncatedNormalInitializerAttrs const &)const;};}// namespace std

///\endcond

namespace nlohmann{template <>
struct adl_serializer<::FlexFlow::TruncatedNormalInitializerAttrs>{static ::FlexFlow::TruncatedNormalInitializerAttrs from_json(json const &);
static void to_json(json &, ::FlexFlow::TruncatedNormalInitializerAttrs const &);
};}// namespace nlohmann

namespace rc{template <>
struct Arbitrary<::FlexFlow::TruncatedNormalInitializerAttrs>{static Gen<::FlexFlow::TruncatedNormalInitializerAttrs> arbitrary();
};}// namespace rc

namespace FlexFlow{std::string format_as(TruncatedNormalInitializerAttrs const &);
std::ostream &operator<<(std::ostream &, TruncatedNormalInitializerAttrs const &);}// namespace FlexFlow

#endif // _FLEXFLOW_LIB_OP_ATTRS_INCLUDE_OP_ATTRS_INITIALIZERS_TRUNCATED_NORMAL_INITIALIZER_ATTRS_DTG_H
