// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/op-attrs/include/op-attrs/activation.dtg.toml
/* proj-data
{
  "generated_from": "ac590c0d441e8b26f5111a199054d33e"
}
*/

#ifndef _FLEXFLOW_LIB_OP_ATTRS_INCLUDE_OP_ATTRS_ACTIVATION_DTG_H
#define _FLEXFLOW_LIB_OP_ATTRS_INCLUDE_OP_ATTRS_ACTIVATION_DTG_H

#include <string>
#include <ostream>
#include <fmt/format.h>
#include <nlohmann/json.hpp>
#include <functional>
#include <rapidcheck.h>

namespace FlexFlow{enum class Activation{RELU, SIGMOID, TANH, GELU, SILU};std::string format_as(Activation);
std::ostream &operator<<(std::ostream &, Activation);
void to_json(::nlohmann::json &, Activation);
void from_json(::nlohmann::json const &, Activation &);
}// namespace FlexFlow

///\cond
namespace std{template <>
struct hash<FlexFlow::Activation> {size_t operator()(FlexFlow::Activation) const;
};}// namespace std

///\endcond
namespace rc{template <>
struct Arbitrary<FlexFlow::Activation> {static Gen<FlexFlow::Activation> arbitrary();
};}// namespace rc

#endif // _FLEXFLOW_LIB_OP_ATTRS_INCLUDE_OP_ATTRS_ACTIVATION_DTG_H
