// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/op-attrs/include/op-attrs/datatype_value.dtg.toml
/* proj-data
{
  "generated_from": "fed0ce57fb97baeddc0d562a129aec57"
}
*/

#ifndef _FLEXFLOW_LIB_OP_ATTRS_INCLUDE_OP_ATTRS_DATATYPE_VALUE_DTG_H
#define _FLEXFLOW_LIB_OP_ATTRS_INCLUDE_OP_ATTRS_DATATYPE_VALUE_DTG_H

#include <cstddef>
#include <fmt/format.h>
#include <functional>
#include <iostream>
#include <libassert/assert.hpp>
#include <nlohmann/json.hpp>
#include <optional>
#include <ostream>
#include <rapidcheck.h>
#include <stdexcept>
#include <type_traits>
#include "utils/half.h"
#include <variant>

namespace FlexFlow{struct DataTypeValue{DataTypeValue() = delete;
explicit DataTypeValue(half const &);
explicit DataTypeValue(float const &);
explicit DataTypeValue(double const &);
explicit DataTypeValue(int32_t const &);
explicit DataTypeValue(int64_t const &);
explicit DataTypeValue(bool const &);template <typename T>
static constexpr bool IsPartOfDataTypeValue_v =std::is_same_v<T, half> || std::is_same_v<T, float> || std::is_same_v<T, double> || std::is_same_v<T, int32_t> || std::is_same_v<T, int64_t> || std::is_same_v<T, bool>;template <typename ReturnType, typename Visitor>
ReturnType visit(Visitor &&v) const{switch (this->index()){case 0: {ReturnType result = v(this->get<half>());
return result;
}case 1: {ReturnType result = v(this->get<float>());
return result;
}case 2: {ReturnType result = v(this->get<double>());
return result;
}case 3: {ReturnType result = v(this->get<int32_t>());
return result;
}case 4: {ReturnType result = v(this->get<int64_t>());
return result;
}case 5: {ReturnType result = v(this->get<bool>());
return result;
}default: {throw std::runtime_error(fmt::format("Unknown index {} for type DataTypeValue", this->index()));
}}}
template <typename ReturnType, typename Visitor>
ReturnType visit(Visitor &&v){switch (this->index()){case 0: {ReturnType result = v(this->get<half>());
return result;
}case 1: {ReturnType result = v(this->get<float>());
return result;
}case 2: {ReturnType result = v(this->get<double>());
return result;
}case 3: {ReturnType result = v(this->get<int32_t>());
return result;
}case 4: {ReturnType result = v(this->get<int64_t>());
return result;
}case 5: {ReturnType result = v(this->get<bool>());
return result;
}default: {throw std::runtime_error(fmt::format("Unknown index {} for type DataTypeValue", this->index()));
}}}
template <typename T>
bool has() const{static_assert(IsPartOfDataTypeValue_v<T>, "DataTypeValue::has() expected one of [half, float, double, int32_t, int64_t, bool], received T");return std::holds_alternative<T>(this->raw_variant);}
template <typename T>
T const & get() const{static_assert(IsPartOfDataTypeValue_v<T>, "DataTypeValue::get() expected one of [half, float, double, int32_t, int64_t, bool], received T");bool holds_expected = std::holds_alternative<T>(this->raw_variant);
ASSERT(holds_expected);
return std::get<T>(this->raw_variant);
}
template <typename T>
T  & get(){static_assert(IsPartOfDataTypeValue_v<T>, "DataTypeValue::get() expected one of [half, float, double, int32_t, int64_t, bool], received T");bool holds_expected = std::holds_alternative<T>(this->raw_variant);
ASSERT(holds_expected);
return std::get<T>(this->raw_variant);
}
size_t index() const { return this->raw_variant.index(); }
bool operator==(DataTypeValue const &) const;bool operator!=(DataTypeValue const &) const;bool operator<(DataTypeValue const &) const;bool operator>(DataTypeValue const &) const;bool operator<=(DataTypeValue const &) const;bool operator>=(DataTypeValue const &) const;std::string debug_to_string() const;void debug_print() const;std::variant<half, float, double, int32_t, int64_t, bool> raw_variant;};}// namespace FlexFlow

///\cond
namespace std{template <>
struct hash<::FlexFlow::DataTypeValue>{size_t operator()(::FlexFlow::DataTypeValue const &) const;
};}// namespace std

///\endcond
namespace nlohmann{template <>
struct adl_serializer<::FlexFlow::DataTypeValue>{static ::FlexFlow::DataTypeValue from_json(json const &);
static void to_json(json &, ::FlexFlow::DataTypeValue const &);
};}// namespace nlohmann
namespace rc{template <>
struct Arbitrary<::FlexFlow::DataTypeValue>{static Gen<::FlexFlow::DataTypeValue> arbitrary();
};}// namespace rc
namespace FlexFlow{std::string format_as(::FlexFlow::DataTypeValue const &);
std::ostream & operator<<(std::ostream &, ::FlexFlow::DataTypeValue const &);
}// namespace FlexFlow

#endif // _FLEXFLOW_LIB_OP_ATTRS_INCLUDE_OP_ATTRS_DATATYPE_VALUE_DTG_H
