// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/op-attrs/include/op-attrs/operator_task_space_to_operator_task_space_mapping.dtg.toml
/* proj-data
{
  "generated_from": "4e7a58c8fb35ecbb0e757190db82cadf"
}
*/

#ifndef _FLEXFLOW_LIB_OP_ATTRS_INCLUDE_OP_ATTRS_OPERATOR_TASK_SPACE_TO_OPERATOR_TASK_SPACE_MAPPING_DTG_H
#define _FLEXFLOW_LIB_OP_ATTRS_INCLUDE_OP_ATTRS_OPERATOR_TASK_SPACE_TO_OPERATOR_TASK_SPACE_MAPPING_DTG_H

#include <tuple>
#include <iostream>
#include "op-attrs/operator_task_space_dim_idx_t.dtg.h"
#include <ostream>
#include "utils/orthotope/dim_domain_mapping.h"
#include <fmt/format.h>
#include <nlohmann/json.hpp>
#include <functional>


namespace FlexFlow{struct OperatorTaskSpaceToOperatorTaskSpaceMapping{OperatorTaskSpaceToOperatorTaskSpaceMapping() = delete;
explicit OperatorTaskSpaceToOperatorTaskSpaceMapping(::FlexFlow::DimDomainMapping<::FlexFlow::operator_task_space_dim_idx_t, ::FlexFlow::operator_task_space_dim_idx_t> const &raw_mapping);

bool operator==(OperatorTaskSpaceToOperatorTaskSpaceMapping const &) const;bool operator!=(OperatorTaskSpaceToOperatorTaskSpaceMapping const &) const;
std::string debug_to_string() const;void debug_print() const;
::FlexFlow::DimDomainMapping<::FlexFlow::operator_task_space_dim_idx_t, ::FlexFlow::operator_task_space_dim_idx_t> raw_mapping;
};}// namespace FlexFlow


///\cond
namespace std{template <>
struct hash<::FlexFlow::OperatorTaskSpaceToOperatorTaskSpaceMapping>{size_t operator()(::FlexFlow::OperatorTaskSpaceToOperatorTaskSpaceMapping const &)const;};}// namespace std

///\endcond

namespace nlohmann{template <>
struct adl_serializer<::FlexFlow::OperatorTaskSpaceToOperatorTaskSpaceMapping>{static void to_json(json &, ::FlexFlow::OperatorTaskSpaceToOperatorTaskSpaceMapping const &);
};}// namespace nlohmann

namespace FlexFlow{std::string format_as(OperatorTaskSpaceToOperatorTaskSpaceMapping const &);
std::ostream &operator<<(std::ostream &, OperatorTaskSpaceToOperatorTaskSpaceMapping const &);}// namespace FlexFlow

#endif // _FLEXFLOW_LIB_OP_ATTRS_INCLUDE_OP_ATTRS_OPERATOR_TASK_SPACE_TO_OPERATOR_TASK_SPACE_MAPPING_DTG_H
