// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/op-attrs/include/op-attrs/tensor_dims_coord.dtg.toml
/* proj-data
{
  "generated_from": "c602ffabba1a4df0762dbe73f748491b"
}
*/

#ifndef _FLEXFLOW_LIB_OP_ATTRS_INCLUDE_OP_ATTRS_TENSOR_DIMS_COORD_DTG_H
#define _FLEXFLOW_LIB_OP_ATTRS_INCLUDE_OP_ATTRS_TENSOR_DIMS_COORD_DTG_H

#include <tuple>
#include <iostream>
#include <ostream>
#include "op-attrs/ff_ordered/ff_ordered.h"
#include <fmt/format.h>
#include <nlohmann/json.hpp>
#include <functional>
#include "utils/nonnegative_int/nonnegative_int.h"


namespace FlexFlow{struct TensorDimsCoord{TensorDimsCoord() = delete;
explicit TensorDimsCoord(::FlexFlow::FFOrdered<::FlexFlow::nonnegative_int> const &ff_ordered);

bool operator==(TensorDimsCoord const &) const;bool operator!=(TensorDimsCoord const &) const;
bool operator<(TensorDimsCoord const &) const;bool operator>(TensorDimsCoord const &) const;bool operator<=(TensorDimsCoord const &) const;bool operator>=(TensorDimsCoord const &) const;
std::string debug_to_string() const;void debug_print() const;
::FlexFlow::FFOrdered<::FlexFlow::nonnegative_int> ff_ordered;
};}// namespace FlexFlow


///\cond
namespace std{template <>
struct hash<::FlexFlow::TensorDimsCoord>{size_t operator()(::FlexFlow::TensorDimsCoord const &)const;};}// namespace std

///\endcond

namespace nlohmann{template <>
struct adl_serializer<::FlexFlow::TensorDimsCoord>{static ::FlexFlow::TensorDimsCoord from_json(json const &);
static void to_json(json &, ::FlexFlow::TensorDimsCoord const &);
};}// namespace nlohmann

namespace FlexFlow{std::string format_as(TensorDimsCoord const &);
std::ostream &operator<<(std::ostream &, TensorDimsCoord const &);}// namespace FlexFlow

#endif // _FLEXFLOW_LIB_OP_ATTRS_INCLUDE_OP_ATTRS_TENSOR_DIMS_COORD_DTG_H
