// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/utils/include/utils/dot/dot_html_table.dtg.toml
/* proj-data
{
  "generated_from": "29b050eb1d70d14453a905c7f7afc993"
}
*/

#ifndef _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_DOT_DOT_HTML_TABLE_DTG_H
#define _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_DOT_DOT_HTML_TABLE_DTG_H

#include <tuple>
#include <iostream>
#include "utils/dot/dot_html_table_row.dtg.h"
#include <ostream>
#include <fmt/format.h>
#include <nlohmann/json.hpp>
#include "utils/nonnegative_int/nonnegative_int.h"


namespace FlexFlow{struct DotHtmlTable{DotHtmlTable() = delete;
explicit DotHtmlTable(::FlexFlow::nonnegative_int const &border, ::FlexFlow::nonnegative_int const &cellborder, ::FlexFlow::nonnegative_int const &cellspacing, std::vector<::FlexFlow::DotHtmlTableRow> const &rows);

bool operator==(DotHtmlTable const &) const;bool operator!=(DotHtmlTable const &) const;
std::string debug_to_string() const;void debug_print() const;
::FlexFlow::nonnegative_int border;
::FlexFlow::nonnegative_int cellborder;
::FlexFlow::nonnegative_int cellspacing;
std::vector<::FlexFlow::DotHtmlTableRow> rows;
};}// namespace FlexFlow

namespace nlohmann{template <>
struct adl_serializer<::FlexFlow::DotHtmlTable>{static void to_json(json &, ::FlexFlow::DotHtmlTable const &);
};}// namespace nlohmann

namespace FlexFlow{std::string format_as(DotHtmlTable const &);
std::ostream &operator<<(std::ostream &, DotHtmlTable const &);}// namespace FlexFlow

#endif // _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_DOT_DOT_HTML_TABLE_DTG_H
