// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/compiler/include/compiler/unity_algorithm/unity_search_config.dtg.toml
/* proj-data
{
  "generated_from": "cc54f90c3e344fefe252735d513368e2"
}
*/

#include "compiler/unity_algorithm/unity_search_config.dtg.h"

#include <sstream>

namespace FlexFlow{UnitySearchConfig::UnitySearchConfig(float const &alpha, int const &budget, int const &max_num_ops) : alpha(alpha), budget(budget), max_num_ops(max_num_ops){}
bool UnitySearchConfig::operator==(UnitySearchConfig const &other) const{
return std::tie(this->alpha, this->budget, this->max_num_ops) == std::tie(other.alpha, other.budget, other.max_num_ops);
}bool UnitySearchConfig::operator!=(UnitySearchConfig const &other) const{
return std::tie(this->alpha, this->budget, this->max_num_ops) != std::tie(other.alpha, other.budget, other.max_num_ops);
}}// namespace FlexFlow


///\cond
namespace std{size_t hash<FlexFlow::UnitySearchConfig>::operator()(::FlexFlow::UnitySearchConfig const &x)const{size_t result = 0;
result ^= std::hash<float>{}(x.alpha) + 0x9e3779b9 + (result << 6) + (result >> 2);result ^= std::hash<int>{}(x.budget) + 0x9e3779b9 + (result << 6) + (result >> 2);result ^= std::hash<int>{}(x.max_num_ops) + 0x9e3779b9 + (result << 6) + (result >> 2);return result;
}}// namespace std

///\endcond

namespace nlohmann{void adl_serializer<::FlexFlow::UnitySearchConfig>::to_json(json &j, ::FlexFlow::UnitySearchConfig const &v) {j["__type"] = "UnitySearchConfig";
j["alpha"] = v.alpha;
j["budget"] = v.budget;
j["max_num_ops"] = v.max_num_ops;
}}// namespace nlohmann

namespace nlohmann{::FlexFlow::UnitySearchConfig adl_serializer<::FlexFlow::UnitySearchConfig>::from_json(json const &j) {return ::FlexFlow::UnitySearchConfig{j.at("alpha").template get<float>(), j.at("budget").template get<int>(), j.at("max_num_ops").template get<int>()};}}// namespace nlohmann

namespace FlexFlow{std::string UnitySearchConfig::debug_to_string() const { return fmt::to_string(*this); }void UnitySearchConfig::debug_print() const { std::cout << this->debug_to_string() << std::endl; }std::string format_as(UnitySearchConfig const &x){::nlohmann::json j = x;
return j.dump();
}std::ostream &operator<<(std::ostream &s, UnitySearchConfig const &x) {return s << fmt::to_string(x);}}// namespace FlexFlow
