// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/task-spec/include/task-spec/ops/op_tensor_slot_spec.dtg.toml
/* proj-data
{
  "generated_from": "6e34d2d10204eb57efc51f2b796b646e"
}
*/

#include "task-spec/ops/op_tensor_slot_spec.dtg.h"

#include <sstream>

namespace FlexFlow{OpTensorSlotSpec::OpTensorSlotSpec(::FlexFlow::TensorSlotName const &name, ::FlexFlow::TensorRole const &tensor_role, ::FlexFlow::IsGrad const &is_grad, ::FlexFlow::OpSlotOptions const &slot_option) : name(name), tensor_role(tensor_role), is_grad(is_grad), slot_option(slot_option){}
bool OpTensorSlotSpec::operator==(OpTensorSlotSpec const &other) const{
return std::tie(this->name, this->tensor_role, this->is_grad, this->slot_option) == std::tie(other.name, other.tensor_role, other.is_grad, other.slot_option);
}bool OpTensorSlotSpec::operator!=(OpTensorSlotSpec const &other) const{
return std::tie(this->name, this->tensor_role, this->is_grad, this->slot_option) != std::tie(other.name, other.tensor_role, other.is_grad, other.slot_option);
}bool OpTensorSlotSpec::operator<(OpTensorSlotSpec const &other) const{
return std::tie(this->name, this->tensor_role, this->is_grad, this->slot_option) < std::tie(other.name, other.tensor_role, other.is_grad, other.slot_option);
}bool OpTensorSlotSpec::operator>(OpTensorSlotSpec const &other) const{
return std::tie(this->name, this->tensor_role, this->is_grad, this->slot_option) > std::tie(other.name, other.tensor_role, other.is_grad, other.slot_option);
}bool OpTensorSlotSpec::operator<=(OpTensorSlotSpec const &other) const{
return std::tie(this->name, this->tensor_role, this->is_grad, this->slot_option) <= std::tie(other.name, other.tensor_role, other.is_grad, other.slot_option);
}bool OpTensorSlotSpec::operator>=(OpTensorSlotSpec const &other) const{
return std::tie(this->name, this->tensor_role, this->is_grad, this->slot_option) >= std::tie(other.name, other.tensor_role, other.is_grad, other.slot_option);
}}// namespace FlexFlow


///\cond
namespace std{size_t hash<FlexFlow::OpTensorSlotSpec>::operator()(::FlexFlow::OpTensorSlotSpec const &x)const{size_t result = 0;
result ^= std::hash<::FlexFlow::TensorSlotName>{}(x.name) + 0x9e3779b9 + (result << 6) + (result >> 2);result ^= std::hash<::FlexFlow::TensorRole>{}(x.tensor_role) + 0x9e3779b9 + (result << 6) + (result >> 2);result ^= std::hash<::FlexFlow::IsGrad>{}(x.is_grad) + 0x9e3779b9 + (result << 6) + (result >> 2);result ^= std::hash<::FlexFlow::OpSlotOptions>{}(x.slot_option) + 0x9e3779b9 + (result << 6) + (result >> 2);return result;
}}// namespace std

///\endcond

namespace nlohmann{void adl_serializer<::FlexFlow::OpTensorSlotSpec>::to_json(json &j, ::FlexFlow::OpTensorSlotSpec const &v) {j["__type"] = "OpTensorSlotSpec";
j["name"] = v.name;
j["tensor_role"] = v.tensor_role;
j["is_grad"] = v.is_grad;
j["slot_option"] = v.slot_option;
}}// namespace nlohmann

namespace FlexFlow{std::string OpTensorSlotSpec::debug_to_string() const { return fmt::to_string(*this); }void OpTensorSlotSpec::debug_print() const { std::cout << this->debug_to_string() << std::endl; }std::string format_as(OpTensorSlotSpec const &x){::nlohmann::json j = x;
return j.dump();
}std::ostream &operator<<(std::ostream &s, OpTensorSlotSpec const &x) {return s << fmt::to_string(x);}}// namespace FlexFlow
