// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/utils/include/utils/full_binary_tree/binary_tree_path.dtg.toml
/* proj-data
{
  "generated_from": "a88e643ab2cfa02b9a618823d015cc9c"
}
*/

#ifndef _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_FULL_BINARY_TREE_BINARY_TREE_PATH_DTG_H
#define _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_FULL_BINARY_TREE_BINARY_TREE_PATH_DTG_H

#include <tuple>
#include <iostream>
#include "utils/full_binary_tree/binary_tree_path_entry.dtg.h"
#include <ostream>
#include <vector>
#include <rapidcheck.h>
#include <fmt/format.h>
#include <nlohmann/json.hpp>
#include <functional>


namespace FlexFlow{struct BinaryTreePath{BinaryTreePath() = delete;
explicit BinaryTreePath(std::vector<::FlexFlow::BinaryTreePathEntry> const &entries);

bool operator==(BinaryTreePath const &) const;bool operator!=(BinaryTreePath const &) const;
bool operator<(BinaryTreePath const &) const;bool operator>(BinaryTreePath const &) const;bool operator<=(BinaryTreePath const &) const;bool operator>=(BinaryTreePath const &) const;
std::string debug_to_string() const;void debug_print() const;
std::vector<::FlexFlow::BinaryTreePathEntry> entries;
};}// namespace FlexFlow


///\cond
namespace std{template <>
struct hash<::FlexFlow::BinaryTreePath>{size_t operator()(::FlexFlow::BinaryTreePath const &)const;};}// namespace std

///\endcond

namespace nlohmann{template <>
struct adl_serializer<::FlexFlow::BinaryTreePath>{static ::FlexFlow::BinaryTreePath from_json(json const &);
static void to_json(json &, ::FlexFlow::BinaryTreePath const &);
};}// namespace nlohmann

namespace rc{template <>
struct Arbitrary<::FlexFlow::BinaryTreePath>{static Gen<::FlexFlow::BinaryTreePath> arbitrary();
};}// namespace rc

namespace FlexFlow{std::string format_as(BinaryTreePath const &);
std::ostream &operator<<(std::ostream &, BinaryTreePath const &);}// namespace FlexFlow

#endif // _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_FULL_BINARY_TREE_BINARY_TREE_PATH_DTG_H
