// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/utils/include/utils/full_binary_tree/full_binary_tree_node_type.dtg.toml
/* proj-data
{
  "generated_from": "e4655e893590a1c8471dd3c49125a024"
}
*/

#ifndef _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_FULL_BINARY_TREE_FULL_BINARY_TREE_NODE_TYPE_DTG_H
#define _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_FULL_BINARY_TREE_FULL_BINARY_TREE_NODE_TYPE_DTG_H

#include <string>
#include <ostream>
#include <fmt/format.h>
#include <nlohmann/json.hpp>
#include <functional>
#include <rapidcheck.h>

namespace FlexFlow{enum class FullBinaryTreeNodeType{PARENT, LEAF};std::string format_as(FullBinaryTreeNodeType);
std::ostream &operator<<(std::ostream &, FullBinaryTreeNodeType);
void to_json(::nlohmann::json &, FullBinaryTreeNodeType);
void from_json(::nlohmann::json const &, FullBinaryTreeNodeType &);
}// namespace FlexFlow

///\cond
namespace std{template <>
struct hash<FlexFlow::FullBinaryTreeNodeType> {size_t operator()(FlexFlow::FullBinaryTreeNodeType) const;
};}// namespace std

///\endcond
namespace rc{template <>
struct Arbitrary<FlexFlow::FullBinaryTreeNodeType> {static Gen<FlexFlow::FullBinaryTreeNodeType> arbitrary();
};}// namespace rc

#endif // _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_FULL_BINARY_TREE_FULL_BINARY_TREE_NODE_TYPE_DTG_H
