// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/compiler/include/compiler/unity_algorithm/unity_search_config.dtg.toml
/* proj-data
{
  "generated_from": "cc54f90c3e344fefe252735d513368e2"
}
*/

#ifndef _FLEXFLOW_LIB_COMPILER_INCLUDE_COMPILER_UNITY_ALGORITHM_UNITY_SEARCH_CONFIG_DTG_H
#define _FLEXFLOW_LIB_COMPILER_INCLUDE_COMPILER_UNITY_ALGORITHM_UNITY_SEARCH_CONFIG_DTG_H

#include <tuple>
#include <iostream>
#include <ostream>
#include <fmt/format.h>
#include <nlohmann/json.hpp>
#include <functional>


namespace FlexFlow{struct UnitySearchConfig{UnitySearchConfig() = delete;
explicit UnitySearchConfig(float const &alpha, int const &budget, int const &max_num_ops);

bool operator==(UnitySearchConfig const &) const;bool operator!=(UnitySearchConfig const &) const;
std::string debug_to_string() const;void debug_print() const;
float alpha;
int budget;
int max_num_ops;
};}// namespace FlexFlow


///\cond
namespace std{template <>
struct hash<::FlexFlow::UnitySearchConfig>{size_t operator()(::FlexFlow::UnitySearchConfig const &)const;};}// namespace std

///\endcond

namespace nlohmann{template <>
struct adl_serializer<::FlexFlow::UnitySearchConfig>{static ::FlexFlow::UnitySearchConfig from_json(json const &);
static void to_json(json &, ::FlexFlow::UnitySearchConfig const &);
};}// namespace nlohmann

namespace FlexFlow{std::string format_as(UnitySearchConfig const &);
std::ostream &operator<<(std::ostream &, UnitySearchConfig const &);}// namespace FlexFlow

#endif // _FLEXFLOW_LIB_COMPILER_INCLUDE_COMPILER_UNITY_ALGORITHM_UNITY_SEARCH_CONFIG_DTG_H
