// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/utils/include/utils/graph/open_kwarg_dataflow_graph/algorithms/new_kwarg_dataflow_graph_input.dtg.toml
/* proj-data
{
  "generated_from": "8cff7f5495ffb6b1758422a31b5bd9ed"
}
*/

#ifndef _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_GRAPH_OPEN_KWARG_DATAFLOW_GRAPH_ALGORITHMS_NEW_KWARG_DATAFLOW_GRAPH_INPUT_DTG_H
#define _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_GRAPH_OPEN_KWARG_DATAFLOW_GRAPH_ALGORITHMS_NEW_KWARG_DATAFLOW_GRAPH_INPUT_DTG_H

#include <tuple>
#include <iostream>
#include <ostream>
#include <fmt/format.h>
#include "utils/graph/open_kwarg_dataflow_graph/kwarg_dataflow_graph_input.dtg.h"
#include <nlohmann/json.hpp>
#include <functional>
#include <sstream>


namespace FlexFlow{template <typename GraphInputName>
struct NewKwargDataflowGraphInput{NewKwargDataflowGraphInput() = delete;
explicit NewKwargDataflowGraphInput(::FlexFlow::KwargDataflowGraphInput<GraphInputName> const &raw_input);

bool operator==(NewKwargDataflowGraphInput const &) const;bool operator!=(NewKwargDataflowGraphInput const &) const;
bool operator<(NewKwargDataflowGraphInput const &) const;bool operator>(NewKwargDataflowGraphInput const &) const;bool operator<=(NewKwargDataflowGraphInput const &) const;bool operator>=(NewKwargDataflowGraphInput const &) const;
std::string debug_to_string() const;void debug_print() const;
::FlexFlow::KwargDataflowGraphInput<GraphInputName> raw_input;
};}// namespace FlexFlow


///\cond
namespace std{template <typename GraphInputName>
struct hash<::FlexFlow::NewKwargDataflowGraphInput<GraphInputName>>{size_t operator()(::FlexFlow::NewKwargDataflowGraphInput<GraphInputName> const &)const;};}// namespace std

///\endcond

namespace nlohmann{template <typename GraphInputName>
struct adl_serializer<::FlexFlow::NewKwargDataflowGraphInput<GraphInputName>>{static void to_json(json &, ::FlexFlow::NewKwargDataflowGraphInput<GraphInputName> const &);
};}// namespace nlohmann

namespace FlexFlow{template <typename GraphInputName>
std::string format_as(NewKwargDataflowGraphInput<GraphInputName> const &);
template <typename GraphInputName>
std::ostream &operator<<(std::ostream &, NewKwargDataflowGraphInput<GraphInputName> const &);}// namespace FlexFlow

namespace FlexFlow{template <typename GraphInputName>
NewKwargDataflowGraphInput<GraphInputName>::NewKwargDataflowGraphInput(::FlexFlow::KwargDataflowGraphInput<GraphInputName> const &raw_input) : raw_input(raw_input){}
template <typename GraphInputName>
bool NewKwargDataflowGraphInput<GraphInputName>::operator==(NewKwargDataflowGraphInput<GraphInputName> const &other) const{
return std::tie(this->raw_input) == std::tie(other.raw_input);
}template <typename GraphInputName>
bool NewKwargDataflowGraphInput<GraphInputName>::operator!=(NewKwargDataflowGraphInput<GraphInputName> const &other) const{
return std::tie(this->raw_input) != std::tie(other.raw_input);
}template <typename GraphInputName>
bool NewKwargDataflowGraphInput<GraphInputName>::operator<(NewKwargDataflowGraphInput<GraphInputName> const &other) const{
return std::tie(this->raw_input) < std::tie(other.raw_input);
}template <typename GraphInputName>
bool NewKwargDataflowGraphInput<GraphInputName>::operator>(NewKwargDataflowGraphInput<GraphInputName> const &other) const{
return std::tie(this->raw_input) > std::tie(other.raw_input);
}template <typename GraphInputName>
bool NewKwargDataflowGraphInput<GraphInputName>::operator<=(NewKwargDataflowGraphInput<GraphInputName> const &other) const{
return std::tie(this->raw_input) <= std::tie(other.raw_input);
}template <typename GraphInputName>
bool NewKwargDataflowGraphInput<GraphInputName>::operator>=(NewKwargDataflowGraphInput<GraphInputName> const &other) const{
return std::tie(this->raw_input) >= std::tie(other.raw_input);
}}// namespace FlexFlow


///\cond
namespace std{template <typename GraphInputName>
size_t hash<FlexFlow::NewKwargDataflowGraphInput<GraphInputName>>::operator()(::FlexFlow::NewKwargDataflowGraphInput<GraphInputName> const &x)const{size_t result = 0;
result ^= std::hash<::FlexFlow::KwargDataflowGraphInput<GraphInputName>>{}(x.raw_input) + 0x9e3779b9 + (result << 6) + (result >> 2);return result;
}}// namespace std

///\endcond

namespace nlohmann{template <typename GraphInputName>
void adl_serializer<::FlexFlow::NewKwargDataflowGraphInput<GraphInputName>>::to_json(json &j, ::FlexFlow::NewKwargDataflowGraphInput<GraphInputName> const &v) {j["__type"] = "NewKwargDataflowGraphInput";
j["raw_input"] = v.raw_input;
}}// namespace nlohmann

namespace FlexFlow{template <typename GraphInputName>
std::string NewKwargDataflowGraphInput<GraphInputName>::debug_to_string() const { return fmt::to_string(*this); }template <typename GraphInputName>
void NewKwargDataflowGraphInput<GraphInputName>::debug_print() const { std::cout << this->debug_to_string() << std::endl; }template <typename GraphInputName>
std::string format_as(NewKwargDataflowGraphInput<GraphInputName> const &x){::nlohmann::json j = x;
return j.dump();
}template <typename GraphInputName>
std::ostream &operator<<(std::ostream &s, NewKwargDataflowGraphInput<GraphInputName> const &x) {return s << fmt::to_string(x);}}// namespace FlexFlow

#endif // _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_GRAPH_OPEN_KWARG_DATAFLOW_GRAPH_ALGORITHMS_NEW_KWARG_DATAFLOW_GRAPH_INPUT_DTG_H
