// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/models/include/models/candle_uno/candle_uno_config.dtg.toml
/* proj-data
{
  "generated_from": "085917499cf4772a0b1f073ad5b791eb"
}
*/

#ifndef _FLEXFLOW_LIB_MODELS_INCLUDE_MODELS_CANDLE_UNO_CANDLE_UNO_CONFIG_DTG_H
#define _FLEXFLOW_LIB_MODELS_INCLUDE_MODELS_CANDLE_UNO_CANDLE_UNO_CONFIG_DTG_H

#include <tuple>
#include <iostream>
#include <map>
#include <ostream>
#include <vector>
#include <string>
#include <rapidcheck.h>
#include <fmt/format.h>
#include "utils/positive_int/positive_int.h"
#include <nlohmann/json.hpp>
#include <functional>


namespace FlexFlow{struct CandleUnoConfig{CandleUnoConfig() = delete;
explicit CandleUnoConfig(::FlexFlow::positive_int const &batch_size, std::vector<::FlexFlow::positive_int> const &dense_layers, std::vector<::FlexFlow::positive_int> const &dense_feature_layers, std::map<std::string, ::FlexFlow::positive_int> const &feature_shapes, std::map<std::string, std::string> const &input_features, float const &dropout, bool const &residual);

bool operator==(CandleUnoConfig const &) const;bool operator!=(CandleUnoConfig const &) const;
bool operator<(CandleUnoConfig const &) const;bool operator>(CandleUnoConfig const &) const;bool operator<=(CandleUnoConfig const &) const;bool operator>=(CandleUnoConfig const &) const;
std::string debug_to_string() const;void debug_print() const;
::FlexFlow::positive_int batch_size;
std::vector<::FlexFlow::positive_int> dense_layers;
std::vector<::FlexFlow::positive_int> dense_feature_layers;
std::map<std::string, ::FlexFlow::positive_int> feature_shapes;
std::map<std::string, std::string> input_features;
float dropout;
bool residual;
};}// namespace FlexFlow


///\cond
namespace std{template <>
struct hash<::FlexFlow::CandleUnoConfig>{size_t operator()(::FlexFlow::CandleUnoConfig const &)const;};}// namespace std

///\endcond

namespace nlohmann{template <>
struct adl_serializer<::FlexFlow::CandleUnoConfig>{static ::FlexFlow::CandleUnoConfig from_json(json const &);
static void to_json(json &, ::FlexFlow::CandleUnoConfig const &);
};}// namespace nlohmann

namespace rc{template <>
struct Arbitrary<::FlexFlow::CandleUnoConfig>{static Gen<::FlexFlow::CandleUnoConfig> arbitrary();
};}// namespace rc

namespace FlexFlow{std::string format_as(CandleUnoConfig const &);
std::ostream &operator<<(std::ostream &, CandleUnoConfig const &);}// namespace FlexFlow

#endif // _FLEXFLOW_LIB_MODELS_INCLUDE_MODELS_CANDLE_UNO_CANDLE_UNO_CONFIG_DTG_H
