// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/utils/include/utils/graph/views/lr_direction.dtg.toml
/* proj-data
{
  "generated_from": "aca9bfe1fc6e370c57dda890ae6d36bd"
}
*/

#ifndef _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_GRAPH_VIEWS_LR_DIRECTION_DTG_H
#define _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_GRAPH_VIEWS_LR_DIRECTION_DTG_H

#include <string>
#include <ostream>
#include <fmt/format.h>
#include <nlohmann/json.hpp>
#include <functional>
#include <rapidcheck.h>

namespace FlexFlow{enum class LRDirection{LEFT, RIGHT};std::string format_as(LRDirection);
std::ostream &operator<<(std::ostream &, LRDirection);
void to_json(::nlohmann::json &, LRDirection);
void from_json(::nlohmann::json const &, LRDirection &);
}// namespace FlexFlow

///\cond
namespace std{template <>
struct hash<FlexFlow::LRDirection> {size_t operator()(FlexFlow::LRDirection) const;
};}// namespace std

///\endcond
namespace rc{template <>
struct Arbitrary<FlexFlow::LRDirection> {static Gen<FlexFlow::LRDirection> arbitrary();
};}// namespace rc

#endif // _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_GRAPH_VIEWS_LR_DIRECTION_DTG_H
