// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/substitutions/include/substitutions/tensor_pattern/tensor_attribute_value.dtg.toml
/* proj-data
{
  "generated_from": "826d93444fb49a613f9ebd66821bc0cd"
}
*/

#include "substitutions/tensor_pattern/tensor_attribute_value.dtg.h"

#include <sstream>

namespace FlexFlow{TensorAttributeValue::TensorAttributeValue(::FlexFlow::nonnegative_int const &v) : raw_variant(v) { }
TensorAttributeValue::TensorAttributeValue(::FlexFlow::positive_int const &v) : raw_variant(v) { }
TensorAttributeValue::TensorAttributeValue(std::vector<::FlexFlow::nonnegative_int> const &v) : raw_variant(v) { }
TensorAttributeValue::TensorAttributeValue(std::vector<::FlexFlow::positive_int> const &v) : raw_variant(v) { }bool TensorAttributeValue::operator==(TensorAttributeValue const &other) const{return this->raw_variant == other.raw_variant;}
bool TensorAttributeValue::operator!=(TensorAttributeValue const &other) const{return this->raw_variant != other.raw_variant;}
bool TensorAttributeValue::operator<(TensorAttributeValue const &other) const{return this->raw_variant < other.raw_variant;}
bool TensorAttributeValue::operator>(TensorAttributeValue const &other) const{return this->raw_variant > other.raw_variant;}
bool TensorAttributeValue::operator<=(TensorAttributeValue const &other) const{return this->raw_variant <= other.raw_variant;}
bool TensorAttributeValue::operator>=(TensorAttributeValue const &other) const{return this->raw_variant >= other.raw_variant;}
}// namespace FlexFlow

///\cond
namespace std{size_t hash<::FlexFlow::TensorAttributeValue>::operator()(::FlexFlow::TensorAttributeValue const &x) const{return std::hash<std::variant<::FlexFlow::nonnegative_int, ::FlexFlow::positive_int, std::vector<::FlexFlow::nonnegative_int>, std::vector<::FlexFlow::positive_int>>>{}(x.raw_variant);}
}// namespace std

///\endcond
namespace nlohmann{void adl_serializer<::FlexFlow::TensorAttributeValue>::to_json(json &j, ::FlexFlow::TensorAttributeValue const &x){j["__type"] = "TensorAttributeValue";
switch (x.index()){case 0:{j["type"] = "::FlexFlow::nonnegative_int";
j["value"] = x.template get<::FlexFlow::nonnegative_int>();
break;
}case 1:{j["type"] = "::FlexFlow::positive_int";
j["value"] = x.template get<::FlexFlow::positive_int>();
break;
}case 2:{j["type"] = "std::vector<::FlexFlow::nonnegative_int>";
j["value"] = x.template get<std::vector<::FlexFlow::nonnegative_int>>();
break;
}case 3:{j["type"] = "std::vector<::FlexFlow::positive_int>";
j["value"] = x.template get<std::vector<::FlexFlow::positive_int>>();
break;
}default:{throw std::runtime_error(fmt::format("Unknown index {} for type TensorAttributeValue", x.index()));
}}}
}// namespace nlohmann
namespace nlohmann{::FlexFlow::TensorAttributeValue adl_serializer<::FlexFlow::TensorAttributeValue>::from_json(json const &j){std::string key = j.at("type").template get<std::string>();
if (key == "::FlexFlow::nonnegative_int"){return ::FlexFlow::TensorAttributeValue{j.at("value").template get<::FlexFlow::nonnegative_int>()};
} else if (key == "::FlexFlow::positive_int"){return ::FlexFlow::TensorAttributeValue{j.at("value").template get<::FlexFlow::positive_int>()};
} else if (key == "std::vector<::FlexFlow::nonnegative_int>"){return ::FlexFlow::TensorAttributeValue{j.at("value").template get<std::vector<::FlexFlow::nonnegative_int>>()};
} else if (key == "std::vector<::FlexFlow::positive_int>"){return ::FlexFlow::TensorAttributeValue{j.at("value").template get<std::vector<::FlexFlow::positive_int>>()};
} else {throw std::runtime_error(fmt::format("Unknown type key {}", key));
}}
}// namespace nlohmann
namespace FlexFlow{std::string TensorAttributeValue::debug_to_string() const{return fmt::to_string(*this);}
void TensorAttributeValue::debug_print() const{std::cout << this->debug_to_string() << std::endl;}
std::string format_as(::FlexFlow::TensorAttributeValue const &x){::nlohmann::json j = x;
return j.dump();
}
std::ostream & operator<<(std::ostream &s, ::FlexFlow::TensorAttributeValue const &x){return s << fmt::to_string(x);
}
}// namespace FlexFlow
