// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/compiler/include/compiler/machine_mapping/abstracted_tensor_set_movement/abstracted_single_communication.dtg.toml
/* proj-data
{
  "generated_from": "6b8016548e767507cdc90e1d96d1e6cc"
}
*/

#include "compiler/machine_mapping/abstracted_tensor_set_movement/abstracted_single_communication.dtg.h"

#include <sstream>

namespace FlexFlow{AbstractedSingleCommunication::AbstractedSingleCommunication(::FlexFlow::AbstractedCommunicationEdge const &edge, ::FlexFlow::num_bytes_t const &size) : edge(edge), size(size){}
bool AbstractedSingleCommunication::operator==(AbstractedSingleCommunication const &other) const{
return std::tie(this->edge, this->size) == std::tie(other.edge, other.size);
}bool AbstractedSingleCommunication::operator!=(AbstractedSingleCommunication const &other) const{
return std::tie(this->edge, this->size) != std::tie(other.edge, other.size);
}bool AbstractedSingleCommunication::operator<(AbstractedSingleCommunication const &other) const{
return std::tie(this->edge, this->size) < std::tie(other.edge, other.size);
}bool AbstractedSingleCommunication::operator>(AbstractedSingleCommunication const &other) const{
return std::tie(this->edge, this->size) > std::tie(other.edge, other.size);
}bool AbstractedSingleCommunication::operator<=(AbstractedSingleCommunication const &other) const{
return std::tie(this->edge, this->size) <= std::tie(other.edge, other.size);
}bool AbstractedSingleCommunication::operator>=(AbstractedSingleCommunication const &other) const{
return std::tie(this->edge, this->size) >= std::tie(other.edge, other.size);
}}// namespace FlexFlow


///\cond
namespace std{size_t hash<FlexFlow::AbstractedSingleCommunication>::operator()(::FlexFlow::AbstractedSingleCommunication const &x)const{size_t result = 0;
result ^= std::hash<::FlexFlow::AbstractedCommunicationEdge>{}(x.edge) + 0x9e3779b9 + (result << 6) + (result >> 2);result ^= std::hash<::FlexFlow::num_bytes_t>{}(x.size) + 0x9e3779b9 + (result << 6) + (result >> 2);return result;
}}// namespace std

///\endcond

namespace nlohmann{void adl_serializer<::FlexFlow::AbstractedSingleCommunication>::to_json(json &j, ::FlexFlow::AbstractedSingleCommunication const &v) {j["__type"] = "AbstractedSingleCommunication";
j["edge"] = v.edge;
j["size"] = v.size;
}}// namespace nlohmann

namespace FlexFlow{std::string AbstractedSingleCommunication::debug_to_string() const { return fmt::to_string(*this); }void AbstractedSingleCommunication::debug_print() const { std::cout << this->debug_to_string() << std::endl; }std::string format_as(AbstractedSingleCommunication const &x){::nlohmann::json j = x;
return j.dump();
}std::ostream &operator<<(std::ostream &s, AbstractedSingleCommunication const &x) {return s << fmt::to_string(x);}}// namespace FlexFlow
