// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/utils/include/utils/graph/series_parallel/series_parallel_decomposition.dtg.toml
/* proj-data
{
  "generated_from": "841eddd1bdd7667149b78359ed3b968e"
}
*/

#ifndef _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_GRAPH_SERIES_PARALLEL_SERIES_PARALLEL_DECOMPOSITION_DTG_H
#define _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_GRAPH_SERIES_PARALLEL_SERIES_PARALLEL_DECOMPOSITION_DTG_H

#include <cstddef>
#include <fmt/format.h>
#include <functional>
#include <iostream>
#include <libassert/assert.hpp>
#include <nlohmann/json.hpp>
#include <optional>
#include <ostream>
#include <stdexcept>
#include <type_traits>
#include "utils/graph/node/node.dtg.h"
#include "utils/graph/series_parallel/parallel_split.dtg.h"
#include "utils/graph/series_parallel/series_split.dtg.h"
#include <variant>

namespace FlexFlow{struct SeriesParallelDecomposition{SeriesParallelDecomposition() = delete;
explicit SeriesParallelDecomposition(::FlexFlow::SeriesSplit const &);
explicit SeriesParallelDecomposition(::FlexFlow::ParallelSplit const &);
explicit SeriesParallelDecomposition(::FlexFlow::Node const &);template <typename T>
static constexpr bool IsPartOfSeriesParallelDecomposition_v =std::is_same_v<T, ::FlexFlow::SeriesSplit> || std::is_same_v<T, ::FlexFlow::ParallelSplit> || std::is_same_v<T, ::FlexFlow::Node>;template <typename ReturnType, typename Visitor>
ReturnType visit(Visitor &&v) const{switch (this->index()){case 0: {ReturnType result = v(this->get<::FlexFlow::SeriesSplit>());
return result;
}case 1: {ReturnType result = v(this->get<::FlexFlow::ParallelSplit>());
return result;
}case 2: {ReturnType result = v(this->get<::FlexFlow::Node>());
return result;
}default: {throw std::runtime_error(fmt::format("Unknown index {} for type SeriesParallelDecomposition", this->index()));
}}}
template <typename ReturnType, typename Visitor>
ReturnType visit(Visitor &&v){switch (this->index()){case 0: {ReturnType result = v(this->get<::FlexFlow::SeriesSplit>());
return result;
}case 1: {ReturnType result = v(this->get<::FlexFlow::ParallelSplit>());
return result;
}case 2: {ReturnType result = v(this->get<::FlexFlow::Node>());
return result;
}default: {throw std::runtime_error(fmt::format("Unknown index {} for type SeriesParallelDecomposition", this->index()));
}}}
template <typename T>
bool has() const{static_assert(IsPartOfSeriesParallelDecomposition_v<T>, "SeriesParallelDecomposition::has() expected one of [::FlexFlow::SeriesSplit, ::FlexFlow::ParallelSplit, ::FlexFlow::Node], received T");return std::holds_alternative<T>(this->raw_variant);}
template <typename T>
T const & get() const{static_assert(IsPartOfSeriesParallelDecomposition_v<T>, "SeriesParallelDecomposition::get() expected one of [::FlexFlow::SeriesSplit, ::FlexFlow::ParallelSplit, ::FlexFlow::Node], received T");bool holds_expected = std::holds_alternative<T>(this->raw_variant);
ASSERT(holds_expected);
return std::get<T>(this->raw_variant);
}
template <typename T>
T  & get(){static_assert(IsPartOfSeriesParallelDecomposition_v<T>, "SeriesParallelDecomposition::get() expected one of [::FlexFlow::SeriesSplit, ::FlexFlow::ParallelSplit, ::FlexFlow::Node], received T");bool holds_expected = std::holds_alternative<T>(this->raw_variant);
ASSERT(holds_expected);
return std::get<T>(this->raw_variant);
}
size_t index() const { return this->raw_variant.index(); }
bool operator==(SeriesParallelDecomposition const &) const;bool operator!=(SeriesParallelDecomposition const &) const;bool operator<(SeriesParallelDecomposition const &) const;bool operator>(SeriesParallelDecomposition const &) const;bool operator<=(SeriesParallelDecomposition const &) const;bool operator>=(SeriesParallelDecomposition const &) const;std::string debug_to_string() const;void debug_print() const;std::variant<::FlexFlow::SeriesSplit, ::FlexFlow::ParallelSplit, ::FlexFlow::Node> raw_variant;};}// namespace FlexFlow

///\cond
namespace std{template <>
struct hash<::FlexFlow::SeriesParallelDecomposition>{size_t operator()(::FlexFlow::SeriesParallelDecomposition const &) const;
};}// namespace std

///\endcond
namespace nlohmann{template <>
struct adl_serializer<::FlexFlow::SeriesParallelDecomposition>{static void to_json(json &, ::FlexFlow::SeriesParallelDecomposition const &);
};}// namespace nlohmann
namespace FlexFlow{std::string format_as(::FlexFlow::SeriesParallelDecomposition const &);
std::ostream & operator<<(std::ostream &, ::FlexFlow::SeriesParallelDecomposition const &);
}// namespace FlexFlow

#endif // _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_GRAPH_SERIES_PARALLEL_SERIES_PARALLEL_DECOMPOSITION_DTG_H
