// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/pcg/include/pcg/machine_specification_dimension.dtg.toml
/* proj-data
{
  "generated_from": "f20ab40d318c7e083c2a97373acfb0c7"
}
*/

#ifndef _FLEXFLOW_LIB_PCG_INCLUDE_PCG_MACHINE_SPECIFICATION_DIMENSION_DTG_H
#define _FLEXFLOW_LIB_PCG_INCLUDE_PCG_MACHINE_SPECIFICATION_DIMENSION_DTG_H

#include <string>
#include <ostream>
#include <fmt/format.h>
#include <nlohmann/json.hpp>
#include <functional>
#include <rapidcheck.h>

namespace FlexFlow{enum class MachineSpecificationDimension{INTER_NODE, INTRA_NODE};std::string format_as(MachineSpecificationDimension);
std::ostream &operator<<(std::ostream &, MachineSpecificationDimension);
void to_json(::nlohmann::json &, MachineSpecificationDimension);
void from_json(::nlohmann::json const &, MachineSpecificationDimension &);
}// namespace FlexFlow

///\cond
namespace std{template <>
struct hash<FlexFlow::MachineSpecificationDimension> {size_t operator()(FlexFlow::MachineSpecificationDimension) const;
};}// namespace std

///\endcond
namespace rc{template <>
struct Arbitrary<FlexFlow::MachineSpecificationDimension> {static Gen<FlexFlow::MachineSpecificationDimension> arbitrary();
};}// namespace rc

#endif // _FLEXFLOW_LIB_PCG_INCLUDE_PCG_MACHINE_SPECIFICATION_DIMENSION_DTG_H
