// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/pcg/include/pcg/machine_space_coordinate.dtg.toml
/* proj-data
{
  "generated_from": "f189abeccb37536449391a4cb13b4475"
}
*/

#ifndef _FLEXFLOW_LIB_PCG_INCLUDE_PCG_MACHINE_SPACE_COORDINATE_DTG_H
#define _FLEXFLOW_LIB_PCG_INCLUDE_PCG_MACHINE_SPACE_COORDINATE_DTG_H

#include <tuple>
#include <iostream>
#include <ostream>
#include <rapidcheck.h>
#include <fmt/format.h>
#include <nlohmann/json.hpp>
#include <functional>
#include "utils/nonnegative_int/nonnegative_int.h"


namespace FlexFlow{struct MachineSpaceCoordinate{MachineSpaceCoordinate() = delete;
explicit MachineSpaceCoordinate(::FlexFlow::nonnegative_int const &node_idx, ::FlexFlow::nonnegative_int const &device_idx);

bool operator==(MachineSpaceCoordinate const &) const;bool operator!=(MachineSpaceCoordinate const &) const;
bool operator<(MachineSpaceCoordinate const &) const;bool operator>(MachineSpaceCoordinate const &) const;bool operator<=(MachineSpaceCoordinate const &) const;bool operator>=(MachineSpaceCoordinate const &) const;
std::string debug_to_string() const;void debug_print() const;
::FlexFlow::nonnegative_int node_idx;
::FlexFlow::nonnegative_int device_idx;
};}// namespace FlexFlow


///\cond
namespace std{template <>
struct hash<::FlexFlow::MachineSpaceCoordinate>{size_t operator()(::FlexFlow::MachineSpaceCoordinate const &)const;};}// namespace std

///\endcond

namespace nlohmann{template <>
struct adl_serializer<::FlexFlow::MachineSpaceCoordinate>{static ::FlexFlow::MachineSpaceCoordinate from_json(json const &);
static void to_json(json &, ::FlexFlow::MachineSpaceCoordinate const &);
};}// namespace nlohmann

namespace rc{template <>
struct Arbitrary<::FlexFlow::MachineSpaceCoordinate>{static Gen<::FlexFlow::MachineSpaceCoordinate> arbitrary();
};}// namespace rc

namespace FlexFlow{std::string format_as(MachineSpaceCoordinate const &);
std::ostream &operator<<(std::ostream &, MachineSpaceCoordinate const &);}// namespace FlexFlow

#endif // _FLEXFLOW_LIB_PCG_INCLUDE_PCG_MACHINE_SPACE_COORDINATE_DTG_H
