// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/pcg/include/pcg/machine_interconnect_specification.dtg.toml
/* proj-data
{
  "generated_from": "02bf8c38db9cab4d2fe7d6a49d68ef7d"
}
*/

#ifndef _FLEXFLOW_LIB_PCG_INCLUDE_PCG_MACHINE_INTERCONNECT_SPECIFICATION_DTG_H
#define _FLEXFLOW_LIB_PCG_INCLUDE_PCG_MACHINE_INTERCONNECT_SPECIFICATION_DTG_H

#include <tuple>
#include <iostream>
#include "utils/units/bytes_per_second_t.h"
#include <ostream>
#include <rapidcheck.h>
#include <fmt/format.h>
#include <nlohmann/json.hpp>
#include <functional>


namespace FlexFlow{struct MachineInterconnectSpecification{MachineInterconnectSpecification() = delete;
explicit MachineInterconnectSpecification(::FlexFlow::bytes_per_second_t const &inter_node_bandwidth, ::FlexFlow::bytes_per_second_t const &intra_node_bandwidth);

bool operator==(MachineInterconnectSpecification const &) const;bool operator!=(MachineInterconnectSpecification const &) const;
bool operator<(MachineInterconnectSpecification const &) const;bool operator>(MachineInterconnectSpecification const &) const;bool operator<=(MachineInterconnectSpecification const &) const;bool operator>=(MachineInterconnectSpecification const &) const;
std::string debug_to_string() const;void debug_print() const;
::FlexFlow::bytes_per_second_t inter_node_bandwidth;
::FlexFlow::bytes_per_second_t intra_node_bandwidth;
};}// namespace FlexFlow


///\cond
namespace std{template <>
struct hash<::FlexFlow::MachineInterconnectSpecification>{size_t operator()(::FlexFlow::MachineInterconnectSpecification const &)const;};}// namespace std

///\endcond

namespace nlohmann{template <>
struct adl_serializer<::FlexFlow::MachineInterconnectSpecification>{static ::FlexFlow::MachineInterconnectSpecification from_json(json const &);
static void to_json(json &, ::FlexFlow::MachineInterconnectSpecification const &);
};}// namespace nlohmann

namespace rc{template <>
struct Arbitrary<::FlexFlow::MachineInterconnectSpecification>{static Gen<::FlexFlow::MachineInterconnectSpecification> arbitrary();
};}// namespace rc

namespace FlexFlow{std::string format_as(MachineInterconnectSpecification const &);
std::ostream &operator<<(std::ostream &, MachineInterconnectSpecification const &);}// namespace FlexFlow

#endif // _FLEXFLOW_LIB_PCG_INCLUDE_PCG_MACHINE_INTERCONNECT_SPECIFICATION_DTG_H
