// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/pcg/include/pcg/node_idx_t.dtg.toml
/* proj-data
{
  "generated_from": "b4d451a087f5be3d9feaeba4db69b5fc"
}
*/

#ifndef _FLEXFLOW_LIB_PCG_INCLUDE_PCG_NODE_IDX_T_DTG_H
#define _FLEXFLOW_LIB_PCG_INCLUDE_PCG_NODE_IDX_T_DTG_H

#include <tuple>
#include <iostream>
#include <ostream>
#include <rapidcheck.h>
#include <fmt/format.h>
#include <nlohmann/json.hpp>
#include <functional>
#include "utils/nonnegative_int/nonnegative_int.h"


namespace FlexFlow{struct node_idx_t{node_idx_t() = delete;
explicit node_idx_t(::FlexFlow::nonnegative_int const &raw);

bool operator==(node_idx_t const &) const;bool operator!=(node_idx_t const &) const;
bool operator<(node_idx_t const &) const;bool operator>(node_idx_t const &) const;bool operator<=(node_idx_t const &) const;bool operator>=(node_idx_t const &) const;
std::string debug_to_string() const;void debug_print() const;
::FlexFlow::nonnegative_int raw;
};}// namespace FlexFlow


///\cond
namespace std{template <>
struct hash<::FlexFlow::node_idx_t>{size_t operator()(::FlexFlow::node_idx_t const &)const;};}// namespace std

///\endcond

namespace nlohmann{template <>
struct adl_serializer<::FlexFlow::node_idx_t>{static ::FlexFlow::node_idx_t from_json(json const &);
static void to_json(json &, ::FlexFlow::node_idx_t const &);
};}// namespace nlohmann

namespace rc{template <>
struct Arbitrary<::FlexFlow::node_idx_t>{static Gen<::FlexFlow::node_idx_t> arbitrary();
};}// namespace rc

namespace FlexFlow{std::string format_as(node_idx_t const &);
std::ostream &operator<<(std::ostream &, node_idx_t const &);}// namespace FlexFlow

#endif // _FLEXFLOW_LIB_PCG_INCLUDE_PCG_NODE_IDX_T_DTG_H
