// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/utils/include/utils/graph/node/node.dtg.toml
/* proj-data
{
  "generated_from": "cba3a2bd9dffc28b0f655a5277b712f3"
}
*/

#include "utils/graph/node/node.dtg.h"

#include <sstream>

namespace FlexFlow{Node::Node(size_t const &raw_uid) : raw_uid(raw_uid){}
bool Node::operator==(Node const &other) const{
return std::tie(this->raw_uid) == std::tie(other.raw_uid);
}bool Node::operator!=(Node const &other) const{
return std::tie(this->raw_uid) != std::tie(other.raw_uid);
}bool Node::operator<(Node const &other) const{
return std::tie(this->raw_uid) < std::tie(other.raw_uid);
}bool Node::operator>(Node const &other) const{
return std::tie(this->raw_uid) > std::tie(other.raw_uid);
}bool Node::operator<=(Node const &other) const{
return std::tie(this->raw_uid) <= std::tie(other.raw_uid);
}bool Node::operator>=(Node const &other) const{
return std::tie(this->raw_uid) >= std::tie(other.raw_uid);
}}// namespace FlexFlow


///\cond
namespace std{size_t hash<FlexFlow::Node>::operator()(::FlexFlow::Node const &x)const{size_t result = 0;
result ^= std::hash<size_t>{}(x.raw_uid) + 0x9e3779b9 + (result << 6) + (result >> 2);return result;
}}// namespace std

///\endcond

namespace nlohmann{void adl_serializer<::FlexFlow::Node>::to_json(json &j, ::FlexFlow::Node const &v) {j["__type"] = "Node";
j["raw_uid"] = v.raw_uid;
}}// namespace nlohmann

namespace nlohmann{::FlexFlow::Node adl_serializer<::FlexFlow::Node>::from_json(json const &j) {return ::FlexFlow::Node{j.at("raw_uid").template get<size_t>()};}}// namespace nlohmann

namespace FlexFlow{std::string Node::debug_to_string() const { return fmt::to_string(*this); }void Node::debug_print() const { std::cout << this->debug_to_string() << std::endl; }std::string format_as(Node const &x){::nlohmann::json j = x;
return j.dump();
}std::ostream &operator<<(std::ostream &s, Node const &x) {return s << fmt::to_string(x);}}// namespace FlexFlow
