// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/pcg/include/pcg/file_format/v1/v1_binary_sp_decomposition/v1_binary_sp_decomposition.dtg.toml
/* proj-data
{
  "generated_from": "c541496447822500bfb80ebcb232ea14"
}
*/

#include "pcg/file_format/v1/v1_binary_sp_decomposition/v1_binary_sp_decomposition.dtg.h"

#include <sstream>

namespace FlexFlow{V1BinarySPDecomposition::V1BinarySPDecomposition(::FlexFlow::V1BinarySeriesSplit const &v) : raw_variant(v) { }
V1BinarySPDecomposition::V1BinarySPDecomposition(::FlexFlow::V1BinaryParallelSplit const &v) : raw_variant(v) { }
V1BinarySPDecomposition::V1BinarySPDecomposition(::FlexFlow::nonnegative_int const &v) : raw_variant(v) { }bool V1BinarySPDecomposition::operator==(V1BinarySPDecomposition const &other) const{return this->raw_variant == other.raw_variant;}
bool V1BinarySPDecomposition::operator!=(V1BinarySPDecomposition const &other) const{return this->raw_variant != other.raw_variant;}
::FlexFlow::V1BinarySeriesSplit const & V1BinarySPDecomposition::require_series() const{bool holds_expected = std::holds_alternative<::FlexFlow::V1BinarySeriesSplit>(this->raw_variant);
ASSERT(holds_expected, "Expected ::FlexFlow::V1BinarySeriesSplit");
return std::get<::FlexFlow::V1BinarySeriesSplit>(this->raw_variant);
}
::FlexFlow::V1BinarySeriesSplit & V1BinarySPDecomposition::require_series(){bool holds_expected = std::holds_alternative<::FlexFlow::V1BinarySeriesSplit>(this->raw_variant);
ASSERT(holds_expected, "Expected ::FlexFlow::V1BinarySeriesSplit");
return std::get<::FlexFlow::V1BinarySeriesSplit>(this->raw_variant);
}
::FlexFlow::V1BinaryParallelSplit const & V1BinarySPDecomposition::require_parallel() const{bool holds_expected = std::holds_alternative<::FlexFlow::V1BinaryParallelSplit>(this->raw_variant);
ASSERT(holds_expected, "Expected ::FlexFlow::V1BinaryParallelSplit");
return std::get<::FlexFlow::V1BinaryParallelSplit>(this->raw_variant);
}
::FlexFlow::V1BinaryParallelSplit & V1BinarySPDecomposition::require_parallel(){bool holds_expected = std::holds_alternative<::FlexFlow::V1BinaryParallelSplit>(this->raw_variant);
ASSERT(holds_expected, "Expected ::FlexFlow::V1BinaryParallelSplit");
return std::get<::FlexFlow::V1BinaryParallelSplit>(this->raw_variant);
}
::FlexFlow::nonnegative_int const & V1BinarySPDecomposition::require_leaf() const{bool holds_expected = std::holds_alternative<::FlexFlow::nonnegative_int>(this->raw_variant);
ASSERT(holds_expected, "Expected ::FlexFlow::nonnegative_int");
return std::get<::FlexFlow::nonnegative_int>(this->raw_variant);
}
::FlexFlow::nonnegative_int & V1BinarySPDecomposition::require_leaf(){bool holds_expected = std::holds_alternative<::FlexFlow::nonnegative_int>(this->raw_variant);
ASSERT(holds_expected, "Expected ::FlexFlow::nonnegative_int");
return std::get<::FlexFlow::nonnegative_int>(this->raw_variant);
}
std::optional<::FlexFlow::V1BinarySeriesSplit> V1BinarySPDecomposition::try_require_series() const{if (this->is_series()) {return this->require_series();
}else {return std::nullopt;
}}
std::optional<::FlexFlow::V1BinaryParallelSplit> V1BinarySPDecomposition::try_require_parallel() const{if (this->is_parallel()) {return this->require_parallel();
}else {return std::nullopt;
}}
std::optional<::FlexFlow::nonnegative_int> V1BinarySPDecomposition::try_require_leaf() const{if (this->is_leaf()) {return this->require_leaf();
}else {return std::nullopt;
}}
bool V1BinarySPDecomposition::is_series() const{return std::holds_alternative<::FlexFlow::V1BinarySeriesSplit>(this->raw_variant);
}
bool V1BinarySPDecomposition::is_parallel() const{return std::holds_alternative<::FlexFlow::V1BinaryParallelSplit>(this->raw_variant);
}
bool V1BinarySPDecomposition::is_leaf() const{return std::holds_alternative<::FlexFlow::nonnegative_int>(this->raw_variant);
}
}// namespace FlexFlow

///\cond
namespace std{size_t hash<::FlexFlow::V1BinarySPDecomposition>::operator()(::FlexFlow::V1BinarySPDecomposition const &x) const{return std::hash<std::variant<::FlexFlow::V1BinarySeriesSplit, ::FlexFlow::V1BinaryParallelSplit, ::FlexFlow::nonnegative_int>>{}(x.raw_variant);}
}// namespace std

///\endcond
namespace FlexFlow{std::string V1BinarySPDecomposition::debug_to_string() const{return fmt::to_string(*this);}
void V1BinarySPDecomposition::debug_print() const{std::cout << this->debug_to_string() << std::endl;}
std::string format_as(::FlexFlow::V1BinarySPDecomposition const &x){std::ostringstream oss;
switch (x.index()){case 0: {oss << "<V1BinarySPDecomposition series=" << x.template get<::FlexFlow::V1BinarySeriesSplit>() << ">";
break;
}case 1: {oss << "<V1BinarySPDecomposition parallel=" << x.template get<::FlexFlow::V1BinaryParallelSplit>() << ">";
break;
}case 2: {oss << "<V1BinarySPDecomposition leaf=" << x.template get<::FlexFlow::nonnegative_int>() << ">";
break;
}default: {throw std::runtime_error(fmt::format("Unknown index {} for type V1BinarySPDecomposition", x.index()));
break;
}}return oss.str();
}
std::ostream & operator<<(std::ostream &s, ::FlexFlow::V1BinarySPDecomposition const &x){return s << fmt::to_string(x);
}
}// namespace FlexFlow
