// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/pcg/include/pcg/parallel_computation_graph/parallel_computation_graph.dtg.toml
/* proj-data
{
  "generated_from": "83edaa180a9debbe06d9066928f1d143"
}
*/

#include "pcg/parallel_computation_graph/parallel_computation_graph.dtg.h"


namespace FlexFlow{ParallelComputationGraph::ParallelComputationGraph(::FlexFlow::LabelledKwargDataflowGraph<::FlexFlow::ParallelLayerAttrs, ::FlexFlow::ParallelTensorAttrs, ::FlexFlow::TensorSlotName> const &raw_graph) : raw_graph(raw_graph){}
}// namespace FlexFlow
