// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/pcg/include/pcg/parallel_computation_graph/parallel_tensor_use_t.dtg.toml
/* proj-data
{
  "generated_from": "e1d79a11152a1d5d05e3fdd3c8235295"
}
*/

#include "pcg/parallel_computation_graph/parallel_tensor_use_t.dtg.h"

#include <sstream>

namespace FlexFlow{parallel_tensor_use_t::parallel_tensor_use_t(::FlexFlow::KwargDataflowInput<::FlexFlow::TensorSlotName> const &raw_dataflow_input) : raw_dataflow_input(raw_dataflow_input){}
bool parallel_tensor_use_t::operator==(parallel_tensor_use_t const &other) const{
return std::tie(this->raw_dataflow_input) == std::tie(other.raw_dataflow_input);
}bool parallel_tensor_use_t::operator!=(parallel_tensor_use_t const &other) const{
return std::tie(this->raw_dataflow_input) != std::tie(other.raw_dataflow_input);
}bool parallel_tensor_use_t::operator<(parallel_tensor_use_t const &other) const{
return std::tie(this->raw_dataflow_input) < std::tie(other.raw_dataflow_input);
}bool parallel_tensor_use_t::operator>(parallel_tensor_use_t const &other) const{
return std::tie(this->raw_dataflow_input) > std::tie(other.raw_dataflow_input);
}bool parallel_tensor_use_t::operator<=(parallel_tensor_use_t const &other) const{
return std::tie(this->raw_dataflow_input) <= std::tie(other.raw_dataflow_input);
}bool parallel_tensor_use_t::operator>=(parallel_tensor_use_t const &other) const{
return std::tie(this->raw_dataflow_input) >= std::tie(other.raw_dataflow_input);
}}// namespace FlexFlow


///\cond
namespace std{size_t hash<FlexFlow::parallel_tensor_use_t>::operator()(::FlexFlow::parallel_tensor_use_t const &x)const{size_t result = 0;
result ^= std::hash<::FlexFlow::KwargDataflowInput<::FlexFlow::TensorSlotName>>{}(x.raw_dataflow_input) + 0x9e3779b9 + (result << 6) + (result >> 2);return result;
}}// namespace std

///\endcond

namespace nlohmann{void adl_serializer<::FlexFlow::parallel_tensor_use_t>::to_json(json &j, ::FlexFlow::parallel_tensor_use_t const &v) {j["__type"] = "parallel_tensor_use_t";
j["raw_dataflow_input"] = v.raw_dataflow_input;
}}// namespace nlohmann

namespace FlexFlow{std::string parallel_tensor_use_t::debug_to_string() const { return fmt::to_string(*this); }void parallel_tensor_use_t::debug_print() const { std::cout << this->debug_to_string() << std::endl; }std::string format_as(parallel_tensor_use_t const &x){::nlohmann::json j = x;
return j.dump();
}std::ostream &operator<<(std::ostream &s, parallel_tensor_use_t const &x) {return s << fmt::to_string(x);}}// namespace FlexFlow
