// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/kernels/include/kernels/batch_norm_per_device_state.dtg.toml
/* proj-data
{
  "generated_from": "ef3d77bde318a091531422e40747932c"
}
*/

#include "kernels/batch_norm_per_device_state.dtg.h"


namespace FlexFlow{BatchNormPerDeviceState::BatchNormPerDeviceState(ffTensorDescriptor_t const &inputTensor, ffTensorDescriptor_t const &outputTensor, ffTensorDescriptor_t const &biasTensor, ffBatchNormMode_t const &mode, float * const &runningMean, float * const &runningVar, float * const &saveMean, float * const &saveVar) : inputTensor(inputTensor), outputTensor(outputTensor), biasTensor(biasTensor), mode(mode), runningMean(runningMean), runningVar(runningVar), saveMean(saveMean), saveVar(saveVar){}
}// namespace FlexFlow
