// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/kernels/include/kernels/conv_2d_per_device_state.dtg.toml
/* proj-data
{
  "generated_from": "d00f63b0486ea8eb14370918df0b80a3"
}
*/

#include "kernels/conv_2d_per_device_state.dtg.h"


namespace FlexFlow{Conv2DPerDeviceState::Conv2DPerDeviceState(ffTensorDescriptor_t const &inputTensor, ffTensorDescriptor_t const &biasTensor, ffTensorDescriptor_t const &outputTensor, ffFilterDescriptor_t const &filterDesc, ffConvolutionDescriptor_t const &convDesc, ffConvolutionFwdAlgo_t const &fwdAlgo, ffConvolutionBwdFilterAlgo_t const &bwdFilterAlgo, ffConvolutionBwdDataAlgo_t const &bwdDataAlgo, size_t const &fwdWorkspaceSize, size_t const &bwdFilterWorkspaceSize, size_t const &bwdDataWorkspaceSize) : inputTensor(inputTensor), biasTensor(biasTensor), outputTensor(outputTensor), filterDesc(filterDesc), convDesc(convDesc), fwdAlgo(fwdAlgo), bwdFilterAlgo(bwdFilterAlgo), bwdDataAlgo(bwdDataAlgo), fwdWorkspaceSize(fwdWorkspaceSize), bwdFilterWorkspaceSize(bwdFilterWorkspaceSize), bwdDataWorkspaceSize(bwdDataWorkspaceSize){}
}// namespace FlexFlow
