// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/kernels/include/kernels/element_binary_per_device_state.dtg.toml
/* proj-data
{
  "generated_from": "873f60ff79da7a9694c80389e3e769d0"
}
*/

#include "kernels/element_binary_per_device_state.dtg.h"


namespace FlexFlow{ElementBinaryPerDeviceState::ElementBinaryPerDeviceState(ffTensorDescriptor_t const &inputLHSTensor, ffTensorDescriptor_t const &inputRHSTensor, ffTensorDescriptor_t const &outputTensor, ffOpTensorDescriptor_t const &opDesc, ffReduceTensorDescriptor_t const &reduceAddDesc) : inputLHSTensor(inputLHSTensor), inputRHSTensor(inputRHSTensor), outputTensor(outputTensor), opDesc(opDesc), reduceAddDesc(reduceAddDesc){}
}// namespace FlexFlow
