// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/kernels/include/kernels/reverse_kernels_params.dtg.toml
/* proj-data
{
  "generated_from": "94afe55489577b9d2f89972d4174eb79"
}
*/

#include "kernels/reverse_kernels_params.dtg.h"

#include <sstream>

namespace FlexFlow{ReverseKernelsParams::ReverseKernelsParams(::FlexFlow::positive_int const &num_out_blks, ::FlexFlow::positive_int const &reverse_dim_size, ::FlexFlow::positive_int const &in_blk_size, ::FlexFlow::positive_int const &out_size) : num_out_blks(num_out_blks), reverse_dim_size(reverse_dim_size), in_blk_size(in_blk_size), out_size(out_size){}
bool ReverseKernelsParams::operator==(ReverseKernelsParams const &other) const{
return std::tie(this->num_out_blks, this->reverse_dim_size, this->in_blk_size, this->out_size) == std::tie(other.num_out_blks, other.reverse_dim_size, other.in_blk_size, other.out_size);
}bool ReverseKernelsParams::operator!=(ReverseKernelsParams const &other) const{
return std::tie(this->num_out_blks, this->reverse_dim_size, this->in_blk_size, this->out_size) != std::tie(other.num_out_blks, other.reverse_dim_size, other.in_blk_size, other.out_size);
}bool ReverseKernelsParams::operator<(ReverseKernelsParams const &other) const{
return std::tie(this->num_out_blks, this->reverse_dim_size, this->in_blk_size, this->out_size) < std::tie(other.num_out_blks, other.reverse_dim_size, other.in_blk_size, other.out_size);
}bool ReverseKernelsParams::operator>(ReverseKernelsParams const &other) const{
return std::tie(this->num_out_blks, this->reverse_dim_size, this->in_blk_size, this->out_size) > std::tie(other.num_out_blks, other.reverse_dim_size, other.in_blk_size, other.out_size);
}bool ReverseKernelsParams::operator<=(ReverseKernelsParams const &other) const{
return std::tie(this->num_out_blks, this->reverse_dim_size, this->in_blk_size, this->out_size) <= std::tie(other.num_out_blks, other.reverse_dim_size, other.in_blk_size, other.out_size);
}bool ReverseKernelsParams::operator>=(ReverseKernelsParams const &other) const{
return std::tie(this->num_out_blks, this->reverse_dim_size, this->in_blk_size, this->out_size) >= std::tie(other.num_out_blks, other.reverse_dim_size, other.in_blk_size, other.out_size);
}}// namespace FlexFlow


///\cond
namespace std{size_t hash<FlexFlow::ReverseKernelsParams>::operator()(::FlexFlow::ReverseKernelsParams const &x)const{size_t result = 0;
result ^= std::hash<::FlexFlow::positive_int>{}(x.num_out_blks) + 0x9e3779b9 + (result << 6) + (result >> 2);result ^= std::hash<::FlexFlow::positive_int>{}(x.reverse_dim_size) + 0x9e3779b9 + (result << 6) + (result >> 2);result ^= std::hash<::FlexFlow::positive_int>{}(x.in_blk_size) + 0x9e3779b9 + (result << 6) + (result >> 2);result ^= std::hash<::FlexFlow::positive_int>{}(x.out_size) + 0x9e3779b9 + (result << 6) + (result >> 2);return result;
}}// namespace std

///\endcond

namespace nlohmann{void adl_serializer<::FlexFlow::ReverseKernelsParams>::to_json(json &j, ::FlexFlow::ReverseKernelsParams const &v) {j["__type"] = "ReverseKernelsParams";
j["num_out_blks"] = v.num_out_blks;
j["reverse_dim_size"] = v.reverse_dim_size;
j["in_blk_size"] = v.in_blk_size;
j["out_size"] = v.out_size;
}}// namespace nlohmann

namespace FlexFlow{std::string ReverseKernelsParams::debug_to_string() const { return fmt::to_string(*this); }void ReverseKernelsParams::debug_print() const { std::cout << this->debug_to_string() << std::endl; }std::string format_as(ReverseKernelsParams const &x){::nlohmann::json j = x;
return j.dump();
}std::ostream &operator<<(std::ostream &s, ReverseKernelsParams const &x) {return s << fmt::to_string(x);}}// namespace FlexFlow
