// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/realm-execution/include/realm-execution/tasks/serializer/serializable_realm_instance.dtg.toml
/* proj-data
{
  "generated_from": "d5d39c2eca8bc5ee36d0ea19af9c467d"
}
*/

#include "realm-execution/tasks/serializer/serializable_realm_instance.dtg.h"

#include "utils/fmt/vector.h"
#include "utils/hash/vector.h"
#include <sstream>

namespace FlexFlow{SerializableRealmInstance::SerializableRealmInstance(std::vector<uint8_t> const &instance) : instance(instance){}
bool SerializableRealmInstance::operator==(SerializableRealmInstance const &other) const{
return std::tie(this->instance) == std::tie(other.instance);
}bool SerializableRealmInstance::operator!=(SerializableRealmInstance const &other) const{
return std::tie(this->instance) != std::tie(other.instance);
}}// namespace FlexFlow


///\cond
namespace std{size_t hash<FlexFlow::SerializableRealmInstance>::operator()(::FlexFlow::SerializableRealmInstance const &x)const{size_t result = 0;
result ^= std::hash<std::vector<uint8_t>>{}(x.instance) + 0x9e3779b9 + (result << 6) + (result >> 2);return result;
}}// namespace std

///\endcond

namespace nlohmann{void adl_serializer<::FlexFlow::SerializableRealmInstance>::to_json(json &j, ::FlexFlow::SerializableRealmInstance const &v) {j["__type"] = "SerializableRealmInstance";
j["instance"] = v.instance;
}}// namespace nlohmann

namespace nlohmann{::FlexFlow::SerializableRealmInstance adl_serializer<::FlexFlow::SerializableRealmInstance>::from_json(json const &j) {return ::FlexFlow::SerializableRealmInstance{j.at("instance").template get<std::vector<uint8_t>>()};}}// namespace nlohmann

namespace FlexFlow{std::string SerializableRealmInstance::debug_to_string() const { return fmt::to_string(*this); }void SerializableRealmInstance::debug_print() const { std::cout << this->debug_to_string() << std::endl; }std::string format_as(SerializableRealmInstance const &x){::nlohmann::json j = x;
return j.dump();
}std::ostream &operator<<(std::ostream &s, SerializableRealmInstance const &x) {return s << fmt::to_string(x);}}// namespace FlexFlow
