// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/compiler/include/compiler/task_graph_simulator/in_progress_task.dtg.toml
/* proj-data
{
  "generated_from": "54c7a0a630434736e3fc273b09795d25"
}
*/

#ifndef _FLEXFLOW_LIB_COMPILER_INCLUDE_COMPILER_TASK_GRAPH_SIMULATOR_IN_PROGRESS_TASK_DTG_H
#define _FLEXFLOW_LIB_COMPILER_INCLUDE_COMPILER_TASK_GRAPH_SIMULATOR_IN_PROGRESS_TASK_DTG_H

#include <tuple>
#include <iostream>
#include <ostream>
#include <fmt/format.h>
#include <nlohmann/json.hpp>
#include <functional>
#include "utils/graph/node/node.dtg.h"


namespace FlexFlow{struct InProgressTask{InProgressTask() = delete;
explicit InProgressTask(float const &start_time, float const &end_time, ::FlexFlow::Node const &node);

bool operator==(InProgressTask const &) const;bool operator!=(InProgressTask const &) const;
bool operator<(InProgressTask const &) const;bool operator>(InProgressTask const &) const;bool operator<=(InProgressTask const &) const;bool operator>=(InProgressTask const &) const;
std::string debug_to_string() const;void debug_print() const;
float start_time;
float end_time;
::FlexFlow::Node node;
};}// namespace FlexFlow


///\cond
namespace std{template <>
struct hash<::FlexFlow::InProgressTask>{size_t operator()(::FlexFlow::InProgressTask const &)const;};}// namespace std

///\endcond

namespace nlohmann{template <>
struct adl_serializer<::FlexFlow::InProgressTask>{static void to_json(json &, ::FlexFlow::InProgressTask const &);
};}// namespace nlohmann

namespace FlexFlow{std::string format_as(InProgressTask const &);
std::ostream &operator<<(std::ostream &, InProgressTask const &);}// namespace FlexFlow

#endif // _FLEXFLOW_LIB_COMPILER_INCLUDE_COMPILER_TASK_GRAPH_SIMULATOR_IN_PROGRESS_TASK_DTG_H
