// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/compiler/include/compiler/task_graph_simulator/task_graph_execution_trace.dtg.toml
/* proj-data
{
  "generated_from": "44f999ea64a6e4debc06893d1fbcbff6"
}
*/

#ifndef _FLEXFLOW_LIB_COMPILER_INCLUDE_COMPILER_TASK_GRAPH_SIMULATOR_TASK_GRAPH_EXECUTION_TRACE_DTG_H
#define _FLEXFLOW_LIB_COMPILER_INCLUDE_COMPILER_TASK_GRAPH_SIMULATOR_TASK_GRAPH_EXECUTION_TRACE_DTG_H

#include <tuple>
#include <iostream>
#include "compiler/task_graph_simulator/task_profile.dtg.h"
#include <set>
#include <ostream>
#include <fmt/format.h>
#include <nlohmann/json.hpp>
#include <functional>


namespace FlexFlow{struct TaskGraphExecutionTrace{TaskGraphExecutionTrace() = delete;
explicit TaskGraphExecutionTrace(std::set<::FlexFlow::TaskProfile> const &task_profiles);

bool operator==(TaskGraphExecutionTrace const &) const;bool operator!=(TaskGraphExecutionTrace const &) const;
std::string debug_to_string() const;void debug_print() const;
std::set<::FlexFlow::TaskProfile> task_profiles;
};}// namespace FlexFlow


///\cond
namespace std{template <>
struct hash<::FlexFlow::TaskGraphExecutionTrace>{size_t operator()(::FlexFlow::TaskGraphExecutionTrace const &)const;};}// namespace std

///\endcond

namespace nlohmann{template <>
struct adl_serializer<::FlexFlow::TaskGraphExecutionTrace>{static void to_json(json &, ::FlexFlow::TaskGraphExecutionTrace const &);
};}// namespace nlohmann

namespace FlexFlow{std::string format_as(TaskGraphExecutionTrace const &);
std::ostream &operator<<(std::ostream &, TaskGraphExecutionTrace const &);}// namespace FlexFlow

#endif // _FLEXFLOW_LIB_COMPILER_INCLUDE_COMPILER_TASK_GRAPH_SIMULATOR_TASK_GRAPH_EXECUTION_TRACE_DTG_H
