// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/compiler/include/compiler/task_graph_simulator/task_profile.dtg.toml
/* proj-data
{
  "generated_from": "d6a72431d367cad8279fc4914d0d735b"
}
*/

#ifndef _FLEXFLOW_LIB_COMPILER_INCLUDE_COMPILER_TASK_GRAPH_SIMULATOR_TASK_PROFILE_DTG_H
#define _FLEXFLOW_LIB_COMPILER_INCLUDE_COMPILER_TASK_GRAPH_SIMULATOR_TASK_PROFILE_DTG_H

#include <tuple>
#include <iostream>
#include <ostream>
#include <fmt/format.h>
#include <nlohmann/json.hpp>
#include <functional>
#include "utils/graph/node/node.dtg.h"


namespace FlexFlow{struct TaskProfile{TaskProfile() = delete;
explicit TaskProfile(::FlexFlow::Node const &node, float const &start_time, float const &end_time);

bool operator==(TaskProfile const &) const;bool operator!=(TaskProfile const &) const;
bool operator<(TaskProfile const &) const;bool operator>(TaskProfile const &) const;bool operator<=(TaskProfile const &) const;bool operator>=(TaskProfile const &) const;
std::string debug_to_string() const;void debug_print() const;
::FlexFlow::Node node;
float start_time;
float end_time;
};}// namespace FlexFlow


///\cond
namespace std{template <>
struct hash<::FlexFlow::TaskProfile>{size_t operator()(::FlexFlow::TaskProfile const &)const;};}// namespace std

///\endcond

namespace nlohmann{template <>
struct adl_serializer<::FlexFlow::TaskProfile>{static void to_json(json &, ::FlexFlow::TaskProfile const &);
};}// namespace nlohmann

namespace FlexFlow{std::string format_as(TaskProfile const &);
std::ostream &operator<<(std::ostream &, TaskProfile const &);}// namespace FlexFlow

#endif // _FLEXFLOW_LIB_COMPILER_INCLUDE_COMPILER_TASK_GRAPH_SIMULATOR_TASK_PROFILE_DTG_H
