// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/utils/include/utils/graph/node/algorithms/new_node.dtg.toml
/* proj-data
{
  "generated_from": "e21eda69e98181ede2588ac96f491ca9"
}
*/

#ifndef _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_GRAPH_NODE_ALGORITHMS_NEW_NODE_DTG_H
#define _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_GRAPH_NODE_ALGORITHMS_NEW_NODE_DTG_H

#include <tuple>
#include <iostream>
#include <ostream>
#include <fmt/format.h>
#include <nlohmann/json.hpp>
#include <functional>
#include "utils/graph/node/node.dtg.h"


namespace FlexFlow{struct NewNode{NewNode() = delete;
explicit NewNode(::FlexFlow::Node const &raw_node);

bool operator==(NewNode const &) const;bool operator!=(NewNode const &) const;
bool operator<(NewNode const &) const;bool operator>(NewNode const &) const;bool operator<=(NewNode const &) const;bool operator>=(NewNode const &) const;
std::string debug_to_string() const;void debug_print() const;
::FlexFlow::Node raw_node;
};}// namespace FlexFlow


///\cond
namespace std{template <>
struct hash<::FlexFlow::NewNode>{size_t operator()(::FlexFlow::NewNode const &)const;};}// namespace std

///\endcond

namespace nlohmann{template <>
struct adl_serializer<::FlexFlow::NewNode>{static void to_json(json &, ::FlexFlow::NewNode const &);
};}// namespace nlohmann

namespace FlexFlow{std::string format_as(NewNode const &);
std::ostream &operator<<(std::ostream &, NewNode const &);}// namespace FlexFlow

#endif // _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_GRAPH_NODE_ALGORITHMS_NEW_NODE_DTG_H
