// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/substitutions/include/substitutions/unlabelled/input_pattern_edge.dtg.toml
/* proj-data
{
  "generated_from": "485eb7e78412ef67d43e970347f29bd6"
}
*/

#include "substitutions/unlabelled/input_pattern_edge.dtg.h"

#include <sstream>

namespace FlexFlow{InputPatternEdge::InputPatternEdge(::FlexFlow::KwargDataflowInputEdge<int, ::FlexFlow::TensorSlotName> const &raw_edge) : raw_edge(raw_edge){}
bool InputPatternEdge::operator==(InputPatternEdge const &other) const{
return std::tie(this->raw_edge) == std::tie(other.raw_edge);
}bool InputPatternEdge::operator!=(InputPatternEdge const &other) const{
return std::tie(this->raw_edge) != std::tie(other.raw_edge);
}bool InputPatternEdge::operator<(InputPatternEdge const &other) const{
return std::tie(this->raw_edge) < std::tie(other.raw_edge);
}bool InputPatternEdge::operator>(InputPatternEdge const &other) const{
return std::tie(this->raw_edge) > std::tie(other.raw_edge);
}bool InputPatternEdge::operator<=(InputPatternEdge const &other) const{
return std::tie(this->raw_edge) <= std::tie(other.raw_edge);
}bool InputPatternEdge::operator>=(InputPatternEdge const &other) const{
return std::tie(this->raw_edge) >= std::tie(other.raw_edge);
}}// namespace FlexFlow


///\cond
namespace std{size_t hash<FlexFlow::InputPatternEdge>::operator()(::FlexFlow::InputPatternEdge const &x)const{size_t result = 0;
result ^= std::hash<::FlexFlow::KwargDataflowInputEdge<int, ::FlexFlow::TensorSlotName>>{}(x.raw_edge) + 0x9e3779b9 + (result << 6) + (result >> 2);return result;
}}// namespace std

///\endcond

namespace nlohmann{void adl_serializer<::FlexFlow::InputPatternEdge>::to_json(json &j, ::FlexFlow::InputPatternEdge const &v) {j["__type"] = "InputPatternEdge";
j["raw_edge"] = v.raw_edge;
}}// namespace nlohmann

namespace FlexFlow{std::string InputPatternEdge::debug_to_string() const { return fmt::to_string(*this); }void InputPatternEdge::debug_print() const { std::cout << this->debug_to_string() << std::endl; }std::string format_as(InputPatternEdge const &x){::nlohmann::json j = x;
return j.dump();
}std::ostream &operator<<(std::ostream &s, InputPatternEdge const &x) {return s << fmt::to_string(x);}}// namespace FlexFlow
