// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/substitutions/include/substitutions/unlabelled/match_additional_criterion.dtg.toml
/* proj-data
{
  "generated_from": "4c019613fc0a235ad150dd936cf08ba8"
}
*/

#include "substitutions/unlabelled/match_additional_criterion.dtg.h"


namespace FlexFlow{MatchAdditionalCriterion::MatchAdditionalCriterion(std::function<bool(::FlexFlow::PatternNode const &, ::FlexFlow::Node const &)> const &node_criterion, std::function<bool(::FlexFlow::PatternValue const &, ::FlexFlow::OpenKwargDataflowValue<int, ::FlexFlow::TensorSlotName> const &)> const &value_criterion) : node_criterion(node_criterion), value_criterion(value_criterion){}
}// namespace FlexFlow
