// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/substitutions/include/substitutions/unlabelled/pattern_edge.dtg.toml
/* proj-data
{
  "generated_from": "5b6d24df3d4aa0a2d4934027de06908a"
}
*/

#include "substitutions/unlabelled/pattern_edge.dtg.h"

#include <sstream>

namespace FlexFlow{PatternEdge::PatternEdge(::FlexFlow::InputPatternEdge const &v) : raw_variant(v) { }
PatternEdge::PatternEdge(::FlexFlow::StandardPatternEdge const &v) : raw_variant(v) { }bool PatternEdge::operator==(PatternEdge const &other) const{return this->raw_variant == other.raw_variant;}
bool PatternEdge::operator!=(PatternEdge const &other) const{return this->raw_variant != other.raw_variant;}
bool PatternEdge::operator<(PatternEdge const &other) const{return this->raw_variant < other.raw_variant;}
bool PatternEdge::operator>(PatternEdge const &other) const{return this->raw_variant > other.raw_variant;}
bool PatternEdge::operator<=(PatternEdge const &other) const{return this->raw_variant <= other.raw_variant;}
bool PatternEdge::operator>=(PatternEdge const &other) const{return this->raw_variant >= other.raw_variant;}
}// namespace FlexFlow

///\cond
namespace std{size_t hash<::FlexFlow::PatternEdge>::operator()(::FlexFlow::PatternEdge const &x) const{return std::hash<std::variant<::FlexFlow::InputPatternEdge, ::FlexFlow::StandardPatternEdge>>{}(x.raw_variant);}
}// namespace std

///\endcond
namespace nlohmann{void adl_serializer<::FlexFlow::PatternEdge>::to_json(json &j, ::FlexFlow::PatternEdge const &x){j["__type"] = "PatternEdge";
switch (x.index()){case 0:{j["type"] = "::FlexFlow::InputPatternEdge";
j["value"] = x.template get<::FlexFlow::InputPatternEdge>();
break;
}case 1:{j["type"] = "::FlexFlow::StandardPatternEdge";
j["value"] = x.template get<::FlexFlow::StandardPatternEdge>();
break;
}default:{throw std::runtime_error(fmt::format("Unknown index {} for type PatternEdge", x.index()));
}}}
}// namespace nlohmann
namespace FlexFlow{std::string PatternEdge::debug_to_string() const{return fmt::to_string(*this);}
void PatternEdge::debug_print() const{std::cout << this->debug_to_string() << std::endl;}
std::string format_as(::FlexFlow::PatternEdge const &x){::nlohmann::json j = x;
return j.dump();
}
std::ostream & operator<<(std::ostream &s, ::FlexFlow::PatternEdge const &x){return s << fmt::to_string(x);
}
}// namespace FlexFlow
