// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/substitutions/include/substitutions/unlabelled/pattern_input.dtg.toml
/* proj-data
{
  "generated_from": "6ae307450afbe61e6354b49b946358bd"
}
*/

#include "substitutions/unlabelled/pattern_input.dtg.h"

#include <sstream>

namespace FlexFlow{PatternInput::PatternInput(::FlexFlow::KwargDataflowGraphInput<int> const &raw_dataflow_graph_input) : raw_dataflow_graph_input(raw_dataflow_graph_input){}
bool PatternInput::operator==(PatternInput const &other) const{
return std::tie(this->raw_dataflow_graph_input) == std::tie(other.raw_dataflow_graph_input);
}bool PatternInput::operator!=(PatternInput const &other) const{
return std::tie(this->raw_dataflow_graph_input) != std::tie(other.raw_dataflow_graph_input);
}bool PatternInput::operator<(PatternInput const &other) const{
return std::tie(this->raw_dataflow_graph_input) < std::tie(other.raw_dataflow_graph_input);
}bool PatternInput::operator>(PatternInput const &other) const{
return std::tie(this->raw_dataflow_graph_input) > std::tie(other.raw_dataflow_graph_input);
}bool PatternInput::operator<=(PatternInput const &other) const{
return std::tie(this->raw_dataflow_graph_input) <= std::tie(other.raw_dataflow_graph_input);
}bool PatternInput::operator>=(PatternInput const &other) const{
return std::tie(this->raw_dataflow_graph_input) >= std::tie(other.raw_dataflow_graph_input);
}}// namespace FlexFlow


///\cond
namespace std{size_t hash<FlexFlow::PatternInput>::operator()(::FlexFlow::PatternInput const &x)const{size_t result = 0;
result ^= std::hash<::FlexFlow::KwargDataflowGraphInput<int>>{}(x.raw_dataflow_graph_input) + 0x9e3779b9 + (result << 6) + (result >> 2);return result;
}}// namespace std

///\endcond

namespace nlohmann{void adl_serializer<::FlexFlow::PatternInput>::to_json(json &j, ::FlexFlow::PatternInput const &v) {j["__type"] = "PatternInput";
j["raw_dataflow_graph_input"] = v.raw_dataflow_graph_input;
}}// namespace nlohmann

namespace FlexFlow{std::string PatternInput::debug_to_string() const { return fmt::to_string(*this); }void PatternInput::debug_print() const { std::cout << this->debug_to_string() << std::endl; }std::string format_as(PatternInput const &x){::nlohmann::json j = x;
return j.dump();
}std::ostream &operator<<(std::ostream &s, PatternInput const &x) {return s << fmt::to_string(x);}}// namespace FlexFlow
