// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/substitutions/include/substitutions/unlabelled/unlabelled_graph_pattern.dtg.toml
/* proj-data
{
  "generated_from": "bfa7208d5c9b69181abd7f2750776858"
}
*/

#include "substitutions/unlabelled/unlabelled_graph_pattern.dtg.h"


namespace FlexFlow{UnlabelledGraphPattern::UnlabelledGraphPattern(::FlexFlow::OpenKwargDataflowGraphView<int, ::FlexFlow::TensorSlotName> const &raw_graph) : raw_graph(raw_graph){}
}// namespace FlexFlow
