// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/compiler/include/compiler/series_parallel/pcg/pcg_binary_series_split.dtg.toml
/* proj-data
{
  "generated_from": "67a0e0525eedee9c7925aebddd6ac6c0"
}
*/

#include "compiler/series_parallel/pcg/pcg_binary_series_split.dtg.h"

#include <sstream>

namespace FlexFlow{PCGBinarySeriesSplit::PCGBinarySeriesSplit(::FlexFlow::PCGBinarySPDecomposition const &left_child, ::FlexFlow::PCGBinarySPDecomposition const &right_child) : left_child_ptr(std::make_shared<::FlexFlow::PCGBinarySPDecomposition>(left_child)), right_child_ptr(std::make_shared<::FlexFlow::PCGBinarySPDecomposition>(right_child)){}
::FlexFlow::PCGBinarySPDecomposition const & PCGBinarySeriesSplit::get_left_child() const{return *this->left_child_ptr;
}
::FlexFlow::PCGBinarySPDecomposition const & PCGBinarySeriesSplit::get_right_child() const{return *this->right_child_ptr;
}
bool PCGBinarySeriesSplit::operator==(PCGBinarySeriesSplit const &other) const{
return std::tie(this->get_left_child(), this->get_right_child()) == std::tie(other.get_left_child(), other.get_right_child());
}bool PCGBinarySeriesSplit::operator!=(PCGBinarySeriesSplit const &other) const{
return std::tie(this->get_left_child(), this->get_right_child()) != std::tie(other.get_left_child(), other.get_right_child());
}}// namespace FlexFlow


///\cond
namespace std{size_t hash<FlexFlow::PCGBinarySeriesSplit>::operator()(::FlexFlow::PCGBinarySeriesSplit const &x)const{size_t result = 0;
result ^= std::hash<::FlexFlow::PCGBinarySPDecomposition>{}(x.get_left_child()) + 0x9e3779b9 + (result << 6) + (result >> 2);result ^= std::hash<::FlexFlow::PCGBinarySPDecomposition>{}(x.get_right_child()) + 0x9e3779b9 + (result << 6) + (result >> 2);return result;
}}// namespace std

///\endcond

namespace nlohmann{void adl_serializer<::FlexFlow::PCGBinarySeriesSplit>::to_json(json &j, ::FlexFlow::PCGBinarySeriesSplit const &v) {j["__type"] = "PCGBinarySeriesSplit";
j["left_child"] = v.get_left_child();
j["right_child"] = v.get_right_child();
}}// namespace nlohmann

namespace FlexFlow{std::string PCGBinarySeriesSplit::debug_to_string() const { return fmt::to_string(*this); }void PCGBinarySeriesSplit::debug_print() const { std::cout << this->debug_to_string() << std::endl; }std::string format_as(PCGBinarySeriesSplit const &x){::nlohmann::json j = x;
return j.dump();
}std::ostream &operator<<(std::ostream &s, PCGBinarySeriesSplit const &x) {return s << fmt::to_string(x);}}// namespace FlexFlow
