// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/op-attrs/include/op-attrs/l2_regularizer_attrs.dtg.toml
/* proj-data
{
  "generated_from": "20aa66d902d205bc510c6d2f47796545"
}
*/

#include "op-attrs/l2_regularizer_attrs.dtg.h"

#include <sstream>

namespace FlexFlow{L2RegularizerAttrs::L2RegularizerAttrs(float const &lambda) : lambda(lambda){}
bool L2RegularizerAttrs::operator==(L2RegularizerAttrs const &other) const{
return std::tie(this->lambda) == std::tie(other.lambda);
}bool L2RegularizerAttrs::operator!=(L2RegularizerAttrs const &other) const{
return std::tie(this->lambda) != std::tie(other.lambda);
}bool L2RegularizerAttrs::operator<(L2RegularizerAttrs const &other) const{
return std::tie(this->lambda) < std::tie(other.lambda);
}bool L2RegularizerAttrs::operator>(L2RegularizerAttrs const &other) const{
return std::tie(this->lambda) > std::tie(other.lambda);
}bool L2RegularizerAttrs::operator<=(L2RegularizerAttrs const &other) const{
return std::tie(this->lambda) <= std::tie(other.lambda);
}bool L2RegularizerAttrs::operator>=(L2RegularizerAttrs const &other) const{
return std::tie(this->lambda) >= std::tie(other.lambda);
}}// namespace FlexFlow


///\cond
namespace std{size_t hash<FlexFlow::L2RegularizerAttrs>::operator()(::FlexFlow::L2RegularizerAttrs const &x)const{size_t result = 0;
result ^= std::hash<float>{}(x.lambda) + 0x9e3779b9 + (result << 6) + (result >> 2);return result;
}}// namespace std

///\endcond

namespace nlohmann{void adl_serializer<::FlexFlow::L2RegularizerAttrs>::to_json(json &j, ::FlexFlow::L2RegularizerAttrs const &v) {j["__type"] = "L2RegularizerAttrs";
j["lambda"] = v.lambda;
}}// namespace nlohmann

namespace nlohmann{::FlexFlow::L2RegularizerAttrs adl_serializer<::FlexFlow::L2RegularizerAttrs>::from_json(json const &j) {return ::FlexFlow::L2RegularizerAttrs{j.at("lambda").template get<float>()};}}// namespace nlohmann

namespace rc{Gen<::FlexFlow::L2RegularizerAttrs> Arbitrary<::FlexFlow::L2RegularizerAttrs>::arbitrary() {return gen::construct<::FlexFlow::L2RegularizerAttrs>(gen::arbitrary<float>());}}// namespace rc

namespace FlexFlow{std::string L2RegularizerAttrs::debug_to_string() const { return fmt::to_string(*this); }void L2RegularizerAttrs::debug_print() const { std::cout << this->debug_to_string() << std::endl; }std::string format_as(L2RegularizerAttrs const &x){::nlohmann::json j = x;
return j.dump();
}std::ostream &operator<<(std::ostream &s, L2RegularizerAttrs const &x) {return s << fmt::to_string(x);}}// namespace FlexFlow
