// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/op-attrs/include/op-attrs/operator_task_space_to_operator_task_space_mapping.dtg.toml
/* proj-data
{
  "generated_from": "4e7a58c8fb35ecbb0e757190db82cadf"
}
*/

#include "op-attrs/operator_task_space_to_operator_task_space_mapping.dtg.h"

#include <sstream>

namespace FlexFlow{OperatorTaskSpaceToOperatorTaskSpaceMapping::OperatorTaskSpaceToOperatorTaskSpaceMapping(::FlexFlow::DimDomainMapping<::FlexFlow::operator_task_space_dim_idx_t, ::FlexFlow::operator_task_space_dim_idx_t> const &raw_mapping) : raw_mapping(raw_mapping){}
bool OperatorTaskSpaceToOperatorTaskSpaceMapping::operator==(OperatorTaskSpaceToOperatorTaskSpaceMapping const &other) const{
return std::tie(this->raw_mapping) == std::tie(other.raw_mapping);
}bool OperatorTaskSpaceToOperatorTaskSpaceMapping::operator!=(OperatorTaskSpaceToOperatorTaskSpaceMapping const &other) const{
return std::tie(this->raw_mapping) != std::tie(other.raw_mapping);
}}// namespace FlexFlow


///\cond
namespace std{size_t hash<FlexFlow::OperatorTaskSpaceToOperatorTaskSpaceMapping>::operator()(::FlexFlow::OperatorTaskSpaceToOperatorTaskSpaceMapping const &x)const{size_t result = 0;
result ^= std::hash<::FlexFlow::DimDomainMapping<::FlexFlow::operator_task_space_dim_idx_t, ::FlexFlow::operator_task_space_dim_idx_t>>{}(x.raw_mapping) + 0x9e3779b9 + (result << 6) + (result >> 2);return result;
}}// namespace std

///\endcond

namespace nlohmann{void adl_serializer<::FlexFlow::OperatorTaskSpaceToOperatorTaskSpaceMapping>::to_json(json &j, ::FlexFlow::OperatorTaskSpaceToOperatorTaskSpaceMapping const &v) {j["__type"] = "OperatorTaskSpaceToOperatorTaskSpaceMapping";
j["raw_mapping"] = v.raw_mapping;
}}// namespace nlohmann

namespace FlexFlow{std::string OperatorTaskSpaceToOperatorTaskSpaceMapping::debug_to_string() const { return fmt::to_string(*this); }void OperatorTaskSpaceToOperatorTaskSpaceMapping::debug_print() const { std::cout << this->debug_to_string() << std::endl; }std::string format_as(OperatorTaskSpaceToOperatorTaskSpaceMapping const &x){::nlohmann::json j = x;
return j.dump();
}std::ostream &operator<<(std::ostream &s, OperatorTaskSpaceToOperatorTaskSpaceMapping const &x) {return s << fmt::to_string(x);}}// namespace FlexFlow
