// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/op-attrs/include/op-attrs/parallel_dim.dtg.toml
/* proj-data
{
  "generated_from": "f61fd857703ed037f40cb8cfd56d0815"
}
*/

#include "op-attrs/parallel_dim.dtg.h"

#include <sstream>

namespace FlexFlow{ParallelDim::ParallelDim(::FlexFlow::ShardParallelDim const &v) : raw_variant(v) { }
ParallelDim::ParallelDim(::FlexFlow::ReplicaParallelDim const &v) : raw_variant(v) { }bool ParallelDim::operator==(ParallelDim const &other) const{return this->raw_variant == other.raw_variant;}
bool ParallelDim::operator!=(ParallelDim const &other) const{return this->raw_variant != other.raw_variant;}
bool ParallelDim::operator<(ParallelDim const &other) const{return this->raw_variant < other.raw_variant;}
bool ParallelDim::operator>(ParallelDim const &other) const{return this->raw_variant > other.raw_variant;}
bool ParallelDim::operator<=(ParallelDim const &other) const{return this->raw_variant <= other.raw_variant;}
bool ParallelDim::operator>=(ParallelDim const &other) const{return this->raw_variant >= other.raw_variant;}
::FlexFlow::ShardParallelDim const & ParallelDim::require_shard_dim() const{bool holds_expected = std::holds_alternative<::FlexFlow::ShardParallelDim>(this->raw_variant);
ASSERT(holds_expected, "Expected ::FlexFlow::ShardParallelDim");
return std::get<::FlexFlow::ShardParallelDim>(this->raw_variant);
}
::FlexFlow::ShardParallelDim & ParallelDim::require_shard_dim(){bool holds_expected = std::holds_alternative<::FlexFlow::ShardParallelDim>(this->raw_variant);
ASSERT(holds_expected, "Expected ::FlexFlow::ShardParallelDim");
return std::get<::FlexFlow::ShardParallelDim>(this->raw_variant);
}
::FlexFlow::ReplicaParallelDim const & ParallelDim::require_replica_dim() const{bool holds_expected = std::holds_alternative<::FlexFlow::ReplicaParallelDim>(this->raw_variant);
ASSERT(holds_expected, "Expected ::FlexFlow::ReplicaParallelDim");
return std::get<::FlexFlow::ReplicaParallelDim>(this->raw_variant);
}
::FlexFlow::ReplicaParallelDim & ParallelDim::require_replica_dim(){bool holds_expected = std::holds_alternative<::FlexFlow::ReplicaParallelDim>(this->raw_variant);
ASSERT(holds_expected, "Expected ::FlexFlow::ReplicaParallelDim");
return std::get<::FlexFlow::ReplicaParallelDim>(this->raw_variant);
}
std::optional<::FlexFlow::ShardParallelDim> ParallelDim::try_require_shard_dim() const{if (this->is_shard_dim()) {return this->require_shard_dim();
}else {return std::nullopt;
}}
std::optional<::FlexFlow::ReplicaParallelDim> ParallelDim::try_require_replica_dim() const{if (this->is_replica_dim()) {return this->require_replica_dim();
}else {return std::nullopt;
}}
bool ParallelDim::is_shard_dim() const{return std::holds_alternative<::FlexFlow::ShardParallelDim>(this->raw_variant);
}
bool ParallelDim::is_replica_dim() const{return std::holds_alternative<::FlexFlow::ReplicaParallelDim>(this->raw_variant);
}
}// namespace FlexFlow

///\cond
namespace std{size_t hash<::FlexFlow::ParallelDim>::operator()(::FlexFlow::ParallelDim const &x) const{return std::hash<std::variant<::FlexFlow::ShardParallelDim, ::FlexFlow::ReplicaParallelDim>>{}(x.raw_variant);}
}// namespace std

///\endcond
namespace nlohmann{void adl_serializer<::FlexFlow::ParallelDim>::to_json(json &j, ::FlexFlow::ParallelDim const &x){j["__type"] = "ParallelDim";
switch (x.index()){case 0:{j["type"] = "shard_dim";
j["value"] = x.template get<::FlexFlow::ShardParallelDim>();
break;
}case 1:{j["type"] = "replica_dim";
j["value"] = x.template get<::FlexFlow::ReplicaParallelDim>();
break;
}default:{throw std::runtime_error(fmt::format("Unknown index {} for type ParallelDim", x.index()));
}}}
}// namespace nlohmann
namespace nlohmann{::FlexFlow::ParallelDim adl_serializer<::FlexFlow::ParallelDim>::from_json(json const &j){std::string key = j.at("type").template get<std::string>();
if (key == "shard_dim"){return ::FlexFlow::ParallelDim{j.at("value").template get<::FlexFlow::ShardParallelDim>()};
} else if (key == "replica_dim"){return ::FlexFlow::ParallelDim{j.at("value").template get<::FlexFlow::ReplicaParallelDim>()};
} else {throw std::runtime_error(fmt::format("Unknown type key {}", key));
}}
}// namespace nlohmann
namespace rc{Gen<::FlexFlow::ParallelDim> Arbitrary<::FlexFlow::ParallelDim>::arbitrary(){return gen::oneOf(gen::construct<::FlexFlow::ParallelDim>(gen::arbitrary<::FlexFlow::ShardParallelDim>()), gen::construct<::FlexFlow::ParallelDim>(gen::arbitrary<::FlexFlow::ReplicaParallelDim>()));
}
}// namespace rc
namespace FlexFlow{std::string ParallelDim::debug_to_string() const{return fmt::to_string(*this);}
void ParallelDim::debug_print() const{std::cout << this->debug_to_string() << std::endl;}
std::string format_as(::FlexFlow::ParallelDim const &x){::nlohmann::json j = x;
return j.dump();
}
std::ostream & operator<<(std::ostream &s, ::FlexFlow::ParallelDim const &x){return s << fmt::to_string(x);
}
}// namespace FlexFlow
