// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/op-attrs/include/op-attrs/regularizer_attrs.dtg.toml
/* proj-data
{
  "generated_from": "2686c95fe11be5245681529cc18a1f43"
}
*/

#include "op-attrs/regularizer_attrs.dtg.h"

#include <sstream>

namespace FlexFlow{RegularizerAttrs::RegularizerAttrs(::FlexFlow::L1RegularizerAttrs const &v) : raw_variant(v) { }
RegularizerAttrs::RegularizerAttrs(::FlexFlow::L2RegularizerAttrs const &v) : raw_variant(v) { }bool RegularizerAttrs::operator==(RegularizerAttrs const &other) const{return this->raw_variant == other.raw_variant;}
bool RegularizerAttrs::operator!=(RegularizerAttrs const &other) const{return this->raw_variant != other.raw_variant;}
bool RegularizerAttrs::operator<(RegularizerAttrs const &other) const{return this->raw_variant < other.raw_variant;}
bool RegularizerAttrs::operator>(RegularizerAttrs const &other) const{return this->raw_variant > other.raw_variant;}
bool RegularizerAttrs::operator<=(RegularizerAttrs const &other) const{return this->raw_variant <= other.raw_variant;}
bool RegularizerAttrs::operator>=(RegularizerAttrs const &other) const{return this->raw_variant >= other.raw_variant;}
::FlexFlow::L1RegularizerAttrs const & RegularizerAttrs::require_l1() const{bool holds_expected = std::holds_alternative<::FlexFlow::L1RegularizerAttrs>(this->raw_variant);
ASSERT(holds_expected, "Expected ::FlexFlow::L1RegularizerAttrs");
return std::get<::FlexFlow::L1RegularizerAttrs>(this->raw_variant);
}
::FlexFlow::L1RegularizerAttrs & RegularizerAttrs::require_l1(){bool holds_expected = std::holds_alternative<::FlexFlow::L1RegularizerAttrs>(this->raw_variant);
ASSERT(holds_expected, "Expected ::FlexFlow::L1RegularizerAttrs");
return std::get<::FlexFlow::L1RegularizerAttrs>(this->raw_variant);
}
::FlexFlow::L2RegularizerAttrs const & RegularizerAttrs::require_l2() const{bool holds_expected = std::holds_alternative<::FlexFlow::L2RegularizerAttrs>(this->raw_variant);
ASSERT(holds_expected, "Expected ::FlexFlow::L2RegularizerAttrs");
return std::get<::FlexFlow::L2RegularizerAttrs>(this->raw_variant);
}
::FlexFlow::L2RegularizerAttrs & RegularizerAttrs::require_l2(){bool holds_expected = std::holds_alternative<::FlexFlow::L2RegularizerAttrs>(this->raw_variant);
ASSERT(holds_expected, "Expected ::FlexFlow::L2RegularizerAttrs");
return std::get<::FlexFlow::L2RegularizerAttrs>(this->raw_variant);
}
std::optional<::FlexFlow::L1RegularizerAttrs> RegularizerAttrs::try_require_l1() const{if (this->is_l1()) {return this->require_l1();
}else {return std::nullopt;
}}
std::optional<::FlexFlow::L2RegularizerAttrs> RegularizerAttrs::try_require_l2() const{if (this->is_l2()) {return this->require_l2();
}else {return std::nullopt;
}}
bool RegularizerAttrs::is_l1() const{return std::holds_alternative<::FlexFlow::L1RegularizerAttrs>(this->raw_variant);
}
bool RegularizerAttrs::is_l2() const{return std::holds_alternative<::FlexFlow::L2RegularizerAttrs>(this->raw_variant);
}
}// namespace FlexFlow

///\cond
namespace std{size_t hash<::FlexFlow::RegularizerAttrs>::operator()(::FlexFlow::RegularizerAttrs const &x) const{return std::hash<std::variant<::FlexFlow::L1RegularizerAttrs, ::FlexFlow::L2RegularizerAttrs>>{}(x.raw_variant);}
}// namespace std

///\endcond
namespace nlohmann{void adl_serializer<::FlexFlow::RegularizerAttrs>::to_json(json &j, ::FlexFlow::RegularizerAttrs const &x){j["__type"] = "RegularizerAttrs";
switch (x.index()){case 0:{j["type"] = "l1";
j["value"] = x.template get<::FlexFlow::L1RegularizerAttrs>();
break;
}case 1:{j["type"] = "l2";
j["value"] = x.template get<::FlexFlow::L2RegularizerAttrs>();
break;
}default:{throw std::runtime_error(fmt::format("Unknown index {} for type RegularizerAttrs", x.index()));
}}}
}// namespace nlohmann
namespace nlohmann{::FlexFlow::RegularizerAttrs adl_serializer<::FlexFlow::RegularizerAttrs>::from_json(json const &j){std::string key = j.at("type").template get<std::string>();
if (key == "l1"){return ::FlexFlow::RegularizerAttrs{j.at("value").template get<::FlexFlow::L1RegularizerAttrs>()};
} else if (key == "l2"){return ::FlexFlow::RegularizerAttrs{j.at("value").template get<::FlexFlow::L2RegularizerAttrs>()};
} else {throw std::runtime_error(fmt::format("Unknown type key {}", key));
}}
}// namespace nlohmann
namespace rc{Gen<::FlexFlow::RegularizerAttrs> Arbitrary<::FlexFlow::RegularizerAttrs>::arbitrary(){return gen::oneOf(gen::construct<::FlexFlow::RegularizerAttrs>(gen::arbitrary<::FlexFlow::L1RegularizerAttrs>()), gen::construct<::FlexFlow::RegularizerAttrs>(gen::arbitrary<::FlexFlow::L2RegularizerAttrs>()));
}
}// namespace rc
namespace FlexFlow{std::string RegularizerAttrs::debug_to_string() const{return fmt::to_string(*this);}
void RegularizerAttrs::debug_print() const{std::cout << this->debug_to_string() << std::endl;}
std::string format_as(::FlexFlow::RegularizerAttrs const &x){::nlohmann::json j = x;
return j.dump();
}
std::ostream & operator<<(std::ostream &s, ::FlexFlow::RegularizerAttrs const &x){return s << fmt::to_string(x);
}
}// namespace FlexFlow
