// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/op-attrs/include/op-attrs/shard_parallel_dim.dtg.toml
/* proj-data
{
  "generated_from": "edb64dad232376991880d1418f7d00af"
}
*/

#include "op-attrs/shard_parallel_dim.dtg.h"

#include <sstream>

namespace FlexFlow{ShardParallelDim::ShardParallelDim(::FlexFlow::positive_int const &size, ::FlexFlow::positive_int const &degree) : size(size), degree(degree){}
bool ShardParallelDim::operator==(ShardParallelDim const &other) const{
return std::tie(this->size, this->degree) == std::tie(other.size, other.degree);
}bool ShardParallelDim::operator!=(ShardParallelDim const &other) const{
return std::tie(this->size, this->degree) != std::tie(other.size, other.degree);
}bool ShardParallelDim::operator<(ShardParallelDim const &other) const{
return std::tie(this->size, this->degree) < std::tie(other.size, other.degree);
}bool ShardParallelDim::operator>(ShardParallelDim const &other) const{
return std::tie(this->size, this->degree) > std::tie(other.size, other.degree);
}bool ShardParallelDim::operator<=(ShardParallelDim const &other) const{
return std::tie(this->size, this->degree) <= std::tie(other.size, other.degree);
}bool ShardParallelDim::operator>=(ShardParallelDim const &other) const{
return std::tie(this->size, this->degree) >= std::tie(other.size, other.degree);
}}// namespace FlexFlow


///\cond
namespace std{size_t hash<FlexFlow::ShardParallelDim>::operator()(::FlexFlow::ShardParallelDim const &x)const{size_t result = 0;
result ^= std::hash<::FlexFlow::positive_int>{}(x.size) + 0x9e3779b9 + (result << 6) + (result >> 2);result ^= std::hash<::FlexFlow::positive_int>{}(x.degree) + 0x9e3779b9 + (result << 6) + (result >> 2);return result;
}}// namespace std

///\endcond

namespace nlohmann{void adl_serializer<::FlexFlow::ShardParallelDim>::to_json(json &j, ::FlexFlow::ShardParallelDim const &v) {j["__type"] = "ShardParallelDim";
j["size"] = v.size;
j["degree"] = v.degree;
}}// namespace nlohmann

namespace nlohmann{::FlexFlow::ShardParallelDim adl_serializer<::FlexFlow::ShardParallelDim>::from_json(json const &j) {return ::FlexFlow::ShardParallelDim{j.at("size").template get<::FlexFlow::positive_int>(), j.at("degree").template get<::FlexFlow::positive_int>()};}}// namespace nlohmann

namespace rc{Gen<::FlexFlow::ShardParallelDim> Arbitrary<::FlexFlow::ShardParallelDim>::arbitrary() {return gen::construct<::FlexFlow::ShardParallelDim>(gen::arbitrary<::FlexFlow::positive_int>(), gen::arbitrary<::FlexFlow::positive_int>());}}// namespace rc

namespace FlexFlow{std::string ShardParallelDim::debug_to_string() const { return fmt::to_string(*this); }void ShardParallelDim::debug_print() const { std::cout << this->debug_to_string() << std::endl; }std::string format_as(ShardParallelDim const &x){::nlohmann::json j = x;
return j.dump();
}std::ostream &operator<<(std::ostream &s, ShardParallelDim const &x) {return s << fmt::to_string(x);}}// namespace FlexFlow
