// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/op-attrs/include/op-attrs/tensor_slot_name.dtg.toml
/* proj-data
{
  "generated_from": "ac4940209ebccac0ec0cbe1fff4f3f3b"
}
*/

#include "op-attrs/tensor_slot_name.dtg.h"

#include <stdexcept>
#include <sstream>


///\cond
namespace std{size_t hash<FlexFlow::TensorSlotName>::operator()(FlexFlow::TensorSlotName x) const{return std::hash<int>{}(static_cast<int>(x));
}}// namespace std

///\endcond
namespace FlexFlow{std::string format_as(TensorSlotName x){::nlohmann::json j = x;
return j.dump();
}std::ostream &operator<<(std::ostream &s, TensorSlotName x){return s << fmt::to_string(x);}}// namespace FlexFlow
namespace FlexFlow{void to_json(::nlohmann::json &j, TensorSlotName x){switch (x){case TensorSlotName::INPUT:
j = "INPUT";
break;
case TensorSlotName::OUTPUT:
j = "OUTPUT";
break;
case TensorSlotName::FILTER:
j = "FILTER";
break;
case TensorSlotName::BIAS:
j = "BIAS";
break;
case TensorSlotName::INPUT_BIAS:
j = "INPUT_BIAS";
break;
case TensorSlotName::OUTPUT_BIAS:
j = "OUTPUT_BIAS";
break;
case TensorSlotName::LHS_INPUT:
j = "LHS_INPUT";
break;
case TensorSlotName::RHS_INPUT:
j = "RHS_INPUT";
break;
case TensorSlotName::INDEX:
j = "INDEX";
break;
case TensorSlotName::GAMMA:
j = "GAMMA";
break;
case TensorSlotName::BETA:
j = "BETA";
break;
case TensorSlotName::WEIGHT:
j = "WEIGHT";
break;
case TensorSlotName::QUERY:
j = "QUERY";
break;
case TensorSlotName::KEY:
j = "KEY";
break;
case TensorSlotName::VALUE:
j = "VALUE";
break;
case TensorSlotName::LOGIT:
j = "LOGIT";
break;
case TensorSlotName::INPUT_00:
j = "INPUT_00";
break;
case TensorSlotName::INPUT_01:
j = "INPUT_01";
break;
case TensorSlotName::INPUT_02:
j = "INPUT_02";
break;
case TensorSlotName::INPUT_03:
j = "INPUT_03";
break;
case TensorSlotName::INPUT_04:
j = "INPUT_04";
break;
case TensorSlotName::INPUT_05:
j = "INPUT_05";
break;
case TensorSlotName::INPUT_06:
j = "INPUT_06";
break;
case TensorSlotName::INPUT_07:
j = "INPUT_07";
break;
case TensorSlotName::INPUT_08:
j = "INPUT_08";
break;
case TensorSlotName::INPUT_09:
j = "INPUT_09";
break;
case TensorSlotName::INPUT_10:
j = "INPUT_10";
break;
case TensorSlotName::INPUT_11:
j = "INPUT_11";
break;
case TensorSlotName::INPUT_12:
j = "INPUT_12";
break;
case TensorSlotName::INPUT_13:
j = "INPUT_13";
break;
case TensorSlotName::INPUT_14:
j = "INPUT_14";
break;
case TensorSlotName::INPUT_15:
j = "INPUT_15";
break;
case TensorSlotName::OUTPUT_00:
j = "OUTPUT_00";
break;
case TensorSlotName::OUTPUT_01:
j = "OUTPUT_01";
break;
case TensorSlotName::OUTPUT_02:
j = "OUTPUT_02";
break;
case TensorSlotName::OUTPUT_03:
j = "OUTPUT_03";
break;
case TensorSlotName::OUTPUT_04:
j = "OUTPUT_04";
break;
case TensorSlotName::OUTPUT_05:
j = "OUTPUT_05";
break;
case TensorSlotName::SCALE:
j = "SCALE";
break;
default:
std::ostringstream oss;
oss << "Unknown TensorSlotName value " << static_cast<int>(x);
throw std::runtime_error(oss.str());
}}}// namespace FlexFlow
namespace FlexFlow{void from_json(::nlohmann::json const &j, TensorSlotName &x){std::string as_str = j.get<std::string>();
if (as_str == "INPUT"){x = TensorSlotName::INPUT;
}else if (as_str == "OUTPUT"){x = TensorSlotName::OUTPUT;
}else if (as_str == "FILTER"){x = TensorSlotName::FILTER;
}else if (as_str == "BIAS"){x = TensorSlotName::BIAS;
}else if (as_str == "INPUT_BIAS"){x = TensorSlotName::INPUT_BIAS;
}else if (as_str == "OUTPUT_BIAS"){x = TensorSlotName::OUTPUT_BIAS;
}else if (as_str == "LHS_INPUT"){x = TensorSlotName::LHS_INPUT;
}else if (as_str == "RHS_INPUT"){x = TensorSlotName::RHS_INPUT;
}else if (as_str == "INDEX"){x = TensorSlotName::INDEX;
}else if (as_str == "GAMMA"){x = TensorSlotName::GAMMA;
}else if (as_str == "BETA"){x = TensorSlotName::BETA;
}else if (as_str == "WEIGHT"){x = TensorSlotName::WEIGHT;
}else if (as_str == "QUERY"){x = TensorSlotName::QUERY;
}else if (as_str == "KEY"){x = TensorSlotName::KEY;
}else if (as_str == "VALUE"){x = TensorSlotName::VALUE;
}else if (as_str == "LOGIT"){x = TensorSlotName::LOGIT;
}else if (as_str == "INPUT_00"){x = TensorSlotName::INPUT_00;
}else if (as_str == "INPUT_01"){x = TensorSlotName::INPUT_01;
}else if (as_str == "INPUT_02"){x = TensorSlotName::INPUT_02;
}else if (as_str == "INPUT_03"){x = TensorSlotName::INPUT_03;
}else if (as_str == "INPUT_04"){x = TensorSlotName::INPUT_04;
}else if (as_str == "INPUT_05"){x = TensorSlotName::INPUT_05;
}else if (as_str == "INPUT_06"){x = TensorSlotName::INPUT_06;
}else if (as_str == "INPUT_07"){x = TensorSlotName::INPUT_07;
}else if (as_str == "INPUT_08"){x = TensorSlotName::INPUT_08;
}else if (as_str == "INPUT_09"){x = TensorSlotName::INPUT_09;
}else if (as_str == "INPUT_10"){x = TensorSlotName::INPUT_10;
}else if (as_str == "INPUT_11"){x = TensorSlotName::INPUT_11;
}else if (as_str == "INPUT_12"){x = TensorSlotName::INPUT_12;
}else if (as_str == "INPUT_13"){x = TensorSlotName::INPUT_13;
}else if (as_str == "INPUT_14"){x = TensorSlotName::INPUT_14;
}else if (as_str == "INPUT_15"){x = TensorSlotName::INPUT_15;
}else if (as_str == "OUTPUT_00"){x = TensorSlotName::OUTPUT_00;
}else if (as_str == "OUTPUT_01"){x = TensorSlotName::OUTPUT_01;
}else if (as_str == "OUTPUT_02"){x = TensorSlotName::OUTPUT_02;
}else if (as_str == "OUTPUT_03"){x = TensorSlotName::OUTPUT_03;
}else if (as_str == "OUTPUT_04"){x = TensorSlotName::OUTPUT_04;
}else if (as_str == "OUTPUT_05"){x = TensorSlotName::OUTPUT_05;
}else if (as_str == "SCALE"){x = TensorSlotName::SCALE;
}else {std::ostringstream oss;
oss << "Unknown TensorSlotName value " << as_str;
throw std::runtime_error(oss.str());
}}}// namespace FlexFlow
namespace rc{Gen<FlexFlow::TensorSlotName> Arbitrary<FlexFlow::TensorSlotName>::arbitrary(){return gen::element<FlexFlow::TensorSlotName>(FlexFlow::TensorSlotName::INPUT, FlexFlow::TensorSlotName::OUTPUT, FlexFlow::TensorSlotName::FILTER, FlexFlow::TensorSlotName::BIAS, FlexFlow::TensorSlotName::INPUT_BIAS, FlexFlow::TensorSlotName::OUTPUT_BIAS, FlexFlow::TensorSlotName::LHS_INPUT, FlexFlow::TensorSlotName::RHS_INPUT, FlexFlow::TensorSlotName::INDEX, FlexFlow::TensorSlotName::GAMMA, FlexFlow::TensorSlotName::BETA, FlexFlow::TensorSlotName::WEIGHT, FlexFlow::TensorSlotName::QUERY, FlexFlow::TensorSlotName::KEY, FlexFlow::TensorSlotName::VALUE, FlexFlow::TensorSlotName::LOGIT, FlexFlow::TensorSlotName::INPUT_00, FlexFlow::TensorSlotName::INPUT_01, FlexFlow::TensorSlotName::INPUT_02, FlexFlow::TensorSlotName::INPUT_03, FlexFlow::TensorSlotName::INPUT_04, FlexFlow::TensorSlotName::INPUT_05, FlexFlow::TensorSlotName::INPUT_06, FlexFlow::TensorSlotName::INPUT_07, FlexFlow::TensorSlotName::INPUT_08, FlexFlow::TensorSlotName::INPUT_09, FlexFlow::TensorSlotName::INPUT_10, FlexFlow::TensorSlotName::INPUT_11, FlexFlow::TensorSlotName::INPUT_12, FlexFlow::TensorSlotName::INPUT_13, FlexFlow::TensorSlotName::INPUT_14, FlexFlow::TensorSlotName::INPUT_15, FlexFlow::TensorSlotName::OUTPUT_00, FlexFlow::TensorSlotName::OUTPUT_01, FlexFlow::TensorSlotName::OUTPUT_02, FlexFlow::TensorSlotName::OUTPUT_03, FlexFlow::TensorSlotName::OUTPUT_04, FlexFlow::TensorSlotName::OUTPUT_05, FlexFlow::TensorSlotName::SCALE);}}// namespace rc
