// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/op-attrs/include/op-attrs/tensor_role.dtg.toml
/* proj-data
{
  "generated_from": "095468592844b2b52082c4817b6d8ee0"
}
*/

#include "op-attrs/tensor_role.dtg.h"

#include <stdexcept>
#include <sstream>


///\cond
namespace std{size_t hash<FlexFlow::TensorRole>::operator()(FlexFlow::TensorRole x) const{return std::hash<int>{}(static_cast<int>(x));
}}// namespace std

///\endcond
namespace FlexFlow{std::string format_as(TensorRole x){::nlohmann::json j = x;
return j.dump();
}std::ostream &operator<<(std::ostream &s, TensorRole x){return s << fmt::to_string(x);}}// namespace FlexFlow
namespace FlexFlow{void to_json(::nlohmann::json &j, TensorRole x){switch (x){case TensorRole::INPUT:
j = "INPUT";
break;
case TensorRole::WEIGHT:
j = "WEIGHT";
break;
case TensorRole::OUTPUT:
j = "OUTPUT";
break;
default:
std::ostringstream oss;
oss << "Unknown TensorRole value " << static_cast<int>(x);
throw std::runtime_error(oss.str());
}}}// namespace FlexFlow
namespace FlexFlow{void from_json(::nlohmann::json const &j, TensorRole &x){std::string as_str = j.get<std::string>();
if (as_str == "INPUT"){x = TensorRole::INPUT;
}else if (as_str == "WEIGHT"){x = TensorRole::WEIGHT;
}else if (as_str == "OUTPUT"){x = TensorRole::OUTPUT;
}else {std::ostringstream oss;
oss << "Unknown TensorRole value " << as_str;
throw std::runtime_error(oss.str());
}}}// namespace FlexFlow
namespace rc{Gen<FlexFlow::TensorRole> Arbitrary<FlexFlow::TensorRole>::arbitrary(){return gen::element<FlexFlow::TensorRole>(FlexFlow::TensorRole::INPUT, FlexFlow::TensorRole::WEIGHT, FlexFlow::TensorRole::OUTPUT);}}// namespace rc
