// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/op-attrs/include/op-attrs/ops/loss_functions/loss_function.dtg.toml
/* proj-data
{
  "generated_from": "5b4afe076cd39dfbea1dc108637947f0"
}
*/

#include "op-attrs/ops/loss_functions/loss_function.dtg.h"

#include <stdexcept>
#include <sstream>


///\cond
namespace std{size_t hash<FlexFlow::LossFunction>::operator()(FlexFlow::LossFunction x) const{return std::hash<int>{}(static_cast<int>(x));
}}// namespace std

///\endcond
namespace FlexFlow{std::string format_as(LossFunction x){::nlohmann::json j = x;
return j.dump();
}std::ostream &operator<<(std::ostream &s, LossFunction x){return s << fmt::to_string(x);}}// namespace FlexFlow
namespace FlexFlow{void to_json(::nlohmann::json &j, LossFunction x){switch (x){case LossFunction::CATEGORICAL_CROSSENTROPY:
j = "CATEGORICAL_CROSSENTROPY";
break;
case LossFunction::SPARSE_CATEGORICAL_CROSSENTROPY:
j = "SPARSE_CATEGORICAL_CROSSENTROPY";
break;
case LossFunction::MEAN_SQUARED_ERROR_AVG_REDUCE:
j = "MEAN_SQUARED_ERROR_AVG_REDUCE";
break;
case LossFunction::MEAN_SQUARED_ERROR_SUM_REDUCE:
j = "MEAN_SQUARED_ERROR_SUM_REDUCE";
break;
case LossFunction::IDENTITY:
j = "IDENTITY";
break;
default:
std::ostringstream oss;
oss << "Unknown LossFunction value " << static_cast<int>(x);
throw std::runtime_error(oss.str());
}}}// namespace FlexFlow
namespace FlexFlow{void from_json(::nlohmann::json const &j, LossFunction &x){std::string as_str = j.get<std::string>();
if (as_str == "CATEGORICAL_CROSSENTROPY"){x = LossFunction::CATEGORICAL_CROSSENTROPY;
}else if (as_str == "SPARSE_CATEGORICAL_CROSSENTROPY"){x = LossFunction::SPARSE_CATEGORICAL_CROSSENTROPY;
}else if (as_str == "MEAN_SQUARED_ERROR_AVG_REDUCE"){x = LossFunction::MEAN_SQUARED_ERROR_AVG_REDUCE;
}else if (as_str == "MEAN_SQUARED_ERROR_SUM_REDUCE"){x = LossFunction::MEAN_SQUARED_ERROR_SUM_REDUCE;
}else if (as_str == "IDENTITY"){x = LossFunction::IDENTITY;
}else {std::ostringstream oss;
oss << "Unknown LossFunction value " << as_str;
throw std::runtime_error(oss.str());
}}}// namespace FlexFlow
namespace rc{Gen<FlexFlow::LossFunction> Arbitrary<FlexFlow::LossFunction>::arbitrary(){return gen::element<FlexFlow::LossFunction>(FlexFlow::LossFunction::CATEGORICAL_CROSSENTROPY, FlexFlow::LossFunction::SPARSE_CATEGORICAL_CROSSENTROPY, FlexFlow::LossFunction::MEAN_SQUARED_ERROR_AVG_REDUCE, FlexFlow::LossFunction::MEAN_SQUARED_ERROR_SUM_REDUCE, FlexFlow::LossFunction::IDENTITY);}}// namespace rc
