// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/compiler/include/compiler/machine_mapping/abstracted_tensor_set_movement/abstracted_device.dtg.toml
/* proj-data
{
  "generated_from": "cfae12613214f1df2142aca1867f4397"
}
*/

#ifndef _FLEXFLOW_LIB_COMPILER_INCLUDE_COMPILER_MACHINE_MAPPING_ABSTRACTED_TENSOR_SET_MOVEMENT_ABSTRACTED_DEVICE_DTG_H
#define _FLEXFLOW_LIB_COMPILER_INCLUDE_COMPILER_MACHINE_MAPPING_ABSTRACTED_TENSOR_SET_MOVEMENT_ABSTRACTED_DEVICE_DTG_H

#include <tuple>
#include <iostream>
#include "op-attrs/task_space_coordinate.dtg.h"
#include "utils/full_binary_tree/binary_tree_path.dtg.h"
#include <ostream>
#include <fmt/format.h>
#include <nlohmann/json.hpp>
#include <functional>


namespace FlexFlow{struct AbstractedDevice{AbstractedDevice() = delete;
explicit AbstractedDevice(::FlexFlow::BinaryTreePath const &operator_tree_path, ::FlexFlow::TaskSpaceCoordinate const &task_space_coordinate);

bool operator==(AbstractedDevice const &) const;bool operator!=(AbstractedDevice const &) const;
bool operator<(AbstractedDevice const &) const;bool operator>(AbstractedDevice const &) const;bool operator<=(AbstractedDevice const &) const;bool operator>=(AbstractedDevice const &) const;
std::string debug_to_string() const;void debug_print() const;
::FlexFlow::BinaryTreePath operator_tree_path;
::FlexFlow::TaskSpaceCoordinate task_space_coordinate;
};}// namespace FlexFlow


///\cond
namespace std{template <>
struct hash<::FlexFlow::AbstractedDevice>{size_t operator()(::FlexFlow::AbstractedDevice const &)const;};}// namespace std

///\endcond

namespace nlohmann{template <>
struct adl_serializer<::FlexFlow::AbstractedDevice>{static ::FlexFlow::AbstractedDevice from_json(json const &);
static void to_json(json &, ::FlexFlow::AbstractedDevice const &);
};}// namespace nlohmann

namespace FlexFlow{std::string format_as(AbstractedDevice const &);
std::ostream &operator<<(std::ostream &, AbstractedDevice const &);}// namespace FlexFlow

#endif // _FLEXFLOW_LIB_COMPILER_INCLUDE_COMPILER_MACHINE_MAPPING_ABSTRACTED_TENSOR_SET_MOVEMENT_ABSTRACTED_DEVICE_DTG_H
