// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/compiler/include/compiler/machine_mapping/start_invariant_machine_view.dtg.toml
/* proj-data
{
  "generated_from": "d67fcd67ce257d5bba3d498b04a1d651"
}
*/

#include "compiler/machine_mapping/start_invariant_machine_view.dtg.h"

#include "utils/fmt/vector.h"
#include "utils/hash/vector.h"
#include <sstream>

namespace FlexFlow{StartInvariantMachineView::StartInvariantMachineView(std::vector<::FlexFlow::MachineViewDimension> const &dimensions) : dimensions(dimensions){}
bool StartInvariantMachineView::operator==(StartInvariantMachineView const &other) const{
return std::tie(this->dimensions) == std::tie(other.dimensions);
}bool StartInvariantMachineView::operator!=(StartInvariantMachineView const &other) const{
return std::tie(this->dimensions) != std::tie(other.dimensions);
}bool StartInvariantMachineView::operator<(StartInvariantMachineView const &other) const{
return std::tie(this->dimensions) < std::tie(other.dimensions);
}bool StartInvariantMachineView::operator>(StartInvariantMachineView const &other) const{
return std::tie(this->dimensions) > std::tie(other.dimensions);
}bool StartInvariantMachineView::operator<=(StartInvariantMachineView const &other) const{
return std::tie(this->dimensions) <= std::tie(other.dimensions);
}bool StartInvariantMachineView::operator>=(StartInvariantMachineView const &other) const{
return std::tie(this->dimensions) >= std::tie(other.dimensions);
}}// namespace FlexFlow


///\cond
namespace std{size_t hash<FlexFlow::StartInvariantMachineView>::operator()(::FlexFlow::StartInvariantMachineView const &x)const{size_t result = 0;
result ^= std::hash<std::vector<::FlexFlow::MachineViewDimension>>{}(x.dimensions) + 0x9e3779b9 + (result << 6) + (result >> 2);return result;
}}// namespace std

///\endcond

namespace nlohmann{void adl_serializer<::FlexFlow::StartInvariantMachineView>::to_json(json &j, ::FlexFlow::StartInvariantMachineView const &v) {j["__type"] = "StartInvariantMachineView";
j["dimensions"] = v.dimensions;
}}// namespace nlohmann

namespace nlohmann{::FlexFlow::StartInvariantMachineView adl_serializer<::FlexFlow::StartInvariantMachineView>::from_json(json const &j) {return ::FlexFlow::StartInvariantMachineView{j.at("dimensions").template get<std::vector<::FlexFlow::MachineViewDimension>>()};}}// namespace nlohmann

namespace FlexFlow{std::string StartInvariantMachineView::debug_to_string() const { return fmt::to_string(*this); }void StartInvariantMachineView::debug_print() const { std::cout << this->debug_to_string() << std::endl; }std::string format_as(StartInvariantMachineView const &x){::nlohmann::json j = x;
return j.dump();
}std::ostream &operator<<(std::ostream &s, StartInvariantMachineView const &x) {return s << fmt::to_string(x);}}// namespace FlexFlow
