// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/task-spec/include/task-spec/op_training_tensor_type.dtg.toml
/* proj-data
{
  "generated_from": "ed2641ade03be55338784e09f6c7be76"
}
*/

#include "task-spec/op_training_tensor_type.dtg.h"

#include <stdexcept>
#include <sstream>


///\cond
namespace std{size_t hash<FlexFlow::OpTrainingTensorType>::operator()(FlexFlow::OpTrainingTensorType x) const{return std::hash<int>{}(static_cast<int>(x));
}}// namespace std

///\endcond
namespace FlexFlow{std::string format_as(OpTrainingTensorType x){::nlohmann::json j = x;
return j.dump();
}std::ostream &operator<<(std::ostream &s, OpTrainingTensorType x){return s << fmt::to_string(x);}}// namespace FlexFlow
namespace FlexFlow{void to_json(::nlohmann::json &j, OpTrainingTensorType x){switch (x){case OpTrainingTensorType::FORWARD:
j = "FORWARD";
break;
case OpTrainingTensorType::GRADIENT:
j = "GRADIENT";
break;
case OpTrainingTensorType::OPTIMIZER:
j = "OPTIMIZER";
break;
default:
std::ostringstream oss;
oss << "Unknown OpTrainingTensorType value " << static_cast<int>(x);
throw std::runtime_error(oss.str());
}}}// namespace FlexFlow
namespace FlexFlow{void from_json(::nlohmann::json const &j, OpTrainingTensorType &x){std::string as_str = j.get<std::string>();
if (as_str == "FORWARD"){x = OpTrainingTensorType::FORWARD;
}else if (as_str == "GRADIENT"){x = OpTrainingTensorType::GRADIENT;
}else if (as_str == "OPTIMIZER"){x = OpTrainingTensorType::OPTIMIZER;
}else {std::ostringstream oss;
oss << "Unknown OpTrainingTensorType value " << as_str;
throw std::runtime_error(oss.str());
}}}// namespace FlexFlow
namespace rc{Gen<FlexFlow::OpTrainingTensorType> Arbitrary<FlexFlow::OpTrainingTensorType>::arbitrary(){return gen::element<FlexFlow::OpTrainingTensorType>(FlexFlow::OpTrainingTensorType::FORWARD, FlexFlow::OpTrainingTensorType::GRADIENT, FlexFlow::OpTrainingTensorType::OPTIMIZER);}}// namespace rc
