// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/task-spec/include/task-spec/per_device_op_state_ref_type.dtg.toml
/* proj-data
{
  "generated_from": "42746176f5233df33a62531ec38225f3"
}
*/

#include "task-spec/per_device_op_state_ref_type.dtg.h"

#include <sstream>

namespace FlexFlow{bool PerDeviceOpStateRefType::operator==(PerDeviceOpStateRefType const &other) const{
return std::tie() == std::tie();
}bool PerDeviceOpStateRefType::operator!=(PerDeviceOpStateRefType const &other) const{
return std::tie() != std::tie();
}bool PerDeviceOpStateRefType::operator<(PerDeviceOpStateRefType const &other) const{
return std::tie() < std::tie();
}bool PerDeviceOpStateRefType::operator>(PerDeviceOpStateRefType const &other) const{
return std::tie() > std::tie();
}bool PerDeviceOpStateRefType::operator<=(PerDeviceOpStateRefType const &other) const{
return std::tie() <= std::tie();
}bool PerDeviceOpStateRefType::operator>=(PerDeviceOpStateRefType const &other) const{
return std::tie() >= std::tie();
}}// namespace FlexFlow


///\cond
namespace std{size_t hash<FlexFlow::PerDeviceOpStateRefType>::operator()(::FlexFlow::PerDeviceOpStateRefType const &x)const{size_t result = 0;
return result;
}}// namespace std

///\endcond

namespace nlohmann{void adl_serializer<::FlexFlow::PerDeviceOpStateRefType>::to_json(json &j, ::FlexFlow::PerDeviceOpStateRefType const &v) {j["__type"] = "PerDeviceOpStateRefType";
}}// namespace nlohmann

namespace nlohmann{::FlexFlow::PerDeviceOpStateRefType adl_serializer<::FlexFlow::PerDeviceOpStateRefType>::from_json(json const &j) {return ::FlexFlow::PerDeviceOpStateRefType{};}}// namespace nlohmann

namespace FlexFlow{std::string PerDeviceOpStateRefType::debug_to_string() const { return fmt::to_string(*this); }void PerDeviceOpStateRefType::debug_print() const { std::cout << this->debug_to_string() << std::endl; }std::string format_as(PerDeviceOpStateRefType const &x){::nlohmann::json j = x;
return j.dump();
}std::ostream &operator<<(std::ostream &s, PerDeviceOpStateRefType const &x) {return s << fmt::to_string(x);}}// namespace FlexFlow
