// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/pcg/include/pcg/parallel_computation_graph/parallel_layer_info.dtg.toml
/* proj-data
{
  "generated_from": "d602ab83f20330353e02ec4141e1a264"
}
*/

#ifndef _FLEXFLOW_LIB_PCG_INCLUDE_PCG_PARALLEL_COMPUTATION_GRAPH_PARALLEL_LAYER_INFO_DTG_H
#define _FLEXFLOW_LIB_PCG_INCLUDE_PCG_PARALLEL_COMPUTATION_GRAPH_PARALLEL_LAYER_INFO_DTG_H

#include <tuple>
#include <iostream>
#include "pcg/parallel_computation_graph/parallel_layer_attrs.dtg.h"
#include <ostream>
#include "pcg/parallel_computation_graph/parallel_layer_guid_t.dtg.h"
#include <fmt/format.h>
#include <nlohmann/json.hpp>
#include <functional>


namespace FlexFlow{struct ParallelLayerInfo{ParallelLayerInfo() = delete;
explicit ParallelLayerInfo(::FlexFlow::parallel_layer_guid_t const &guid, ::FlexFlow::ParallelLayerAttrs const &attrs);

bool operator==(ParallelLayerInfo const &) const;bool operator!=(ParallelLayerInfo const &) const;
bool operator<(ParallelLayerInfo const &) const;bool operator>(ParallelLayerInfo const &) const;bool operator<=(ParallelLayerInfo const &) const;bool operator>=(ParallelLayerInfo const &) const;
std::string debug_to_string() const;void debug_print() const;
::FlexFlow::parallel_layer_guid_t guid;
::FlexFlow::ParallelLayerAttrs attrs;
};}// namespace FlexFlow


///\cond
namespace std{template <>
struct hash<::FlexFlow::ParallelLayerInfo>{size_t operator()(::FlexFlow::ParallelLayerInfo const &)const;};}// namespace std

///\endcond

namespace nlohmann{template <>
struct adl_serializer<::FlexFlow::ParallelLayerInfo>{static ::FlexFlow::ParallelLayerInfo from_json(json const &);
static void to_json(json &, ::FlexFlow::ParallelLayerInfo const &);
};}// namespace nlohmann

namespace FlexFlow{std::string format_as(ParallelLayerInfo const &);
std::ostream &operator<<(std::ostream &, ParallelLayerInfo const &);}// namespace FlexFlow

#endif // _FLEXFLOW_LIB_PCG_INCLUDE_PCG_PARALLEL_COMPUTATION_GRAPH_PARALLEL_LAYER_INFO_DTG_H
