// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/pcg/include/pcg/parallel_computation_graph/parallel_tensor_guid_t.dtg.toml
/* proj-data
{
  "generated_from": "5599d8b632ee20b482b27ecb8b52db7d"
}
*/

#ifndef _FLEXFLOW_LIB_PCG_INCLUDE_PCG_PARALLEL_COMPUTATION_GRAPH_PARALLEL_TENSOR_GUID_T_DTG_H
#define _FLEXFLOW_LIB_PCG_INCLUDE_PCG_PARALLEL_COMPUTATION_GRAPH_PARALLEL_TENSOR_GUID_T_DTG_H

#include <tuple>
#include <iostream>
#include <functional>
#include <ostream>
#include <fmt/format.h>
#include "op-attrs/tensor_slot_name.dtg.h"
#include <nlohmann/json.hpp>
#include "utils/graph/kwarg_dataflow_graph/kwarg_dataflow_output.dtg.h"


namespace FlexFlow{struct parallel_tensor_guid_t{parallel_tensor_guid_t() = delete;
explicit parallel_tensor_guid_t(::FlexFlow::KwargDataflowOutput<::FlexFlow::TensorSlotName> const &raw_graph_output);

bool operator==(parallel_tensor_guid_t const &) const;bool operator!=(parallel_tensor_guid_t const &) const;
bool operator<(parallel_tensor_guid_t const &) const;bool operator>(parallel_tensor_guid_t const &) const;bool operator<=(parallel_tensor_guid_t const &) const;bool operator>=(parallel_tensor_guid_t const &) const;
std::string debug_to_string() const;void debug_print() const;
::FlexFlow::KwargDataflowOutput<::FlexFlow::TensorSlotName> raw_graph_output;
};}// namespace FlexFlow


///\cond
namespace std{template <>
struct hash<::FlexFlow::parallel_tensor_guid_t>{size_t operator()(::FlexFlow::parallel_tensor_guid_t const &)const;};}// namespace std

///\endcond

namespace nlohmann{template <>
struct adl_serializer<::FlexFlow::parallel_tensor_guid_t>{static ::FlexFlow::parallel_tensor_guid_t from_json(json const &);
static void to_json(json &, ::FlexFlow::parallel_tensor_guid_t const &);
};}// namespace nlohmann

namespace FlexFlow{std::string format_as(parallel_tensor_guid_t const &);
std::ostream &operator<<(std::ostream &, parallel_tensor_guid_t const &);}// namespace FlexFlow

#endif // _FLEXFLOW_LIB_PCG_INCLUDE_PCG_PARALLEL_COMPUTATION_GRAPH_PARALLEL_TENSOR_GUID_T_DTG_H
