// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/utils/include/utils/graph/open_dataflow_graph/dataflow_graph_input.dtg.toml
/* proj-data
{
  "generated_from": "15339c461699cdbb081408e35f7e8e1e"
}
*/

#ifndef _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_GRAPH_OPEN_DATAFLOW_GRAPH_DATAFLOW_GRAPH_INPUT_DTG_H
#define _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_GRAPH_OPEN_DATAFLOW_GRAPH_DATAFLOW_GRAPH_INPUT_DTG_H

#include <tuple>
#include <iostream>
#include <cstddef>
#include <ostream>
#include <fmt/format.h>
#include <nlohmann/json.hpp>
#include <functional>


namespace FlexFlow{struct DataflowGraphInput{DataflowGraphInput() = delete;
explicit DataflowGraphInput(size_t const &idx);

bool operator==(DataflowGraphInput const &) const;bool operator!=(DataflowGraphInput const &) const;
bool operator<(DataflowGraphInput const &) const;bool operator>(DataflowGraphInput const &) const;bool operator<=(DataflowGraphInput const &) const;bool operator>=(DataflowGraphInput const &) const;
std::string debug_to_string() const;void debug_print() const;
size_t idx;
};}// namespace FlexFlow


///\cond
namespace std{template <>
struct hash<::FlexFlow::DataflowGraphInput>{size_t operator()(::FlexFlow::DataflowGraphInput const &)const;};}// namespace std

///\endcond

namespace nlohmann{template <>
struct adl_serializer<::FlexFlow::DataflowGraphInput>{static void to_json(json &, ::FlexFlow::DataflowGraphInput const &);
};}// namespace nlohmann

namespace FlexFlow{std::string format_as(DataflowGraphInput const &);
std::ostream &operator<<(std::ostream &, DataflowGraphInput const &);}// namespace FlexFlow

#endif // _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_GRAPH_OPEN_DATAFLOW_GRAPH_DATAFLOW_GRAPH_INPUT_DTG_H
