// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/utils/include/utils/graph/open_dataflow_graph/dataflow_input_edge_query.dtg.toml
/* proj-data
{
  "generated_from": "d392939cd301e9ed26eecddee576a0c1"
}
*/

#ifndef _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_GRAPH_OPEN_DATAFLOW_GRAPH_DATAFLOW_INPUT_EDGE_QUERY_DTG_H
#define _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_GRAPH_OPEN_DATAFLOW_GRAPH_DATAFLOW_INPUT_EDGE_QUERY_DTG_H

#include <tuple>
#include <iostream>
#include <functional>
#include "utils/graph/query_set.h"
#include <ostream>
#include <fmt/format.h>
#include <nlohmann/json.hpp>
#include "utils/graph/open_dataflow_graph/dataflow_graph_input.dtg.h"
#include "utils/nonnegative_int/nonnegative_int.h"
#include "utils/graph/node/node.dtg.h"


namespace FlexFlow{struct DataflowInputEdgeQuery{DataflowInputEdgeQuery() = delete;
explicit DataflowInputEdgeQuery(::FlexFlow::query_set<::FlexFlow::DataflowGraphInput> const &srcs, ::FlexFlow::query_set<::FlexFlow::Node> const &dst_nodes, ::FlexFlow::query_set<::FlexFlow::nonnegative_int> const &dst_idxs);

bool operator==(DataflowInputEdgeQuery const &) const;bool operator!=(DataflowInputEdgeQuery const &) const;
bool operator<(DataflowInputEdgeQuery const &) const;bool operator>(DataflowInputEdgeQuery const &) const;bool operator<=(DataflowInputEdgeQuery const &) const;bool operator>=(DataflowInputEdgeQuery const &) const;
std::string debug_to_string() const;void debug_print() const;
::FlexFlow::query_set<::FlexFlow::DataflowGraphInput> srcs;
::FlexFlow::query_set<::FlexFlow::Node> dst_nodes;
::FlexFlow::query_set<::FlexFlow::nonnegative_int> dst_idxs;
};}// namespace FlexFlow


///\cond
namespace std{template <>
struct hash<::FlexFlow::DataflowInputEdgeQuery>{size_t operator()(::FlexFlow::DataflowInputEdgeQuery const &)const;};}// namespace std

///\endcond

namespace nlohmann{template <>
struct adl_serializer<::FlexFlow::DataflowInputEdgeQuery>{static void to_json(json &, ::FlexFlow::DataflowInputEdgeQuery const &);
};}// namespace nlohmann

namespace FlexFlow{std::string format_as(DataflowInputEdgeQuery const &);
std::ostream &operator<<(std::ostream &, DataflowInputEdgeQuery const &);}// namespace FlexFlow

#endif // _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_GRAPH_OPEN_DATAFLOW_GRAPH_DATAFLOW_INPUT_EDGE_QUERY_DTG_H
