// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/utils/include/utils/graph/open_dataflow_graph/open_dataflow_edge_query.dtg.toml
/* proj-data
{
  "generated_from": "31c73f2bbae47293f981cac2b803d695"
}
*/

#ifndef _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_GRAPH_OPEN_DATAFLOW_GRAPH_OPEN_DATAFLOW_EDGE_QUERY_DTG_H
#define _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_GRAPH_OPEN_DATAFLOW_GRAPH_OPEN_DATAFLOW_EDGE_QUERY_DTG_H

#include <tuple>
#include <iostream>
#include <ostream>
#include "utils/graph/dataflow_graph/dataflow_edge_query.dtg.h"
#include <fmt/format.h>
#include "utils/graph/open_dataflow_graph/dataflow_input_edge_query.dtg.h"
#include <nlohmann/json.hpp>
#include <functional>


namespace FlexFlow{struct OpenDataflowEdgeQuery{OpenDataflowEdgeQuery() = delete;
explicit OpenDataflowEdgeQuery(::FlexFlow::DataflowInputEdgeQuery const &input_edge_query, ::FlexFlow::DataflowEdgeQuery const &standard_edge_query);

bool operator==(OpenDataflowEdgeQuery const &) const;bool operator!=(OpenDataflowEdgeQuery const &) const;
bool operator<(OpenDataflowEdgeQuery const &) const;bool operator>(OpenDataflowEdgeQuery const &) const;bool operator<=(OpenDataflowEdgeQuery const &) const;bool operator>=(OpenDataflowEdgeQuery const &) const;
std::string debug_to_string() const;void debug_print() const;
::FlexFlow::DataflowInputEdgeQuery input_edge_query;
::FlexFlow::DataflowEdgeQuery standard_edge_query;
};}// namespace FlexFlow


///\cond
namespace std{template <>
struct hash<::FlexFlow::OpenDataflowEdgeQuery>{size_t operator()(::FlexFlow::OpenDataflowEdgeQuery const &)const;};}// namespace std

///\endcond

namespace nlohmann{template <>
struct adl_serializer<::FlexFlow::OpenDataflowEdgeQuery>{static void to_json(json &, ::FlexFlow::OpenDataflowEdgeQuery const &);
};}// namespace nlohmann

namespace FlexFlow{std::string format_as(OpenDataflowEdgeQuery const &);
std::ostream &operator<<(std::ostream &, OpenDataflowEdgeQuery const &);}// namespace FlexFlow

#endif // _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_GRAPH_OPEN_DATAFLOW_GRAPH_OPEN_DATAFLOW_EDGE_QUERY_DTG_H
