// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/compiler/include/compiler/task_graph_simulator/in_progress_task.dtg.toml
/* proj-data
{
  "generated_from": "54c7a0a630434736e3fc273b09795d25"
}
*/

#include "compiler/task_graph_simulator/in_progress_task.dtg.h"

#include <sstream>

namespace FlexFlow{InProgressTask::InProgressTask(float const &start_time, float const &end_time, ::FlexFlow::Node const &node) : start_time(start_time), end_time(end_time), node(node){}
bool InProgressTask::operator==(InProgressTask const &other) const{
return std::tie(this->start_time, this->end_time, this->node) == std::tie(other.start_time, other.end_time, other.node);
}bool InProgressTask::operator!=(InProgressTask const &other) const{
return std::tie(this->start_time, this->end_time, this->node) != std::tie(other.start_time, other.end_time, other.node);
}bool InProgressTask::operator<(InProgressTask const &other) const{
return std::tie(this->start_time, this->end_time, this->node) < std::tie(other.start_time, other.end_time, other.node);
}bool InProgressTask::operator>(InProgressTask const &other) const{
return std::tie(this->start_time, this->end_time, this->node) > std::tie(other.start_time, other.end_time, other.node);
}bool InProgressTask::operator<=(InProgressTask const &other) const{
return std::tie(this->start_time, this->end_time, this->node) <= std::tie(other.start_time, other.end_time, other.node);
}bool InProgressTask::operator>=(InProgressTask const &other) const{
return std::tie(this->start_time, this->end_time, this->node) >= std::tie(other.start_time, other.end_time, other.node);
}}// namespace FlexFlow


///\cond
namespace std{size_t hash<FlexFlow::InProgressTask>::operator()(::FlexFlow::InProgressTask const &x)const{size_t result = 0;
result ^= std::hash<float>{}(x.start_time) + 0x9e3779b9 + (result << 6) + (result >> 2);result ^= std::hash<float>{}(x.end_time) + 0x9e3779b9 + (result << 6) + (result >> 2);result ^= std::hash<::FlexFlow::Node>{}(x.node) + 0x9e3779b9 + (result << 6) + (result >> 2);return result;
}}// namespace std

///\endcond

namespace nlohmann{void adl_serializer<::FlexFlow::InProgressTask>::to_json(json &j, ::FlexFlow::InProgressTask const &v) {j["__type"] = "InProgressTask";
j["start_time"] = v.start_time;
j["end_time"] = v.end_time;
j["node"] = v.node;
}}// namespace nlohmann

namespace FlexFlow{std::string InProgressTask::debug_to_string() const { return fmt::to_string(*this); }void InProgressTask::debug_print() const { std::cout << this->debug_to_string() << std::endl; }std::string format_as(InProgressTask const &x){::nlohmann::json j = x;
return j.dump();
}std::ostream &operator<<(std::ostream &s, InProgressTask const &x) {return s << fmt::to_string(x);}}// namespace FlexFlow
