// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/compiler/include/compiler/task_graph_simulator/pcg_task.dtg.toml
/* proj-data
{
  "generated_from": "2f0cc904bb84fadda9340b34e606ad6d"
}
*/

#include "compiler/task_graph_simulator/pcg_task.dtg.h"

#include <sstream>

namespace FlexFlow{PCGTask::PCGTask(::FlexFlow::RuntimeOnlyOpCostEstimateKey const &v) : raw_variant(v) { }
PCGTask::PCGTask(::FlexFlow::TensorSetMovement const &v) : raw_variant(v) { }bool PCGTask::operator==(PCGTask const &other) const{return this->raw_variant == other.raw_variant;}
bool PCGTask::operator!=(PCGTask const &other) const{return this->raw_variant != other.raw_variant;}
bool PCGTask::operator<(PCGTask const &other) const{return this->raw_variant < other.raw_variant;}
bool PCGTask::operator>(PCGTask const &other) const{return this->raw_variant > other.raw_variant;}
bool PCGTask::operator<=(PCGTask const &other) const{return this->raw_variant <= other.raw_variant;}
bool PCGTask::operator>=(PCGTask const &other) const{return this->raw_variant >= other.raw_variant;}
::FlexFlow::RuntimeOnlyOpCostEstimateKey const & PCGTask::require_operator() const{bool holds_expected = std::holds_alternative<::FlexFlow::RuntimeOnlyOpCostEstimateKey>(this->raw_variant);
ASSERT(holds_expected, "Expected ::FlexFlow::RuntimeOnlyOpCostEstimateKey");
return std::get<::FlexFlow::RuntimeOnlyOpCostEstimateKey>(this->raw_variant);
}
::FlexFlow::RuntimeOnlyOpCostEstimateKey & PCGTask::require_operator(){bool holds_expected = std::holds_alternative<::FlexFlow::RuntimeOnlyOpCostEstimateKey>(this->raw_variant);
ASSERT(holds_expected, "Expected ::FlexFlow::RuntimeOnlyOpCostEstimateKey");
return std::get<::FlexFlow::RuntimeOnlyOpCostEstimateKey>(this->raw_variant);
}
::FlexFlow::TensorSetMovement const & PCGTask::require_tensor_movement() const{bool holds_expected = std::holds_alternative<::FlexFlow::TensorSetMovement>(this->raw_variant);
ASSERT(holds_expected, "Expected ::FlexFlow::TensorSetMovement");
return std::get<::FlexFlow::TensorSetMovement>(this->raw_variant);
}
::FlexFlow::TensorSetMovement & PCGTask::require_tensor_movement(){bool holds_expected = std::holds_alternative<::FlexFlow::TensorSetMovement>(this->raw_variant);
ASSERT(holds_expected, "Expected ::FlexFlow::TensorSetMovement");
return std::get<::FlexFlow::TensorSetMovement>(this->raw_variant);
}
std::optional<::FlexFlow::RuntimeOnlyOpCostEstimateKey> PCGTask::try_require_operator() const{if (this->is_operator()) {return this->require_operator();
}else {return std::nullopt;
}}
std::optional<::FlexFlow::TensorSetMovement> PCGTask::try_require_tensor_movement() const{if (this->is_tensor_movement()) {return this->require_tensor_movement();
}else {return std::nullopt;
}}
bool PCGTask::is_operator() const{return std::holds_alternative<::FlexFlow::RuntimeOnlyOpCostEstimateKey>(this->raw_variant);
}
bool PCGTask::is_tensor_movement() const{return std::holds_alternative<::FlexFlow::TensorSetMovement>(this->raw_variant);
}
}// namespace FlexFlow

///\cond
namespace std{size_t hash<::FlexFlow::PCGTask>::operator()(::FlexFlow::PCGTask const &x) const{return std::hash<std::variant<::FlexFlow::RuntimeOnlyOpCostEstimateKey, ::FlexFlow::TensorSetMovement>>{}(x.raw_variant);}
}// namespace std

///\endcond
namespace nlohmann{void adl_serializer<::FlexFlow::PCGTask>::to_json(json &j, ::FlexFlow::PCGTask const &x){j["__type"] = "PCGTask";
switch (x.index()){case 0:{j["type"] = "operator";
j["value"] = x.template get<::FlexFlow::RuntimeOnlyOpCostEstimateKey>();
break;
}case 1:{j["type"] = "tensor_movement";
j["value"] = x.template get<::FlexFlow::TensorSetMovement>();
break;
}default:{throw std::runtime_error(fmt::format("Unknown index {} for type PCGTask", x.index()));
}}}
}// namespace nlohmann
namespace FlexFlow{std::string PCGTask::debug_to_string() const{return fmt::to_string(*this);}
void PCGTask::debug_print() const{std::cout << this->debug_to_string() << std::endl;}
std::string format_as(::FlexFlow::PCGTask const &x){::nlohmann::json j = x;
return j.dump();
}
std::ostream & operator<<(std::ostream &s, ::FlexFlow::PCGTask const &x){return s << fmt::to_string(x);
}
}// namespace FlexFlow
