// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/compiler/include/compiler/task_graph_simulator/task_execution_constraint.dtg.toml
/* proj-data
{
  "generated_from": "7ab2682a42b33b017d1c4c384db15078"
}
*/

#include "compiler/task_graph_simulator/task_execution_constraint.dtg.h"


namespace FlexFlow{TaskExecutionConstraint::TaskExecutionConstraint(std::function<bool(Node const &, std::set<Node> const &, std::set<Node> const &)> const &is_satisfied) : is_satisfied(is_satisfied){}
}// namespace FlexFlow
