// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/compiler/include/compiler/task_graph_simulator/task_graph_execution_state.dtg.toml
/* proj-data
{
  "generated_from": "e61d878c0edb2f01152b67677f8213e7"
}
*/

#include "compiler/task_graph_simulator/task_graph_execution_state.dtg.h"

#include "utils/hash/set.h"
#include "utils/fmt/vector.h"
#include "utils/fmt/set.h"
#include "utils/hash/vector.h"

namespace FlexFlow{TaskGraphExecutionState::TaskGraphExecutionState(std::set<::FlexFlow::Node> const &ready_tasks, ::FlexFlow::DeduplicatedPriorityQueue<::FlexFlow::InProgressTask, std::vector<::FlexFlow::InProgressTask>, ::FlexFlow::InProgressTaskComparator> const &in_progress_tasks, std::set<::FlexFlow::Node> const &finished_tasks, float const &current_time) : ready_tasks(ready_tasks), in_progress_tasks(in_progress_tasks), finished_tasks(finished_tasks), current_time(current_time){}
}// namespace FlexFlow
