// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/utils/include/utils/graph/kwarg_dataflow_graph/kwarg_dataflow_output_query.dtg.toml
/* proj-data
{
  "generated_from": "234061085596cdb3d26e8503552f1cb3"
}
*/

#ifndef _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_GRAPH_KWARG_DATAFLOW_GRAPH_KWARG_DATAFLOW_OUTPUT_QUERY_DTG_H
#define _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_GRAPH_KWARG_DATAFLOW_GRAPH_KWARG_DATAFLOW_OUTPUT_QUERY_DTG_H

#include <tuple>
#include <iostream>
#include "utils/graph/query_set.h"
#include <ostream>
#include <fmt/format.h>
#include <nlohmann/json.hpp>
#include <functional>
#include "utils/nonnegative_int/nonnegative_int.h"
#include "utils/graph/node/node.dtg.h"
#include "utils/fmt/set.h"
#include <sstream>


namespace FlexFlow{template <typename SlotName>
struct KwargDataflowOutputQuery{KwargDataflowOutputQuery() = delete;
explicit KwargDataflowOutputQuery(::FlexFlow::query_set<::FlexFlow::Node> const &nodes, ::FlexFlow::query_set<SlotName> const &output_idxs);

bool operator==(KwargDataflowOutputQuery const &) const;bool operator!=(KwargDataflowOutputQuery const &) const;
bool operator<(KwargDataflowOutputQuery const &) const;bool operator>(KwargDataflowOutputQuery const &) const;bool operator<=(KwargDataflowOutputQuery const &) const;bool operator>=(KwargDataflowOutputQuery const &) const;
std::string debug_to_string() const;void debug_print() const;
::FlexFlow::query_set<::FlexFlow::Node> nodes;
::FlexFlow::query_set<SlotName> output_idxs;
};}// namespace FlexFlow


///\cond
namespace std{template <typename SlotName>
struct hash<::FlexFlow::KwargDataflowOutputQuery<SlotName>>{size_t operator()(::FlexFlow::KwargDataflowOutputQuery<SlotName> const &)const;};}// namespace std

///\endcond

namespace nlohmann{template <typename SlotName>
struct adl_serializer<::FlexFlow::KwargDataflowOutputQuery<SlotName>>{static void to_json(json &, ::FlexFlow::KwargDataflowOutputQuery<SlotName> const &);
};}// namespace nlohmann

namespace FlexFlow{template <typename SlotName>
std::string format_as(KwargDataflowOutputQuery<SlotName> const &);
template <typename SlotName>
std::ostream &operator<<(std::ostream &, KwargDataflowOutputQuery<SlotName> const &);}// namespace FlexFlow

namespace FlexFlow{template <typename SlotName>
KwargDataflowOutputQuery<SlotName>::KwargDataflowOutputQuery(::FlexFlow::query_set<::FlexFlow::Node> const &nodes, ::FlexFlow::query_set<SlotName> const &output_idxs) : nodes(nodes), output_idxs(output_idxs){}
template <typename SlotName>
bool KwargDataflowOutputQuery<SlotName>::operator==(KwargDataflowOutputQuery<SlotName> const &other) const{
return std::tie(this->nodes, this->output_idxs) == std::tie(other.nodes, other.output_idxs);
}template <typename SlotName>
bool KwargDataflowOutputQuery<SlotName>::operator!=(KwargDataflowOutputQuery<SlotName> const &other) const{
return std::tie(this->nodes, this->output_idxs) != std::tie(other.nodes, other.output_idxs);
}template <typename SlotName>
bool KwargDataflowOutputQuery<SlotName>::operator<(KwargDataflowOutputQuery<SlotName> const &other) const{
return std::tie(this->nodes, this->output_idxs) < std::tie(other.nodes, other.output_idxs);
}template <typename SlotName>
bool KwargDataflowOutputQuery<SlotName>::operator>(KwargDataflowOutputQuery<SlotName> const &other) const{
return std::tie(this->nodes, this->output_idxs) > std::tie(other.nodes, other.output_idxs);
}template <typename SlotName>
bool KwargDataflowOutputQuery<SlotName>::operator<=(KwargDataflowOutputQuery<SlotName> const &other) const{
return std::tie(this->nodes, this->output_idxs) <= std::tie(other.nodes, other.output_idxs);
}template <typename SlotName>
bool KwargDataflowOutputQuery<SlotName>::operator>=(KwargDataflowOutputQuery<SlotName> const &other) const{
return std::tie(this->nodes, this->output_idxs) >= std::tie(other.nodes, other.output_idxs);
}}// namespace FlexFlow


///\cond
namespace std{template <typename SlotName>
size_t hash<FlexFlow::KwargDataflowOutputQuery<SlotName>>::operator()(::FlexFlow::KwargDataflowOutputQuery<SlotName> const &x)const{size_t result = 0;
result ^= std::hash<::FlexFlow::query_set<::FlexFlow::Node>>{}(x.nodes) + 0x9e3779b9 + (result << 6) + (result >> 2);result ^= std::hash<::FlexFlow::query_set<SlotName>>{}(x.output_idxs) + 0x9e3779b9 + (result << 6) + (result >> 2);return result;
}}// namespace std

///\endcond

namespace nlohmann{template <typename SlotName>
void adl_serializer<::FlexFlow::KwargDataflowOutputQuery<SlotName>>::to_json(json &j, ::FlexFlow::KwargDataflowOutputQuery<SlotName> const &v) {j["__type"] = "KwargDataflowOutputQuery";
j["nodes"] = v.nodes;
j["output_idxs"] = v.output_idxs;
}}// namespace nlohmann

namespace FlexFlow{template <typename SlotName>
std::string KwargDataflowOutputQuery<SlotName>::debug_to_string() const { return fmt::to_string(*this); }template <typename SlotName>
void KwargDataflowOutputQuery<SlotName>::debug_print() const { std::cout << this->debug_to_string() << std::endl; }template <typename SlotName>
std::string format_as(KwargDataflowOutputQuery<SlotName> const &x){::nlohmann::json j = x;
return j.dump();
}template <typename SlotName>
std::ostream &operator<<(std::ostream &s, KwargDataflowOutputQuery<SlotName> const &x) {return s << fmt::to_string(x);}}// namespace FlexFlow

#endif // _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_GRAPH_KWARG_DATAFLOW_GRAPH_KWARG_DATAFLOW_OUTPUT_QUERY_DTG_H
