// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/utils/include/utils/graph/kwarg_dataflow_graph/kwarg_dataflow_edge_query.dtg.toml
/* proj-data
{
  "generated_from": "195b98545a7bb743c59fe3290ed40181"
}
*/

#ifndef _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_GRAPH_KWARG_DATAFLOW_GRAPH_KWARG_DATAFLOW_EDGE_QUERY_DTG_H
#define _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_GRAPH_KWARG_DATAFLOW_GRAPH_KWARG_DATAFLOW_EDGE_QUERY_DTG_H

#include <tuple>
#include <iostream>
#include "utils/graph/query_set.h"
#include <ostream>
#include <fmt/format.h>
#include <nlohmann/json.hpp>
#include <functional>
#include "utils/graph/node/node.dtg.h"
#include <sstream>


namespace FlexFlow{template <typename SlotName>
struct KwargDataflowEdgeQuery{KwargDataflowEdgeQuery() = delete;
explicit KwargDataflowEdgeQuery(::FlexFlow::query_set<::FlexFlow::Node> const &src_nodes, ::FlexFlow::query_set<SlotName> const &src_slots, ::FlexFlow::query_set<::FlexFlow::Node> const &dst_nodes, ::FlexFlow::query_set<SlotName> const &dst_slots);

bool operator==(KwargDataflowEdgeQuery const &) const;bool operator!=(KwargDataflowEdgeQuery const &) const;
bool operator<(KwargDataflowEdgeQuery const &) const;bool operator>(KwargDataflowEdgeQuery const &) const;bool operator<=(KwargDataflowEdgeQuery const &) const;bool operator>=(KwargDataflowEdgeQuery const &) const;
std::string debug_to_string() const;void debug_print() const;
::FlexFlow::query_set<::FlexFlow::Node> src_nodes;
::FlexFlow::query_set<SlotName> src_slots;
::FlexFlow::query_set<::FlexFlow::Node> dst_nodes;
::FlexFlow::query_set<SlotName> dst_slots;
};}// namespace FlexFlow


///\cond
namespace std{template <typename SlotName>
struct hash<::FlexFlow::KwargDataflowEdgeQuery<SlotName>>{size_t operator()(::FlexFlow::KwargDataflowEdgeQuery<SlotName> const &)const;};}// namespace std

///\endcond

namespace nlohmann{template <typename SlotName>
struct adl_serializer<::FlexFlow::KwargDataflowEdgeQuery<SlotName>>{static void to_json(json &, ::FlexFlow::KwargDataflowEdgeQuery<SlotName> const &);
};}// namespace nlohmann

namespace FlexFlow{template <typename SlotName>
std::string format_as(KwargDataflowEdgeQuery<SlotName> const &);
template <typename SlotName>
std::ostream &operator<<(std::ostream &, KwargDataflowEdgeQuery<SlotName> const &);}// namespace FlexFlow

namespace FlexFlow{template <typename SlotName>
KwargDataflowEdgeQuery<SlotName>::KwargDataflowEdgeQuery(::FlexFlow::query_set<::FlexFlow::Node> const &src_nodes, ::FlexFlow::query_set<SlotName> const &src_slots, ::FlexFlow::query_set<::FlexFlow::Node> const &dst_nodes, ::FlexFlow::query_set<SlotName> const &dst_slots) : src_nodes(src_nodes), src_slots(src_slots), dst_nodes(dst_nodes), dst_slots(dst_slots){}
template <typename SlotName>
bool KwargDataflowEdgeQuery<SlotName>::operator==(KwargDataflowEdgeQuery<SlotName> const &other) const{
return std::tie(this->src_nodes, this->src_slots, this->dst_nodes, this->dst_slots) == std::tie(other.src_nodes, other.src_slots, other.dst_nodes, other.dst_slots);
}template <typename SlotName>
bool KwargDataflowEdgeQuery<SlotName>::operator!=(KwargDataflowEdgeQuery<SlotName> const &other) const{
return std::tie(this->src_nodes, this->src_slots, this->dst_nodes, this->dst_slots) != std::tie(other.src_nodes, other.src_slots, other.dst_nodes, other.dst_slots);
}template <typename SlotName>
bool KwargDataflowEdgeQuery<SlotName>::operator<(KwargDataflowEdgeQuery<SlotName> const &other) const{
return std::tie(this->src_nodes, this->src_slots, this->dst_nodes, this->dst_slots) < std::tie(other.src_nodes, other.src_slots, other.dst_nodes, other.dst_slots);
}template <typename SlotName>
bool KwargDataflowEdgeQuery<SlotName>::operator>(KwargDataflowEdgeQuery<SlotName> const &other) const{
return std::tie(this->src_nodes, this->src_slots, this->dst_nodes, this->dst_slots) > std::tie(other.src_nodes, other.src_slots, other.dst_nodes, other.dst_slots);
}template <typename SlotName>
bool KwargDataflowEdgeQuery<SlotName>::operator<=(KwargDataflowEdgeQuery<SlotName> const &other) const{
return std::tie(this->src_nodes, this->src_slots, this->dst_nodes, this->dst_slots) <= std::tie(other.src_nodes, other.src_slots, other.dst_nodes, other.dst_slots);
}template <typename SlotName>
bool KwargDataflowEdgeQuery<SlotName>::operator>=(KwargDataflowEdgeQuery<SlotName> const &other) const{
return std::tie(this->src_nodes, this->src_slots, this->dst_nodes, this->dst_slots) >= std::tie(other.src_nodes, other.src_slots, other.dst_nodes, other.dst_slots);
}}// namespace FlexFlow


///\cond
namespace std{template <typename SlotName>
size_t hash<FlexFlow::KwargDataflowEdgeQuery<SlotName>>::operator()(::FlexFlow::KwargDataflowEdgeQuery<SlotName> const &x)const{size_t result = 0;
result ^= std::hash<::FlexFlow::query_set<::FlexFlow::Node>>{}(x.src_nodes) + 0x9e3779b9 + (result << 6) + (result >> 2);result ^= std::hash<::FlexFlow::query_set<SlotName>>{}(x.src_slots) + 0x9e3779b9 + (result << 6) + (result >> 2);result ^= std::hash<::FlexFlow::query_set<::FlexFlow::Node>>{}(x.dst_nodes) + 0x9e3779b9 + (result << 6) + (result >> 2);result ^= std::hash<::FlexFlow::query_set<SlotName>>{}(x.dst_slots) + 0x9e3779b9 + (result << 6) + (result >> 2);return result;
}}// namespace std

///\endcond

namespace nlohmann{template <typename SlotName>
void adl_serializer<::FlexFlow::KwargDataflowEdgeQuery<SlotName>>::to_json(json &j, ::FlexFlow::KwargDataflowEdgeQuery<SlotName> const &v) {j["__type"] = "KwargDataflowEdgeQuery";
j["src_nodes"] = v.src_nodes;
j["src_slots"] = v.src_slots;
j["dst_nodes"] = v.dst_nodes;
j["dst_slots"] = v.dst_slots;
}}// namespace nlohmann

namespace FlexFlow{template <typename SlotName>
std::string KwargDataflowEdgeQuery<SlotName>::debug_to_string() const { return fmt::to_string(*this); }template <typename SlotName>
void KwargDataflowEdgeQuery<SlotName>::debug_print() const { std::cout << this->debug_to_string() << std::endl; }template <typename SlotName>
std::string format_as(KwargDataflowEdgeQuery<SlotName> const &x){::nlohmann::json j = x;
return j.dump();
}template <typename SlotName>
std::ostream &operator<<(std::ostream &s, KwargDataflowEdgeQuery<SlotName> const &x) {return s << fmt::to_string(x);}}// namespace FlexFlow

#endif // _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_GRAPH_KWARG_DATAFLOW_GRAPH_KWARG_DATAFLOW_EDGE_QUERY_DTG_H
