// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/utils/include/utils/orthotope/dim_projection.dtg.toml
/* proj-data
{
  "generated_from": "d94585a675c9fa8df3c75bcb78f5a816"
}
*/

#ifndef _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_ORTHOTOPE_DIM_PROJECTION_DTG_H
#define _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_ORTHOTOPE_DIM_PROJECTION_DTG_H

#include <cstddef>
#include <fmt/format.h>
#include <functional>
#include <iostream>
#include <libassert/assert.hpp>
#include <nlohmann/json.hpp>
#include <optional>
#include <ostream>
#include <stdexcept>
#include <type_traits>
#include "utils/orthotope/down_projection.dtg.h"
#include "utils/orthotope/eq_projection.dtg.h"
#include "utils/orthotope/up_projection.dtg.h"
#include <variant>
#include <sstream>

namespace FlexFlow{template <typename L, typename R>
struct DimProjection{DimProjection() = delete;
explicit DimProjection(::FlexFlow::UpProjection<L, R> const &);
explicit DimProjection(::FlexFlow::EqProjection<L, R> const &);
explicit DimProjection(::FlexFlow::DownProjection<L, R> const &);template <typename T>
static constexpr bool IsPartOfDimProjection_v =std::is_same_v<T, ::FlexFlow::UpProjection<L, R>> || std::is_same_v<T, ::FlexFlow::EqProjection<L, R>> || std::is_same_v<T, ::FlexFlow::DownProjection<L, R>>;template <typename ReturnType, typename Visitor>
ReturnType visit(Visitor &&v) const{switch (this->index()){case 0: {ReturnType result = v(this->get<::FlexFlow::UpProjection<L, R>>());
return result;
}case 1: {ReturnType result = v(this->get<::FlexFlow::EqProjection<L, R>>());
return result;
}case 2: {ReturnType result = v(this->get<::FlexFlow::DownProjection<L, R>>());
return result;
}default: {throw std::runtime_error(fmt::format("Unknown index {} for type DimProjection", this->index()));
}}}
template <typename ReturnType, typename Visitor>
ReturnType visit(Visitor &&v){switch (this->index()){case 0: {ReturnType result = v(this->get<::FlexFlow::UpProjection<L, R>>());
return result;
}case 1: {ReturnType result = v(this->get<::FlexFlow::EqProjection<L, R>>());
return result;
}case 2: {ReturnType result = v(this->get<::FlexFlow::DownProjection<L, R>>());
return result;
}default: {throw std::runtime_error(fmt::format("Unknown index {} for type DimProjection", this->index()));
}}}
template <typename T>
bool has() const{static_assert(IsPartOfDimProjection_v<T>, "DimProjection::has() expected one of [::FlexFlow::UpProjection<L, R>, ::FlexFlow::EqProjection<L, R>, ::FlexFlow::DownProjection<L, R>], received T");return std::holds_alternative<T>(this->raw_variant);}
template <typename T>
T const & get() const{static_assert(IsPartOfDimProjection_v<T>, "DimProjection::get() expected one of [::FlexFlow::UpProjection<L, R>, ::FlexFlow::EqProjection<L, R>, ::FlexFlow::DownProjection<L, R>], received T");bool holds_expected = std::holds_alternative<T>(this->raw_variant);
ASSERT(holds_expected);
return std::get<T>(this->raw_variant);
}
template <typename T>
T  & get(){static_assert(IsPartOfDimProjection_v<T>, "DimProjection::get() expected one of [::FlexFlow::UpProjection<L, R>, ::FlexFlow::EqProjection<L, R>, ::FlexFlow::DownProjection<L, R>], received T");bool holds_expected = std::holds_alternative<T>(this->raw_variant);
ASSERT(holds_expected);
return std::get<T>(this->raw_variant);
}
size_t index() const { return this->raw_variant.index(); }
bool operator==(DimProjection const &) const;bool operator!=(DimProjection const &) const;bool operator<(DimProjection const &) const;bool operator>(DimProjection const &) const;bool operator<=(DimProjection const &) const;bool operator>=(DimProjection const &) const;::FlexFlow::UpProjection<L, R> const & require_up_proj() const;
::FlexFlow::UpProjection<L, R> & require_up_proj();
::FlexFlow::EqProjection<L, R> const & require_eq_proj() const;
::FlexFlow::EqProjection<L, R> & require_eq_proj();
::FlexFlow::DownProjection<L, R> const & require_down_proj() const;
::FlexFlow::DownProjection<L, R> & require_down_proj();
std::optional<::FlexFlow::UpProjection<L, R>> try_require_up_proj() const;
std::optional<::FlexFlow::EqProjection<L, R>> try_require_eq_proj() const;
std::optional<::FlexFlow::DownProjection<L, R>> try_require_down_proj() const;
bool is_up_proj() const;
bool is_eq_proj() const;
bool is_down_proj() const;
std::string debug_to_string() const;void debug_print() const;std::variant<::FlexFlow::UpProjection<L, R>, ::FlexFlow::EqProjection<L, R>, ::FlexFlow::DownProjection<L, R>> raw_variant;};}// namespace FlexFlow

///\cond
namespace std{template <typename L, typename R>
struct hash<::FlexFlow::DimProjection<L, R>>{size_t operator()(::FlexFlow::DimProjection<L, R> const &) const;
};}// namespace std

///\endcond
namespace nlohmann{template <typename L, typename R>
struct adl_serializer<::FlexFlow::DimProjection<L, R>>{static void to_json(json &, ::FlexFlow::DimProjection<L, R> const &);
};}// namespace nlohmann
namespace FlexFlow{template <typename L, typename R>
std::string format_as(::FlexFlow::DimProjection<L, R> const &);
template <typename L, typename R>
std::ostream & operator<<(std::ostream &, ::FlexFlow::DimProjection<L, R> const &);
}// namespace FlexFlow

namespace FlexFlow{template <typename L, typename R>
DimProjection<L, R>::DimProjection(::FlexFlow::UpProjection<L, R> const &v) : raw_variant(v) { }
template <typename L, typename R>
DimProjection<L, R>::DimProjection(::FlexFlow::EqProjection<L, R> const &v) : raw_variant(v) { }
template <typename L, typename R>
DimProjection<L, R>::DimProjection(::FlexFlow::DownProjection<L, R> const &v) : raw_variant(v) { }template <typename L, typename R>
bool DimProjection<L, R>::operator==(DimProjection<L, R> const &other) const{return this->raw_variant == other.raw_variant;}
template <typename L, typename R>
bool DimProjection<L, R>::operator!=(DimProjection<L, R> const &other) const{return this->raw_variant != other.raw_variant;}
template <typename L, typename R>
bool DimProjection<L, R>::operator<(DimProjection<L, R> const &other) const{return this->raw_variant < other.raw_variant;}
template <typename L, typename R>
bool DimProjection<L, R>::operator>(DimProjection<L, R> const &other) const{return this->raw_variant > other.raw_variant;}
template <typename L, typename R>
bool DimProjection<L, R>::operator<=(DimProjection<L, R> const &other) const{return this->raw_variant <= other.raw_variant;}
template <typename L, typename R>
bool DimProjection<L, R>::operator>=(DimProjection<L, R> const &other) const{return this->raw_variant >= other.raw_variant;}
template <typename L, typename R>
::FlexFlow::UpProjection<L, R> const & DimProjection<L, R>::require_up_proj() const{bool holds_expected = std::holds_alternative<::FlexFlow::UpProjection<L, R>>(this->raw_variant);
ASSERT(holds_expected, "Expected ::FlexFlow::UpProjection<L, R>");
return std::get<::FlexFlow::UpProjection<L, R>>(this->raw_variant);
}
template <typename L, typename R>
::FlexFlow::UpProjection<L, R> & DimProjection<L, R>::require_up_proj(){bool holds_expected = std::holds_alternative<::FlexFlow::UpProjection<L, R>>(this->raw_variant);
ASSERT(holds_expected, "Expected ::FlexFlow::UpProjection<L, R>");
return std::get<::FlexFlow::UpProjection<L, R>>(this->raw_variant);
}
template <typename L, typename R>
::FlexFlow::EqProjection<L, R> const & DimProjection<L, R>::require_eq_proj() const{bool holds_expected = std::holds_alternative<::FlexFlow::EqProjection<L, R>>(this->raw_variant);
ASSERT(holds_expected, "Expected ::FlexFlow::EqProjection<L, R>");
return std::get<::FlexFlow::EqProjection<L, R>>(this->raw_variant);
}
template <typename L, typename R>
::FlexFlow::EqProjection<L, R> & DimProjection<L, R>::require_eq_proj(){bool holds_expected = std::holds_alternative<::FlexFlow::EqProjection<L, R>>(this->raw_variant);
ASSERT(holds_expected, "Expected ::FlexFlow::EqProjection<L, R>");
return std::get<::FlexFlow::EqProjection<L, R>>(this->raw_variant);
}
template <typename L, typename R>
::FlexFlow::DownProjection<L, R> const & DimProjection<L, R>::require_down_proj() const{bool holds_expected = std::holds_alternative<::FlexFlow::DownProjection<L, R>>(this->raw_variant);
ASSERT(holds_expected, "Expected ::FlexFlow::DownProjection<L, R>");
return std::get<::FlexFlow::DownProjection<L, R>>(this->raw_variant);
}
template <typename L, typename R>
::FlexFlow::DownProjection<L, R> & DimProjection<L, R>::require_down_proj(){bool holds_expected = std::holds_alternative<::FlexFlow::DownProjection<L, R>>(this->raw_variant);
ASSERT(holds_expected, "Expected ::FlexFlow::DownProjection<L, R>");
return std::get<::FlexFlow::DownProjection<L, R>>(this->raw_variant);
}
template <typename L, typename R>
std::optional<::FlexFlow::UpProjection<L, R>> DimProjection<L, R>::try_require_up_proj() const{if (this->is_up_proj()) {return this->require_up_proj();
}else {return std::nullopt;
}}
template <typename L, typename R>
std::optional<::FlexFlow::EqProjection<L, R>> DimProjection<L, R>::try_require_eq_proj() const{if (this->is_eq_proj()) {return this->require_eq_proj();
}else {return std::nullopt;
}}
template <typename L, typename R>
std::optional<::FlexFlow::DownProjection<L, R>> DimProjection<L, R>::try_require_down_proj() const{if (this->is_down_proj()) {return this->require_down_proj();
}else {return std::nullopt;
}}
template <typename L, typename R>
bool DimProjection<L, R>::is_up_proj() const{return std::holds_alternative<::FlexFlow::UpProjection<L, R>>(this->raw_variant);
}
template <typename L, typename R>
bool DimProjection<L, R>::is_eq_proj() const{return std::holds_alternative<::FlexFlow::EqProjection<L, R>>(this->raw_variant);
}
template <typename L, typename R>
bool DimProjection<L, R>::is_down_proj() const{return std::holds_alternative<::FlexFlow::DownProjection<L, R>>(this->raw_variant);
}
}// namespace FlexFlow

///\cond
namespace std{template <typename L, typename R>
size_t hash<::FlexFlow::DimProjection<L, R>>::operator()(::FlexFlow::DimProjection<L, R> const &x) const{return std::hash<std::variant<::FlexFlow::UpProjection<L, R>, ::FlexFlow::EqProjection<L, R>, ::FlexFlow::DownProjection<L, R>>>{}(x.raw_variant);}
}// namespace std

///\endcond
namespace nlohmann{template <typename L, typename R>
void adl_serializer<::FlexFlow::DimProjection<L, R>>::to_json(json &j, ::FlexFlow::DimProjection<L, R> const &x){j["__type"] = "DimProjection";
switch (x.index()){case 0:{j["type"] = "up_proj";
j["value"] = x.template get<::FlexFlow::UpProjection<L, R>>();
break;
}case 1:{j["type"] = "eq_proj";
j["value"] = x.template get<::FlexFlow::EqProjection<L, R>>();
break;
}case 2:{j["type"] = "down_proj";
j["value"] = x.template get<::FlexFlow::DownProjection<L, R>>();
break;
}default:{throw std::runtime_error(fmt::format("Unknown index {} for type DimProjection", x.index()));
}}}
}// namespace nlohmann
namespace FlexFlow{template <typename L, typename R>
std::string DimProjection<L, R>::debug_to_string() const{return fmt::to_string(*this);}
template <typename L, typename R>
void DimProjection<L, R>::debug_print() const{std::cout << this->debug_to_string() << std::endl;}
template <typename L, typename R>
std::string format_as(::FlexFlow::DimProjection<L, R> const &x){::nlohmann::json j = x;
return j.dump();
}
template <typename L, typename R>
std::ostream & operator<<(std::ostream &s, ::FlexFlow::DimProjection<L, R> const &x){return s << fmt::to_string(x);
}
}// namespace FlexFlow

#endif // _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_ORTHOTOPE_DIM_PROJECTION_DTG_H
