// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/utils/include/utils/orthotope/down_projection.dtg.toml
/* proj-data
{
  "generated_from": "f2f977b70a45b31b7599a7334c535c4f"
}
*/

#ifndef _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_ORTHOTOPE_DOWN_PROJECTION_DTG_H
#define _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_ORTHOTOPE_DOWN_PROJECTION_DTG_H

#include <tuple>
#include <iostream>
#include <ostream>
#include "utils/many_to_one/many_to_one.h"
#include <fmt/format.h>
#include <nlohmann/json.hpp>
#include <functional>
#include <sstream>


namespace FlexFlow{template <typename L, typename R>
struct DownProjection{DownProjection() = delete;
explicit DownProjection(::FlexFlow::ManyToOne<L, R> const &dim_mapping);

bool operator==(DownProjection const &) const;bool operator!=(DownProjection const &) const;
bool operator<(DownProjection const &) const;bool operator>(DownProjection const &) const;bool operator<=(DownProjection const &) const;bool operator>=(DownProjection const &) const;
std::string debug_to_string() const;void debug_print() const;
::FlexFlow::ManyToOne<L, R> dim_mapping;
};}// namespace FlexFlow


///\cond
namespace std{template <typename L, typename R>
struct hash<::FlexFlow::DownProjection<L, R>>{size_t operator()(::FlexFlow::DownProjection<L, R> const &)const;};}// namespace std

///\endcond

namespace nlohmann{template <typename L, typename R>
struct adl_serializer<::FlexFlow::DownProjection<L, R>>{static void to_json(json &, ::FlexFlow::DownProjection<L, R> const &);
};}// namespace nlohmann

namespace FlexFlow{template <typename L, typename R>
std::string format_as(DownProjection<L, R> const &);
template <typename L, typename R>
std::ostream &operator<<(std::ostream &, DownProjection<L, R> const &);}// namespace FlexFlow

namespace FlexFlow{template <typename L, typename R>
DownProjection<L, R>::DownProjection(::FlexFlow::ManyToOne<L, R> const &dim_mapping) : dim_mapping(dim_mapping){}
template <typename L, typename R>
bool DownProjection<L, R>::operator==(DownProjection<L, R> const &other) const{
return std::tie(this->dim_mapping) == std::tie(other.dim_mapping);
}template <typename L, typename R>
bool DownProjection<L, R>::operator!=(DownProjection<L, R> const &other) const{
return std::tie(this->dim_mapping) != std::tie(other.dim_mapping);
}template <typename L, typename R>
bool DownProjection<L, R>::operator<(DownProjection<L, R> const &other) const{
return std::tie(this->dim_mapping) < std::tie(other.dim_mapping);
}template <typename L, typename R>
bool DownProjection<L, R>::operator>(DownProjection<L, R> const &other) const{
return std::tie(this->dim_mapping) > std::tie(other.dim_mapping);
}template <typename L, typename R>
bool DownProjection<L, R>::operator<=(DownProjection<L, R> const &other) const{
return std::tie(this->dim_mapping) <= std::tie(other.dim_mapping);
}template <typename L, typename R>
bool DownProjection<L, R>::operator>=(DownProjection<L, R> const &other) const{
return std::tie(this->dim_mapping) >= std::tie(other.dim_mapping);
}}// namespace FlexFlow


///\cond
namespace std{template <typename L, typename R>
size_t hash<FlexFlow::DownProjection<L, R>>::operator()(::FlexFlow::DownProjection<L, R> const &x)const{size_t result = 0;
result ^= std::hash<::FlexFlow::ManyToOne<L, R>>{}(x.dim_mapping) + 0x9e3779b9 + (result << 6) + (result >> 2);return result;
}}// namespace std

///\endcond

namespace nlohmann{template <typename L, typename R>
void adl_serializer<::FlexFlow::DownProjection<L, R>>::to_json(json &j, ::FlexFlow::DownProjection<L, R> const &v) {j["__type"] = "DownProjection";
j["dim_mapping"] = v.dim_mapping;
}}// namespace nlohmann

namespace FlexFlow{template <typename L, typename R>
std::string DownProjection<L, R>::debug_to_string() const { return fmt::to_string(*this); }template <typename L, typename R>
void DownProjection<L, R>::debug_print() const { std::cout << this->debug_to_string() << std::endl; }template <typename L, typename R>
std::string format_as(DownProjection<L, R> const &x){::nlohmann::json j = x;
return j.dump();
}template <typename L, typename R>
std::ostream &operator<<(std::ostream &s, DownProjection<L, R> const &x) {return s << fmt::to_string(x);}}// namespace FlexFlow

#endif // _FLEXFLOW_LIB_UTILS_INCLUDE_UTILS_ORTHOTOPE_DOWN_PROJECTION_DTG_H
