// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/models/include/models/bert/bert_config.dtg.toml
/* proj-data
{
  "generated_from": "a4483e82e41e66414902783886bca90e"
}
*/

#include "models/bert/bert_config.dtg.h"

#include <sstream>

namespace FlexFlow{BertConfig::BertConfig(::FlexFlow::positive_int const &vocab_size, ::FlexFlow::positive_int const &hidden_size, ::FlexFlow::positive_int const &num_encoder_layers, ::FlexFlow::positive_int const &num_heads, ::FlexFlow::positive_int const &dim_feedforward, ::FlexFlow::Activation const &hidden_act, float const &hidden_dropout_prob, float const &attention_probs_dropout_prob, float const &initializer_range, float const &layer_norm_eps, std::string const &position_embedding_type, float const &classifier_dropout, ::FlexFlow::positive_int const &sequence_length, ::FlexFlow::positive_int const &batch_size) : vocab_size(vocab_size), hidden_size(hidden_size), num_encoder_layers(num_encoder_layers), num_heads(num_heads), dim_feedforward(dim_feedforward), hidden_act(hidden_act), hidden_dropout_prob(hidden_dropout_prob), attention_probs_dropout_prob(attention_probs_dropout_prob), initializer_range(initializer_range), layer_norm_eps(layer_norm_eps), position_embedding_type(position_embedding_type), classifier_dropout(classifier_dropout), sequence_length(sequence_length), batch_size(batch_size){}
bool BertConfig::operator==(BertConfig const &other) const{
return std::tie(this->vocab_size, this->hidden_size, this->num_encoder_layers, this->num_heads, this->dim_feedforward, this->hidden_act, this->hidden_dropout_prob, this->attention_probs_dropout_prob, this->initializer_range, this->layer_norm_eps, this->position_embedding_type, this->classifier_dropout, this->sequence_length, this->batch_size) == std::tie(other.vocab_size, other.hidden_size, other.num_encoder_layers, other.num_heads, other.dim_feedforward, other.hidden_act, other.hidden_dropout_prob, other.attention_probs_dropout_prob, other.initializer_range, other.layer_norm_eps, other.position_embedding_type, other.classifier_dropout, other.sequence_length, other.batch_size);
}bool BertConfig::operator!=(BertConfig const &other) const{
return std::tie(this->vocab_size, this->hidden_size, this->num_encoder_layers, this->num_heads, this->dim_feedforward, this->hidden_act, this->hidden_dropout_prob, this->attention_probs_dropout_prob, this->initializer_range, this->layer_norm_eps, this->position_embedding_type, this->classifier_dropout, this->sequence_length, this->batch_size) != std::tie(other.vocab_size, other.hidden_size, other.num_encoder_layers, other.num_heads, other.dim_feedforward, other.hidden_act, other.hidden_dropout_prob, other.attention_probs_dropout_prob, other.initializer_range, other.layer_norm_eps, other.position_embedding_type, other.classifier_dropout, other.sequence_length, other.batch_size);
}bool BertConfig::operator<(BertConfig const &other) const{
return std::tie(this->vocab_size, this->hidden_size, this->num_encoder_layers, this->num_heads, this->dim_feedforward, this->hidden_act, this->hidden_dropout_prob, this->attention_probs_dropout_prob, this->initializer_range, this->layer_norm_eps, this->position_embedding_type, this->classifier_dropout, this->sequence_length, this->batch_size) < std::tie(other.vocab_size, other.hidden_size, other.num_encoder_layers, other.num_heads, other.dim_feedforward, other.hidden_act, other.hidden_dropout_prob, other.attention_probs_dropout_prob, other.initializer_range, other.layer_norm_eps, other.position_embedding_type, other.classifier_dropout, other.sequence_length, other.batch_size);
}bool BertConfig::operator>(BertConfig const &other) const{
return std::tie(this->vocab_size, this->hidden_size, this->num_encoder_layers, this->num_heads, this->dim_feedforward, this->hidden_act, this->hidden_dropout_prob, this->attention_probs_dropout_prob, this->initializer_range, this->layer_norm_eps, this->position_embedding_type, this->classifier_dropout, this->sequence_length, this->batch_size) > std::tie(other.vocab_size, other.hidden_size, other.num_encoder_layers, other.num_heads, other.dim_feedforward, other.hidden_act, other.hidden_dropout_prob, other.attention_probs_dropout_prob, other.initializer_range, other.layer_norm_eps, other.position_embedding_type, other.classifier_dropout, other.sequence_length, other.batch_size);
}bool BertConfig::operator<=(BertConfig const &other) const{
return std::tie(this->vocab_size, this->hidden_size, this->num_encoder_layers, this->num_heads, this->dim_feedforward, this->hidden_act, this->hidden_dropout_prob, this->attention_probs_dropout_prob, this->initializer_range, this->layer_norm_eps, this->position_embedding_type, this->classifier_dropout, this->sequence_length, this->batch_size) <= std::tie(other.vocab_size, other.hidden_size, other.num_encoder_layers, other.num_heads, other.dim_feedforward, other.hidden_act, other.hidden_dropout_prob, other.attention_probs_dropout_prob, other.initializer_range, other.layer_norm_eps, other.position_embedding_type, other.classifier_dropout, other.sequence_length, other.batch_size);
}bool BertConfig::operator>=(BertConfig const &other) const{
return std::tie(this->vocab_size, this->hidden_size, this->num_encoder_layers, this->num_heads, this->dim_feedforward, this->hidden_act, this->hidden_dropout_prob, this->attention_probs_dropout_prob, this->initializer_range, this->layer_norm_eps, this->position_embedding_type, this->classifier_dropout, this->sequence_length, this->batch_size) >= std::tie(other.vocab_size, other.hidden_size, other.num_encoder_layers, other.num_heads, other.dim_feedforward, other.hidden_act, other.hidden_dropout_prob, other.attention_probs_dropout_prob, other.initializer_range, other.layer_norm_eps, other.position_embedding_type, other.classifier_dropout, other.sequence_length, other.batch_size);
}}// namespace FlexFlow


///\cond
namespace std{size_t hash<FlexFlow::BertConfig>::operator()(::FlexFlow::BertConfig const &x)const{size_t result = 0;
result ^= std::hash<::FlexFlow::positive_int>{}(x.vocab_size) + 0x9e3779b9 + (result << 6) + (result >> 2);result ^= std::hash<::FlexFlow::positive_int>{}(x.hidden_size) + 0x9e3779b9 + (result << 6) + (result >> 2);result ^= std::hash<::FlexFlow::positive_int>{}(x.num_encoder_layers) + 0x9e3779b9 + (result << 6) + (result >> 2);result ^= std::hash<::FlexFlow::positive_int>{}(x.num_heads) + 0x9e3779b9 + (result << 6) + (result >> 2);result ^= std::hash<::FlexFlow::positive_int>{}(x.dim_feedforward) + 0x9e3779b9 + (result << 6) + (result >> 2);result ^= std::hash<::FlexFlow::Activation>{}(x.hidden_act) + 0x9e3779b9 + (result << 6) + (result >> 2);result ^= std::hash<float>{}(x.hidden_dropout_prob) + 0x9e3779b9 + (result << 6) + (result >> 2);result ^= std::hash<float>{}(x.attention_probs_dropout_prob) + 0x9e3779b9 + (result << 6) + (result >> 2);result ^= std::hash<float>{}(x.initializer_range) + 0x9e3779b9 + (result << 6) + (result >> 2);result ^= std::hash<float>{}(x.layer_norm_eps) + 0x9e3779b9 + (result << 6) + (result >> 2);result ^= std::hash<std::string>{}(x.position_embedding_type) + 0x9e3779b9 + (result << 6) + (result >> 2);result ^= std::hash<float>{}(x.classifier_dropout) + 0x9e3779b9 + (result << 6) + (result >> 2);result ^= std::hash<::FlexFlow::positive_int>{}(x.sequence_length) + 0x9e3779b9 + (result << 6) + (result >> 2);result ^= std::hash<::FlexFlow::positive_int>{}(x.batch_size) + 0x9e3779b9 + (result << 6) + (result >> 2);return result;
}}// namespace std

///\endcond

namespace nlohmann{void adl_serializer<::FlexFlow::BertConfig>::to_json(json &j, ::FlexFlow::BertConfig const &v) {j["__type"] = "BertConfig";
j["vocab_size"] = v.vocab_size;
j["hidden_size"] = v.hidden_size;
j["num_encoder_layers"] = v.num_encoder_layers;
j["num_heads"] = v.num_heads;
j["dim_feedforward"] = v.dim_feedforward;
j["hidden_act"] = v.hidden_act;
j["hidden_dropout_prob"] = v.hidden_dropout_prob;
j["attention_probs_dropout_prob"] = v.attention_probs_dropout_prob;
j["initializer_range"] = v.initializer_range;
j["layer_norm_eps"] = v.layer_norm_eps;
j["position_embedding_type"] = v.position_embedding_type;
j["classifier_dropout"] = v.classifier_dropout;
j["sequence_length"] = v.sequence_length;
j["batch_size"] = v.batch_size;
}}// namespace nlohmann

namespace nlohmann{::FlexFlow::BertConfig adl_serializer<::FlexFlow::BertConfig>::from_json(json const &j) {return ::FlexFlow::BertConfig{j.at("vocab_size").template get<::FlexFlow::positive_int>(), j.at("hidden_size").template get<::FlexFlow::positive_int>(), j.at("num_encoder_layers").template get<::FlexFlow::positive_int>(), j.at("num_heads").template get<::FlexFlow::positive_int>(), j.at("dim_feedforward").template get<::FlexFlow::positive_int>(), j.at("hidden_act").template get<::FlexFlow::Activation>(), j.at("hidden_dropout_prob").template get<float>(), j.at("attention_probs_dropout_prob").template get<float>(), j.at("initializer_range").template get<float>(), j.at("layer_norm_eps").template get<float>(), j.at("position_embedding_type").template get<std::string>(), j.at("classifier_dropout").template get<float>(), j.at("sequence_length").template get<::FlexFlow::positive_int>(), j.at("batch_size").template get<::FlexFlow::positive_int>()};}}// namespace nlohmann

namespace rc{Gen<::FlexFlow::BertConfig> Arbitrary<::FlexFlow::BertConfig>::arbitrary() {return gen::construct<::FlexFlow::BertConfig>(gen::arbitrary<::FlexFlow::positive_int>(), gen::arbitrary<::FlexFlow::positive_int>(), gen::arbitrary<::FlexFlow::positive_int>(), gen::arbitrary<::FlexFlow::positive_int>(), gen::arbitrary<::FlexFlow::positive_int>(), gen::arbitrary<::FlexFlow::Activation>(), gen::arbitrary<float>(), gen::arbitrary<float>(), gen::arbitrary<float>(), gen::arbitrary<float>(), gen::arbitrary<std::string>(), gen::arbitrary<float>(), gen::arbitrary<::FlexFlow::positive_int>(), gen::arbitrary<::FlexFlow::positive_int>());}}// namespace rc

namespace FlexFlow{std::string BertConfig::debug_to_string() const { return fmt::to_string(*this); }void BertConfig::debug_print() const { std::cout << this->debug_to_string() << std::endl; }std::string format_as(BertConfig const &x){::nlohmann::json j = x;
return j.dump();
}std::ostream &operator<<(std::ostream &s, BertConfig const &x) {return s << fmt::to_string(x);}}// namespace FlexFlow
