// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/substitutions/include/substitutions/output_graph/output_graph_expr_value.dtg.toml
/* proj-data
{
  "generated_from": "fd23bc15939de0fcd3eb49c409479e11"
}
*/

#ifndef _FLEXFLOW_LIB_SUBSTITUTIONS_INCLUDE_SUBSTITUTIONS_OUTPUT_GRAPH_OUTPUT_GRAPH_EXPR_VALUE_DTG_H
#define _FLEXFLOW_LIB_SUBSTITUTIONS_INCLUDE_SUBSTITUTIONS_OUTPUT_GRAPH_OUTPUT_GRAPH_EXPR_VALUE_DTG_H

#include <cstddef>
#include <fmt/format.h>
#include <functional>
#include <iostream>
#include <libassert/assert.hpp>
#include <nlohmann/json.hpp>
#include <optional>
#include <ostream>
#include <stdexcept>
#include "substitutions/output_graph/output_graph_expr_input.dtg.h"
#include "substitutions/output_graph/output_graph_expr_node_output.dtg.h"
#include <type_traits>
#include <variant>

namespace FlexFlow{struct OutputGraphExprValue{OutputGraphExprValue() = delete;
explicit OutputGraphExprValue(::FlexFlow::OutputGraphExprNodeOutput const &);
explicit OutputGraphExprValue(::FlexFlow::OutputGraphExprInput const &);template <typename T>
static constexpr bool IsPartOfOutputGraphExprValue_v =std::is_same_v<T, ::FlexFlow::OutputGraphExprNodeOutput> || std::is_same_v<T, ::FlexFlow::OutputGraphExprInput>;template <typename ReturnType, typename Visitor>
ReturnType visit(Visitor &&v) const{switch (this->index()){case 0: {ReturnType result = v(this->get<::FlexFlow::OutputGraphExprNodeOutput>());
return result;
}case 1: {ReturnType result = v(this->get<::FlexFlow::OutputGraphExprInput>());
return result;
}default: {throw std::runtime_error(fmt::format("Unknown index {} for type OutputGraphExprValue", this->index()));
}}}
template <typename ReturnType, typename Visitor>
ReturnType visit(Visitor &&v){switch (this->index()){case 0: {ReturnType result = v(this->get<::FlexFlow::OutputGraphExprNodeOutput>());
return result;
}case 1: {ReturnType result = v(this->get<::FlexFlow::OutputGraphExprInput>());
return result;
}default: {throw std::runtime_error(fmt::format("Unknown index {} for type OutputGraphExprValue", this->index()));
}}}
template <typename T>
bool has() const{static_assert(IsPartOfOutputGraphExprValue_v<T>, "OutputGraphExprValue::has() expected one of [::FlexFlow::OutputGraphExprNodeOutput, ::FlexFlow::OutputGraphExprInput], received T");return std::holds_alternative<T>(this->raw_variant);}
template <typename T>
T const & get() const{static_assert(IsPartOfOutputGraphExprValue_v<T>, "OutputGraphExprValue::get() expected one of [::FlexFlow::OutputGraphExprNodeOutput, ::FlexFlow::OutputGraphExprInput], received T");bool holds_expected = std::holds_alternative<T>(this->raw_variant);
ASSERT(holds_expected);
return std::get<T>(this->raw_variant);
}
template <typename T>
T  & get(){static_assert(IsPartOfOutputGraphExprValue_v<T>, "OutputGraphExprValue::get() expected one of [::FlexFlow::OutputGraphExprNodeOutput, ::FlexFlow::OutputGraphExprInput], received T");bool holds_expected = std::holds_alternative<T>(this->raw_variant);
ASSERT(holds_expected);
return std::get<T>(this->raw_variant);
}
size_t index() const { return this->raw_variant.index(); }
bool operator==(OutputGraphExprValue const &) const;bool operator!=(OutputGraphExprValue const &) const;bool operator<(OutputGraphExprValue const &) const;bool operator>(OutputGraphExprValue const &) const;bool operator<=(OutputGraphExprValue const &) const;bool operator>=(OutputGraphExprValue const &) const;std::string debug_to_string() const;void debug_print() const;std::variant<::FlexFlow::OutputGraphExprNodeOutput, ::FlexFlow::OutputGraphExprInput> raw_variant;};}// namespace FlexFlow

///\cond
namespace std{template <>
struct hash<::FlexFlow::OutputGraphExprValue>{size_t operator()(::FlexFlow::OutputGraphExprValue const &) const;
};}// namespace std

///\endcond
namespace nlohmann{template <>
struct adl_serializer<::FlexFlow::OutputGraphExprValue>{static void to_json(json &, ::FlexFlow::OutputGraphExprValue const &);
};}// namespace nlohmann
namespace FlexFlow{std::string format_as(::FlexFlow::OutputGraphExprValue const &);
std::ostream & operator<<(std::ostream &, ::FlexFlow::OutputGraphExprValue const &);
}// namespace FlexFlow

#endif // _FLEXFLOW_LIB_SUBSTITUTIONS_INCLUDE_SUBSTITUTIONS_OUTPUT_GRAPH_OUTPUT_GRAPH_EXPR_VALUE_DTG_H
