// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/substitutions/include/substitutions/output_graph/output_graph_expr_node.dtg.toml
/* proj-data
{
  "generated_from": "55954afe2506c90d530100916a643a27"
}
*/

#ifndef _FLEXFLOW_LIB_SUBSTITUTIONS_INCLUDE_SUBSTITUTIONS_OUTPUT_GRAPH_OUTPUT_GRAPH_EXPR_NODE_DTG_H
#define _FLEXFLOW_LIB_SUBSTITUTIONS_INCLUDE_SUBSTITUTIONS_OUTPUT_GRAPH_OUTPUT_GRAPH_EXPR_NODE_DTG_H

#include <tuple>
#include <iostream>
#include <ostream>
#include <fmt/format.h>
#include <nlohmann/json.hpp>
#include <functional>
#include "utils/graph/node/node.dtg.h"


namespace FlexFlow{struct OutputGraphExprNode{OutputGraphExprNode() = delete;
explicit OutputGraphExprNode(::FlexFlow::Node const &raw_graph_node);

bool operator==(OutputGraphExprNode const &) const;bool operator!=(OutputGraphExprNode const &) const;
bool operator<(OutputGraphExprNode const &) const;bool operator>(OutputGraphExprNode const &) const;bool operator<=(OutputGraphExprNode const &) const;bool operator>=(OutputGraphExprNode const &) const;
std::string debug_to_string() const;void debug_print() const;
::FlexFlow::Node raw_graph_node;
};}// namespace FlexFlow


///\cond
namespace std{template <>
struct hash<::FlexFlow::OutputGraphExprNode>{size_t operator()(::FlexFlow::OutputGraphExprNode const &)const;};}// namespace std

///\endcond

namespace nlohmann{template <>
struct adl_serializer<::FlexFlow::OutputGraphExprNode>{static void to_json(json &, ::FlexFlow::OutputGraphExprNode const &);
};}// namespace nlohmann

namespace FlexFlow{std::string format_as(OutputGraphExprNode const &);
std::ostream &operator<<(std::ostream &, OutputGraphExprNode const &);}// namespace FlexFlow

#endif // _FLEXFLOW_LIB_SUBSTITUTIONS_INCLUDE_SUBSTITUTIONS_OUTPUT_GRAPH_OUTPUT_GRAPH_EXPR_NODE_DTG_H
