// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/substitutions/include/substitutions/output_graph/output_graph_expr_node_output.dtg.toml
/* proj-data
{
  "generated_from": "e8d1c6939c49cbe80e4d25cd579a6a08"
}
*/

#ifndef _FLEXFLOW_LIB_SUBSTITUTIONS_INCLUDE_SUBSTITUTIONS_OUTPUT_GRAPH_OUTPUT_GRAPH_EXPR_NODE_OUTPUT_DTG_H
#define _FLEXFLOW_LIB_SUBSTITUTIONS_INCLUDE_SUBSTITUTIONS_OUTPUT_GRAPH_OUTPUT_GRAPH_EXPR_NODE_OUTPUT_DTG_H

#include <tuple>
#include <iostream>
#include <functional>
#include <ostream>
#include <fmt/format.h>
#include "op-attrs/tensor_slot_name.dtg.h"
#include <nlohmann/json.hpp>
#include "utils/graph/kwarg_dataflow_graph/kwarg_dataflow_output.dtg.h"


namespace FlexFlow{struct OutputGraphExprNodeOutput{OutputGraphExprNodeOutput() = delete;
explicit OutputGraphExprNodeOutput(::FlexFlow::KwargDataflowOutput<::FlexFlow::TensorSlotName> const &raw_dataflow_output);

bool operator==(OutputGraphExprNodeOutput const &) const;bool operator!=(OutputGraphExprNodeOutput const &) const;
bool operator<(OutputGraphExprNodeOutput const &) const;bool operator>(OutputGraphExprNodeOutput const &) const;bool operator<=(OutputGraphExprNodeOutput const &) const;bool operator>=(OutputGraphExprNodeOutput const &) const;
std::string debug_to_string() const;void debug_print() const;
::FlexFlow::KwargDataflowOutput<::FlexFlow::TensorSlotName> raw_dataflow_output;
};}// namespace FlexFlow


///\cond
namespace std{template <>
struct hash<::FlexFlow::OutputGraphExprNodeOutput>{size_t operator()(::FlexFlow::OutputGraphExprNodeOutput const &)const;};}// namespace std

///\endcond

namespace nlohmann{template <>
struct adl_serializer<::FlexFlow::OutputGraphExprNodeOutput>{static void to_json(json &, ::FlexFlow::OutputGraphExprNodeOutput const &);
};}// namespace nlohmann

namespace FlexFlow{std::string format_as(OutputGraphExprNodeOutput const &);
std::ostream &operator<<(std::ostream &, OutputGraphExprNodeOutput const &);}// namespace FlexFlow

#endif // _FLEXFLOW_LIB_SUBSTITUTIONS_INCLUDE_SUBSTITUTIONS_OUTPUT_GRAPH_OUTPUT_GRAPH_EXPR_NODE_OUTPUT_DTG_H
