// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/utils/include/utils/cli/cli_named_argument_key.dtg.toml
/* proj-data
{
  "generated_from": "5e3d584c7181dd842922dae7ed381442"
}
*/

#include "utils/cli/cli_named_argument_key.dtg.h"

#include <sstream>

namespace FlexFlow{CLINamedArgumentKey::CLINamedArgumentKey(::FlexFlow::nonnegative_int const &raw_idx) : raw_idx(raw_idx){}
bool CLINamedArgumentKey::operator==(CLINamedArgumentKey const &other) const{
return std::tie(this->raw_idx) == std::tie(other.raw_idx);
}bool CLINamedArgumentKey::operator!=(CLINamedArgumentKey const &other) const{
return std::tie(this->raw_idx) != std::tie(other.raw_idx);
}bool CLINamedArgumentKey::operator<(CLINamedArgumentKey const &other) const{
return std::tie(this->raw_idx) < std::tie(other.raw_idx);
}bool CLINamedArgumentKey::operator>(CLINamedArgumentKey const &other) const{
return std::tie(this->raw_idx) > std::tie(other.raw_idx);
}bool CLINamedArgumentKey::operator<=(CLINamedArgumentKey const &other) const{
return std::tie(this->raw_idx) <= std::tie(other.raw_idx);
}bool CLINamedArgumentKey::operator>=(CLINamedArgumentKey const &other) const{
return std::tie(this->raw_idx) >= std::tie(other.raw_idx);
}}// namespace FlexFlow


///\cond
namespace std{size_t hash<FlexFlow::CLINamedArgumentKey>::operator()(::FlexFlow::CLINamedArgumentKey const &x)const{size_t result = 0;
result ^= std::hash<::FlexFlow::nonnegative_int>{}(x.raw_idx) + 0x9e3779b9 + (result << 6) + (result >> 2);return result;
}}// namespace std

///\endcond

namespace nlohmann{void adl_serializer<::FlexFlow::CLINamedArgumentKey>::to_json(json &j, ::FlexFlow::CLINamedArgumentKey const &v) {j["__type"] = "CLINamedArgumentKey";
j["raw_idx"] = v.raw_idx;
}}// namespace nlohmann

namespace FlexFlow{std::string CLINamedArgumentKey::debug_to_string() const { return fmt::to_string(*this); }void CLINamedArgumentKey::debug_print() const { std::cout << this->debug_to_string() << std::endl; }std::string format_as(CLINamedArgumentKey const &x){::nlohmann::json j = x;
return j.dump();
}std::ostream &operator<<(std::ostream &s, CLINamedArgumentKey const &x) {return s << fmt::to_string(x);}}// namespace FlexFlow
