// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/utils/include/utils/cli/cli_flag_spec.dtg.toml
/* proj-data
{
  "generated_from": "785ef7576db181d52905c19fdde9ddac"
}
*/

#include "utils/cli/cli_flag_spec.dtg.h"

#include <sstream>
#include "utils/json/optional.h"
#include "utils/fmt/optional.h"

namespace FlexFlow{CLIFlagSpec::CLIFlagSpec(std::string const &long_flag, std::optional<char> const &short_flag, std::optional<std::string> const &description) : long_flag(long_flag), short_flag(short_flag), description(description){}
bool CLIFlagSpec::operator==(CLIFlagSpec const &other) const{
return std::tie(this->long_flag, this->short_flag, this->description) == std::tie(other.long_flag, other.short_flag, other.description);
}bool CLIFlagSpec::operator!=(CLIFlagSpec const &other) const{
return std::tie(this->long_flag, this->short_flag, this->description) != std::tie(other.long_flag, other.short_flag, other.description);
}bool CLIFlagSpec::operator<(CLIFlagSpec const &other) const{
return std::tie(this->long_flag, this->short_flag, this->description) < std::tie(other.long_flag, other.short_flag, other.description);
}bool CLIFlagSpec::operator>(CLIFlagSpec const &other) const{
return std::tie(this->long_flag, this->short_flag, this->description) > std::tie(other.long_flag, other.short_flag, other.description);
}bool CLIFlagSpec::operator<=(CLIFlagSpec const &other) const{
return std::tie(this->long_flag, this->short_flag, this->description) <= std::tie(other.long_flag, other.short_flag, other.description);
}bool CLIFlagSpec::operator>=(CLIFlagSpec const &other) const{
return std::tie(this->long_flag, this->short_flag, this->description) >= std::tie(other.long_flag, other.short_flag, other.description);
}}// namespace FlexFlow


///\cond
namespace std{size_t hash<FlexFlow::CLIFlagSpec>::operator()(::FlexFlow::CLIFlagSpec const &x)const{size_t result = 0;
result ^= std::hash<std::string>{}(x.long_flag) + 0x9e3779b9 + (result << 6) + (result >> 2);result ^= std::hash<std::optional<char>>{}(x.short_flag) + 0x9e3779b9 + (result << 6) + (result >> 2);result ^= std::hash<std::optional<std::string>>{}(x.description) + 0x9e3779b9 + (result << 6) + (result >> 2);return result;
}}// namespace std

///\endcond

namespace nlohmann{void adl_serializer<::FlexFlow::CLIFlagSpec>::to_json(json &j, ::FlexFlow::CLIFlagSpec const &v) {j["__type"] = "CLIFlagSpec";
j["long_flag"] = v.long_flag;
j["short_flag"] = v.short_flag;
j["description"] = v.description;
}}// namespace nlohmann

namespace nlohmann{::FlexFlow::CLIFlagSpec adl_serializer<::FlexFlow::CLIFlagSpec>::from_json(json const &j) {return ::FlexFlow::CLIFlagSpec{j.at("long_flag").template get<std::string>(), j.at("short_flag").template get<std::optional<char>>(), j.at("description").template get<std::optional<std::string>>()};}}// namespace nlohmann

namespace FlexFlow{std::string CLIFlagSpec::debug_to_string() const { return fmt::to_string(*this); }void CLIFlagSpec::debug_print() const { std::cout << this->debug_to_string() << std::endl; }std::string format_as(CLIFlagSpec const &x){::nlohmann::json j = x;
return j.dump();
}std::ostream &operator<<(std::ostream &s, CLIFlagSpec const &x) {return s << fmt::to_string(x);}}// namespace FlexFlow
