// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/substitutions/include/substitutions/input_parallel_tensor_guid_t.dtg.toml
/* proj-data
{
  "generated_from": "96e270db5ff0134101962a0a603cf37c"
}
*/

#include "substitutions/input_parallel_tensor_guid_t.dtg.h"

#include <sstream>

namespace FlexFlow{input_parallel_tensor_guid_t::input_parallel_tensor_guid_t(::FlexFlow::KwargDataflowGraphInput<int> const &raw_dataflow_graph_input) : raw_dataflow_graph_input(raw_dataflow_graph_input){}
bool input_parallel_tensor_guid_t::operator==(input_parallel_tensor_guid_t const &other) const{
return std::tie(this->raw_dataflow_graph_input) == std::tie(other.raw_dataflow_graph_input);
}bool input_parallel_tensor_guid_t::operator!=(input_parallel_tensor_guid_t const &other) const{
return std::tie(this->raw_dataflow_graph_input) != std::tie(other.raw_dataflow_graph_input);
}bool input_parallel_tensor_guid_t::operator<(input_parallel_tensor_guid_t const &other) const{
return std::tie(this->raw_dataflow_graph_input) < std::tie(other.raw_dataflow_graph_input);
}bool input_parallel_tensor_guid_t::operator>(input_parallel_tensor_guid_t const &other) const{
return std::tie(this->raw_dataflow_graph_input) > std::tie(other.raw_dataflow_graph_input);
}bool input_parallel_tensor_guid_t::operator<=(input_parallel_tensor_guid_t const &other) const{
return std::tie(this->raw_dataflow_graph_input) <= std::tie(other.raw_dataflow_graph_input);
}bool input_parallel_tensor_guid_t::operator>=(input_parallel_tensor_guid_t const &other) const{
return std::tie(this->raw_dataflow_graph_input) >= std::tie(other.raw_dataflow_graph_input);
}}// namespace FlexFlow


///\cond
namespace std{size_t hash<FlexFlow::input_parallel_tensor_guid_t>::operator()(::FlexFlow::input_parallel_tensor_guid_t const &x)const{size_t result = 0;
result ^= std::hash<::FlexFlow::KwargDataflowGraphInput<int>>{}(x.raw_dataflow_graph_input) + 0x9e3779b9 + (result << 6) + (result >> 2);return result;
}}// namespace std

///\endcond

namespace nlohmann{void adl_serializer<::FlexFlow::input_parallel_tensor_guid_t>::to_json(json &j, ::FlexFlow::input_parallel_tensor_guid_t const &v) {j["__type"] = "input_parallel_tensor_guid_t";
j["raw_dataflow_graph_input"] = v.raw_dataflow_graph_input;
}}// namespace nlohmann

namespace FlexFlow{std::string input_parallel_tensor_guid_t::debug_to_string() const { return fmt::to_string(*this); }void input_parallel_tensor_guid_t::debug_print() const { std::cout << this->debug_to_string() << std::endl; }std::string format_as(input_parallel_tensor_guid_t const &x){::nlohmann::json j = x;
return j.dump();
}std::ostream &operator<<(std::ostream &s, input_parallel_tensor_guid_t const &x) {return s << fmt::to_string(x);}}// namespace FlexFlow
