// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/utils/include/utils/orthotope/dim_projection.dtg.toml
/* proj-data
{
  "generated_from": "d94585a675c9fa8df3c75bcb78f5a816"
}
*/

#include "utils/orthotope/dim_projection.dtg.h"

