// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/utils/include/utils/orthotope/dim_ordering.dtg.toml
/* proj-data
{
  "generated_from": "66eb5f81c59ade9a3dc1664304cdf1ea"
}
*/

#include "utils/orthotope/dim_ordering.dtg.h"

