// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/utils/include/utils/orthotope/minimal_dim_domain.dtg.toml
/* proj-data
{
  "generated_from": "908fc094f0ca5d45648cdc6510912d47"
}
*/

#include "utils/orthotope/minimal_dim_domain.dtg.h"

