// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/utils/include/utils/orthotope/minimal_orthotope.dtg.toml
/* proj-data
{
  "generated_from": "f78c324d8d5bcc7c20f465acc0c84738"
}
*/

#include "utils/orthotope/minimal_orthotope.dtg.h"

#include "utils/fmt/vector.h"
#include "utils/hash/vector.h"
#include <sstream>

namespace FlexFlow{MinimalOrthotope::MinimalOrthotope(std::vector<::FlexFlow::int_ge_two> const &dims) : dims(dims){}
bool MinimalOrthotope::operator==(MinimalOrthotope const &other) const{
return std::tie(this->dims) == std::tie(other.dims);
}bool MinimalOrthotope::operator!=(MinimalOrthotope const &other) const{
return std::tie(this->dims) != std::tie(other.dims);
}bool MinimalOrthotope::operator<(MinimalOrthotope const &other) const{
return std::tie(this->dims) < std::tie(other.dims);
}bool MinimalOrthotope::operator>(MinimalOrthotope const &other) const{
return std::tie(this->dims) > std::tie(other.dims);
}bool MinimalOrthotope::operator<=(MinimalOrthotope const &other) const{
return std::tie(this->dims) <= std::tie(other.dims);
}bool MinimalOrthotope::operator>=(MinimalOrthotope const &other) const{
return std::tie(this->dims) >= std::tie(other.dims);
}}// namespace FlexFlow


///\cond
namespace std{size_t hash<FlexFlow::MinimalOrthotope>::operator()(::FlexFlow::MinimalOrthotope const &x)const{size_t result = 0;
result ^= std::hash<std::vector<::FlexFlow::int_ge_two>>{}(x.dims) + 0x9e3779b9 + (result << 6) + (result >> 2);return result;
}}// namespace std

///\endcond

namespace nlohmann{void adl_serializer<::FlexFlow::MinimalOrthotope>::to_json(json &j, ::FlexFlow::MinimalOrthotope const &v) {j["__type"] = "MinimalOrthotope";
j["dims"] = v.dims;
}}// namespace nlohmann

namespace nlohmann{::FlexFlow::MinimalOrthotope adl_serializer<::FlexFlow::MinimalOrthotope>::from_json(json const &j) {return ::FlexFlow::MinimalOrthotope{j.at("dims").template get<std::vector<::FlexFlow::int_ge_two>>()};}}// namespace nlohmann

namespace rc{Gen<::FlexFlow::MinimalOrthotope> Arbitrary<::FlexFlow::MinimalOrthotope>::arbitrary() {return gen::construct<::FlexFlow::MinimalOrthotope>(gen::arbitrary<std::vector<::FlexFlow::int_ge_two>>());}}// namespace rc

namespace FlexFlow{std::string MinimalOrthotope::debug_to_string() const { return fmt::to_string(*this); }void MinimalOrthotope::debug_print() const { std::cout << this->debug_to_string() << std::endl; }std::string format_as(MinimalOrthotope const &x){::nlohmann::json j = x;
return j.dump();
}std::ostream &operator<<(std::ostream &s, MinimalOrthotope const &x) {return s << fmt::to_string(x);}}// namespace FlexFlow
