// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/utils/include/utils/orthotope/orthotope_coord.dtg.toml
/* proj-data
{
  "generated_from": "2af0b36d6581d9d7ec12ecf19cf2f886"
}
*/

#include "utils/orthotope/orthotope_coord.dtg.h"

#include "utils/fmt/vector.h"
#include "utils/hash/vector.h"
#include <sstream>

namespace FlexFlow{OrthotopeCoord::OrthotopeCoord(std::vector<::FlexFlow::nonnegative_int> const &raw) : raw(raw){}
bool OrthotopeCoord::operator==(OrthotopeCoord const &other) const{
return std::tie(this->raw) == std::tie(other.raw);
}bool OrthotopeCoord::operator!=(OrthotopeCoord const &other) const{
return std::tie(this->raw) != std::tie(other.raw);
}bool OrthotopeCoord::operator<(OrthotopeCoord const &other) const{
return std::tie(this->raw) < std::tie(other.raw);
}bool OrthotopeCoord::operator>(OrthotopeCoord const &other) const{
return std::tie(this->raw) > std::tie(other.raw);
}bool OrthotopeCoord::operator<=(OrthotopeCoord const &other) const{
return std::tie(this->raw) <= std::tie(other.raw);
}bool OrthotopeCoord::operator>=(OrthotopeCoord const &other) const{
return std::tie(this->raw) >= std::tie(other.raw);
}}// namespace FlexFlow


///\cond
namespace std{size_t hash<FlexFlow::OrthotopeCoord>::operator()(::FlexFlow::OrthotopeCoord const &x)const{size_t result = 0;
result ^= std::hash<std::vector<::FlexFlow::nonnegative_int>>{}(x.raw) + 0x9e3779b9 + (result << 6) + (result >> 2);return result;
}}// namespace std

///\endcond

namespace nlohmann{void adl_serializer<::FlexFlow::OrthotopeCoord>::to_json(json &j, ::FlexFlow::OrthotopeCoord const &v) {j["__type"] = "OrthotopeCoord";
j["raw"] = v.raw;
}}// namespace nlohmann

namespace nlohmann{::FlexFlow::OrthotopeCoord adl_serializer<::FlexFlow::OrthotopeCoord>::from_json(json const &j) {return ::FlexFlow::OrthotopeCoord{j.at("raw").template get<std::vector<::FlexFlow::nonnegative_int>>()};}}// namespace nlohmann

namespace FlexFlow{std::string OrthotopeCoord::debug_to_string() const { return fmt::to_string(*this); }void OrthotopeCoord::debug_print() const { std::cout << this->debug_to_string() << std::endl; }std::string format_as(OrthotopeCoord const &x){::nlohmann::json j = x;
return j.dump();
}std::ostream &operator<<(std::ostream &s, OrthotopeCoord const &x) {return s << fmt::to_string(x);}}// namespace FlexFlow
