// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/op-attrs/include/op-attrs/ops/attention_attrs.dtg.toml
/* proj-data
{
  "generated_from": "b8990e04f11dd14692469984fa4789c8"
}
*/

#include "op-attrs/ops/attention_attrs.dtg.h"

#include <sstream>

namespace FlexFlow{MultiHeadAttentionAttrs::MultiHeadAttentionAttrs(::FlexFlow::positive_int const &embed_dim, ::FlexFlow::positive_int const &num_heads, ::FlexFlow::positive_int const &kdim, ::FlexFlow::positive_int const &vdim, float const &dropout, bool const &bias, bool const &add_bias_kv, bool const &add_zero_attn) : embed_dim(embed_dim), num_heads(num_heads), kdim(kdim), vdim(vdim), dropout(dropout), bias(bias), add_bias_kv(add_bias_kv), add_zero_attn(add_zero_attn){}
bool MultiHeadAttentionAttrs::operator==(MultiHeadAttentionAttrs const &other) const{
return std::tie(this->embed_dim, this->num_heads, this->kdim, this->vdim, this->dropout, this->bias, this->add_bias_kv, this->add_zero_attn) == std::tie(other.embed_dim, other.num_heads, other.kdim, other.vdim, other.dropout, other.bias, other.add_bias_kv, other.add_zero_attn);
}bool MultiHeadAttentionAttrs::operator!=(MultiHeadAttentionAttrs const &other) const{
return std::tie(this->embed_dim, this->num_heads, this->kdim, this->vdim, this->dropout, this->bias, this->add_bias_kv, this->add_zero_attn) != std::tie(other.embed_dim, other.num_heads, other.kdim, other.vdim, other.dropout, other.bias, other.add_bias_kv, other.add_zero_attn);
}bool MultiHeadAttentionAttrs::operator<(MultiHeadAttentionAttrs const &other) const{
return std::tie(this->embed_dim, this->num_heads, this->kdim, this->vdim, this->dropout, this->bias, this->add_bias_kv, this->add_zero_attn) < std::tie(other.embed_dim, other.num_heads, other.kdim, other.vdim, other.dropout, other.bias, other.add_bias_kv, other.add_zero_attn);
}bool MultiHeadAttentionAttrs::operator>(MultiHeadAttentionAttrs const &other) const{
return std::tie(this->embed_dim, this->num_heads, this->kdim, this->vdim, this->dropout, this->bias, this->add_bias_kv, this->add_zero_attn) > std::tie(other.embed_dim, other.num_heads, other.kdim, other.vdim, other.dropout, other.bias, other.add_bias_kv, other.add_zero_attn);
}bool MultiHeadAttentionAttrs::operator<=(MultiHeadAttentionAttrs const &other) const{
return std::tie(this->embed_dim, this->num_heads, this->kdim, this->vdim, this->dropout, this->bias, this->add_bias_kv, this->add_zero_attn) <= std::tie(other.embed_dim, other.num_heads, other.kdim, other.vdim, other.dropout, other.bias, other.add_bias_kv, other.add_zero_attn);
}bool MultiHeadAttentionAttrs::operator>=(MultiHeadAttentionAttrs const &other) const{
return std::tie(this->embed_dim, this->num_heads, this->kdim, this->vdim, this->dropout, this->bias, this->add_bias_kv, this->add_zero_attn) >= std::tie(other.embed_dim, other.num_heads, other.kdim, other.vdim, other.dropout, other.bias, other.add_bias_kv, other.add_zero_attn);
}}// namespace FlexFlow


///\cond
namespace std{size_t hash<FlexFlow::MultiHeadAttentionAttrs>::operator()(::FlexFlow::MultiHeadAttentionAttrs const &x)const{size_t result = 0;
result ^= std::hash<::FlexFlow::positive_int>{}(x.embed_dim) + 0x9e3779b9 + (result << 6) + (result >> 2);result ^= std::hash<::FlexFlow::positive_int>{}(x.num_heads) + 0x9e3779b9 + (result << 6) + (result >> 2);result ^= std::hash<::FlexFlow::positive_int>{}(x.kdim) + 0x9e3779b9 + (result << 6) + (result >> 2);result ^= std::hash<::FlexFlow::positive_int>{}(x.vdim) + 0x9e3779b9 + (result << 6) + (result >> 2);result ^= std::hash<float>{}(x.dropout) + 0x9e3779b9 + (result << 6) + (result >> 2);result ^= std::hash<bool>{}(x.bias) + 0x9e3779b9 + (result << 6) + (result >> 2);result ^= std::hash<bool>{}(x.add_bias_kv) + 0x9e3779b9 + (result << 6) + (result >> 2);result ^= std::hash<bool>{}(x.add_zero_attn) + 0x9e3779b9 + (result << 6) + (result >> 2);return result;
}}// namespace std

///\endcond

namespace nlohmann{void adl_serializer<::FlexFlow::MultiHeadAttentionAttrs>::to_json(json &j, ::FlexFlow::MultiHeadAttentionAttrs const &v) {j["__type"] = "MultiHeadAttentionAttrs";
j["embed_dim"] = v.embed_dim;
j["num_heads"] = v.num_heads;
j["kdim"] = v.kdim;
j["vdim"] = v.vdim;
j["dropout"] = v.dropout;
j["bias"] = v.bias;
j["add_bias_kv"] = v.add_bias_kv;
j["add_zero_attn"] = v.add_zero_attn;
}}// namespace nlohmann

namespace nlohmann{::FlexFlow::MultiHeadAttentionAttrs adl_serializer<::FlexFlow::MultiHeadAttentionAttrs>::from_json(json const &j) {return ::FlexFlow::MultiHeadAttentionAttrs{j.at("embed_dim").template get<::FlexFlow::positive_int>(), j.at("num_heads").template get<::FlexFlow::positive_int>(), j.at("kdim").template get<::FlexFlow::positive_int>(), j.at("vdim").template get<::FlexFlow::positive_int>(), j.at("dropout").template get<float>(), j.at("bias").template get<bool>(), j.at("add_bias_kv").template get<bool>(), j.at("add_zero_attn").template get<bool>()};}}// namespace nlohmann

namespace rc{Gen<::FlexFlow::MultiHeadAttentionAttrs> Arbitrary<::FlexFlow::MultiHeadAttentionAttrs>::arbitrary() {return gen::construct<::FlexFlow::MultiHeadAttentionAttrs>(gen::arbitrary<::FlexFlow::positive_int>(), gen::arbitrary<::FlexFlow::positive_int>(), gen::arbitrary<::FlexFlow::positive_int>(), gen::arbitrary<::FlexFlow::positive_int>(), gen::arbitrary<float>(), gen::arbitrary<bool>(), gen::arbitrary<bool>(), gen::arbitrary<bool>());}}// namespace rc

namespace FlexFlow{std::string MultiHeadAttentionAttrs::debug_to_string() const { return fmt::to_string(*this); }void MultiHeadAttentionAttrs::debug_print() const { std::cout << this->debug_to_string() << std::endl; }std::string format_as(MultiHeadAttentionAttrs const &x){::nlohmann::json j = x;
return j.dump();
}std::ostream &operator<<(std::ostream &s, MultiHeadAttentionAttrs const &x) {return s << fmt::to_string(x);}}// namespace FlexFlow
