// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/op-attrs/include/op-attrs/ops/broadcast_attrs.dtg.toml
/* proj-data
{
  "generated_from": "fe9d7470a36a426b6eec03e8d27633f3"
}
*/

#include "op-attrs/ops/broadcast_attrs.dtg.h"

#include <sstream>

namespace FlexFlow{BroadcastAttrs::BroadcastAttrs(::FlexFlow::TensorDims const &target_dims) : target_dims(target_dims){}
bool BroadcastAttrs::operator==(BroadcastAttrs const &other) const{
return std::tie(this->target_dims) == std::tie(other.target_dims);
}bool BroadcastAttrs::operator!=(BroadcastAttrs const &other) const{
return std::tie(this->target_dims) != std::tie(other.target_dims);
}bool BroadcastAttrs::operator<(BroadcastAttrs const &other) const{
return std::tie(this->target_dims) < std::tie(other.target_dims);
}bool BroadcastAttrs::operator>(BroadcastAttrs const &other) const{
return std::tie(this->target_dims) > std::tie(other.target_dims);
}bool BroadcastAttrs::operator<=(BroadcastAttrs const &other) const{
return std::tie(this->target_dims) <= std::tie(other.target_dims);
}bool BroadcastAttrs::operator>=(BroadcastAttrs const &other) const{
return std::tie(this->target_dims) >= std::tie(other.target_dims);
}}// namespace FlexFlow


///\cond
namespace std{size_t hash<FlexFlow::BroadcastAttrs>::operator()(::FlexFlow::BroadcastAttrs const &x)const{size_t result = 0;
result ^= std::hash<::FlexFlow::TensorDims>{}(x.target_dims) + 0x9e3779b9 + (result << 6) + (result >> 2);return result;
}}// namespace std

///\endcond

namespace nlohmann{void adl_serializer<::FlexFlow::BroadcastAttrs>::to_json(json &j, ::FlexFlow::BroadcastAttrs const &v) {j["__type"] = "BroadcastAttrs";
j["target_dims"] = v.target_dims;
}}// namespace nlohmann

namespace nlohmann{::FlexFlow::BroadcastAttrs adl_serializer<::FlexFlow::BroadcastAttrs>::from_json(json const &j) {return ::FlexFlow::BroadcastAttrs{j.at("target_dims").template get<::FlexFlow::TensorDims>()};}}// namespace nlohmann

namespace rc{Gen<::FlexFlow::BroadcastAttrs> Arbitrary<::FlexFlow::BroadcastAttrs>::arbitrary() {return gen::construct<::FlexFlow::BroadcastAttrs>(gen::arbitrary<::FlexFlow::TensorDims>());}}// namespace rc

namespace FlexFlow{std::string BroadcastAttrs::debug_to_string() const { return fmt::to_string(*this); }void BroadcastAttrs::debug_print() const { std::cout << this->debug_to_string() << std::endl; }std::string format_as(BroadcastAttrs const &x){::nlohmann::json j = x;
return j.dump();
}std::ostream &operator<<(std::ostream &s, BroadcastAttrs const &x) {return s << fmt::to_string(x);}}// namespace FlexFlow
