// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/op-attrs/include/op-attrs/ops/cast_attrs.dtg.toml
/* proj-data
{
  "generated_from": "7fb0f31358e6b7851b03ef176e9b50d0"
}
*/

#include "op-attrs/ops/cast_attrs.dtg.h"

#include <sstream>

namespace FlexFlow{CastAttrs::CastAttrs(::FlexFlow::DataType const &dtype) : dtype(dtype){}
bool CastAttrs::operator==(CastAttrs const &other) const{
return std::tie(this->dtype) == std::tie(other.dtype);
}bool CastAttrs::operator!=(CastAttrs const &other) const{
return std::tie(this->dtype) != std::tie(other.dtype);
}bool CastAttrs::operator<(CastAttrs const &other) const{
return std::tie(this->dtype) < std::tie(other.dtype);
}bool CastAttrs::operator>(CastAttrs const &other) const{
return std::tie(this->dtype) > std::tie(other.dtype);
}bool CastAttrs::operator<=(CastAttrs const &other) const{
return std::tie(this->dtype) <= std::tie(other.dtype);
}bool CastAttrs::operator>=(CastAttrs const &other) const{
return std::tie(this->dtype) >= std::tie(other.dtype);
}}// namespace FlexFlow


///\cond
namespace std{size_t hash<FlexFlow::CastAttrs>::operator()(::FlexFlow::CastAttrs const &x)const{size_t result = 0;
result ^= std::hash<::FlexFlow::DataType>{}(x.dtype) + 0x9e3779b9 + (result << 6) + (result >> 2);return result;
}}// namespace std

///\endcond

namespace nlohmann{void adl_serializer<::FlexFlow::CastAttrs>::to_json(json &j, ::FlexFlow::CastAttrs const &v) {j["__type"] = "CastAttrs";
j["dtype"] = v.dtype;
}}// namespace nlohmann

namespace nlohmann{::FlexFlow::CastAttrs adl_serializer<::FlexFlow::CastAttrs>::from_json(json const &j) {return ::FlexFlow::CastAttrs{j.at("dtype").template get<::FlexFlow::DataType>()};}}// namespace nlohmann

namespace rc{Gen<::FlexFlow::CastAttrs> Arbitrary<::FlexFlow::CastAttrs>::arbitrary() {return gen::construct<::FlexFlow::CastAttrs>(gen::arbitrary<::FlexFlow::DataType>());}}// namespace rc

namespace FlexFlow{std::string CastAttrs::debug_to_string() const { return fmt::to_string(*this); }void CastAttrs::debug_print() const { std::cout << this->debug_to_string() << std::endl; }std::string format_as(CastAttrs const &x){::nlohmann::json j = x;
return j.dump();
}std::ostream &operator<<(std::ostream &s, CastAttrs const &x) {return s << fmt::to_string(x);}}// namespace FlexFlow
