// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/op-attrs/include/op-attrs/ops/input_attrs.dtg.toml
/* proj-data
{
  "generated_from": "07f77a4358ba55c4c45dea2dcaf25f1b"
}
*/

#include "op-attrs/ops/input_attrs.dtg.h"

#include <sstream>

namespace FlexFlow{InputAttrs::InputAttrs(::FlexFlow::TensorShape const &tensor_shape) : tensor_shape(tensor_shape){}
bool InputAttrs::operator==(InputAttrs const &other) const{
return std::tie(this->tensor_shape) == std::tie(other.tensor_shape);
}bool InputAttrs::operator!=(InputAttrs const &other) const{
return std::tie(this->tensor_shape) != std::tie(other.tensor_shape);
}bool InputAttrs::operator<(InputAttrs const &other) const{
return std::tie(this->tensor_shape) < std::tie(other.tensor_shape);
}bool InputAttrs::operator>(InputAttrs const &other) const{
return std::tie(this->tensor_shape) > std::tie(other.tensor_shape);
}bool InputAttrs::operator<=(InputAttrs const &other) const{
return std::tie(this->tensor_shape) <= std::tie(other.tensor_shape);
}bool InputAttrs::operator>=(InputAttrs const &other) const{
return std::tie(this->tensor_shape) >= std::tie(other.tensor_shape);
}}// namespace FlexFlow


///\cond
namespace std{size_t hash<FlexFlow::InputAttrs>::operator()(::FlexFlow::InputAttrs const &x)const{size_t result = 0;
result ^= std::hash<::FlexFlow::TensorShape>{}(x.tensor_shape) + 0x9e3779b9 + (result << 6) + (result >> 2);return result;
}}// namespace std

///\endcond

namespace nlohmann{void adl_serializer<::FlexFlow::InputAttrs>::to_json(json &j, ::FlexFlow::InputAttrs const &v) {j["__type"] = "InputAttrs";
j["tensor_shape"] = v.tensor_shape;
}}// namespace nlohmann

namespace nlohmann{::FlexFlow::InputAttrs adl_serializer<::FlexFlow::InputAttrs>::from_json(json const &j) {return ::FlexFlow::InputAttrs{j.at("tensor_shape").template get<::FlexFlow::TensorShape>()};}}// namespace nlohmann

namespace rc{Gen<::FlexFlow::InputAttrs> Arbitrary<::FlexFlow::InputAttrs>::arbitrary() {return gen::construct<::FlexFlow::InputAttrs>(gen::arbitrary<::FlexFlow::TensorShape>());}}// namespace rc

namespace FlexFlow{std::string InputAttrs::debug_to_string() const { return fmt::to_string(*this); }void InputAttrs::debug_print() const { std::cout << this->debug_to_string() << std::endl; }std::string format_as(InputAttrs const &x){::nlohmann::json j = x;
return j.dump();
}std::ostream &operator<<(std::ostream &s, InputAttrs const &x) {return s << fmt::to_string(x);}}// namespace FlexFlow
