// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/op-attrs/include/op-attrs/ops/reduction_attrs.dtg.toml
/* proj-data
{
  "generated_from": "7ff84768ceb598540e019983604c231c"
}
*/

#include "op-attrs/ops/reduction_attrs.dtg.h"

#include <sstream>

namespace FlexFlow{ReductionAttrs::ReductionAttrs(::FlexFlow::positive_int const &reduction_degree) : reduction_degree(reduction_degree){}
bool ReductionAttrs::operator==(ReductionAttrs const &other) const{
return std::tie(this->reduction_degree) == std::tie(other.reduction_degree);
}bool ReductionAttrs::operator!=(ReductionAttrs const &other) const{
return std::tie(this->reduction_degree) != std::tie(other.reduction_degree);
}bool ReductionAttrs::operator<(ReductionAttrs const &other) const{
return std::tie(this->reduction_degree) < std::tie(other.reduction_degree);
}bool ReductionAttrs::operator>(ReductionAttrs const &other) const{
return std::tie(this->reduction_degree) > std::tie(other.reduction_degree);
}bool ReductionAttrs::operator<=(ReductionAttrs const &other) const{
return std::tie(this->reduction_degree) <= std::tie(other.reduction_degree);
}bool ReductionAttrs::operator>=(ReductionAttrs const &other) const{
return std::tie(this->reduction_degree) >= std::tie(other.reduction_degree);
}}// namespace FlexFlow


///\cond
namespace std{size_t hash<FlexFlow::ReductionAttrs>::operator()(::FlexFlow::ReductionAttrs const &x)const{size_t result = 0;
result ^= std::hash<::FlexFlow::positive_int>{}(x.reduction_degree) + 0x9e3779b9 + (result << 6) + (result >> 2);return result;
}}// namespace std

///\endcond

namespace nlohmann{void adl_serializer<::FlexFlow::ReductionAttrs>::to_json(json &j, ::FlexFlow::ReductionAttrs const &v) {j["__type"] = "ReductionAttrs";
j["reduction_degree"] = v.reduction_degree;
}}// namespace nlohmann

namespace nlohmann{::FlexFlow::ReductionAttrs adl_serializer<::FlexFlow::ReductionAttrs>::from_json(json const &j) {return ::FlexFlow::ReductionAttrs{j.at("reduction_degree").template get<::FlexFlow::positive_int>()};}}// namespace nlohmann

namespace rc{Gen<::FlexFlow::ReductionAttrs> Arbitrary<::FlexFlow::ReductionAttrs>::arbitrary() {return gen::construct<::FlexFlow::ReductionAttrs>(gen::arbitrary<::FlexFlow::positive_int>());}}// namespace rc

namespace FlexFlow{std::string ReductionAttrs::debug_to_string() const { return fmt::to_string(*this); }void ReductionAttrs::debug_print() const { std::cout << this->debug_to_string() << std::endl; }std::string format_as(ReductionAttrs const &x){::nlohmann::json j = x;
return j.dump();
}std::ostream &operator<<(std::ostream &s, ReductionAttrs const &x) {return s << fmt::to_string(x);}}// namespace FlexFlow
