// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/op-attrs/include/op-attrs/ops/topk_attrs.dtg.toml
/* proj-data
{
  "generated_from": "b9223f9ebfdb7b3eab35233055613fc4"
}
*/

#include "op-attrs/ops/topk_attrs.dtg.h"

#include <sstream>

namespace FlexFlow{TopKAttrs::TopKAttrs(::FlexFlow::positive_int const &k, bool const &sorted) : k(k), sorted(sorted){}
bool TopKAttrs::operator==(TopKAttrs const &other) const{
return std::tie(this->k, this->sorted) == std::tie(other.k, other.sorted);
}bool TopKAttrs::operator!=(TopKAttrs const &other) const{
return std::tie(this->k, this->sorted) != std::tie(other.k, other.sorted);
}bool TopKAttrs::operator<(TopKAttrs const &other) const{
return std::tie(this->k, this->sorted) < std::tie(other.k, other.sorted);
}bool TopKAttrs::operator>(TopKAttrs const &other) const{
return std::tie(this->k, this->sorted) > std::tie(other.k, other.sorted);
}bool TopKAttrs::operator<=(TopKAttrs const &other) const{
return std::tie(this->k, this->sorted) <= std::tie(other.k, other.sorted);
}bool TopKAttrs::operator>=(TopKAttrs const &other) const{
return std::tie(this->k, this->sorted) >= std::tie(other.k, other.sorted);
}}// namespace FlexFlow


///\cond
namespace std{size_t hash<FlexFlow::TopKAttrs>::operator()(::FlexFlow::TopKAttrs const &x)const{size_t result = 0;
result ^= std::hash<::FlexFlow::positive_int>{}(x.k) + 0x9e3779b9 + (result << 6) + (result >> 2);result ^= std::hash<bool>{}(x.sorted) + 0x9e3779b9 + (result << 6) + (result >> 2);return result;
}}// namespace std

///\endcond

namespace nlohmann{void adl_serializer<::FlexFlow::TopKAttrs>::to_json(json &j, ::FlexFlow::TopKAttrs const &v) {j["__type"] = "TopKAttrs";
j["k"] = v.k;
j["sorted"] = v.sorted;
}}// namespace nlohmann

namespace nlohmann{::FlexFlow::TopKAttrs adl_serializer<::FlexFlow::TopKAttrs>::from_json(json const &j) {return ::FlexFlow::TopKAttrs{j.at("k").template get<::FlexFlow::positive_int>(), j.at("sorted").template get<bool>()};}}// namespace nlohmann

namespace rc{Gen<::FlexFlow::TopKAttrs> Arbitrary<::FlexFlow::TopKAttrs>::arbitrary() {return gen::construct<::FlexFlow::TopKAttrs>(gen::arbitrary<::FlexFlow::positive_int>(), gen::arbitrary<bool>());}}// namespace rc

namespace FlexFlow{std::string TopKAttrs::debug_to_string() const { return fmt::to_string(*this); }void TopKAttrs::debug_print() const { std::cout << this->debug_to_string() << std::endl; }std::string format_as(TopKAttrs const &x){::nlohmann::json j = x;
return j.dump();
}std::ostream &operator<<(std::ostream &s, TopKAttrs const &x) {return s << fmt::to_string(x);}}// namespace FlexFlow
