// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/utils/include/utils/graph/series_parallel/split_type.dtg.toml
/* proj-data
{
  "generated_from": "f0c52914c8248c6854aaa5f8bf4d4388"
}
*/

#include "utils/graph/series_parallel/split_type.dtg.h"

#include <stdexcept>
#include <sstream>


///\cond
namespace std{size_t hash<FlexFlow::SplitType>::operator()(FlexFlow::SplitType x) const{return std::hash<int>{}(static_cast<int>(x));
}}// namespace std

///\endcond
namespace FlexFlow{std::string format_as(SplitType x){::nlohmann::json j = x;
return j.dump();
}std::ostream &operator<<(std::ostream &s, SplitType x){return s << fmt::to_string(x);}}// namespace FlexFlow
namespace FlexFlow{void to_json(::nlohmann::json &j, SplitType x){switch (x){case SplitType::SERIES:
j = "SERIES";
break;
case SplitType::PARALLEL:
j = "PARALLEL";
break;
default:
std::ostringstream oss;
oss << "Unknown SplitType value " << static_cast<int>(x);
throw std::runtime_error(oss.str());
}}}// namespace FlexFlow
namespace FlexFlow{void from_json(::nlohmann::json const &j, SplitType &x){std::string as_str = j.get<std::string>();
if (as_str == "SERIES"){x = SplitType::SERIES;
}else if (as_str == "PARALLEL"){x = SplitType::PARALLEL;
}else {std::ostringstream oss;
oss << "Unknown SplitType value " << as_str;
throw std::runtime_error(oss.str());
}}}// namespace FlexFlow
namespace rc{Gen<FlexFlow::SplitType> Arbitrary<FlexFlow::SplitType>::arbitrary(){return gen::element<FlexFlow::SplitType>(FlexFlow::SplitType::SERIES, FlexFlow::SplitType::PARALLEL);}}// namespace rc
