// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/realm-execution/include/realm-execution/redops/redop_id_t.dtg.toml
/* proj-data
{
  "generated_from": "ded3fb8289f30f84a626b5e56a8c7410"
}
*/

#include "realm-execution/redops/redop_id_t.dtg.h"

#include <stdexcept>
#include <sstream>


///\cond
namespace std{size_t hash<FlexFlow::redop_id_t>::operator()(FlexFlow::redop_id_t x) const{return std::hash<int>{}(static_cast<int>(x));
}}// namespace std

///\endcond
namespace FlexFlow{std::string format_as(redop_id_t x){::nlohmann::json j = x;
return j.dump();
}std::ostream &operator<<(std::ostream &s, redop_id_t x){return s << fmt::to_string(x);}}// namespace FlexFlow
namespace FlexFlow{void to_json(::nlohmann::json &j, redop_id_t x){switch (x){case redop_id_t::SUM_BOOL_REDOP_ID:
j = "SUM_BOOL_REDOP_ID";
break;
case redop_id_t::SUM_INT32_REDOP_ID:
j = "SUM_INT32_REDOP_ID";
break;
case redop_id_t::SUM_INT64_REDOP_ID:
j = "SUM_INT64_REDOP_ID";
break;
case redop_id_t::SUM_FLOAT_REDOP_ID:
j = "SUM_FLOAT_REDOP_ID";
break;
case redop_id_t::SUM_DOUBLE_REDOP_ID:
j = "SUM_DOUBLE_REDOP_ID";
break;
default:
std::ostringstream oss;
oss << "Unknown redop_id_t value " << static_cast<int>(x);
throw std::runtime_error(oss.str());
}}}// namespace FlexFlow
namespace FlexFlow{void from_json(::nlohmann::json const &j, redop_id_t &x){std::string as_str = j.get<std::string>();
if (as_str == "SUM_BOOL_REDOP_ID"){x = redop_id_t::SUM_BOOL_REDOP_ID;
}else if (as_str == "SUM_INT32_REDOP_ID"){x = redop_id_t::SUM_INT32_REDOP_ID;
}else if (as_str == "SUM_INT64_REDOP_ID"){x = redop_id_t::SUM_INT64_REDOP_ID;
}else if (as_str == "SUM_FLOAT_REDOP_ID"){x = redop_id_t::SUM_FLOAT_REDOP_ID;
}else if (as_str == "SUM_DOUBLE_REDOP_ID"){x = redop_id_t::SUM_DOUBLE_REDOP_ID;
}else {std::ostringstream oss;
oss << "Unknown redop_id_t value " << as_str;
throw std::runtime_error(oss.str());
}}}// namespace FlexFlow
namespace rc{Gen<FlexFlow::redop_id_t> Arbitrary<FlexFlow::redop_id_t>::arbitrary(){return gen::element<FlexFlow::redop_id_t>(FlexFlow::redop_id_t::SUM_BOOL_REDOP_ID, FlexFlow::redop_id_t::SUM_INT32_REDOP_ID, FlexFlow::redop_id_t::SUM_INT64_REDOP_ID, FlexFlow::redop_id_t::SUM_FLOAT_REDOP_ID, FlexFlow::redop_id_t::SUM_DOUBLE_REDOP_ID);}}// namespace rc
