// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/compiler/include/compiler/machine_mapping/memory_optimization/machine_mapping_with_memory_cache.dtg.toml
/* proj-data
{
  "generated_from": "14116e3270d1302f835c09cd6d63640c"
}
*/

#include "compiler/machine_mapping/memory_optimization/machine_mapping_with_memory_cache.dtg.h"

#include "utils/fmt/map.h"
#include "utils/hash/map.h"
#include <sstream>

namespace FlexFlow{MachineMappingWithMemoryCache::MachineMappingWithMemoryCache(std::map<::FlexFlow::MachineMappingState, ::FlexFlow::MachineMappingWithMemoryResult> const &raw_map) : raw_map(raw_map){}
bool MachineMappingWithMemoryCache::operator==(MachineMappingWithMemoryCache const &other) const{
return std::tie(this->raw_map) == std::tie(other.raw_map);
}bool MachineMappingWithMemoryCache::operator!=(MachineMappingWithMemoryCache const &other) const{
return std::tie(this->raw_map) != std::tie(other.raw_map);
}}// namespace FlexFlow


///\cond
namespace std{size_t hash<FlexFlow::MachineMappingWithMemoryCache>::operator()(::FlexFlow::MachineMappingWithMemoryCache const &x)const{size_t result = 0;
result ^= std::hash<std::map<::FlexFlow::MachineMappingState, ::FlexFlow::MachineMappingWithMemoryResult>>{}(x.raw_map) + 0x9e3779b9 + (result << 6) + (result >> 2);return result;
}}// namespace std

///\endcond

namespace nlohmann{void adl_serializer<::FlexFlow::MachineMappingWithMemoryCache>::to_json(json &j, ::FlexFlow::MachineMappingWithMemoryCache const &v) {j["__type"] = "MachineMappingWithMemoryCache";
j["raw_map"] = v.raw_map;
}}// namespace nlohmann

namespace nlohmann{::FlexFlow::MachineMappingWithMemoryCache adl_serializer<::FlexFlow::MachineMappingWithMemoryCache>::from_json(json const &j) {return ::FlexFlow::MachineMappingWithMemoryCache{j.at("raw_map").template get<std::map<::FlexFlow::MachineMappingState, ::FlexFlow::MachineMappingWithMemoryResult>>()};}}// namespace nlohmann

namespace FlexFlow{std::string MachineMappingWithMemoryCache::debug_to_string() const { return fmt::to_string(*this); }void MachineMappingWithMemoryCache::debug_print() const { std::cout << this->debug_to_string() << std::endl; }std::string format_as(MachineMappingWithMemoryCache const &x){::nlohmann::json j = x;
return j.dump();
}std::ostream &operator<<(std::ostream &s, MachineMappingWithMemoryCache const &x) {return s << fmt::to_string(x);}}// namespace FlexFlow
