// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/compiler/include/compiler/cost_estimator/op_cost_estimate_key.dtg.toml
/* proj-data
{
  "generated_from": "7bab7e8b852b5e2ca4a084807e81d5bd"
}
*/

#ifndef _FLEXFLOW_LIB_COMPILER_INCLUDE_COMPILER_COST_ESTIMATOR_OP_COST_ESTIMATE_KEY_DTG_H
#define _FLEXFLOW_LIB_COMPILER_INCLUDE_COMPILER_COST_ESTIMATOR_OP_COST_ESTIMATE_KEY_DTG_H

#include <tuple>
#include <iostream>
#include "pcg/optimizer_attrs.dtg.h"
#include "op-attrs/pcg_operator_attrs.dtg.h"
#include <ostream>
#include <vector>
#include <fmt/format.h>
#include "op-attrs/tensor_slot_name.dtg.h"
#include <nlohmann/json.hpp>
#include <functional>
#include "op-attrs/parallel_tensor_shape.dtg.h"
#include "compiler/machine_mapping/machine_view.dtg.h"


namespace FlexFlow{

/**
 * @brief The minimum amount of information needed to compute the cost of an
 * operator (runtime and memory).
 * 
 * For the runtime-only analogue, see RuntimeOnlyOpCostEstimateKey
 */struct OpCostEstimateKey{OpCostEstimateKey() = delete;
explicit OpCostEstimateKey(::FlexFlow::PCGOperatorAttrs const &op_attrs, std::map<::FlexFlow::TensorSlotName, ::FlexFlow::ParallelTensorShape> const &input_shapes, std::map<::FlexFlow::TensorSlotName, ::FlexFlow::ParallelTensorShape> const &weight_shapes, std::map<::FlexFlow::TensorSlotName, ::FlexFlow::ParallelTensorShape> const &output_shapes, ::FlexFlow::OptimizerAttrs const &optimizer_attrs, ::FlexFlow::MachineView const &machine_view);

bool operator==(OpCostEstimateKey const &) const;bool operator!=(OpCostEstimateKey const &) const;
bool operator<(OpCostEstimateKey const &) const;bool operator>(OpCostEstimateKey const &) const;bool operator<=(OpCostEstimateKey const &) const;bool operator>=(OpCostEstimateKey const &) const;
std::string debug_to_string() const;void debug_print() const;
::FlexFlow::PCGOperatorAttrs op_attrs;
std::map<::FlexFlow::TensorSlotName, ::FlexFlow::ParallelTensorShape> input_shapes;
std::map<::FlexFlow::TensorSlotName, ::FlexFlow::ParallelTensorShape> weight_shapes;
std::map<::FlexFlow::TensorSlotName, ::FlexFlow::ParallelTensorShape> output_shapes;
::FlexFlow::OptimizerAttrs optimizer_attrs;
::FlexFlow::MachineView machine_view;
};}// namespace FlexFlow


///\cond
namespace std{template <>
struct hash<::FlexFlow::OpCostEstimateKey>{size_t operator()(::FlexFlow::OpCostEstimateKey const &)const;};}// namespace std

///\endcond

namespace nlohmann{template <>
struct adl_serializer<::FlexFlow::OpCostEstimateKey>{static void to_json(json &, ::FlexFlow::OpCostEstimateKey const &);
};}// namespace nlohmann

namespace FlexFlow{std::string format_as(OpCostEstimateKey const &);
std::ostream &operator<<(std::ostream &, OpCostEstimateKey const &);}// namespace FlexFlow

#endif // _FLEXFLOW_LIB_COMPILER_INCLUDE_COMPILER_COST_ESTIMATOR_OP_COST_ESTIMATE_KEY_DTG_H
