// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/compiler/include/compiler/cost_estimator/runtime_only_op_cost_metrics.dtg.toml
/* proj-data
{
  "generated_from": "d2536f0003007878a7d760d77f1a6686"
}
*/

#ifndef _FLEXFLOW_LIB_COMPILER_INCLUDE_COMPILER_COST_ESTIMATOR_RUNTIME_ONLY_OP_COST_METRICS_DTG_H
#define _FLEXFLOW_LIB_COMPILER_INCLUDE_COMPILER_COST_ESTIMATOR_RUNTIME_ONLY_OP_COST_METRICS_DTG_H

#include <tuple>
#include <iostream>
#include "utils/units/milliseconds_t.h"
#include <ostream>
#include <fmt/format.h>
#include <nlohmann/json.hpp>
#include <functional>


namespace FlexFlow{struct RuntimeOnlyOpCostMetrics{RuntimeOnlyOpCostMetrics() = delete;
explicit RuntimeOnlyOpCostMetrics(::FlexFlow::milliseconds_t const &forward_runtime, ::FlexFlow::milliseconds_t const &backward_runtime);

bool operator==(RuntimeOnlyOpCostMetrics const &) const;bool operator!=(RuntimeOnlyOpCostMetrics const &) const;
std::string debug_to_string() const;void debug_print() const;
::FlexFlow::milliseconds_t forward_runtime;
::FlexFlow::milliseconds_t backward_runtime;
};}// namespace FlexFlow


///\cond
namespace std{template <>
struct hash<::FlexFlow::RuntimeOnlyOpCostMetrics>{size_t operator()(::FlexFlow::RuntimeOnlyOpCostMetrics const &)const;};}// namespace std

///\endcond

namespace nlohmann{template <>
struct adl_serializer<::FlexFlow::RuntimeOnlyOpCostMetrics>{static void to_json(json &, ::FlexFlow::RuntimeOnlyOpCostMetrics const &);
};}// namespace nlohmann

namespace FlexFlow{std::string format_as(RuntimeOnlyOpCostMetrics const &);
std::ostream &operator<<(std::ostream &, RuntimeOnlyOpCostMetrics const &);}// namespace FlexFlow

#endif // _FLEXFLOW_LIB_COMPILER_INCLUDE_COMPILER_COST_ESTIMATOR_RUNTIME_ONLY_OP_COST_METRICS_DTG_H
