// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/compiler/include/compiler/series_parallel/pcg/pcg_binary_sp_decomposition.dtg.toml
/* proj-data
{
  "generated_from": "bac059440a4187f2e126b51a7d43814e"
}
*/

#ifndef _FLEXFLOW_LIB_COMPILER_INCLUDE_COMPILER_SERIES_PARALLEL_PCG_PCG_BINARY_SP_DECOMPOSITION_DTG_H
#define _FLEXFLOW_LIB_COMPILER_INCLUDE_COMPILER_SERIES_PARALLEL_PCG_PCG_BINARY_SP_DECOMPOSITION_DTG_H

#include "compiler/series_parallel/pcg/pcg_binary_parallel_split.dtg.h"
#include "compiler/series_parallel/pcg/pcg_binary_series_split.dtg.h"
#include <cstddef>
#include <fmt/format.h>
#include <functional>
#include <iostream>
#include <libassert/assert.hpp>
#include <nlohmann/json.hpp>
#include <optional>
#include <ostream>
#include "pcg/parallel_computation_graph/parallel_layer_guid_t.dtg.h"
#include <stdexcept>
#include <type_traits>
#include <variant>

namespace FlexFlow{struct PCGBinarySPDecomposition{PCGBinarySPDecomposition() = delete;
explicit PCGBinarySPDecomposition(::FlexFlow::PCGBinarySeriesSplit const &);
explicit PCGBinarySPDecomposition(::FlexFlow::PCGBinaryParallelSplit const &);
explicit PCGBinarySPDecomposition(::FlexFlow::parallel_layer_guid_t const &);template <typename T>
static constexpr bool IsPartOfPCGBinarySPDecomposition_v =std::is_same_v<T, ::FlexFlow::PCGBinarySeriesSplit> || std::is_same_v<T, ::FlexFlow::PCGBinaryParallelSplit> || std::is_same_v<T, ::FlexFlow::parallel_layer_guid_t>;template <typename ReturnType, typename Visitor>
ReturnType visit(Visitor &&v) const{switch (this->index()){case 0: {ReturnType result = v(this->get<::FlexFlow::PCGBinarySeriesSplit>());
return result;
}case 1: {ReturnType result = v(this->get<::FlexFlow::PCGBinaryParallelSplit>());
return result;
}case 2: {ReturnType result = v(this->get<::FlexFlow::parallel_layer_guid_t>());
return result;
}default: {throw std::runtime_error(fmt::format("Unknown index {} for type PCGBinarySPDecomposition", this->index()));
}}}
template <typename ReturnType, typename Visitor>
ReturnType visit(Visitor &&v){switch (this->index()){case 0: {ReturnType result = v(this->get<::FlexFlow::PCGBinarySeriesSplit>());
return result;
}case 1: {ReturnType result = v(this->get<::FlexFlow::PCGBinaryParallelSplit>());
return result;
}case 2: {ReturnType result = v(this->get<::FlexFlow::parallel_layer_guid_t>());
return result;
}default: {throw std::runtime_error(fmt::format("Unknown index {} for type PCGBinarySPDecomposition", this->index()));
}}}
template <typename T>
bool has() const{static_assert(IsPartOfPCGBinarySPDecomposition_v<T>, "PCGBinarySPDecomposition::has() expected one of [::FlexFlow::PCGBinarySeriesSplit, ::FlexFlow::PCGBinaryParallelSplit, ::FlexFlow::parallel_layer_guid_t], received T");return std::holds_alternative<T>(this->raw_variant);}
template <typename T>
T const & get() const{static_assert(IsPartOfPCGBinarySPDecomposition_v<T>, "PCGBinarySPDecomposition::get() expected one of [::FlexFlow::PCGBinarySeriesSplit, ::FlexFlow::PCGBinaryParallelSplit, ::FlexFlow::parallel_layer_guid_t], received T");bool holds_expected = std::holds_alternative<T>(this->raw_variant);
ASSERT(holds_expected);
return std::get<T>(this->raw_variant);
}
template <typename T>
T  & get(){static_assert(IsPartOfPCGBinarySPDecomposition_v<T>, "PCGBinarySPDecomposition::get() expected one of [::FlexFlow::PCGBinarySeriesSplit, ::FlexFlow::PCGBinaryParallelSplit, ::FlexFlow::parallel_layer_guid_t], received T");bool holds_expected = std::holds_alternative<T>(this->raw_variant);
ASSERT(holds_expected);
return std::get<T>(this->raw_variant);
}
size_t index() const { return this->raw_variant.index(); }
bool operator==(PCGBinarySPDecomposition const &) const;bool operator!=(PCGBinarySPDecomposition const &) const;::FlexFlow::PCGBinarySeriesSplit const & require_series() const;
::FlexFlow::PCGBinarySeriesSplit & require_series();
::FlexFlow::PCGBinaryParallelSplit const & require_parallel() const;
::FlexFlow::PCGBinaryParallelSplit & require_parallel();
::FlexFlow::parallel_layer_guid_t const & require_leaf() const;
::FlexFlow::parallel_layer_guid_t & require_leaf();
std::optional<::FlexFlow::PCGBinarySeriesSplit> try_require_series() const;
std::optional<::FlexFlow::PCGBinaryParallelSplit> try_require_parallel() const;
std::optional<::FlexFlow::parallel_layer_guid_t> try_require_leaf() const;
bool is_series() const;
bool is_parallel() const;
bool is_leaf() const;
std::string debug_to_string() const;void debug_print() const;std::variant<::FlexFlow::PCGBinarySeriesSplit, ::FlexFlow::PCGBinaryParallelSplit, ::FlexFlow::parallel_layer_guid_t> raw_variant;};}// namespace FlexFlow

///\cond
namespace std{template <>
struct hash<::FlexFlow::PCGBinarySPDecomposition>{size_t operator()(::FlexFlow::PCGBinarySPDecomposition const &) const;
};}// namespace std

///\endcond
namespace nlohmann{template <>
struct adl_serializer<::FlexFlow::PCGBinarySPDecomposition>{static void to_json(json &, ::FlexFlow::PCGBinarySPDecomposition const &);
};}// namespace nlohmann
namespace FlexFlow{std::string format_as(::FlexFlow::PCGBinarySPDecomposition const &);
std::ostream & operator<<(std::ostream &, ::FlexFlow::PCGBinarySPDecomposition const &);
}// namespace FlexFlow

#endif // _FLEXFLOW_LIB_COMPILER_INCLUDE_COMPILER_SERIES_PARALLEL_PCG_PCG_BINARY_SP_DECOMPOSITION_DTG_H
