// THIS FILE WAS AUTO-GENERATED BY proj. DO NOT MODIFY IT!
// If you would like to modify this datatype, instead modify
// lib/substitutions/include/substitutions/unlabelled/pattern_split.dtg.toml
/* proj-data
{
  "generated_from": "b4706f202484f4f985018be85242de43"
}
*/

#ifndef _FLEXFLOW_LIB_SUBSTITUTIONS_INCLUDE_SUBSTITUTIONS_UNLABELLED_PATTERN_SPLIT_DTG_H
#define _FLEXFLOW_LIB_SUBSTITUTIONS_INCLUDE_SUBSTITUTIONS_UNLABELLED_PATTERN_SPLIT_DTG_H

#include <tuple>
#include <iostream>
#include <set>
#include "utils/fmt/set.h"
#include <ostream>
#include "substitutions/unlabelled/pattern_node.dtg.h"
#include <fmt/format.h>
#include "utils/hash/set.h"
#include <functional>


namespace FlexFlow{struct PatternSplit{PatternSplit() = delete;
explicit PatternSplit(std::set<::FlexFlow::PatternNode> const &first, std::set<::FlexFlow::PatternNode> const &second);

bool operator==(PatternSplit const &) const;bool operator!=(PatternSplit const &) const;
std::string debug_to_string() const;void debug_print() const;
std::set<::FlexFlow::PatternNode> first;
std::set<::FlexFlow::PatternNode> second;
};}// namespace FlexFlow


///\cond
namespace std{template <>
struct hash<::FlexFlow::PatternSplit>{size_t operator()(::FlexFlow::PatternSplit const &)const;};}// namespace std

///\endcond

namespace FlexFlow{std::string format_as(PatternSplit const &);
std::ostream &operator<<(std::ostream &, PatternSplit const &);}// namespace FlexFlow

#endif // _FLEXFLOW_LIB_SUBSTITUTIONS_INCLUDE_SUBSTITUTIONS_UNLABELLED_PATTERN_SPLIT_DTG_H
